---
title: 5.2 Cohomology of simplicial topological spaces
---

{{< include ../macros.qmd >}}

:::: {.rmenv #env-iii-5.2.1 number="5.2.1"}
To each simplicial topological space $X_\bullet$ is associated a usual topological space $|X_\bullet|$, called its geometric realisation (see below).
In the particular case where the $X_n$ are discrete, we recover the usual notion of geometric realisation of a simplicial set.

In [@S1968], G. Segal defined the cohomology of $X_\bullet$ with values in an abelian group $A$ as $\HH^\bullet(|X_\bullet|,A)$.
Under suitable hypotheses, the filtration of $|X_\bullet|$ by successive skeletons gives a spectral sequence
$$
  E_1^{pq}
  = \HH^q(X_p,A)
  \To \HH^{p+q}(X_\bullet,A).
\tag{5.2.1.1}
$$

One of the interests in using this definition is that it also applies, for example, to the definition of the groups $K(X_\bullet)$.
We will adopt another definition, which is better adapted to sheaf-theoretic techniques.

::: {.rmenv #env-iii-5.2.1-geometric-realisation taxon="Definition"}
*Geometric realisation.*
For an integer $n\geqslant0$, we denote by $|\Delta_n|$ the simplex in $\RR^{\Delta_n}$ whose vertices are the set of basis vectors.
We identify $\Delta_n$ with the set of vertices of $|\Delta_n|$.
Every function $f\colon\Delta_n\to\Delta_m$ extends by linearity to $|f|\colon|\Delta_n|\to|\Delta_m|$.

Let $X_\bullet$ be a simplicial topological space.
Let
$$
  Y=\coprod_{n\geqslant0}(X_n\times|\Delta_n|).
$$
Let $R$ be the finest equivalence relation on $Y$ for which, for any $f\colon\Delta_n\to\Delta_m$ in $(\Delta)$, any $x_m\in X_m$, and any $a\in|\Delta_n|$, we have
$$
  (x_m,|f|(a))
  \equiv (f(x_m),a)
  \mod R.
$$
The **geometric realisation** of $X_\bullet$ is by definition
$$
  |X_\bullet|
  = Y/R.
$$
:::
::::

::: {.rmenv #env-iii-5.2.2 number="5.2.2" taxon="Definition"}
Let $X_\bullet$ be a simplicial topological space.
The functors $\HH^i(X_\bullet,F^\bullet)$ of **cohomology with coefficients in the abelian sheaf $F^\bullet$ on $X_\bullet$** are the derived functors of the functor $\Gamma$ [(5.1.13.1)](5.1-simplicial-topological-spaces.qmd#iii-5.1.13).
:::

This definition is equivalent to the following, sometimes more convenient definition.

::: {.rmenv #env-iii-5.2.3 number="5.2.3"}
Let $F^\bullet$ be an abelian sheaf on $X_\bullet$.
\oldpage{13}
We can show (by example, using (iii) of [(5.1.9)](5.1-simplicial-topological-spaces.qmd#iii-5.1.9)) that $F^\bullet$ always admits resolutions $K$ on the right such that
$$
  \HH^r(X_q,K^{p,q})
  =0
  \quad\text{for } p,q\geqslant0 \text{ and } r>0.
$$
If $K$ is such a resolution, then we canonically have that
$$
  \HH^n(X_\bullet,F^\bullet)
  \simeq \HH^n(\simp\Gamma^\bullet(X_\bullet,K)).
\tag{5.2.3.1}
$$
It is easy to show directly that the right-hand side is independent (up to unique isomorphism) of the choice of $K$;
for what follows, we are free to *define* $\HH^\bullet(X_\bullet,F^\bullet)$ by [(5.2.3.1)](#iii-5.2.3).
We can further show that the spectral sequence of the complex $\simp\Gamma^\bullet(X_\bullet,K)$, filtered by $L$ ([(5.1.9.3)](5.1-simplicial-topological-spaces.qmd#iii-5.1.9) and [(5.1.12.1)](5.1-simplicial-topological-spaces.qmd#iii-5.1.12) for $S=P^t$)
$$
  E_1^{pq}
  = \HH^q(X_p,F^p)
  \To \HH^{p+q}(X_\bullet,F^\bullet)
\tag{5.2.3.2}
$$
is independent (up to unique isomorphism) of the choice of $K$ (cf. [(5.2.1.1)](#iii-5.2.1)).
:::

::: {.rmenv #env-iii-5.2.4 number="5.2.4"}
We will need to make precise the above construction when passing to derived categories, and to give a relative variant of it.

Let $a\colon X_\bullet\to S$, let $S_\bullet$ be the constant simplicial space defined by $S$ with augmentation map $\varepsilon\colon S_\bullet\to S$, and let $a_\bullet\colon X_\bullet\to S_\bullet$ be the map induced by $a$.
Then
$$
  a_*
  = \varepsilon_* {a_\bullet}_*\colon
  (X_\bullet)^\sim
  \to (S)^\sim.
\tag{5.2.4.1}
$$

The derived version of this equation is
$$
  \Rd a_*
  = \Rd\varepsilon_* \Rd{a_\bullet}_*\colon
  \DD^+(X_\bullet)
  \to \DD^+(S)
  \to (S)^\sim.
\tag{5.2.4.2}
$$
where $\DD^+(X_\bullet)$ is the bounded-below derived category of the category of abelian sheaves on $X_\bullet$.
We will calculate $\Rd{a_\bullet}_*$ and $\Rd\varepsilon_*$.
:::

::: {.rmenv #env-iii-5.2.5 number="5.2.5"}
Let $u\colon X_\bullet\to Y_\bullet$ be a morphism of simplicial topological spaces.
The functor $\Rd u_*\colon\DD^+(X_\bullet)\to\DD^+(Y_\bullet)$ can be calculated "component by component": if $K$ is a complex of abelian sheaves on $X_\bullet$, then to calculate $\Rd u_*K$ we take a resolution $K\simto K'$ such that the components $F$ of $K'$ satisfy $\Rd^i {u_p}_*(F^p)=0$ for $i>0$, $p\geqslant0$ (cf. (iii) of [(5.1.9)](#iii-5.1.9));
then $\Rd u_*K\approx u_*K'$.
:::

::: {.rmenv #env-iii-5.2.6 number="5.2.6"}
The functor $\simp\colon\operatorname{C}^+(S_\bullet)\to\operatorname{C}^+(S)$ sends acyclic complexes to acyclic complexes.
It thus trivially derives to
$$
  \simp\colon \DD^+(S_\bullet)
  \to \DD^+(S).
$$
If $F$ is an injective sheaf on $S_\bullet$, then the chain complex $\simp F$ is a resolution of $\varepsilon_*F$.
We thus obtain an isomorphism $\Rd\varepsilon_*\simto\simp$, and [(5.2.4.2)](#iii-5.2.4) becomes
$$
  \Rd a_*
  = \simp\Rd{a_\bullet}_*
\tag{5.2.6.1}
$$
:::

::: {.rmenv #env-iii-5.2.7 number="5.2.7"}
Combined with [(5.2.5)](#iii-5.2.5) and specialised to the case where $S=P^t$, this equation proves [(5.2.3.1)](#iii-5.2.3).
\oldpage{14}
In concrete terms, this implies that, to calculate $\Rd a_*K$, we can proceed in two steps:

a. We take a resolution $K\simto K'$ such that the components $F$ of $K'$ satisfy $\Rd^i {a_p}_*(F^p)=0$ for $i>0$.
    The complex ${a_\bullet}_*K'\in\DD^+(S_\bullet)$ (the derived category of the category of cosimplicial abelian sheaves on $S$) can be identified with $\Rd{a_\bullet}_*K$.
b. $\Rd a_*K$ is the simple complex $\simp{a_\bullet}_*K'$ associated to the double complex ${a_\bullet}_*K'$.

The spectral sequence [(5.2.3.2)](#iii-5.2.3) generalises to a spectral sequence
$$
  E_1^{pq}
  = \Rd^q{a_p}_*(K|X_p)
  \To \Rd^{p+q}a_*K
\tag{5.2.7.1}
$$
induced by [(5.1.12.2)](5.1-simplicial-topological-spaces.qmd#iii-5.1.12).
:::
