---
title: 6.1 Classifying spaces
---

{{< include ../macros.qmd >}}

::: {.rmenv #env-iii-6.1.1 number="6.1.1"}
Let $u\colon X\to S$ be a continuous map.
For every sheaf $F$ on $S$, the sheaf $u^*F$ is endowed with a "descent data" with respect to $u$, i.e. we have an isomorphism between the two inverse images of $u^*F$ on $X\times_S X$, and this isomorphism satisfies a cocycle condition.
If $u$ admits a section locally on $S$, then this construction defines an equivalence between the category of sheaves on $S$ and that of sheaves on $X$ endowed with a descent data.

Take $X$ to be a (left) principal homogeneous space for the group $G$ on a space $S$.
Then the $G$-equivariant sheaves on $X$ are exactly the sheaves endowed with a descent data: every equivariant sheaf on $X$ is, in a unique way (as an equivariant sheaf), the inverse image of a sheaf on $S=X/G$.
:::

:::: {.rmenv #env-iii-6.1.2 number="6.1.2"}
If a topological group $G$ acts on a space $X$, then $G$ acts on $G^{\Delta_n}\times X$ by
$$
  g\cdot(g_0,\ldots,g_n,x)
  = (g_0g^{-1},\ldots,g_ng^{-1},gx).
$$
We denote by $[X/G]_\bullet$ the simplicial space
$$
  [X/G]_\bullet
  = \big((G^{\Delta_n}\times X)/G\big)_{n\geqslant0}.
\tag{6.1.2.1}
$$

a. If $X$ is a principal homogeneous space for the group $G$ on $S=X/G$, then the map
    $$
      \begin{aligned}
        G^{\Delta_n}\times X
        &\to X^{\Delta_n}
      \\(g_0,\ldots,g_n,x)
        &\mapsto (g_0x,\ldots,g_nx)
      \end{aligned}
    $$
    identifies $[X/G]_n$ with the iterated fibre product $(X/S)^{\Delta_n}$:
    $$
      \cosq(X\to S)
      = ([X/G]_\bullet\to S).
    $$
    \oldpage{17}
    In particular, we have (by (iii) of [(5.3.5)](5.3-cohomological-descent.qmd#iii-5.3.5))
    $$
      \HH^\bullet([X/G]_\bullet)
      \simeq \HH^\bullet(X/G)
    \tag{6.1.2.2}
    $$
    (for a principal homogeneous space).

b. For all $n$, $G^{\Delta_n}\times X$ is a principal homogeneous space for the group $G$ on $[X/G]_n$.
    For every equivariant sheaf $F$ on $X$, $\pr_2^*F$ is an equivariant sheaf on $G^{\Delta_n}\times X$;
    by [(6.1.1)](#iii-6.1.1), the latter is the inverse image of $F^n$ on $[X/G]_n$.
    Every equivariant sheaf $F$ on $X$ thus defines a sheaf on $[X/G]_\bullet$.
    It is easy to show that we thus obtain an equivalence between the category of equivariant sheaves on $X$ and the category of sheaves $F^\bullet$ on $[X/G]_\bullet$ that satisfy

    **(\*)** For every $f\colon\Delta_n\to\Delta_m$, the structure morphism $f^*F^n\to F^m$ is an isomorphism.

c. Construction (b) above is natural in $(G,X,F)$.
    We set
    $$
      \HH^\bullet(X,G;F)
      = \HH^\bullet([X/G]_\bullet,F^\bullet)
    \tag{6.1.2.3}
    $$
    (mixed cohomology of $X,G$ with coefficients in $F$).
    Under the hypotheses of (a), if $F$ is the inverse image of $F^{-1}$ on $S=X/G$, then
    $$
      \HH^\bullet(X,G;F)
      = \HH^\bullet(X/G,F^{-1})
    \tag{6.1.2.4}
    $$
    (for a principal homogeneous space).
    This generalises [(6.1.2.2)](#iii-6.1.2) (which is the case $F=\underline{\ZZ}$).
::::

::: {.rmenv #env-iii-6.1.3 number="6.1.3"}
Let $P^t$ be the topological space consisting of a single point.
We define the **simplicial classifying space** of $G$, denoted $B_{\bullet G}$, to be the simplicial space
$$
  B_{\bullet G}
  = [P^t/G]_\bullet.
$$
Let $P$ be a principal homogeneous space for the group $G$ on $S$.
The evident morphism
$$
  \cosq(P\to S)
  = [P/G]_\bullet
  \to [P^t/G]_\bullet
  = B_{\bullet G}
$$
defines a composite morphism
$$
  [P]
  \colon \HH^\bullet(B_{\bullet G})
  \to \HH^\bullet([P/G]_\bullet)
  \xleftarrow[(6.1.2.2)]{\sim} \HH^\bullet(S).
\tag{6.1.3.1}
$$

We will see below that, in good cases, $\HH^\bullet(B_{\bullet G})=\HH^\bullet(B_G)$, and that the image of $[P]$ consists of the **characteristic classes** of $P$.
:::

::: {.rmenv #env-iii-6.1.4 number="6.1.4"}
Let $G$ be a Lie group, $B_G$ a classifying space for $G$, and $a\colon U_G\to B_G$ the universal principal homogeneous $G$-space.
Let $X$ be a $G$-space;
then $X\times U_G$ is a principal homogeneous $G$-space over $X\times U_G/G$ such that, for every equivariant sheaf $F$ on $X$, $\pr_1^*F$ is the inverse image of a sheaf $F^G$ on $X\times U_G/G$.
Since $U_G$ is contractible, and by [(6.1.2.2)](#iii-6.1.2), we have
$$
  \HH^\bullet(X,G;F)
  \simto \HH^\bullet(X\times U_G,G;\pr_1^*F)
  \simfrom \HH^\bullet(X\times U_G/G,F^G).
\tag{6.1.4.1}
$$

In particular, for $X=P^t$,
$$
  \HH^\bullet(B_{\bullet G})
  = \HH^\bullet(B_G).
\tag{6.1.4.2}
$$

\oldpage{18}
We can see that the isomorphism in [(6.1.4.2)](#iii-6.1.4) is a particular case of [(6.1.3.1)](#iii-6.1.3) where $S=B_G$ and $P=U_G$.
:::

::: {.rmenv #env-iii-6.1.5 number="6.1.5"}
The spectral sequence in [(5.2.3.2)](5.2-cohomology-of-simplicial-topological-spaces.qmd#iii-5.2.3) for $B_{\bullet G}$
$$
  E_1^{pq}
  = \HH^q(G^{\Delta_p}/G)
  \To \HH^{p+q}(B_{\bullet G})
  =\HH^{p+q}(B_G)
$$
is essentially the **Eilenberg–Moore spectral sequence**.
We briefly recall how it allows us to relate the rational cohomologies of $G$ and of $B_G$, for connected $G$.

a. The algebra $\HH^\bullet(G,\QQ)$ is a connected graded Hopf algebra of finite dimension over $\QQ$.
    If $P^\bullet(G)$ is the graded module of its primitive elements, then we have
    $$
      H^\bullet(G,\QQ)
      = \bigwedge P^\bullet(G)
    $$
    and the generators of $P^\bullet(G)$ are of odd degree.
b. The simplicial algebra $(E_1^{p\bullet})_{p\geqslant0}$ is
    $$
      E_1^{p\bullet}
      = \bigwedge\big(P^\bullet(G)^{\Delta_p}/P^\bullet(G)\big)
    $$
    which is the exterior algebra of the suspension of the constant cosimplicial module $P^\bullet(G)$;
    we thus have (by Quillen [@Q1968]) that $E_2^{p\bullet}=\Sym^p(P^\bullet(G))$.
    The pages $E_2^{pq}$ are only zero for $p+q$ even;
    we thus have that $E_2^{pq}=E_\infty^{pq}$, and, for a suitable filtration, we canonically have that
    $$
      \Gr\HH^\bullet(B_G,\QQ)
      \simeq \Sym^\bullet(P^\bullet(G)[-1])
    $$
    and non-canonically that
    $$
      \HH^\bullet(B_G,\QQ)
      \simeq \Sym^\bullet(P^\bullet(G)[-1]).
    $$
:::

::: {.rmenv #env-iii-6.1.6 number="6.1.6"}
Let $G$ be a (complex) linear algebraic group.

a. If $T$ is a maximal torus of $G$, with Weyl group $W$, then
    $$
      \HH^\bullet(B_G,\QQ)
      \simto \HH^\bullet(B_T,\QQ)^W.
    \tag{6.1.6.1}
    $$
b. If $T$ is a torus with character group $X(T)$, then
    $$
      \HH^\bullet(T,\ZZ)
      \simeq \bigwedge^\bullet X(T)
    \tag{6.1.6.2}
    $$
    (an isomorphism of graded Hopf algebras).


We will only use (a) in the following weaker form:

a'. *(The splitting principle).*
    The map $\HH^\bullet(B_G,\QQ)\to\HH^\bullet(B_T,\QQ)$ is injective.

For completion, we recall a proof of (a').

If $B$ is a Borel subgroup of $G$, then the bundle $U_G/B$ on $B_G$ is a fibre in flag spaces.
By [@D1968, 2.1 and 2.6.3], which is better explained in [@G1970, Proposition 3.1], or by [@B1956], the Leray spectral sequence of $U_G/B\to B_G$ degenerates to rational cohomology.
We thus have that $\HH^\bullet(B_G,\QQ)\hookrightarrow\HH^\bullet(U_G/B,\QQ)$.
We conclude by noting that $U_G/B\sim B_B\sim B_T$.
:::
