---
title: 7.1 Filtered derived category
---

{{< include ../macros.qmd >}}

This section completes [§1.4](../hodge-theory-ii/1.4-hypercohomology-of-filtered-complexes.qmd).

::: {.rmenv #env-iii-7.1.1 number="7.1.1"}
Let $\cat{A}$ be an abelian category.
We set:

- $\FF\cat{A}$ (resp. $\FF_2\cat{A}$)
    = the category of filtered (resp. bifiltered) objects with finite filtration(s) of $\cat{A}$.
- $\KK^+\FF\cat{A}$ (resp. $\KK^+\FF_2\cat{A}$)
    = the category of filtered (resp. bifiltered) bounded-below complexes of objects of $\cat{A}$, up to homotopy that respects the filtration(s).
- $\DD^+\FF\cat{A}$ (resp. $\DD^+\FF_2\cat{A}$)
    = the triangulated category induced from $\KK^+\FF\cat{A}$ (resp. from $\KK^+\FF_2\cat{A}$) by inverting the filtered (resp. bifiltered) quasi-isomorphisms [(1.3.6)](../hodge-theory-ii/1.3-the-two-filtrations-lemma.qmd#ii-1.3.6);
    this is the **derived filtered category** (resp. **derived bifiltered category**).
:::

::: {.rmenv #env-iii-7.1.2 number="7.1.2"}
A filtered quasi-isomorphism $u\colon(K,F)\to(K',F')$ induces an isomorphism of spectral sequences $u\colon E_\bullet^{\bullet\bullet}(K,F)\to E_\bullet^{\bullet\bullet}(K',F')$.
An object $K$ of $\DD^+\FF\cat{A}$ thus defines a spectral sequence $E_\bullet^{\bullet\bullet}(K)$.
\oldpage{24}
Similarly, an object $L$ of $\DD^+\FF_2\cat{A}$ defines an accumulation of spectral sequences of the type considered in [(1.4.9)](../hodge-theory-ii/1.4-hypercohomology-of-filtered-complexes.qmd#ii-1.4.9).
:::

::: {.rmenv #env-iii-7.1.3 number="7.1.3"}
Let $T$ be a left exact functor from $\cat{A}$ to an abelian category $\cat{B}$.
Suppose that every object of $\cat{A}$ injects into an injective object.
The functor $T$ can then be "derived" to give the functors
$$
  \Rd\colon
  \DD^+(\cat{A})
  \to \DD^+(\cat{B})
\tag{7.1.3.1}
$$
$$
  \Rd\colon
  \DD^+\FF(\cat{A})
  \to \DD^+\FF(\cat{B})
\tag{7.1.3.2}
$$
$$
  \Rd\colon
  \DD^+\FF_2(\cat{A})
  \to \DD^+\FF_2(\cat{B}).
\tag{7.1.3.3}
$$
They can be calculated as follows: if $K'$ is a $T$-acyclic resolution (resp. a filtered resolution, resp. a bifiltered resolution) of $K$ ([(1.4.5)](../hodge-theory-ii/1.4-hypercohomology-of-filtered-complexes.qmd#ii-1.4.5) and [(1.4.11)](../hodge-theory-ii/1.4-hypercohomology-of-filtered-complexes.qmd#ii-1.4.11)), then $\Rd T(K)=T(K')$.

The hypercohomology spectral sequence (for $T$) of $K\in\Ob\DD^+\FF(\cat{A})$ is the spectral sequence of $\Rd TK\in\Ob\DD^+\FF(\cat{B})$ (cf. [(1.4.5)](../hodge-theory-ii/1.4-hypercohomology-of-filtered-complexes.qmd#ii-1.4.5)).
:::

::: {.rmenv #env-iii-7.1.4 number="7.1.4"}
We will need more precise results for the functors $\Rd a_*$, where $a\colon X_\bullet\to S$ is an augmentation of a simplicial topological space.
The case $S=P^t$, where $\Rd a_*=\Rd\Gamma$ will suffice.

We reuse the notation of [(5.1.12)](5.1-simplicial-topological-spaces.qmd#iii-5.1.12), and recall [(5.2.6.1)](5.2-cohomology-of-simplicial-topological-spaces.qmd#iii-5.2.6):
$$
  \Rd a_*
  = \simp\Rd {a_\bullet}_*.
$$
For every complex $K\in\Ob\mathrm{C}^+(S_\bullet)$, the simple complex $\simp K$ is endowed with a natural filtration $L$ [(5.1.9.3)](5.1-simplicial-topological-spaces.qmd#iii-5.1.9).
A quasi-isomorphism $u\colon K'\simto K''$ induces a filtered quasi-isomorphism $u\colon(\simp K',L)\simto(\simp K'',L)$.
Then $\simp$ factors as
$$
  \simp\colon \DD^+(S_\bullet)
  \to \DD^+\FF(S)
$$
and $\Rd a_*$ factors as
$$
  \Rd a_*\colon \DD^+(X_\bullet)
  \to \DD^+\FF(S).
$$
The spectral sequence of the filtered complex $(\Rd a_* K,L)\in\DD^+\FF(S)$ is exactly [(5.2.7.1)](5.2-cohomology-of-simplicial-topological-spaces.qmd#iii-5.2.7).
:::

::: {.rmenv #env-iii-7.1.5 number="7.1.5"}
If $K$ is filtered (resp. bifiltered), then $\Rd{a_\bullet}_*K$ is filtered (resp. bifiltered): we have
$$
  \Rd{a_\bullet}_*
  \colon \DD^+\FF(X_\bullet)
  \to \DD^+\FF(S_\bullet)
\tag{7.1.5.1}
$$
$$
  \Rd{a_\bullet}_*
  \colon \DD^+\FF_2(X_\bullet)
  \to \DD^+\FF_2(S_\bullet).
\tag{7.1.5.2}
$$
:::

::: {.rmenv #env-iii-7.1.6 number="7.1.6"}
Let $K$ be a complex of cosimplicial sheaves on $S$, endowed with an increasing filtration $W$.
We define the **diagonal filtration** $\delta(W,L)$ of $W$ and $L$ to be the increasing filtration of $\simp K$ given by
$$
  \begin{aligned}
    \delta(W,L)_n(\simp K)
    &= \bigoplus_{p,q} W_{n+p}(K^{p,q})
  \\&= \sum_p \simp(W_{n+p}(K)) \cap L^p(\simp K).
  \end{aligned}
\tag{7.1.6.1}
$$

\oldpage{25}
We have
$$
  \Gr_n^{\delta(W,L)}(\simp K)
  \simeq \bigoplus_p \Gr_{n+p}^W(K^{\bullet p})[-p].
\tag{7.1.6.2}
$$

The functor $(K,W)\mapsto(\simp K,\delta(W,L))$ sends filtered quasi-isomorphisms to filtered quasi-isomorphisms, and defines
$$
  \begin{aligned}
    (s,\delta)
    \colon \DD^+\FF(S_\bullet)
    &\to \DD^+\FF(S)
  \\(K,W)
    &\mapsto (\simp K,\delta(W,L))
  \end{aligned}
\tag{7.1.6.3}
$$
whence, by composition with [(7.1.5.1)](#iii-7.1.5),
$$
  \begin{aligned}
    (\Rd\Gamma,\delta(-,L))
    \colon \DD^+\FF(X_\bullet)
    &\to \DD^+\FF(S)
  \\(K,W)
    &\mapsto (\Rd\Gamma K,\delta(W,L)).
  \end{aligned}
\tag{7.1.6.4}
$$
From [(7.1.6.2)](#iii-7.1.6), we see that
$$
  \Gr_n^{\delta(W,L)}
  = \bigoplus_p \Rd{a_p}_*(\Gr_{n+p}^W K)[-p].
\tag{7.1.6.5}
$$
:::

::: {.rmenv #env-iii-7.1.7 number="7.1.7"}
If $(K,W,F)$ is a bifiltered complex of cosimplicial sheaves, then $\simp K$ is endowed with the three filtrations $W$, $F$, and $L$, and defines different bifiltered complexes.

For example, for increasing $W$, the functor $(K,W,F)\mapsto(K,\delta(W,L),F)$ sends bifiltered quasi-isomorphisms to bifiltered quasi-isomorphisms, and thus defines
$$
  \begin{aligned}
    \DD^+\FF_2(S_\bullet)
    &\to \DD^+\FF_2(S)
  \\(K,W,F)
    &\mapsto (K,\delta(W,L),F).
  \end{aligned}
\tag{7.1.7.1}
$$
By composition with [(7.1.5.2)](#iii-7.1.5), we thus obtain
$$
  \begin{aligned}
    \DD^+\FF_2(X_\bullet)
    &\to \DD^+\FF_2(S)
  \\(K,W,F)
    &\mapsto (\Rd\Gamma K,\delta(W,L),F).
  \end{aligned}
\tag{7.1.7.2}
$$
and we have that
$$
  \Gr_n^{\delta(W,L)}(\Rd\Gamma K,F)
  = \bigoplus_p \Rd{a_p}_*(\Gr_{n+p}^W K,F)[-p]
\tag{7.1.7.3}
$$
in $\DD^+\FF(S)$.
:::
