---
title: 9.1 Cohomology of groups and of classifying spaces
---

{{< include ../macros.qmd >}}

Let $G$ be a complex connected linear algebraic group.
We intend to calculated the mixed Hodge structure of $\HH^\bullet(G)$.
We will start by calculating that of $\HH^\bullet(\BB_{\bullet G})$, by reduction to the case of tori;
we will then calculate that of $\HH^\bullet(G)$ via the Eilenberg–Moore spectral sequence [(6.1.5)](6.1-classifying-spaces.qmd#iii-6.1.5).
As a bonus, we obtain the strange Theorem [(9.1.7)](#iii-9.1.7).

::: {.itenv #env-iii-9.1.1 number="9.1.1" taxon="Theorem"}
Let $G$ be a linear algebraic group.
We have that $\HH^{2n+1}(\BB_{\bullet G},\QQ)=0$, and that $\HH^{2n}(\BB_{\bullet G},\QQ)\otimes\CC$ is pure of type $(n,n)$ [(0.5)](terminology-and-notation.qmd#iii-0.5).
:::

::: {.proof}
Let $G^0$ be the identity component of $G$, and let $T\subset G^0$ be a maximal torus.
Since $\HH^\bullet(\BB_{\bullet G},\QQ)=\HH^\bullet(\BB_{\bullet G^0},\QQ)^{G/G^0}$, we have, by the **splitting principle** (see [(6.1.6)](6.1-classifying-spaces.qmd#iii-6.1.6))
$$
  \HH^\bullet(\BB_{\bullet G},\QQ)
  \hookrightarrow \HH^\bullet(\BB_{\bullet T},\QQ).
$$
This inclusion is a morphism of mixed Hodge structures: it suffices to consider the case of a torus, or even, by the Künneth formula, the case where $G=\Gm$.
Here are two proofs of [(9.1.1)](#iii-9.1.1) in this case.
}

*1st proof. —*
The cohomology of $\Gm$ (i.e. of the projective line minus two points) is $\HH^0=\HH^1=\ZZ$.
The only Hodge numbers $h^{pq}$ of $\HH^1(\Gm)$ that can be non-zero are $h^{01}=h^{10}$ and $h^{11}$ ((i) and (iv) of [(8.2.4)](8.2-separated-algebraic-spaces.qmd#iii-8.2.4)).
Since $h^{01}+h^{10}+h^{11}=2h^{01}+h^{11}=1$, we have that $h^{01}=0$, and so $\HH^1(\Gm)$ is pure of type $(1,1)$ (for another proof, see [(10.3.8)](10.3-algebraic-interpretation-of-the-mixed-H1-the-case-of-curves.qmd#iii-10.3.8)).
The $E_2^{p,q}$ page of the spectral sequence [(6.1.5)](6.1-classifying-spaces.qmd#iii-6.1.5), which is zero for odd $p+q$, is thus pure of type $((p+q)/2,(p+q)/2)$.
Its abutment has the same homogeneity.

*2nd proof. —*
We know that $\PP^r(\CC)$, endowed with $\OO(1)$, is an "approximation" of $\BB_{\Gm}$: the homomorphism $[\OO(1)]\colon\HH^i(\BB_{\bullet\Gm})\to\HH^i(\PP^r(\CC))$ is bijective for $i\leqslant 2r$.
The cohomology group $\HH^{2i}(\PP^r(\CC))$ is generated by the cohomology class of an algebraic cycle (that is, a linear subspace), and is thus of type $(i,i)$.
The following proposition allows us to deduce that $\HH^{2i}(\BB_{\Gm})$ is of type $(i,i)$.
:::

::: {.itenv #env-iii-9.1.2 number="9.1.2" taxon="Proposition"}
Let $G$ be an algebraic group (over $\CC$), and $P$ a (algebraic) principal homogeneous space of group $G$ over a scheme $X$.
\oldpage{46}
Then the morphism
$$
  [P]\colon\HH^\bullet(\BB_G)=\HH^\bullet(\BB_{\bullet G})
  \to \HH^\bullet(X)
$$
is a morphism of mixed Hodge structures.
:::

::: {.proof}
This follows from the definition [(6.1.3.1)](6.1-classifying-spaces.qmd#iii-6.1.3)  of $[P]$ and from functoriality [(8.3.4)](8.3-hodge-theory-of-simplicial-schemes.qmd#iii-8.3.4).
:::

::: {.itenv #env-iii-9.1.3 number="9.1.3" taxon="Corollary"}
The characteristic classes, in $\HH^{2n}(S)$, of a (algebraic) principal homogeneous space $P$ over $S$, with structure group a linear group $G$, are pure of type $(n,n)$: they come from morphisms $\QQ(-n)\to\HH^{2n}(S,\QQ)$.
:::

In the particular case where $S$ is smooth and quasi-projective, we know that the characteristic classes of $P$ are even algebraic, i.e. in the image of the Chow ring $(\otimes\QQ)$.

::: {.rmenv #env-iii-9.1.4 number="9.1.4"}
Let $G$ be a linear algebraic group over a finite field $\field{F}_q$, and let $\overline{G}/\overline{\field{F}}_q$ be the group induced by extension of scalars to an algebraic closure of $\field{F}_q$.
A proof parallel to that of [(9.1.1)](#iii-9.1.1) shows that, in $\ell$-adic cohomology, the proper values of the (geometric) Frobenius acting on $\HH^{2n}(\BB_{\bullet\overline{G}},\QQ_\ell)$ are of the form $q^n\zeta$ (with $\zeta$ a root of unity).
This agrees with the philosophy of [I §3](../hodge-theory-i).
Similarly, the statement of [(9.1.5)](#iii-9.1.5) below is inspired by the formulas that give the number of points of reductive groups over finite fields.
:::

::: {.itenv #env-iii-9.1.5 number="9.1.5" taxon="Theorem"}
Let $G$ be a connected linear algebraic group.
Let $P^\bullet\subset\HH^\bullet(G,\QQ)$ be the primitive part of the Hopf algebra $\HH^\bullet(G,\QQ)$.
It is a mixed Hodge substructure.
We have that $P^{2i}(G)=0$, and $P^{2i-1}(G)$ is pure of type $(i,i)$.
Finally, the isomorphism
$$
  \bigwedge P^\bullet(G)
  \to \HH^\bullet(G,\QQ)
\startverb\tag{9.1.5.1}\stopverb
$$
is an isomorphism of mixed Hodge structures.
:::

::: {.proof}
In the spectral sequence [(6.1.5)](6.1-classifying-spaces.qmd#iii-6.1.5) , $E^{0,q}=0$ for $q>0$.
For $n>0$, the \em{edge homomorphism}
$$
  \HH^{2n}(\BB_G,\QQ)
  \to E_1^{1,2n}
  = \HH^{2n-1}(G,\QQ)
$$
is a morphism of mixed Hodge structures [(8.3.5)](8.3-hodge-theory-of-simplicial-schemes.qmd#iii-8.3.5);
its image $P^{2n-1}(G)$ is thus a mixed Hodge substructure, and is pure of type $(n,n)$ by [(9.1.1)](#iii-9.1.1).
The isomorphism [(9.1.5.1)](#iii-9.1.5) is given by the cup product, and we conclude by [(8.2.11)](8.2-separated-algebraic-spaces.qmd#iii-8.2.11).
:::

::: {.itenv #env-iii-9.1.6 number="9.1.6" taxon="Corollary"}
Let $G$ be a linear algebraic group.
For $n>0$, we have that
$$
  W_n(\HH^n(G,\QQ))
  = 0.
$$
:::

::: {.proof}
We can reduce to the case where $G$ is connected, and then apply [(9.1.5)](#iii-9.1.5).
:::

::: {.itenv #env-iii-9.1.7 number="9.1.7" taxon="Theorem"}
Let $X$ be a smooth and proper algebraic space on which a connected linear algebraic group $G$ acts via $\rho\colon G\times X\to X$.
Then the diagram
```tikz
\begin{tikzcd}
  \HH^\bullet(X,\QQ)
    \ar[r,"\rho^*"]
    \ar[d,equals]
  & \HH^\bullet(X,\QQ)\otimes\HH^\bullet(G,\QQ)
\\\HH^\bullet(X,\QQ)\otimes_\QQ\QQ
    \ar[r,equals]
  & \HH^\bullet(X,\QQ)\otimes\HH^0(G,\QQ)
    \ar[u]
\end{tikzcd}
```
commutes.
:::

::: {.proof}
Since the composite map
$$
  \HH^\bullet(X,\QQ)
  \xrightarrow{p^*} \HH^\bullet(X,\QQ)\otimes\HH^\bullet(G,\QQ)
  \to \HH^\bullet(X,\QQ)\otimes\HH^0(G,\QQ)
  = \HH^\bullet(X,\QQ)
$$
is the identity (the composite $X=\{e\}\times X\to G\times X\to X$ is the identity), it suffices to prove that, for $i>0$, the $i$-th Künneth component of $\rho^*$
$$
  \rho_i^*\colon \HH^n(X,\QQ)
  \to \HH^{n-i}(X,\QQ)\otimes\HH^i(G,\QQ)
$$
is zero.
Since $\HH^n(X,\QQ)$ is pure of weight $n$, and $\HH^{n-i}(X,\QQ)$ is pure of weight $n-i$, we have that
$$
  \Im(\HH^n(X,\QQ))
  \subset W_n(\HH^{n-i}(X,\QQ)\otimes\HH^i(G,\QQ))
  = \HH^{n-i}(X,\QQ)\otimes W_i\HH_i(G,\QQ).
$$
By [(9.1.6)](#iii-9.1.6), this image is thus null.
:::

::: {.rmenv #env-iii-9.1.8 number="9.1.8" taxon="Variant"}
Let $X$ be a separated algebraic space on which a connected linear group $G$ acts.

i. If $X$ is smooth, and $\overline{X}$ is a compactification of $X$, then the diagram

    ```tikz
    \begin{tikzcd}
      \HH^\bullet(\overline{X},\QQ)
        \ar[r]
        \ar[d]
      & \HH^\bullet(X,\QQ)
        \ar[r,"\rho^*"]
      & \HH^\bullet(X,\QQ)\otimes\HH^\bullet(G,\QQ)
    \\\HH^\bullet(X,\QQ)
        \ar[rr,equals]
      && \HH^\bullet(X,\QQ)\otimes\HH^0(G,\QQ)
        \ar[u,hook]
    \end{tikzcd}
    ```
    commutes.
ii. If $X$ is proper, and $\widetilde{X}$ is a resolution of singularities of $X$, then the diagram
    ```tikz
    \begin{tikzcd}
      \HH^\bullet(X,\QQ)
        \ar[r,"\rho^*"]
        \ar[d]
      & \HH^\bullet(X,\QQ)\otimes\HH^\bullet(G,\QQ)
        \ar[r]
      & \HH^\bullet(\widetilde{X},\QQ)\otimes\HH^\bullet(G,\QQ)
    \\\HH^\bullet(\widetilde{X},\QQ)
        \ar[rr,equals]
      && \HH^\bullet(\widetilde{X},\QQ)\otimes\HH^0(G,\QQ)
        \ar[u,hook]
    \end{tikzcd}
    ```
    commutes.
:::

::: {.proof}
It suffices to prove that, for $i>0$, the Künneth components
\oldpage{48}
$$
  \begin{gathered}
    \HH^n(\overline{X},\QQ)
    \to \HH^n(X,\QQ)
    \to \HH^{n-i}(X,\QQ)\otimes\HH^i(G,\QQ)
  \\(\text{resp.}\quad
    \HH^n(X,\QQ)
    \to \HH^{n-i}(X,\QQ)\otimes\HH^i(G,\QQ)
    \to \HH^{n-i}(\widetilde{X},\QQ)\otimes\HH^i(G,\QQ)
    )
  \end{gathered}
$$
are zero.
In case (i) (resp. case (ii)), we have [(8.2.4)](8.2-separated-algebraic-spaces.qmd#iii-8.2.4)
$$
  \begin{gathered}
    W_n\HH^n(\overline{X},\QQ)
    = \HH^n(\overline{X},\QQ)
  \\(\text{resp.}\quad
    W_n\HH^n(X,\QQ)
    = \HH^n(X,\QQ)
    )
  \end{gathered}
$$
and so, by [(8.2.4)](8.2-separated-algebraic-spaces.qmd#iii-8.2.4) and [(9.1.6)](#iii-9.1.6),
$$
  \begin{gathered}
    W_n(\HH^{n-i}(X,\QQ)\otimes\HH^i(G,\QQ))
    = 0
  \\(\text{resp.}\quad
    W_n(\HH^{n-i}(\widetilde{X},\QQ)\otimes\HH^i(G,\QQ))
    = 0
    )
  \end{gathered}
$$
whence the claim.
:::
