---
title: 9.2 Hodge theory of smooth hypersurfaces, following Griffiths
---

{{< include ../macros.qmd >}}

This section depends only on [Hodge Theory I, §1 to §3](../hodge-theory-i).
We will explain Theorem (8.6) of [@G1969].

::: {.rmenv #env-iii-9.2.1 number="9.2.1"}
Let $X$ be a smooth and proper algebraic variety, and $Y$ a smooth divisor in $X$.
Let $j$ be the inclusion of $U=X\setminus Y$ into $X$.
We have that $\Rd^i j_*\ZZ=0$ for $i\neq0,1$, and the Leray spectral sequence for $j$ can be identified with the long exact sequence of cohomology
$$
  \ldots
  \to \HH_Y^n(X)
  \to \HH^n(X)
  \to \HH^n(U)
  \xrightarrow{\partial} \ldots
\tag{9.2.1.1}
$$
with
$$
  \HH_Y^n(X)
  = \HH^{n-2}(Y,\sHH_Y^2).
$$

For a reason that was made clear in [(3.1.9)](../hodge-theory-ii/3.1-logarithmic-poles-and-residues.qmd#ii-3.1.9), we identify $\sHH_Y^2$ with the constant sheaf $\ZZ(-1)_\ZZ$.
Since the Leray spectral sequence for $j$ converges, by definition, to the mixed Hodge structure of $\HH^n(U)$, we find that the exact sequence
$$
  \ldots
  \to \HH^{n-2}(Y,\ZZ)(-1)
  \to \HH^n(X,\ZZ)
  \to\HH^n(U,\ZZ)
  \xrightarrow{\partial} \ldots
\tag{9.2.1.2}
$$
is an exact sequence of mixed Hodge structures.

The Leray spectral sequence for $j$ is also the spectral sequence of the filtered complex $(\Omega_X^\bullet(\log Y),W)$;
the exact sequence above can thus also be identified with that induced by the short exact sequence
$$
  0
  \to \Omega_X^\bullet
  \to \Omega_X^\bullet(\log Y)
  \xrightarrow{\Res} \Omega_Y^\bullet
  \to 0.
\tag{9.2.1.3}
$$
For this reason, the homomorphism $\partial$ in [(9.2.1.2)](#iii-9.2.1) is also called the **residue operator**.
:::

::: {.rmenv #env-iii-9.2.2 number="9.2.2"}
The residue operator
$$
  \Res\colon
  \HH^{n+1}(U,\ZZ)
  \to \HH^n(Y,\ZZ)(-1)
\tag{9.2.2.1}
$$
is strictly compatible with the Hodge filtration.
The Hodge filtration of $\HH^n(U,\CC)$ thus determines that of $\Ker(\HH^n(Y,\CC))\to\HH^{n+2}(X,\CC)$.

\oldpage{49}
Suppose that $Y$ is ample.
If $X$ is pure of dimension $N+1$, then $\HH^i(X,\ZZ)\simto\HH^i(Y,\ZZ)$ for $i<N$ (Lefschetz).
By Poincaré duality, for $i\neq N$, $\HH^i(Y,\CC)$ can thus be calculated from $\HH^\bullet(X,\CC)$.
Set
$$
\begin{aligned}
  \HH_\ev^N(Y,\CC)
  &= \Ker(\HH^N(Y,\CC)\to\HH^{N+2}(X,\CC))
\\&= \text{orthogonal complement of }\HH^N(X,\CC)\hookrightarrow\HH^N(Y,\CC)
\end{aligned}
$$
(the evanescent part of the cohomology).
We have that
$$
  \HH^N(Y,\CC)
  = \HH_\ev^N(Y,\CC)\oplus\HH^N(X,\CC)
$$
and we thus obtain a lot of information about the Hodge structure of $\HH^\bullet(Y,\CC)$ when we know about that of $\HH^\bullet(X,\CC)$ and the Hodge filtration of $\HH^{N+1}(U,\CC)$.
:::

::: {.rmenv #env-iii-9.2.3 number="9.2.3"}
By definition, the Hodge filtration of $\HH^\bullet(U,\CC)$ is the abutment of the spectral sequence that **degenerates** at $E_1$
$$
  E_1^{pq}
  = \HH^q(X,\Omega_X^p(\log Y))
  \To \HH^{p+q}(U,\CC).
$$
By [(3.1.11)](../hodge-theory-ii/3.1-logarithmic-poles-and-residues.qmd#ii-3.1.11), this spectral sequence agrees with the spectral sequence of the complex $j_*\Omega_U^\bullet$ endowed with the filtration given by the order of the pole $P$.

In particular, we have that
$$
  F^p(\HH^\bullet(U,\CC))
  = \bHH^\bullet(X,P^p(j_*\Omega_U^\bullet)).
$$
Recall that $P^p(j_*\Omega_U^\bullet)$ is the following complex
$$
  \Omega_X^p(Y)
  \to \Omega_X^{p+1}(2Y)
  \to \ldots
  \to \Omega_X^i((i-p+1)Y)
  \to \ldots
$$
with the first non-zero component placed in degree $p$.

If $\HH^i(X,\Omega_X^p(nY))=0} for $i>0$, $n>0$, and $p\geqslant0$, then we simply have
$$
  \bHH^\bullet(X,P^p(j_*\Omega_U^\bullet))
  = \HH^\bullet(\Gamma(X,P^p(j_*\Omega_U^\bullet)))
$$
whence the following result.
:::

::: {.itenv #env-iii-9.2.4 number="9.2.4" taxon="Proposition"}
Suppose that $\HH^i(X,\Omega_X^p(nY))=0$ for $i>0$, $n>0$, and $p\geqslant0$ (which is the case if $Y$ is sufficiently ample).
Then a cohomology class $c\in\HH^d(U,\CC)$ is of Hodge filtration $\geqslant p$ if and only if it can be represented by a closed $d$-form $\alpha$ on $U$, with a pole of order $\leqslant d-p+1$ along $Y$.
If $\alpha$ is a closed form on $U$, with a pole of order $k$ along $Y$, and if the class of $\alpha$ in $\HH^d(U,\CC)$ is zero, then $\alpha=d\beta$, with $\beta$ presenting a pole of order $\leqslant k-1$ along $Y$;
for $k\leqslant1$, we have that $\alpha=0$.
:::

::: {.rmenv #env-iii-9.2.5 number="9.2.5"}
It is well known (by a theorem of Bott) that the hypotheses of [(9.2.4)](#iii-9.2.4) are satisfied for $Y$ a hypersurface in the projective space $\PP^n(\CC)$ (for $n\geqslant1$), i.e. that
$$
  \HH^i(\PP^n(\CC),\Omega^j(m))
  = 0
  \quad
  \text{for }i>0\text{ and }m>0
$$
(a demonstration appears in [SGA 7, XI], for example).
Furthermore, for $n>1$, the residue map identifies $\HH^n(U,\CC)$ with the primitive part of the cohomology of $\HH^{n-1}(Y,\CC)$.
Thus ([@G1969, (8.6)]):
:::

::: {.itenv #env-iii-9.2.6 number="9.2.6" taxon="Proposition"}
Let $Y$ be a smooth hypersurface in $\PP^n(\CC)$ (with $n>1$) and $U=\PP^n(\CC)\setminus Y$.
\oldpage{50}

i. For a primitive cohomology class $c\in\HH^{n-1}(Y,\CC)$ to be of Hodge filtration $\leqslant p$, it is necessary and sufficient that it be the residue of a regular differential $n$-form on $U$, with a pole of order $\leqslant n-p$ along $Y$.
ii. Let $\alpha$ be a regular differential $n$-form on $U$, with a pole of order $k\geqslant1$ along $Y$.
    For $\Res(\alpha)\in\HH^{n-1}(Y,\CC)$ to be zero, it is necessary and sufficient that $\alpha=d\beta$ with $\beta$ an $(n-1)$-form on $U$ with a pole of order $\leqslant k-1$ along $Y$.
:::
