---
title: "Hodge Theory III"
year: 1974
---

{{< include ../macros.qmd >}}

::: {.callout .original}
Deligne, P. "Théorie de Hodge III".

*Publications Mathématiques de l'IHÉS* **44** (1974) pp. 5--77.

[publications.ias.edu/node/373](https://publications.ias.edu/node/373)
:::


## Table of contents


- [Introduction](introduction.qmd)
- [Terminology and notation](terminology-and-notation.qmd)
5. Cohomological descent
    - [5.1 Simplicial topological spaces](5.1-simplicial-topological-spaces.qmd)
    - [5.2 Cohomology of simplicial topological spaces](5.2-cohomology-of-simplicial-topological-spaces.qmd)
    - [5.3 Cohomological descent](5.3-cohomological-descent.qmd)
6. Examples of simplicial topological spaces
    - [6.1 Classifying spaces](6.1-classifying-spaces.qmd)
    - [6.2 Construction of hypercovers](6.2-construction-of-hypercovers.qmd)
    - [6.3 Relative cohomology](6.3-relative-cohomology.qmd)
    - [6.4 Multi-simplicial spaces](6.4-multi-simplicial-spaces.qmd)
7. Supplements to §1
    - [7.1 Filtered derived category](7.1-filtered-derived-category.qmd)
    - [7.2 Supplements to the two-filtrations lemma](7.2-supplements-to-the-two-filtrations-lemma.qmd)
8. Hodge theory of algebraic spaces
    - [8.1 Hodge complexes](8.1-hodge-complexes.qmd)
    - [8.2 Separated algebraic spaces](8.2-separated-algebraic-spaces.qmd)
    - [8.3 Hodge theory of simplicial schemes](8.3-hodge-theory-of-simplicial-schemes.qmd)
9. Examples and applications
    - [9.1 Cohomology of groups and of classifying spaces](9.1-cohomology-of-groups-and-of-classifying-spaces.qmd)
    - [9.2 Hodge theory of smooth hypersurfaces, following Griffiths](9.2-hodge-theory-of-smooth-hypersurfaces-following-Griffiths.qmd)
    - [9.3 Construction of complexes of first-order differential operators](9.3-construction-of-complexes-of-first-order-differential-operators.qmd)
10. Hodge theory in level ≤1
    - [10.1 1-motives](10.1-1-motives.qmd)
    - [10.2 1-motives and bi-extensions](10.2-1-motives-and-bi-extensions.qmd)
    - [10.3 Algebraic interpretation of the mixed $\mathrm{H}^1$: the case of curves](10.3-algebraic-interpretation-of-the-mixed-H1-the-case-of-curves.qmd)
    - [10.4 Translations of a theorem of Picard](10.4-translations-of-a-theorem-of-Picard.qmd)
