---
title: Terminology and notation
---

{{< include ../macros.qmd >}}

::: {.rmenv #env-iii-0.1 number="0.1"}
Let $u\colon X\to Y$ be a continuous map between topological spaces.
We say that $u$ is **proper** if it is proper in the sense of Bourbaki (i.e. universally closed) and furthermore separated (i.e. the diagonal of $X\times_Y X$ is closed).
:::

::: {.rmenv #env-iii-0.2 number="0.2"}
Following Gabriel and Zisman, we say *simplicial* where we would have previously said semi-simplicial.
\oldpage{8}
:::

::: {.rmenv #env-iii-0.3 number="0.3"}
We denote by $A$ a Noetherian subring of $\RR$ such that $A\otimes\QQ$ is a field.
The useful cases are $A=\ZZ$, $\QQ$, or $\RR$.
:::

::: {.rmenv #env-iii-0.4 number="0.4"}
A **mixed Hodge $A$-structure** consists of an $A$-module $H_A$ of finite type, a finite increasing filtration $W$ on the $A\otimes\QQ$-vector space $H_{A\otimes\QQ}=H_A\otimes\QQ$, and a finite decreasing filtration $F$ on the $\CC$-vector space $H_\CC=H_A\otimes_A\CC$.
We demand that the $(\Gr_n^W(H_{A\otimes\QQ}),\Gr_n^W(F))$ be Hodge $A\otimes\QQ$-structures.
For $A=\ZZ$ (resp. $A=\QQ$), we recover [(2.3.1)](../hodge-theory-ii/2.3-mixed-structures.qmd#ii-2.3.1) (resp. [(2.3.8)](../hodge-theory-ii/2.3-mixed-structures.qmd#ii-2.3.8));
the results of [§2.3](../hodge-theory-ii/2.3-mixed-structures.qmd) carry over as they are.
:::

::: {.rmenv #env-iii-0.5 number="0.5"}
Let $\mathscr{E}$ be a subset of $\ZZ\times\ZZ$.
We say that a mixed Hodge structure $H$ is of **degree $\mathscr{E}$** if the Hodge numbers $h^{pq}$ are zero for $(p,q)\not\in\mathscr{E}$.
:::

::: {.rmenv #env-iii-0.6 number="0.6"}
From now on, we denote by $\Omega_X^\bullet(\log D)$ what we previously denoted by $\Omega_X^\bullet\langle D\rangle$ [(3.1.2)](../hodge-theory-ii/3.1-logarithmic-poles-and-residues.hmtl#ii-3.1.2).
:::

::: {.rmenv #env-iii-0.7 number="0.7"}
Unless explicitly stated otherwise, **scheme** means "scheme of finite type over $\CC$", and a **sheaf** on a scheme $X$ is a sheaf on the underlying topological space of $X_\an$.
:::
