--- 
title: "Regular singular differential equations"
author: "P. Deligne"
date: "1970"
original: 'Deligne, P. "Equations Différentielles à Points Singuliers Réguliers". Springer--Verlag, Lecture Notes in Mathematics **163** (1970). [`publications.ias.edu/node/355`](https://publications.ias.edu/node/355).'
bibliography: 978-3-540-05190-9.bib
nocite: '@*'
link-citations: true
csl: maths-translations.csl
reference-section-title: "Bibliography"
github-repo: "thosgood/translations"
favicon: "favicon.ico"
---

```{r, child = '_translator-note.Rmd'}
```

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\sbullet}{{\mathbin{\vcenter{\hbox{\scalebox{.5}{$\bullet$}}}}}}
\providecommand{\id}{\mathrm{Id}}
\providecommand{\PP}{\mathbb{P}}
\renewcommand{\AA}{\mathbb{A}}
\providecommand{\CC}{\mathbb{C}}
\providecommand{\QQ}{\mathbb{Q}}
\providecommand{\ZZ}{\mathbb{Z}}
\providecommand{\NN}{\mathbb{N}}
\providecommand{\dd}{\mathrm{d}}
\providecommand{\DD}{\mathrm{D}}
\providecommand{\pr}{\mathrm{pr}}
\providecommand{\II}{\mathrm{II}}
\providecommand{\RR}{\mathbf{R}}
\providecommand{\MM}{\mathrm{M}}
\providecommand{\GL}{\mathrm{GL}}
\providecommand{\SL}{\mathrm{SL}}
\providecommand{\SO}{\mathrm{SO}}
\providecommand{\tg}{\mathrm{tg}}
\providecommand{\an}{\mathrm{an}}
\providecommand{\detrow}[2]{\operatorname{det}(#1,#2)}
\providecommand{\simto}{\xrightarrow{\sim}}

\providecommand{\Spec}{\operatorname{Spec}}
\providecommand{\Ker}{\operatorname{Ker}}
\providecommand{\Coker}{\operatorname{Coker}}
\providecommand{\Hom}{\operatorname{Hom}}
\providecommand{\End}{\operatorname{End}}
\providecommand{\shHom}{\underline{Hom}}
\providecommand{\shEnd}{\underline{End}}
\providecommand{\HH}{\operatorname{H}}
\providecommand{\Gr}{\operatorname{Gr}}
\providecommand{\tr}{\operatorname{tr}}
\providecommand{\Res}{\operatorname{Res}}
\providecommand{\codim}{\operatorname{codim}}


<!-- Content -->

\bigskip

_[Trans.]_ We have made changes following the errata, which was written in April 1971, by P.Deligne, at Warwick University.

**TO-DO: numbering of chapters/sections**

# (PART\*) Preliminaries {-}

# **0.** Introduction {-}

If $X$ is a (non-singular) complex-analytic manifold, then there is an equivalence between the notions of
\oldpage{1}

a. local systems of complex vectors on $X$ ; and
b. vector bundles on $X$ endowed with an integrable connection.

The latter of these two notions can be adapted in an evident way to the case where $X$ is a non-singular algebraic variety over a field $k$ (which we will take here to be of characteristic $0$).
However, general algebraic vector bundles with integrable connections are pathological (see [(II.6.19)](#II.6.19));
we only obtain a reasonable theory if we impose a "regularity" condition at infinity.
By a theorem of Griffiths [@8], this condition is automatically satisfied for "Gauss-Manin connections" (see [(II.7)](#II.7)).
In dimension one, this is closely linked to the idea of regular singular points of a differential equation (see [(I.4)](#I.4) and [(II.1)](#II.1)).

In Chapter I, we explain the different forms that the notion of an integrable connection can take.
In Chapter II, we prove the fundamental facts concerning regular connections.
In Chapter III, we translate certain results that we have obtained into the language of Nilsson class functions, and, as an application of the regularity theorem (see [(II.7)](#II.7)), we explain the proof by Brieskorn [@5] of the monodromy theorem.

These notes came from the non-crystalline part of a seminar given at Harvard during the autumn of 1969, under the title: "Regular singular differential equations and crystalline cohomology".

I thank the assistants of this seminar, who had to be subjected to often unclear talks, and who allowed me to find numerous simplifications.

I also thank N. Katz, with whom I had numerous and useful conversations, and to whom are due the principal results of section [(II.1)](#II.1).

## Notation and terminology {-}

\oldpage{2}
Within a single chapter, the references follow the decimal system.
A reference to a different chapter (resp. to the current introduction) is preceded by the Roman numeral of the chapter (resp. by 0).

We will use the following definitions:

::: {.trmenv #zero.1 title="0.1" latex="{0.1}"}
_analytic space_:
the analytic spaces are complex and of locally-finite dimension;
they are assumed to be $\sigma$-compact, but not necessarily separated.
:::

::: {.trmenv #zero.2 title="0.2" latex="{0.2}"}
_multiform function_:
a synonym for multivalued function --- for a precise definition, see [(I.6.2)](#I.6.2).
:::

::: {.trmenv #zero.3 title="0.3" latex="{0.3}"}
_immersion_:
following the tradition of algebraic geometers, immersion is a synonym for "embedding".
:::

::: {.trmenv #zero.4 title="0.4" latex="{0.4}"}
_smooth_:
a morphism $f\colon X\to S$ of analytic spaces is smooth if, locally on $X$, it is isomorphic to the projection from $D^n\times S$ to $S$, where $D^n$ is an open polydisc.
:::

::: {.trmenv #zero.5 title="0.5" latex="{0.5}"}
_locally paracompact_:
a topological space is locally paracompact if every point has a paracompact neighbourhood (and thus a fundamental system of paracompact neighbourhoods).
:::

::: {.trmenv #zero.6 title="0.6" latex="{0.6}"}
non-singular (or smooth) _complex algebraic variety_:
a smooth scheme of finite type over $\Spec(\mathbb{C})$.
:::

::: {.trmenv #zero.7 title="0.7" latex="{0.7}"}
(complex) _analytic manifold_:
a non-singular (or smooth) analytic space.
:::

::: {.trmenv #zero.8 title="0.8" latex="{0.8}"}
_covering_:
following the tradition of topologists, a covering is a continuous map $f\colon X\to Y$ such that every point $y\in Y$ has a neighbourhood $V$ such that $f|V$ is isomorphic to the projection from $F\times V$ to $V$, where $F$ is discrete.
:::


# (PART) Dictionary {-}

# Overview {-}

In this chapter, we explain the relations between various aspects and various uses of the notion of "local systems of complex vectors".
The equivalence between the points of view considered has been well known for a long time.

\oldpage{3}

We do not consider the "crystalline" point of view;
see [@4; @10].


# **1.** Local systems and the fundamental group {- #I.1}

::: {.rmenv #I.1.1 title="Definition 1.1" latex="{Definition 1.1}"}
Let $X$ be a topological space.
A _complex local system_ on $X$ is a sheaf of complex vectors on $X$ that, locally on $X$, is isomorphic to a constant sheaf $\mathbb{C}^n$ (n$\in\mathbb{N}$).
:::

::: {.rmenv #I.1.2 title="1.2" latex="{1.2}"}
Let $X$ be a locally path-connected and locally simply path-connected topological space, along with a basepoint $x_0\in X$.
To avoid any ambiguity, we point out that:

a. The fundamental group $\pi_1(X,x_0)$ of $X$ at $x_0$ has elements given by homotopy classes of loops based at $x_0$;
b. If $\alpha,\beta\in\pi_1(X,x_0)$ are represented by loops $a$ and $b$, then $\alpha\beta$ is represented by the loop $ab$ obtained by juxtaposing $b$ and $a$, in that order.

Let $\scr{F}$ be a locally constant sheaf on $X$.
For every path $a\colon[0,1]\to X$, the inverse image $a^*\scr{F}$ of $\scr{F}$ on $[0,1]$ is a locally constant, and thus constant, sheaf, and there exists exactly one isomorphism between $a^*\scr{F}$ and the constant sheaf defined by the set $(a^*\scr{F})_0 = \scr{F}_{a(0)}$.
This isomorphism defines an isomorphism $a(\scr{F})$ between $(a^*\scr{F})_0$ and $(a^*\scr{F})_1$, i.e. an isomorphism
$$
    a(\scr{F})\colon \scr{F}_{a(0)} \to \scr{F}_{a(1)}.
$$
This isomorphism depends only on the homotopy class of $a$, and satisfies $ab(\scr{F}) = a(\scr{F})\cdot b(\scr{F})$.
In particular, $\pi_1(X,x_0)$ acts (on the left) on the fibre $\scr{F}_{x_0}$ of $\scr{F}$ at $x_0$.
It is well known that:
:::

::: {.itenv #I.1.3 title="Proposition 1.3" latex="{Proposition 1.3}"}
Under the hypotheses of [(1.2)](#I.1.2), with $X$ connected, the functor $\scr{F}\mapsto\scr{F}_{x_0}$ is an equivalence between the category of locally constant sheaves on $X$ and the category of sets endowed with an action by the group $\pi_1(X,x_0)$.
:::

::: {.itenv #I.1.4 title="Corollary 1.4" latex="{Corollary 1.4}"}
Under the hypotheses of [(1.2)](#I.1.2), with $X$ connected, the functor $\scr{F}\mapsto\scr{F}_{x_0}$ is an equivalence between the category of complex local systems on $X$ and the category of complex finite-dimensional representations of $\pi_1(X,x_0)$.
:::

::: {.rmenv #I.1.5 title="1.5" latex="{1.5}"}
Under the hypotheses of [(1.2)](#I.1.2), if $a\colon[0,1]\to X$ is a path, and $b$ a loop based at $a(0)$, then $aba^{-1}=a(b)$ is a path based at $a(1)$.
Its homotopy class depends only on the homotopy classes of $a$ and $b$.
This construction defines an isomorphism between $\pi_1(X,a(0))$ and $\pi_1(X,a(1))$.
:::

:::: {.itenv #I.1.6 title="Proposition 1.6" latex="{Proposition 1.6}"}
Under the hypotheses of [(1.5)](#I.1.5), there exists, up to unique isomorphism, exactly one locally constant sheaf of groups $\Pi_1(X)$ on $X$ (_the fundamental groupoid_), endowed, for all $x_0\in X$, with an isomorphism

::: {.eqtag #I.1.6.1}
$$
  \Pi_1(X)_{x_0} \simeq \pi_1(X,x_0)
\tag{1.6.1}
$$
:::

and such that, for every path $a\colon[0,1]\to X$, the isomorphism in [(1.5)](#I.1.5) between $\pi_1(X,a(0))$ and $\pi_1(X,a(1))$ can be identified, via \hyperref[I.1.6.1]{(1.6.1)}, with the isomorphism in [(1.2)](#I.1.2) between $\Pi_1(X)_{a(0)}$ and $\Pi_1(X)_{a(1)}$.
::::

If $X$ is connected, with base point $x_0$, then the sheaf $\Pi_1(X)$ corresponds, via the equivalence in [(1.3)](#I.1.3), to the group $\pi_1(X,x_0)$ endowed with its action over itself by inner automorphisms.

::: {.itenv #I.1.7 title="Proposition 1.7" latex="{Proposition 1.7}"}
If $\scr{F}$ is a locally constant sheaf on $X$, then there exists exactly one action (said to be _canonical_) of $\Pi_1(X)$ on $\scr{F}$ that, at each $x_0\in X$, induces the action from [(1.2)](#I.1.2) of $\pi_1(X,x_0)$ on $\scr{F}$.
:::

# **2.** Integrable connections and local systems {- #I.2}

\oldpage{5}

:::: {.rmenv #I.2.1 title="2.1" latex="{2.1}"}
Let $X$ be an analytic space [(0.1)](#zero.1).
We define a (holomorphic) _vector bundle_ on $X$ to be a locally free sheaf of modules that is of finite type over the structure sheaf $\cal{O}$ of $X$.
If $\cal{V}$ is a vector bundle on $X$, and $x$ a point of $X$, then we denote by $\cal{V}_{(x)}$ the free $\cal{O}_{(x)}$-module of finite type of germs of sections of $\cal{V}$.
If $\mathfrak{m}_x$ is the maximal ideal of $\cal{O}_{(x)}$, then we define the _fibre at $x$ of the vector bundle $\cal{V}$_ to be the **TO-DO** of finite rank

::: {.eqtag #I.2.1.1}
$$
  \cal{V}_x = \cal{V}_{(x)} \otimes_{\cal{O}_{(x)}} \cal{O}_{(x)}/\mathfrak{m}_x.
\tag{2.1.1}
$$
:::

If $f\colon X\to Y$ is a morphism of analytic spaces, then the _inverse image_ of a vector bundle $\cal{V}$ on $Y$ is the vector bundle $f^*\cal{V}$ on $X$ given by the inverse image of $\cal{V}$ as a coherent module:
if $f^\sbullet\cal{V}$ is the sheaf-theoretic inverse image of $\cal{V}$, then

::: {.eqtag #I.2.1.2}
$$
  f^*\cal{V} \simeq \cal{O}_X \otimes_{f^*\cal{O}_Y} f^\sbullet\cal{V}
\tag{2.1.2}
$$
:::

In particular, if $x\colon P\to X$ is the morphism from the point space $P$ to $X$ defined by a point $x$ of $X$, then

::: {.eqtag #I.2.1.3}
$$
  \cal{V}_x \simeq x^*\cal{V}.
\tag{2.1.3}
$$
:::
::::

:::: {.rmenv #I.2.2 title="2.2" latex="{2.2}"}
Let $X$ be a complex-analytic manifold [(0.7)](#zero.7) and $\cal{V}$ a vector bundle on $X$.
The old school would have defined a (holomorphic) connection on $\cal{V}$ as the data, for every pair of points $(x,y)$ that are first order infinitesimal neighbours in $X$, of an isomorphism $\gamma_{y,x}\colon\cal{V}_x\to\cal{V}_y$ that depends holomorphically on $(x,y)$ and is such that $\gamma_{x,x}=\id$.

Suitably interpreted, this "definition" coincides with the currently fashionable definition [(2.2.4)](#I.2.2.4) given below (which we not be use in the rest of the section).

It suffices to take "point" to mean "point with values in any analytic space":

\oldpage{6}

::: {.rmenv #I.2.2.1 title="2.2.1" latex="{2.2.1}"}
_A point in an analytic space $X$ with values in an analytic space $S$_ is a morphism from $S$ to $X$.
:::

::: {.rmenv #I.2.2.2 title="2.2.2" latex="{2.2.2}"}
If $Y$ is a subspace of $X$, then the _$n$-th infinitesimal neighbourhood_ of $Y$ in $X$ is the subspace of $X$ defined locally by the $(n+1)$-th power of the ideal of $\cal{O}_X$ that defines $Y$.
:::

::: {.rmenv #I.2.2.3 title="2.2.3" latex="{2.2.3}"}
Two points $x,y\in X$ with values in $S$ are said to be _first order infinitesimal neighbours_ if the map $(x,y)\colon S\to X\times X$ that they define factors through the first order infinitesimal neighbourhood of the diagonal of $X\times X$.
:::

::: {.rmenv #I.2.2.4 title="2.2.4" latex="{2.2.4}"}
If $X$ is a complex-analytic manifold and $\cal{V}$ is a vector bundle on $X$, then a (_holomorphic_) _connection_ $\gamma$ on $\cal{V}$ consists of the following data:

for every pair $(x,y)$ of points of $X$ with values in an arbitrary analytic space $S$, with $x$ and $y$ first order infinitesimal neighbours, an isomorphism $\gamma_{x,y}\colon x^*\cal{V}\to y^*\cal{V}$;
this data is subject to the conditions:

i. (_Functoriality_) For any $f\colon T\to S$ and any first order infinitesimal neighbours $x,y\colon S\rightrightarrows X$, we have $f^*(\gamma_{y,x})=\gamma_{yf,xf}$.
ii. We have $\gamma_{x,x}=\id$.
:::
::::
