--- 
title: "A comment about the integral representation of the Riemann xi-function"
author: "George Pólya"
date: "1926"
original: 'Pólya, G. "Bemerkung Über die Integraldarstellung der Riemannschen $\xi$-Funktion". _Acta Math._ **48** (1926), 305--317. DOI: [10.1007/BF02565336](https://doi.org/10.1007/BF02565336).'
github-repo: "thosgood/translations"
favicon: "favicon.ico"
---

```{js, echo = FALSE}
$(document).ready(function(e) {gitbook.sidebar.toggle(false, false)});
```

```{r, child = '_translator-note.Rmd'}
```

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\newcommand{\dd}{\operatorname{d}\!}
\newcommand{\GG}{\frak{G}}
\newcommand{\UU}{\scr{U}}
\newcommand{\TT}{\scr{T}}
\renewcommand{\SS}{\scr{S}}
\newcommand{\error}{\cal{O}}

<!-- Content -->

*[Translator.] The numbering of the footnotes in the original has not been replicated in this translation, since this would have resulted in multiple footnotes with the same number on one page. We also thank [Juan Arias de Reyna](https://personal.us.es/arias/) for their Spanish translation of this paper, which helped greatly.*

The Riemann $\xi$-function, defined by the formula
\oldpage{305}
$$
  \xi(iz)
  =
  \frac12 \left(
    z^2 - \frac14
  \right) \pi^{-\frac{z}{2}-\frac14} \Gamma \left(
    \frac{z}{2} + \frac14
  \right) \zeta \left(
    \frac12 + z
  \right),
\tag{1}
$$
was represented by Riemann himself by an infinite trigonometric integral, namely^[B. Riemann, Werke (1876), S. 138.]
$$
  \xi(z) = 2\int_0^\infty \Phi(u)\cos(zu)\dd u
\tag{2}
$$
$$
  \Phi(u) = 2\pi e^{\frac{5u}{2}} \sum_{n=1}^\infty (2\pi e^{2u}n^2 - 3) n^2 e^{-n^2\pi e^{2u}}.
\tag{3}
$$
It is evident that
$$
  \Phi(u) \sim 4\pi^2 e^{\frac{9u}{2}-\pi e^{2u}}
  \quad\text{as }u\to+\infty.
\tag{4}
$$
Furthermore (see [§4](#section-4)), $\Phi(u)$ is an even function.
Therefore
$$
  \Phi(u) \sim 4\pi^2 \left(
    e^{\frac{9u}{2}} + e^{-\frac{9u}{2}}
  \right) e^{-\pi(e^{2u}+e^{-2u})}
  \quad\text{as }u\to\pm\infty.
\tag{5}
$$

\oldpage{306}
With regards to the Riemann hypothesis, one could ask the following question^[This was casually mentioned by Prof. Landau in a conversation in 1913.]: does the function given by replacing $\Phi(u)$ in the right-hand side of Equation (2) with the right-hand side of Equation (4) have only real zeros?

The answer is no (see [§4](#section-4)): the resulting function has infinitely many imaginary zeros.
If, however, the right-hand side of Equation (5) is used, instead of the right-hand side of Equation (4), then we obtain the function
$$
  \xi^*(z) = 8\pi^2 \int_0^\infty \left(
    e^{\frac{9u}{2}} + e^{-\frac{9u}{2}}
  \right) e^{-\pi(e^{2u}+e^{-2u})} \cos(zu) \dd u,
\tag{6}
$$
which one could call the "modified $\xi$-function", and $\xi^*(z)$ in fact *has only real zeros*.
Incidentally,
$$
  \xi(z) \sim \xi^*(z)
$$
if $z$ tends towards $\infty$ in some closed ray based at the point $0$ and not containing the real axis.
If we denote by $N(r)$ the number of zeros of $\xi(z)$ in the circular region $|z|\leq r$, and by $N^*(r)$ the number of zeros of $\xi^*(z)$ in the same region, then
$$
  N(r) \sim N^*(r)
$$
and even
$$
  N(r) - N^*(r) = O(\log r).
$$

In what follows, I provide a proof of the fact that all the zeros of $\xi^*(z)$ are real.
The proof focuses on another entire function, namely the function
$$
  \GG(z) = \GG(z;a) = \int_{-\infty}^{+\infty} e^{-a(e^u+e^{-u})+zu} \dd u,
\tag{7}
$$
which has some nice, simple properties.
The parameter $a$ is always a positive value.
We can express $\xi^*(z)$ in terms of $\GG(z)$.
\oldpage{307}
Indeed,
$$
  \xi^*(z) = 2\pi^2 \left\{
    \GG\left(
      \frac{iz}{2} - \frac94; \pi
    \right) +
    \GG\left(
      \frac{iz}{2} + \frac94; \pi
    \right)
  \right\}
\tag{8}
$$
as one can easily derive from Equations (6) and (7).
I will show that $\GG(iz)$ *has only real zeros*.
From this, the same property then easily follows for $\xi^*(z)$.


# 1 {.unnumbered #section-1}

The most important property of the entire function $\GG(z)$ is that is satisfies a simple difference equation;
namely
$$
  z\GG(z) = a(\GG(z+1) - \GG(z-1))
\tag{9}
$$
as can easily be proven by partial integration.
Note also that $\GG(z)$ is even:
$$
  \GG(-z) = \GG(z).
\tag{10}
$$
Furthermore, if $z$ is not an integer, then
$$
  \begin{aligned}
    \GG(z)
    &= a^{-z}\Gamma(z) \left(
      1 + \sum_{n=1}^\infty \frac{a^{2n}}{n!(1-z)(2-z)\ldots(n-z)}
    \right)
  \\&+ a^z\Gamma(-z) \left(
      1 + \sum_{n=1}^\infty \frac{a^{2n}}{n!(1+z)(2+z)\ldots(n+z)}
    \right).
  \end{aligned}
\tag{11}
$$

The proof of Equation (11) goes as follows: write
$$
  \Gamma(z)
  = \int_0^a e^{-v} v^{z-1} \dd v + \int_a^\infty e^{-v} v^{z-1} \dd v
  = P(z) + Q(z),
\tag{12}
$$
$$
  P(z) = P(z;a) = \sum_{n=0}^\infty \frac{(-1)^n a^{z+n}}{n!(z+n)},
\tag{13}
$$
$$
  Q(z) = Q(z;a) = a^z \int_0^\infty e^{-ae^u+uz} \dd u.
\tag{14}
$$

Now,
$$
  \begin{aligned}
    \GG(z)
    &= \int_0^\infty e^{-a(e^u+e^{-u})} (e^{uz}+e^{-uz}) \dd u
  \\&= \int_0^\infty \sum_{n=0}^\infty e^{-ae^u} \frac{(-a)^n}{n!} (e^{(-n+z)u}+e^{(-n-z)u}) \dd u.
  \end{aligned}
$$
From this it follows, by Equation (14), after exchanging the order of summation and integration (which can easily be justified by absolute convergence), that
\oldpage{308}
$$
  \GG(z)
  = a^{-z}\sum_{n=0}^\infty \frac{(-1)^n a^{2n}}{n!} Q(-n+z)
  + a^z\sum_{n=0}^\infty \frac{(-1)^n a^{2n}}{n!} Q(-n-z).
\tag{15}
$$
On the other hand, evidently
$$
  \begin{aligned}
    0
    &= \sum_{k=0}^\infty \sum_{l=0}^\infty \frac{(-1)^{k+l}a^{k+l}}{k!l!} \left(
      \frac{1}{-k+z+l} + \frac{1}{k-z-l}
    \right)
  \\&= a^{-z} \sum_{k=0}^\infty \frac{(-1)^ka^{2k}}{k!} \sum_{l=0}^\infty \frac{(-1)^la^{-k+z+l}}{l!(-k+z+l)}
  \\&+ a^z \sum_{l=0}^\infty \frac{(-1)^la^{2l}}{l!} \sum_{k=0}^\infty \frac{(-1)^ka^{-l-z+k}}{k!(-l-z+k)}
  \end{aligned}
$$
and so, by Equation (13),
$$
  \GG(z)
  = a^{-z} \sum_{k=0}^\infty \frac{(-1)^ka^{2k}}{k!} P(-k+z)
  + a^z \sum_{l=0}^\infty \frac{(-1)^la^{2l}}{l!} P(-l-z).
\tag{16}
$$
It follows from Equations (12), (15), and (16) that
$$
  \GG(z)
  = a^{-z} \sum_{n=0}^\infty \frac{(-1)^na^{2n}}{n!} \Gamma(-n+z)
  + a^z \sum_{n=0}^\infty \frac{(-1)^na^{2n}}{n!} \Gamma(-n-z),
$$
which is equivalent to Equation (11).

I will also state here, without proof, the two following representations, which will not be used in what follows:
$$
  \begin{aligned}
    \GG(z)
    &= \frac{1}{2\pi i} \int_{a-i\infty}^{a+i\infty} \Gamma\left(
      s - \frac{z}{2}
    \right) \Gamma \left(
      s + \frac{z}{2}
    \right) a^{-2s} \dd s,
  \\\GG(z)
    &= \frac{\pi}{\sin(\pi z)} e^{\frac{i\pi z}{2}} J_{-z}(2ia) - \frac{\pi}{\sin(\pi z)} e^{-\frac{i\pi z}{2}} J_z(2ia).
  \end{aligned}
$$
In the first one, $2a>|\Re z|$; in the second, both terms on the right-hand side satisfy the same difference equation, which is also satisfied by $\GG(z)$, by Equation (9).


# 2 {.unnumbered #section-2}

The asymptotic representation and the estimates of $\GG(z)$, with which we now concern ourselves, can be obtained by expanding Equation (11).

\oldpage{309}
Different areas of the $z$-plane have to be examined on a case-by-case basis.
Fix $z = x+iy + re^{i\varphi}$, where $x$, $y$, $r$, and $\varphi$ are real; $r\geq0$; if $y>0$, then we assume that $0<\varphi<\pi$; $x-iy = \overline{z}$.


## I {.unnumbered #I}

*For $|y|\geq1$ and $a\leq A$,*
$$
  \GG(z)
  = a^{-z} \Gamma(z) \left(
    1 + \frac{\chi(z)}{z}
  \right) + a^z \Gamma(z) \left(
    1 - \frac{\chi(-z)}{z}
  \right)
\tag{17}
$$
*where the absolute value of the function $\chi(z)=\chi(z;a)$ is bounded above by a value depending only on $A$.*

We know, by Equation (11), that
$$
  \chi(z)
  = \frac{za^2}{1-z} \left(
    1 + \sum_{n=2}^\infty \frac{a^{2n-2}}{n!(2-z)(3-z)\ldots(n-z)}
  \right)
$$
whence, without further ado, the claim.


## II {.unnumbered #II}

*Let $\varepsilon$ and $A$ be fixed positive numbers.*
*Set*
$$
  \frac{a^z\GG(z)}{\Gamma(z)} - 1
  = \psi(z) = \psi(z;a).
\tag{18}
$$
*Then, in the half-plane $x\geq\varepsilon$,*
$$
  \lim_{|z|\to\infty} \psi(z) = 0,
\tag{19}
$$
*and, in fact, if $a\leq A$, then this convergence is uniform in $z$ and $a$.*

It follows, from Stirling's formula, that there exists some constant $C$ such that, for $y\geq1$, $x\geq\varepsilon$, and $r\geq ae$,
$$
  \left\vert
    a^{2z} \frac{\Gamma(-z)}{\Gamma(z)}
  \right\vert \leq a^{2x}Cr^{-2x}e^{-(\pi-2\varphi)y+2x}
  \leq C\left(
    \frac{ae}{r}
  \right)^{2\varepsilon}.
\tag{20}
$$
In the part of the half-plane where $x\geq\varepsilon$, where $y\geq1$, claim (II) follows directly from Equations (17), (18), and (20);
it also follows, by symmetry, in the part where $y\leq-1$.
Then the only remaining part is the half-strip
$$
  x\geq\varepsilon,
  \quad -1\leq y\leq 1.
$$
By the already-proven part of claim (II), Equation (18) tends to zero as $z\to\infty$.
\oldpage{310}
Since Equation (18) is entire and of finite order, by well-known general theorems^[See G. Pólya and G. Szegö, Aufgaben und Lehrsätze aus der Analysis (Berlin 1925), Bd. 1, Aufgaben III 333, III 339.], it must tend uniformly to zero in the entire half-strip as $z\to\infty$;
this completes the proof of claim (II).
Of course, instead of using general theorems, Equation (18) could also be used on suitable curves intersecting the half-strip, e.g. to estimate on the straight lines $x=k+\frac12$, for $k=0,1,2,3,\ldots$.
In the case where $k=0$, we investigate such an estimation for a different purpose, c.f. Equation (22).


## III (.unnumbered #III)

*If $a\leq\frac14$, then there are no zeros of $\GG(z;a)$ outside of the strip $-\frac12<x<\frac12$.*

Since $\GG(z)$ is even, it suffices to consider the half-plane $x\geq\frac12$.
On the straight line $x=\frac12$,
$$
  z+\overline{z} = 1,
  \quad \overline{z} = 1-z
$$
and so, by the symmetry of the values with respect to the real axis,
$$
  |\Gamma(1-z)| = |\Gamma(z)|,
$$
whence
$$
  \left\vert
    \frac{\Gamma(-z)}{\Gamma(z)}
  \right\vert = \left\vert
    \frac{\Gamma(1-z)}{-z\Gamma(z)}
  \right\vert = \frac{1}{|z|} \leq 2
  \qquad\left(
    x=\frac12
  \right).
\tag{21}
$$
Using Equation (21), it follows from Equation (11) that, on the straight line $x=\frac12$,
$$
  \begin{aligned}
    |\psi(z)|
    &= \left\vert
      \frac{a^z\GG(z)}{\Gamma(z)} - 1
    \right\vert
  \\&= \left\vert
      \sum_{n=1}^\infty \frac{a^{2n}}{n!(1-z)\ldots(n-z)}
      + \frac{a^{2z}\Gamma(-z)}{\Gamma(z)} \left(
        1 + \sum_{n=1}^\infty \frac{a^{2n}}{n!(1+z)\ldots(n+z)}
      \right)
    \right\vert
  \\&\leq \sum_{n=1}^\infty \frac{a^{2n}}{n!\frac12\cdot\frac32\cdot\ldots\cdot\frac{2n-1}{2}} + a\cdot2 \left(
    1 + \sum_{n=1}^\infty \frac{a^{2n}}{n!\frac32\cdot\frac52\cdot\ldots\cdot\frac{2n+1}{2}}
  \right)
  \\&= \sum_{n=1}^\infty \frac{(2a)^{2n}}{(2n)!} + \sum_{n=0}^\infty \frac{(2a)^{2n+1}}{(2n+1)!}
  \\&= e^{2a}-1.
  \end{aligned}
\tag{22}
$$
\oldpage{311}
It then follows from Equation (22) that
$$
  |\psi(z)| = |\psi(z;a)| < 1
  \qquad\text{for }x=\frac12$ and $a\leq\frac14.
\tag{23}
$$
It follows from claim (II) that there exists some number $R$ such that
$$
  |\psi(z)| = |\psi(z;a)| <1
  \qquad\text{for }x\geq\frac12\text{, }r\geq R\text{, and }a\leq\frac14.
\tag{24}
$$
Furthermore, $|\psi(z)|<1$ is also satisfied in the circle segment $\{x\geq\frac12,r\leq R\}$, since the inequality in question, by Equations (23) and (24), is satisfied on the boundary of the circle segment.
Thus $|\psi(z)|<1$ is satisfied in the whole half-plane $x\geq\frac12$;
thus $\GG(z)$, cf. Equation (18), does not disappear in this half-plane.

For what follows, it is useful to have in mind a certain partition of the plane (cf. the above figure): the strip $-1\leq x\leq 1$ is denoted by $\SS$; the part of the plane where both $r\leq R$ and $|x|>1$ is denoted by $\TT$; the remaining part, which extends to infinity, is denoted by $\UU$.
We pick the number $R=R(A)$ depending on a certain positive number $A$ such that, inside, and on the boundary of, $\UU$, the inequality $|\psi(z)|<1$ is satisfied for $a\leq A$.
From Equation (18) it follows that $\GG(z)$ does not vanish inside, or on the boundary of, $\UU$.


# 3 {.unnumbered #section-3}

We will now study consequences of the difference equation in (9), and link them to those that we have just obtained from the representation in Equation (11).

## IV (.unnumbered #IV)

*$\GG(z)$ has no zeros on the straight lines $x=1$ or $x=-1$, i.e. on the boundary of $\SS$.*

\oldpage{312}
There are two things that we have to consider:
firstly, the difference equation and the symmetry of $\GG(z)$; secondly, the asymptotic properties of $\GG(z)$.

Firstly:
the function $\GG(z)$ is even, and takes real values for all $z$.
From this it follows that, if $y$ is real, then $\GG(iy)$ is real, and the two values $\GG(1+iy)$ and $\GG(-1+iy)$ are complex conjugate.
So Equation (9) implies, for $z=iy$, that
$$
  y\GG(iy) = 2a\Im\GG(1+iy).
\tag{25}
$$

Secondly:
it is not possible for $\GG(z)$ to vanish at two points simultaneously if the line connecting them is parallel to the real axis and is of length $1$.
This is since, if $\GG(c)=0$ and $\GG(c-1)=0$, then Equation (9) would imply that $\GG(c+1)=0$ as well, and thus that $\GG(c+2)=0$, $\GG(c+3)=0$, $\ldots$, and so $\GG(z)$ would have zeros in the region $\UU$ (see the figure); but this would be a contradiction.

For real $z$, $\GG(z)$ is positive (cf. Equation (7)).
On one hand, $\GG(1+iy)=0$ implies that $y\neq0$, and, on the other hand, $\GG(1+iy)=0$ implies that $\Im\GG(1+iy)=0$, and thus Equation (25) implies that $\GG(iy)=0$.
However, the simultaneous vanishing of $\GG(1+iy)$ and $\GG(iy)$ is impossible, and thus $\GG(1+iy)\neq0$.


## V (.unnumbered #V)

*There are no zeros of $\GG(z)$ outside of the strip $\SS$.*

This has already been proven for $a\leq\frac14$, cf. [(III)](#III).
Let
$$
  \frac14 \leq a \leq A.
\tag{26}
$$
As we have already established, there are no zeros of $\GG(z)$ in the region $\UU$ nor on its boundary.
If we take [(IV)](#IV) into account as well, we see that there are no zeros of $\GG(z)$ on the boundary of $\TT$ either.
If $z$ varies along the boundary of $\TT$, and $a$ in the closed interval Equation (26), then $\GG(z;a)$ is a continuous non-zero function of $z$ and $a$.
Thus the integral
$$
  \frac{1}{2\pi i} \int \frac{\GG'(z;a)\dd z}{\GG(z;a)}
\tag{27}
$$
(along the boundary of $\TT$ in the positive direction) is a continuous function of $a$.
The integral Equation (27) calculates an integer, namely the number of zeros of $\GG(z;a)$ that lie inside $\TT$.
A continuous function that takes only integer values is constant.
Thus the integral is always equal to $0$, since it is equal to zero for $a=\frac14$, cf. [(III)](#III).


## VI {.unnumbered #VI}

*All the zeros of $\GG(z)$ lying inside the strip $\SS$ are simple and purely imaginary.*
\oldpage{313}

It follows from Equation (17) and from Stirling's formula that, in the strip $1\leq x\leq 1$, for $y\to+\infty$,
$$
  \GG(x+iy)
  =
  \frac{1}{\sqrt{2\pi y}} e^{-\frac\pi2 y+ i\frac\pi2 x}
  \left\{
    \left(\frac{y}{a}\right)^x e^{i\Phi} + 
    \left(\frac{y}{a}\right)^{-x} e^{-i\Phi}
  \right\} + \error\left(
    e^{-\frac\pi2 y} y^{|z| - \frac32}
  \right)
\tag{28}
$$
uniformly in $x$, where, for abbreviation, we set
$$
  \Phi = y\log\frac{y}{a} - y - \frac\pi4.
\tag{29}
$$
A weakened form of [claim (VI)](#VI), in which we replace "*all* the zeros" with "*all but finitely many* zeros", can be proved using only Equations (28) and (29); a proof of the full result needs more.

Consider the branch of $\log\GG(z)$ that is real for $z=1$;
by [(IV)](#IV), it can be extended indefinitely along the straight line $x=1$.
Consider $\Im\log\GG(1+iy)$ as $y$ goes from $0$ to $+\infty$, and denote the *smallest* positive value of $y$ for which
$$
  \Im\log\GG(1+iy) = (2n+1)\frac\pi2
$$
does *not* hold by $y_n$ ($n=0,1,2,3,\ldots$).
In the curly brackets on the right-hand side of Equation (28), the $a^{-x}y^xe^{i\Phi}$ term dominates when $x=1$;
by Equation (29), we can exclude the possibility that
$$
  \Im\log\GG(1+iy) \to +\infty
  \qquad\mbox{as $y\to\infty$}.
$$
Thus the $y_n$ exist for $n=0,1,2,3,\ldots$.

Denote by $R_n$ the rectangle whose four corners are
$$
  1+iy_n, \;\; -1+iy_n, \;\; -1-iy_n, \;\; 1-iy_n.
$$
By [(IV)](#IV), there are no zeros of $\GG(z)$ on the vertical sides of $R_n$;
we will soon show that, for sufficiently large $n$, there are also none on the horizontal sides.
Let

- $H_n$ denote the change in $\Im\log\GG(z)$ when $z$ moves in a straight line from $1+iy_n$ to $-1+iy_n$;
- $N_n$ denote the number of *purely imaginary* zeros of $\GG(z)$ lying inside $R_n$, counted *without* multiplicity;
- $N_n+N_n^*$ denote the number of *all* zeros of $\GG(z)$ lying inside $R_n$, counted *with* multiplicity.

\oldpage{314}
So $N_n^*$ includes the number of any not purely imaginary zeros of $\GG(z)$ inside $R_n$.
Furthermore, every purely imaginary zero inside $R_n$ of multiplicity $m$ contributes $m-1$ to $N_n^*$.
Both $N_n$ and $N_n^*$ are non-decreasing as $n$ increases.

The total change of $\Im\log\GG(z)$ as $z$ traces out the boundary of the rectangle $R_n$ one time in the positive direction is
$$
  2\pi(N_n + N_n^*) = 2H_n + (2n+1)2\pi
\tag{30}
$$
as follows from the definitions of $y_n$ and $H_n$ and from symmetry.

By definition, $\Im\log\GG(1+iy)$ takes the value $(v-1/2)\pi$ for $y=y_{v-1}$, and the value $(v+1/2)\pi$ for $y=y_v$;
there thus exists at least one $\eta$ with $y_{v-1}<\eta<y_v$ such that
$$
  \Im\log\GG(1+i\eta) = v\pi.
$$
From this it follows that
$$
  \Im\GG(1+i\eta) = 0
$$
and, by Equation (25), that
$$
  \GG(i\eta) = 0.
$$

Then $-i\eta$, along with $i\eta$, is also a zero of $\GG(z)$, and so, for $v=1,2,3,\ldots$ and $n$ fixed, we have proven the existence of at least $2n$ purely imaginary zeros in the rectangle $R_n$;
i.e. we have
$$
  N_n \geqslant 2n.
\tag{31}
$$
So Equations (30) and (31) give
$$
  2\pi N_n^* \leqslant 2H_n + 2\pi.
\tag{32}
$$
Denote by $\Phi_n$ the value of Equation (29) at $y=y_n$.
Since, as mentioned above, the first term in the curly brackets of Equation (28) dominates when $x=1$, we have that
$$
  \Im\log\GG(1+iy_n)
  = (2n+1)\frac\pi2
  \equiv \Phi_n + \frac\pi2 + \varepsilon_n \mod2\pi,
$$
where
$$
  \lim_{n\to\infty}\varepsilon_n = 0.
$$
\oldpage{315}
Since $\Phi_n=n\pi-\varepsilon_n$, for $y=y_n$ with $n$ large enough, the value of $e^{i\Phi_n}$ is almost $(-1)^n$, and the term in the curly brackets in Equation (28) is almost real.
Two things follow from this:

1. For $y=y_n$ in Equation (28), the leading term in Equation (28) dominates over the error term $\error$ in all of the segment $-1\leqslant x\leqslant 1$, and so $\GG(z)$ has no zeros on the horizontal sides of $R_n$, as we had previously claimed.
2. Moving along an arc in this segment, the $e^{i\pi x/2}$ factor dominates in $\GG(z)$, or, more precisely, for arbitrary $\varepsilon$ we have
    $$
      H_n < -\pi + \varepsilon
    \tag{33}
    $$
    for $n$ sufficiently large.
    Then Equations (32) and (33) give
    $$
      2\pi N_n^* < 2\varepsilon.
    $$

Thus $N_n^*$ is a non-negative integer, and equal to $0$ for sufficiently large $n$, and thus always equal to $0$, since $N_n^*$ is non-decreasing for increasing $n$;
so we have proven [(VI)](#VI).

Now, [(IV)](#IV), [(V)](#V), and [(VI)](#VI) form a complete partition of the plane, and show that *all the zeros of $\GG(z)$ are purely imaginary and simple*.
The above observation also shows that the number of zeros with ordinate between $0$ and $y$ is
$$
  \frac{y}{\pi}\log\frac{y}{a} - \frac{y}{\pi} + \error(1).
$$


# 4 {.unnumbered #section-4}

In order to be able to prove all of the claims in the introduction, we will need two simple, general lemmas.

::: {.itenv #lemma-i title="Lemma I" latex="{Lemma I}"}
Let $F(u)$ be analytic, and taking real values for any non-negative real $u$.
Further, let
$$
  \lim_{u\to\infty} u^2 F^{(n)}(u) = 0
\tag{34}
$$
for $n=0,1,2,\ldots$ (with $F^{(0)}(u)=F(u)$).
If $F(u)$ is not an even function, then the function
$$
  G(x) = \int_0^\infty F(u)\cos xu \dd u
\tag{35}
$$
is non-zero for sufficiently large real $x$.
:::

::: {.proof}
Since $F(u)$ is not even, there exists some integer $q$ such that
$$
  F'(0) = F'''(0) = \ldots = F^{(2q-3)}(0) = 0,
  \qquad F^{(2q-1)}(0) \neq 0.
$$
\oldpage{316}
Taking Equation (34) into account, we obtain, by repeated partial integration,
$$
  G(x) = (-1)^q \frac{F^{(2q-1)}(0)}{x^{2q}} + \frac{{(-1)^{q+1}}}{x^{2q+1}} \int_0^\infty F^{(2q+1)}(u)\sin xu \dd u.
$$
From this it follows, again using Equation (34), that
$$
  \lim_{x\to\infty} x^{2q}G(x) = (-1)^q F^{(2q-1)}(0) \neq 0,
$$
whence our claim.
:::

If we take $F(u)$ to be the right-hand side of Equation (4), or, more generally, take $F(u)$ in Equation (35) to be the sum of finitely many terms of the series in Equation (3), then we obtain an entire function $G(x)$ which, by the theory of Hadamard, can easily be proven to have infinitely many zeros.
Of these zeros, by [Lemma I](#lemma-i), only finitely many are real, since the function $F(u)$ is clearly not even.
The function $\Phi(u)$ in the integral representation Equation (2) of the $\xi$-function must, by [Lemma I](#lemma-i), be even (which could also be shown directly).

::: {.itenv #lemma-ii title="Lemma II" latex="{Lemma II}"}
Let $a$ be a positive constant, and $G(z)$ an entire function of genus $0$ or $1$, that takes real values for real $z$, with no complex zeros and at least one real zero.
Then the function
$$
  G(z-ia) + G(z+ia)
\tag{36}
$$
has only real zeros.^[The corresponding result for polynomials is a special case of a theorem of Ch. Biehler. See e.g. G. Pólya and G. Szegö, op. cit., Aufgabe III 25.]
:::

::: {.proof}
The hypotheses on $G(z)$ imply that
$$
  G(z) = c z^q e^{\alpha z} \prod\left(1-\frac{z}{\alpha_n}\right)e^{z/\alpha_n},
$$
where $c,\alpha,\alpha_1,\alpha_2,\ldots$ are real constants, with $\alpha_n\neq0$ for $n=1,2,\ldots$ such that $\alpha_1^{-2}+\alpha_2^{-2}+\ldots$ converges, and where $q$ is a non-negative integer.
(If $G(z)$ has no zeros, i.e. when $G(z)$ reduces to $ce^{\alpha z}$, then Equation (36) can be identically zero.)
Let $z=x+iy$ be a zero of the function Equation (36), so that
$$
  |G(z-ia)| = |G(z+ia)|
$$
and thus
$$
  1
  =
  \left\vert
    \frac{G(z-ia)}{G(z+ia)}
  \right\vert^2
  =
  \left(
    \frac{x^2+(y-a)^2}{x^2+(y+a)^2}
  \right)^q
  \prod \frac{(x-\alpha_n)^2+(y-a)^2}{(x-\alpha_n)^2+(y+a)^2}.
$$
\oldpage{317}
If $y>0$ then all the factors of the right-hand side are $<1$, and if $y<0$ then all the factors of the right-hand side are $>1$.
Thus, for there to be at least one factor, it must be the case that $y=0$.
:::

The fact that $\GG(\frac12 iz)$ has only real zeros has already been proven.
That $\GG(\frac12 iz)$ also satisfies the genus hypothesis of [Lemma II](#lemma-ii) follows easily from the theory of Hadamard.
If we apply [Lemma II](#lemma-ii) to $G(z)=\GG(\frac12 iz;\pi)$ and $a=9/2$, then, by Equation (8), we obtain that all the zeros of $\xi^*(z)$ are real.

By Equations (8), (17), and (19), we also see that, in the half-plane $y\geqslant\varepsilon$ (for fixed $\varepsilon>0$), as $z\to\infty$,
$$
  \xi^*(iz) \sim \frac12 z^2 \pi^{-\frac{z}{2}-\frac14} \Gamma\left(\frac{z}{2}+\frac14\right).
$$
This formula should be compared with Equation (1).^[*Note added during editing (5th February, 1926).* By suitably extending [Lemma II](#lemma-ii), we can prove that the function $$\xi^{**}(z) = 4\pi\int_0^\infty\left[2\pi\left(e^{\frac{9u}{2}} + e^{-\frac{9u}{2}}\right)-3\left(e^{\frac{5u}{2}} + e^{-\frac{5u}{2}}\right)\right]e^{-\pi(e^{2u}+e^{-2u})} \cos zu \dd u,$$which "better" approximates the true $\xi$-function, also has only real zeros.]

