--- 
title: "Examples of differential groups: irrational flows on the torus"
author: "Paul Donato and Patrick Iglesias"
date: "1985"
original: "Donato, P. and Iglesias, P. \"Exemples de groupes differentiels: flots irrationnels sur le tore\". _Comptes rendus de l'Académie des sciences_ **301** (1985), 127--130."
bibliography: CRASP-301-1985-127.bib
nocite: '@*'
link-citations: true
csl: maths-translations.csl
reference-section-title: "Bibliography"
github-repo: "thosgood/translations"
favicon: "favicon.ico"
---

```{js, echo = FALSE}
$(document).ready(function(e) {gitbook.sidebar.toggle(false, false)});
```

```{r, child = '_translator-note.Rmd'}
```

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\RR}{\mathbb{R}}
\providecommand{\ZZ}{\mathbb{Z}}
\providecommand{\NN}{\mathbb{N}}
\providecommand{\CCinfty}{\mathrm{C}^\infty}
\providecommand{\DL}{\operatorname{DL}}
\providecommand{\Diff}{\operatorname{Diff}}
\providecommand{\GL}{\operatorname{GL}}
\providecommand{\Stab}{\operatorname{Stab}}

<!-- Content -->

# Introduction

\oldpage{127}We consider the standard torus $T^2=\RR^2/\ZZ^2$ endowed with its $\CCinfty$ differential structure.
The projection onto $T^2$ of a line $y=\alpha x$ of $\RR$ defines a one-parameter subgroup of $T^2$ denoted $[\alpha]$.
The quotient group is denoted $T_\alpha=T^2/[\alpha]$, and its quotient topology is the trivial one.
The study of singular objects, of which $T_\alpha$ is the most well known example, has provoked the development of different techniques, algebraic or geometric, such as, amongst others: $C^*$-algebras ([@3] and [@7]), $Q$-varieties [@1], and analytic schemes [@2].
We want to illustrate here the technique of *diffeological spaces*, initially developed by J.-M. Souriau for the study of groups of infinite dimension, but which applies to all quotients (possibly singular) of Lie groups.
The quotient $T_\alpha$ can be endowed with the structure of a diffeological group (we refer to the references [@8] and [@4] for the details concerning this notion).
This structure agrees with the canonical Lie group structure if $\alpha$ is rational.
Here this structure is characterised by the following definition [@8]:

> $f\in\DL(\RR^n,T_\alpha)$ if and only if $f$ is defined on an open $\Omega$ of $\RR^n$ with values in $T_\alpha$ and satisfies the following condition: for all $x$ in $\Omega$, there exists an open neighbourhood $V$ of $x$, and a map $F\in\CCinfty(V,T^2)$ that lifts $f$, i.e. on $V$ we have the relation
> $$
>   P_\alpha\circ F
>   = f.
> \tag{1}
> $$

In the above, $P_\alpha$ is the canonical epimorphism from $T^2$ to $T_\alpha$, and $\DL(\RR^n,T_\alpha)$ is by definition the family of differentiable maps of opens in $\RR^n$ to $T_\alpha$ (also called *$n$-plots* of $T_\alpha$).
THe set of $n$-plots as $n$ runs over $\NN$ characterises the diffeological structure of $T_\alpha$.

The differentiable maps from $T_\alpha$ to a "diffeological space" $E$ are the maps $\varphi\colon T_\alpha\to E$ such that, for every plot $f$ of $T_\alpha$, the composite $\varphi\circ f$ is a plot of $E$.
In particular, the diffeomorphisms from $T_\alpha$ to $E$ are the bi-differentiable bijections.

For every diffeological group and every homogeneous space (quotient of a diffeological group by an arbitrary subgroup) we can define the notion of connectivity, and thus simple connectivity.
In the connected case, we can also define the universal covering and the fundamental group, which depend only on the diffeological structure ([@4] and [@8]).

We illustrate these techniques in the precise case of irrational windings of the torus.
The passage to the universal covering of these quotients allows us to give a complete diffeological classification;
we can also make explicit the group of diffeomorphisms of $T_\alpha$.
\oldpage{128}For the classification, there is agreement with the results obtained by the theory of $C^*$-algebras (cf. [@3] and [@7]);
we also find a similar classification starting from schemes of varieties [@2].


# Covering and fundamental group

We briefly describe the construction of the universal covering of a homogeneous diffeological space:

> Let $G$ be a connected diffeological group, and $p\colon\widetilde{G}\to G$ its universal covering.
> Let $H$ be an arbitrary subgroup of $G$;
> set $\widetilde{H}=p^{-1}(H)$, and let $\widetilde{H}_0$ be its identity component.
> We have the diagram
> $$
>   \begin{CD}
>     \widetilde{G} @>>> \widetilde{G}/\widetilde{H}_0
>   \\@VVV @VVV
>   \\G @>>> G/H
>   \end{CD}
> \tag{2}
> $$
> and $\widetilde{G}/\widetilde{H}_0$ is then the universal covering of $G/H$, and $\widetilde{H}/\widetilde{H}_0$ is its fundamental group.

Conversely, every connected covering of $G/H$ is given by a quotient $\widetilde{G}/K$, where $K$ is an intermediary subgroup $\widetilde{H}_0\subset K\subset\widetilde{H}$.

In the particular case that interests us, writing $D_\alpha$ to mean the line $y=\alpha x$, and $\xi$ to mean the vector $(0,1)$, we have:
$$
  \begin{aligned}
    G &= T^2
  \\\widetilde{G} &= \RR^2
  \\H &= [\alpha]
  \\\widetilde{H} &= D_\alpha + (\ZZ+\alpha\ZZ)\xi.
  \end{aligned}
$$

Connectivity coincides with connectivity by differentiable arcs, and an easy calculation then shows that
$$
  \widetilde{T}_\alpha = \RR
  \qquad\text{and}\qquad
  \pi_1(T_\alpha) = \ZZ^2.
\tag{8}
$$

Some comments: the diffeological universal covering of $T_\alpha$ is thus the projection $\pi_\alpha\colon\RR\to\RR/(\ZZ_\alpha\ZZ)$;
the fibre-type $\ZZ+\alpha\ZZ$ is diffeologically discrete, i.e. the only differentiable maps with values in the fibre are the constants;
finally, the action of $\pi_1(T_\alpha)$ on $\RR$ is given by $(n,m)(x)=x+n+\alpha m$.
The other connected coverings of $T_\alpha$ are of the type
$$
  \RR(k\ZZ+\alpha p\ZZ)
  \qquad\text{or}\qquad
  (k,p)\in\ZZ^2.
\tag{4}
$$

The number of sheets, when $k\cdot p\neq0$, is equal to $k\cdot p$.


# Classification of the $T_\alpha$

Let $T_\alpha$ and $T_\beta$ be irrational toruses.
Then every diffeomorphism $\varphi\in\Diff(T_\alpha,T_\beta)$ lifts to an isomorphism $f$ of their universal coverings:
$$
  \begin{CD}
    \RR @>f>> \RR
  \\@V{\pi_\alpha}VV @VV{\pi_\beta}V
  \\T_\alpha @>>\varphi> T_\beta
  \end{CD}
$$
and the equality $\pi_\alpha\circ f=\varphi\circ\pi_\beta$ says that, for all $x\in\RR$ and $(n,m)\in\ZZ^2$, there exists $(p,q)\in\ZZ^2$ such that
$$
  f(x + n + \alpha m)
  = f(x) + p + \beta q
$$
differentiable at $x$.
Furthermore, $f$ induces an isomorphism from $\ZZ+\alpha\ZZ$ to $\ZZ+\beta\ZZ$;
there thus exists a matrix in $\GL(2,\ZZ)$ such that
$$
  \begin{pmatrix}
    p\\q
  \end{pmatrix}
  = \begin{pmatrix}
    a & c
  \\b & d
  \end{pmatrix}
  \times
  \begin{pmatrix}
    m\\n
  \end{pmatrix}
$$
with $a,b,c,d\in\ZZ$ such that $ad-bc=\pm1$;
the differentiability of $f$ implies that $f'(m+\alpha n)=f'(0)$ for all $m,n\in\ZZ$;
\oldpage{129}we thus have, by density of $\ZZ+\alpha\ZZ$ in $\RR$, that $f'(x)=f'(0)$, and so $f$ is affine: $f(x)=\lambda x+r$ for some $\lambda\neq0$.
Applied to $x=n+\alpha m$, this implies that $\lambda=c+\beta d$ and $\alpha=(a\beta+b)/(c\beta+d)$;
thus $\alpha$ and $\beta$ are equivalent modulo $\GL(2,\ZZ)$, and so the action on $\RR$ is given by
$$
  \begin{pmatrix}
    a&c
  \\b&d
  \end{pmatrix}
  (x)
  = (ax+b)/(cx+d).
$$

Conversely, we see that, if $\alpha\sim\beta$ modulo $\GL(2,\ZZ)$, then the map $f(x)=(c+\beta d)x+r$, with $c$ and $d$ coprime, projects onto a diffeomorphism from $T_\alpha$ to $T_\beta$.

::: {.itenv title="Theorem" latex="{Theorem}"}
Two irrational toruses $T_\alpha$ and $T_\beta$ are diffeomorphic if and only if $\alpha\sim\beta$ modulo $\GL(2,\ZZ)$.
:::

::: {.itenv title="Remark" latex="{Remark}"}
This theorem is trivial satisfied for *rational toruses*.
:::


# Diffeomorphisms of $T_\alpha$.

We have seen in the previous section that the only diffeomorphisms from one irrational torus to another are the projections of affine maps of the form $f(x)=(c+\beta d)x+r$, with $r\in\RR$, and $c,d\in\ZZ$ coprime.
If we impose the condition that $f$ projects onto a diffeomorphism of $T_\alpha$ into itself then there must further exist $(a,b)\in\ZZ^2$ such that
$$
  \begin{pmatrix}
    a&c
  \\b&d
  \end{pmatrix}
  \in\Stab(\alpha)
\tag{6}
$$
where $\Stab(\alpha)$ is the isotropy group of $\alpha$ under the action of $\GL(2,\ZZ)$.
This condition $(6)$ is the translation of $\alpha=(a\beta+b)/(c\beta+d)$ for $\alpha=\beta$;
these maps constitute a subgroup of the affine group of $\RR$.
By characterising their projections, we determine all the diffeomorphisms of $T_\alpha$ into itself.
Two affine maps of the above type project onto the same diffeomorphism if and only if
$$
  \begin{aligned}
    (c,d)
    &= (c',d')
  \\\pi_\alpha(r)
    &= \pi_\alpha(r').
  \end{aligned}
\tag{7}
$$

We define on $\Stab(\alpha)\times T_\alpha$ the affine law
$$
  \begin{aligned}
    (M,\rho)\cdot(M',\rho')
    &= (MM',M\cdot\rho'+\rho)
  \\M\cdot\rho
    &= \pi_\alpha[(c+\alpha d)x]
    \qquad\text{if }\pi_\alpha(x) = \rho
  \end{aligned}
\tag{8}
$$
where $M$ is a matrix in $\GL(2,\ZZ)$ with coefficients $(a,b,c,d)$.
This is a diffeological group law for which
$$
  (M,\pi_\alpha(x))
  \longmapsto (\pi_\alpha(x) \mapsto \pi_\alpha[(c+\alpha d)x])
\tag{9}
$$
is a differentiable isomorphism from $\Stab(\alpha)\times T_\alpha$ to $\Diff(T_\alpha)$.

The action of $\GL(2,\ZZ)$ on a real number can be understood by the modification of its prime coefficients in its decomposition into continued fractions;
thus two reals are equivalent modulo $\GL(2,\ZZ)$ if and only if they have the same decomposition after a certain rank (which is not necessarily the same for both of them).
The quadratic irrationals are the reals whose coefficient sequences become periodic;
thus removing or adding periods to the sequence leaves the number unchanged (cf. [@9] for these questions).
From these remarks, we can show that
$$
  \Stab(\alpha)
  = \ZZ_2
  = \left\{
    \begin{pmatrix}
      1&0
    \\0&1
    \end{pmatrix}
    ,
    \begin{pmatrix}
      -1&0
    \\0&-1
    \end{pmatrix}
  \right\}
\tag{10}
$$
if $\alpha$ is a non-quadratic irrational.

\oldpage{130}If $\alpha$ is a quadratic irrational then $\Stab(\alpha)=\ZZ_2\times\ZZ$, whence:

::: {.itenv #Theorem title="Theorem" latex="{Theorem}"}
The identity component of the group $\Diff(T_\alpha)$ is equal to the group of translations of $T_\alpha$.
The group of these components is equal to

a. $\ZZ_2$ if $\alpha$ is a non-quadratic irrational;
a. $\ZZ_2\times\ZZ$ if $\alpha$ is a quadratic irrational.
:::

This is, to our knowledge, the first time that a classification of the $T_\alpha$ distinguishes quadratic numbers.
The difference between Diophantine numbers and Liouville numbers, which appear in the cohomological study of foliated varieties [@5], can also be found in the classification of $\RR$-principal bundles over $T_\alpha$ (cf. [@6]).

*The discussions that we had with J. Bellissard and J.-M. Souriau were invaluable to us; we thank them.*
