--- 
title: "Techniques of descent and existence theorems in algebraic geometry, II"
subtitle: "The existence theorem and the formal theory of modules"
author: "A. Grothendieck"
date: "February 1960"
original: 'Grothendieck, A. "Technique de descente et théorèmes d’existence en géométrie algébrique, II: Le théorème d’existence et théorie formelle des modules". _Séminaire Bourbaki_ **12** (1959--60), Talk no. 195.'
bibliography: FGA-3-II.bib
nocite: '@*'
link-citations: true
csl: maths-translations.csl
reference-section-title: "Bibliography"
github-repo: "thosgood/translations"
favicon: "favicon.ico"
---

```{r, child = if (knitr::is_html_output()) '_translator-note.Rmd'}
```

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\kres}{\mathfrak{K}}
\providecommand{\simto}{\xrightarrow{\raisebox{-0.7ex}[0ex][0ex]{$\sim$}}}
\providecommand{\simfrom}{\xleftarrow{\raisebox{-0.7ex}[0ex][0ex]{$\sim$}}}
\providecommand{\Set}{\mathtt{Set}}

\providecommand{\id}{\operatorname{id}}
\providecommand{\Hom}{\operatorname{Hom}}
\providecommand{\shHom}{\underline{\Hom}}
\providecommand{\Aut}{\operatorname{Aut}}
\providecommand{\shAut}{\underline{\Aut}}
\providecommand{\HH}{\operatorname{H}}
\providecommand{\RR}{\operatorname{R}}
\providecommand{\GL}{\operatorname{GL}}
\providecommand{\Ga}{\operatorname{G_a}}
\providecommand{\Gm}{\operatorname{G_m}}
\providecommand{\SL}{\operatorname{SL}}
\providecommand{\Sp}{\operatorname{Sp}}
\providecommand{\Spec}{\operatorname{Spec}}
\providecommand{\Pro}{\operatorname{Pro}}
\providecommand{\Ext}{\operatorname{Ext}}

<!-- Content -->

# {-}

[Trans.] We have made changes throughout the text following the errata (_Séminaire Bourbaki_ **14**, 1961--62, Complément); we preface them with "[Comp.]" (except for small corrections, which we insert silently).
