--- 
title: "Formal geometry and algebraic geometry (FGA 2)"
author: "A. Grothendieck"
date: ""
original: 'Grothendieck, A. "Géométrie formelle et géométrie algébrique". _Séminaire Bourbaki_ **11** (1958--59), Talk no. 182.'
bibliography: FGA-2.bib
nocite: '@*'
link-citations: true
csl: maths-translations.csl
reference-section-title: "Bibliography"
---

```{r, child = if (knitr::is_html_output()) '_translator-note.Rmd'}
```

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\from}{\leftarrow}
\providecommand{\bb}{\mathbf}

\providecommand{\Ext}{\operatorname{Ext}}
\providecommand{\Hom}{\operatorname{Hom}}
\providecommand{\Tor}{\operatorname{Tor}}
\providecommand{\shExt}{\underline{\operatorname{Ext}}}
\providecommand{\shHom}{\underline{\operatorname{Hom}}}
\providecommand{\RR}{\operatorname{R}}
\providecommand{\HH}{\operatorname{H}}

<!-- Content -->

# {-}

::: {.itenv title="Remark" data-latex="{Remark}"}
[Trans.] We have made changes throughout the text following the errata (_Séminaire Bourbaki_ **14**, 1961--62, Complément); we preface them with "[Comp.]" (except for small corrections, which we insert silently).
:::

\oldpage{C-03}

The substance of [§1](#section-1) to [§5](#section-5) is contained in the published part of EGA III; that of [§6](#section-6) and [§7](#section-7) is contained in SGA III.
For the study of the fundamental group, see SGA V, IX, X, and XI, as well as SGA 1962 (talks X, XII, and XIII) for the Lefschetz-type theorems and numerous open questions.
Only the theory of moderately ramified coverings (cf. [Theorem 14](#theorem-14)) has not yet been the subject of a dedicated talk.
The [corollary to Theorem 14](#theorem-14-corollary), which completely determines Galois coverings of order coprime to the characteristic of an algebraic curve over an algebraically closed field, has been used in an essential manner on three separate occasions:

1. in the proof by Igusa of the Picard inequality for non-singular projective surfaces in arbitrary characteristic;

2. in the study (developed independently by Ogg and Šafarevič) of the group of homogeneous principal bundles over an abelian variety defined over a function field in one variable, in arbitrary characteristic; and

3. in the recent proof, by Artin, of certain key theorems concerning the "Weil cohomology" of algebraic varieties.


# Schemes {#section-1}

\oldpage{182-01}

We know that

