--- 
title: "Techniques of descent and existence theorems in algebraic geometry"
subtitle: "III: Quotient preschemes"
author: "A. Grothendieck"
date: ""
original: 'Grothendieck, A. "Technique de descente et théorèmes d’existence en géométrie algébrique, III: Préschemas quotients". _Séminaire Bourbaki_ **13** (1960--61), Talk no. 212.'
bibliography: FGA-3-III.bib
nocite: '@*'
link-citations: true
csl: maths-translations.csl
reference-section-title: "Bibliography"
---

```{r, child = if (knitr::is_html_output()) '_translator-note.Rmd'}
```

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\kres}{\mathfrak{K}}
\providecommand{\simto}{\xrightarrow{\raisebox{-0.7ex}[0ex][0ex]{$\sim$}}}
\providecommand{\simfrom}{\xleftarrow{\raisebox{-0.7ex}[0ex][0ex]{$\sim$}}}
\providecommand{\Set}{\mathtt{Set}}
\providecommand{\pr}{\mathrm{pr}}
\providecommand{\Gm}{\mathrm{G}_\mathrm{m}}

\providecommand{\id}{\operatorname{id}}
\providecommand{\Hom}{\operatorname{Hom}}
\providecommand{\Spec}{\operatorname{Spec}}
\providecommand{\Ker}{\operatorname{Ker}}
\providecommand{\GL}{\operatorname{GL}}
\providecommand{\sGL}{\operatorname{\mathscr{G}\!\!\mathscr{L}}}
\providecommand{\GP}{\operatorname{GP}}
\providecommand{\Aut}{\operatorname{Aut}}

<!-- Content -->

# {-}

[Trans.] We have made changes throughout the text following the errata (_Séminaire Bourbaki_ **14**, 1961--62, Complément); we preface them with "[Comp.]" (except for small corrections, which we insert silently).


# Introduction

\oldpage{212-01}