--- 
title: "Duality theorems for coherent algebraic sheaves (FGA 1)"
author: "A. Grothendieck"
date: ""
original: 'Grothendieck, A. "Théorèmes de dualité pour les faisceaux algébriques cohérents". _Séminaire Bourbaki_ **9** (1956--57), Talk no. 149.'
bibliography: FGA-1.bib
nocite: '@*'
link-citations: true
csl: maths-translations.csl
reference-section-title: "Bibliography"
references:
- id: 1
  title: 'Des groups $\operatorname{Ext}^s(A,B)$'
  author: 'Cartier, P.'
  container-title: 'Séminaire A. Grothendieck: Algèbre homologique'
  volume: 1
  issued:
    year: 1957
  page: Talk no. 3
- id: 2
  title: 'Sur quelques points d'algèbre homologique'
  author: 'Grothendieck, A.'
  container-title: 'Tohoku math. J.'
  volume: 9
  issued:
    year: 1957
  page: 119--221
- id: 3
  title: 'Faisceaux algébriques cohérents'
  author: 'Serre, J.-P.'
  container-title: 'Annals of Math.'
  volume: 61
  issued:
    year: 1955
  page: 197--278
- id: 4
  title: 'Sur la dimension homologique des anneaux et des modules noethériens'
  author: 'Serre, J.-P.'
  container-title: 'Proc. Intern. Symp. on alg. number Theory [1955, Tokyo et Nikko]'
  publisher: 'Science Council of Japan, Tokyo'
  issued:
    year: 1956
  page: 175--189
---

```{r, child = if (knitr::is_html_output()) '_translator-note.Rmd'}
```

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\from}{\leftarrow}
\providecommand{\bb}{\mathbf}

\providecommand{\Ext}{\operatorname{Ext}}
\providecommand{\Hom}{\operatorname{Hom}}
\providecommand{\Tor}{\operatorname{Tor}}
\providecommand{\shExt}{\underline{\operatorname{Ext}}}
\providecommand{\shHom}{\underline{\operatorname{Hom}}}
\providecommand{\RR}{\operatorname{R}}
\providecommand{\HH}{\operatorname{H}}

<!-- Content -->

# {-}

::: {.itenv title="Remark" data-latex="{Remark}"}
[Trans.] We have made changes throughout the text following the errata (_Séminaire Bourbaki_ **14**, 1961--62, Complément); we preface them with "[Comp.]" (except for small corrections, which we insert silently).
:::

\oldpage{149-01}

The results that follow, inspired by Serre's "theorem of algebraic duality", were discovered in the winter of 1955 and the winter of 1956.
They can be established very simply, thanks to reasonably elementary results on the cohomology of projective spaces [@3] and an intensive use of Cartan--Eilenberg's homological algebra, in the form given in [@2].


# Ext of sheaves of modules {#section-1}

[cf. @2, chap. 3 and 4]

Let $X$ be a topological space endowed with a sheaf $\scr{O}$ of unital (but not necessarily commutative) rings.
