--- 
title: "On formal complex spaces"
author: "Jürgen Bingener"
date: "1978"
original: 'Bingener, J. "Über formale komplexe Räume". _manuscripta mathematica_ **24** (1978), 253--293. DOI: [10.1007/BF01167833](https://doi.org/10.1007/BF01167833).'
bibliography: mm-24-1978-253.bib
nocite: '@*'
link-citations: true
csl: maths-translations.csl
reference-section-title: "Bibliography"
github-repo: "thosgood/translations"
favicon: "favicon.ico"
---

```{js, echo = FALSE}
$(document).ready(function(e) {gitbook.sidebar.toggle(false, false)});
```

```{r, child = '_translator-note.Rmd'}
```


\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\OO}{\cal{O}}
\providecommand{\CC}{\mathbb{C}}
\renewcommand{\hat}{\widehat}
\providecommand{\Ker}{\operatorname{Ker}}
\providecommand{\Spec}{\operatorname{Spec}}
\providecommand{\NN}{\mathbb{N}}

<!-- Content -->

\oldpage{253}

::: {.rmenv #abstract title="Abstract" latex="{Abstract}"}
Formal complex spaces, introduced by Krasnov [@24] and independently by the author, are the analytic analogues of the formal schemes of Zariski and Grothendieck.
Special cases are the formal completions of complex spaces along analytic sets, see Banica [@3].
The technique of formal complex spaces has proved to be a useful tool in analytic geometry and allows even applications to purely algebraic problems, see [@24], [@4] and [@7].
Here the basic theory of these spaces is developed: coherence of the structure sheave, description of the coherent modules, Grauert's coherence theorem for proper maps....
We further study the question of exactness of the formal Dolbeault and de Rham complexes.
:::


# Introduction {-}

In 1958, Grothendieck introduced formal schemes in algebraic geometry, following on from earlier ideas by Zariski.
Since then, the theory of formal schemes has become an important tool in algebraic geometry, cf. e.g. [@13; @20; @2].
Formal structures appeared in (global) analytic geometry for the first time in Grauert's comparison theorem;
this is clearly expressed in the proof given in [@3].
In [@24], Krasnov then explicitly introduced formal complex spaces, and, in particular, formal complex manifolds, and used this to prove theorems about modifications of complex manifolds.

\oldpage{254}
In the present article, we first develop the basic theory of formal complex spaces.
These are introduced in [§1](#section-1) as inductive limits of a suitable system of complex spaces.
We obtain special formal complex spaces if we consider the formal completions of complex spaces along analytical subsets.
Of course, every complex space is also a formal complex space.
The structure sheaf $\OO_X$ of a formal complex space $X$ is always coherent with local Noetherian stalks ([(1.1)](#equation-1.1) and [(1.4)](#equation-1.4)).
It is important remark that, as in the case of complex spaces, the **TO-DO** of compact Stein subsets of $X$ are excellent Noetherian rings ([(1.4)](#equation-1.4) and [(1.10)](#equation-1.10)).
Formal complex spaces can be (locally) embedded into **TO-DO**, cf. [(1.7)](#equation-1.7).

Formal complex manifolds, i.e. formal complex spaces whose stalks are all regular, are studied in [§2](#section-2).
Every point of a formal manifold has an open neighbourhood that is isomorphic to the formal completion of an open subspace of $\CC^n$ along an analytic subset.
A formal Dolbeault complex can be defined for any formal complex space, and, in the case of formal manifolds, this is a fine resolution of the structure sheaf.
This follows directly from the following statement, which is the main result of [§2](#section-2):

::: {.itenv title="Lemma" latex="{Lemma}"}
Let $Y$ be an open subset of $\CC^n$, $S\subseteq Y$ an analytic set in $Y$, and $\hat{Y}$ the formal completion of $Y$ along $S$.
Let $\scr{E}_Y^{0,\bullet}$ be the ordinary Dolbeault complex of $Y$, $\scr{I}^{(\infty)}(S)$ the ideal of functions of $\scr{E}_Y$ that are flat on $S$, and $\scr{E}_{\hat{Y}}^{0,\bullet} \coloneqq \scr{E}_Y^{0,\bullet}/\scr{I}^{(\infty)}(S)\scr{E}_Y^{0,\bullet}$ the formal Dolbeault complex of $Y$.
Then the sequence
$$
  0 \to
  \OO_{\hat{Y}} \to
  \scr{E}_{\hat{Y}} \xrightarrow{\bar{\partial}}
  \scr{E}_Y^{0,1} \xrightarrow{\bar{\partial}}
  \ldots \to
  \scr{E}_Y^{0,n} \to
  0
$$
is exact.
:::

The fact that $\OO_{\hat{Y}}=\Ker(\scr{E}_{\hat{Y}}\xrightarrow{\bar{\partial}}\scr{E}_{\hat{Y}}^{0,1})$ is exact has already been shown by Krasnov.
\oldpage{255}
To prove this, we reduce the problem, using a resolution of singularities and Hironaka's vanishing theorem, to the case where $S$ is a normal crossing divisor.
In this special case, the problem can be solved by "concrete" calculation using theorems of Malgrange.

An analogous statement can be made for the formal de Rham complex.
In fact, the following more general statement (cf. [(2.11)](#equation-2.11)) holds:

::: {.itenv title="Lemma" latex="{Lemma}"}
Let $S$ be an analytic set in a complex space $Y$, defined by a coherent sheaf of $\OO_Y$-ideals $\scr{J}$, and let $\Omega_{\hat{Y}}^\bullet\coloneqq\varinjlim_k\Omega_Y^\bullet/\scr{J}^{k+1}\Omega_Y^\bullet$.
If $Y\setminus S$ is non-singular, then, for all $n\in\mathbb{N}$, the canonical homomorphism
$$
  \scr{H}^n(\Omega_Y^\bullet|S) \to \scr{H}^n(\Omega_{\hat{Y}}^\bullet)
$$
is bijective.
:::

In the special case where $Y$ is a manifold, then $\Omega_{\hat{Y}}^\bullet$ is a resolution of the constant sheaf $\mathbb{C}_S$.
This latter claim can also be found in Hartshorne [@16].

In [§3](#section-3), **TO-DO** between formal complex spaces are considered.
For such maps, Grauert's coherence law (cf. [(3.1)](#equation-3.1)) applies.
In [§4](#section-4) we show how the most important statements of the relative comparison theory between algebraic and analytic geometry [@15; @5] can be transferred to the case where the base is a formal complex space.

In [§5](#section-5) we use the results of [§4](#section-4) to study formal meromorphic functions.
We mention here the following statement (cf. [(5.2)](#equation-5.2)):

::: {.itenv title="Corollary" latex="{Corollary}"}
Let $T$ be a connected exceptional analytic set in a normal complex space $X$, let $X\to Y$ the associated contraction of $T$ to a point $y\in Y$, and let $\hat{X}$ be the formal completion of $X$ along $T$.
Then the ring $M(\hat{X})$ of meromorphic functions on $\hat{X}$ agrees with the quotient field $Q(\hat{\OO}_{Y,y})$ of the completion of the stalks $\OO_{Y,y}$ of $y$ in $Y$.
:::

In addition, we determine the ring of meromorphic functions on the product of a normal formal complex space $Y$ with a compact complex algebraic space $Z$ (cf. [(5.3)](#equation-5.3)).
\oldpage{256}
In the case where $Z$ is the complex projective space $\mathbb{P}_{\mathbb{C}}^r$, we obtain a corollary of Andreotti--Stoll [@1, Theorem 6.9].

Some results from the present article have already been used in [@4] and [@7].


# Formal complex spaces {#section-1}

Let $X=(X,\OO_X)$ be a locally ringed space.
For $x\in X$, let $\frak{m}_x$ be the maximal ideal of the stalk $\OO_x$ of $X$ at the point $x$.
We denote by $\scr{I}_X$ the $\OO_X$ ideal whose sections over an open subset $U$ of $X$ are exactly the elements of $\Gamma(U,\OO_X)$ such that $f_x\in\frak{m}_x$ for all $x\in X$.

::: {.rmenv title="Definition" latex="{Definition}"}
A locally ringed space $X=(X,\OO_X)$ over $\Spec\CC$ is called a *formal complex space* if the following conditions are satisfied:

1. $X_n\coloneqq (X,\OO_X/\scr{I}_X^{n+1})$ is a complex space for all $n\in\NN$; and
2. the canonical homomorphism $\OO_X\to\varinjlim_n\OO_X/\scr{I}_X^{n+1}$ is bijective.
:::

Formal complex spaces form a category, with $\CC$-morphisms as the morphisms.
If $f\colon X\to Y$ is a morphism between formal complex spaces, then the associated homomorphisms $\OO_{Y,f(x)}\to\OO_{X,x}$ are local.
In particular, we have that $\scr{I}_Y\OO_X\subseteq\scr{I}_X$.
If $X$ is a complex space, then $\scr{I}_X=\scr{N}_X$ is the sheaf of nilpotent elements of $X$, and so every complex space is also a formal complex space.

As usual, we say that a subset of a complex space is Stein compact if it is a compact, semi-analytic subset that has an neighbourhood system of open Stein sets.
This definition can be extended in a trivial way to formal complex spaces: A subset $K$ of a formal complex space $X$ is said to be *Stein compact* if $K$, regarded as a subset of the complex space $X_n$, is Stein compact, for all $n$.
Because a complex space is Stein if and only if its reduction is, this condition only needs to be checked for $n=0$.

\oldpage{5}

The following lemma is fundamental for what follows.

::: {.itenv title="Lemma 1.1" latex="{Lemma 1.1}"}
Let $X=(X,\OO_X)$ be a formal complex space, and $K\subseteq X$ a Stein compact subset.
Then the following hold:
:::
