--- 
title: "The fundamental group of the projective line minus three points"
author: "P. Deligne"
date: "1989"
original: 'Deligne, P. "Le Groupe Fondamental de la Droite Projective Moins Trois Points". In _Galois Groups over $\mathbb{Q}$_, Springer--Verlag, MSRI Publications **16** (1989), 79--297. DOI: [`10.1007/978-1-4613-9649-9_3`](https://doi.org/10.1007/978-1-4613-9649-9_3). [[PDF]](http://publications.ias.edu/node/407)'
bibliography: MSRI-16-1989-79.bib
nocite: '@*'
link-citations: true
csl: maths-translations.csl
reference-section-title: "Bibliography"
github-repo: "thosgood/translations"
favicon: "favicon.ico"
---

```{js, echo = FALSE}
$(document).ready(function(e) {gitbook.sidebar.toggle(false, false)});
```

```{r, child = '_translator-note.Rmd'}
```

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

<!-- General shortcuts -->
\providecommand{\mot}{\mathrm{mot}}
\providecommand{\bb}[1]{{\mathbb{#1}}}
\providecommand{\PP}{\bb{P}}
\providecommand{\ZZ}{\bb{Z}}
\providecommand{\hZZ}{\widehat{\bb{Z}}}
\providecommand{\RR}{\bb{R}}
\providecommand{\Gm}{\bb{G}_\mathrm{m}}
\providecommand{\hGm}{G_\mathrm{m}^\wedge}
\renewcommand{\AA}{\bb{A}}
\providecommand{\AAf}{\AA^\mathrm{f}}
\providecommand{\CC}{\bb{C}}
\providecommand{\FF}{\bb{F}}
\providecommand{\QQ}{\bb{Q}}
\providecommand{\DR}{{\mathrm{DR}}}
\providecommand{\cris}{{\mathrm{cris}}}
\providecommand{\crisp}{{\cris\,\,p}}
\providecommand{\crisv}{{\cris\,\,v}}
\providecommand{\BB}{{\mathrm{B}}}
\providecommand{\simto}{\xrightarrow{\sim}}
\providecommand{\simfrom}{\xleftarrow{\sim}}
\providecommand{\et}{\mathrm{et}}
\providecommand{\OO}{\cal{O}}
\providecommand{\an}{\mathrm{an}}
<!-- DeclareMathOperator-type things -->
\providecommand{\Gal}{\operatorname{Gal}}
\providecommand{\Lie}{\operatorname{Lie}}
\providecommand{\Ext}{\operatorname{Ext}}
\providecommand{\Spec}{\operatorname{Spec}}
\providecommand{\Hom}{\operatorname{Hom}}
\providecommand{\End}{\operatorname{End}}
\providecommand{\limind}{\operatorname{lim\,ind}}
\providecommand{\limproj}{\operatorname{lim\,proj}}
\providecommand{\HH}{\operatorname{H}}
\providecommand{\bHH}{\bb{H}}
\providecommand{\shIsom}{\underline{\operatorname{Isom}}}
\providecommand{\real}{\operatorname{real}}
\providecommand{\comp}{\operatorname{comp}}
\providecommand{\Gr}{\operatorname{Gr}}
\providecommand{\Fr}{\operatorname{Fr}}
\providecommand{\dd}{\operatorname{d}}


<!-- Content -->

# Leitfaden {.unnumbered .unlisted}

**!!!TO-DO!!!**

  <!-- \begin{tikzcd}[row sep=1em]
    1 \ar[dd, no head] & 4 \ar[d, no head] & & 9 \ar[d, no head] &
  \\& 5 \ar[d, no head] & & 10 \ar[dl, no head] \ar[dr, no head] &
  \\2 \ar[dd, no head] \ar[dr, no head] & 6 \ar[d, no head] & 11 \ar[ddr, no head] & & 12 \ar[ddl, no head]
  \\& 7 \ar[d, no head] \ar[drr, no head] & & &
  \\3 \ar[dddddrr, no head] & 8 & & 13 \ar[d, no head] &
  \\ & & & 14 \ar[d, no head] &
  \\ & & & 15 \ar[d, no head] &
  \\ & & & 16 \ar[d, no head] \ar[dr, no head] \ar[ddl, no head] &
  \\ & & & 17 \ar[dl, no head, dashed] & 18
  \\ & & 19 & &
  \end{tikzcd} -->


# Introduction {-}

\oldpage{3 (81)}
The present article owes much to A. Grothendieck.
He invented the philosophy of motives, which is our guiding thread.
Around five years ago, he also said to me, with conviction, that the profinite completion $\hat{\pi}_1$ of the fundamental group of $X\coloneqq\PP^1(\CC)\setminus\{0,1,\infty\}$, with the action of $\Gal(\bar{\QQ}/\QQ)$, is a remarkable object, and that it must be studied.

Every finite cover of $X$ can be described by equations with coefficients in the algebraic numbers.
Applying an element of $\Gal(\bar{\QQ}/\QQ)$ to these coefficients, we obtain the equations of another cover.
Understanding how $\Gal(\bar{\QQ}/\QQ)$ permutes the isomorphism classes of finite covers essentially reduces to understanding the Galois action on $\hat{\pi}_1$.
"Essentially", since I have omitted mentioning the base points, and since the Galois covers have not been thought of as $G$-covers, for $G$ their automorphism group.

Up until now, we have not had the language necessary to study the Galois action on $\hat{\pi}_1$.
A. Grothendieck and his students have developed a combinatorial description ("charts") of finite covers of $X$, based on a decomposition of $\PP^1(\CC)$ into the two "spherical triangles" $\Im(z)\geq0$ and $\Im(z)\leq0$, with sides $[\infty,0]$, $[0,1]$, and $[1,\infty]$.
This has not helped in understanding the Galois action.
We have only a few unresolved examples of covers whose Galois conjugates have been calculated.

In this article, we only consider when $\hat{\pi}_1$ is rendered nilpotent, i.e. quotients $\hat{\pi}_1^{(N)}$ of $\hat{\pi}_1$ by the subgroups of its decreasing central series.
The profinite group $\hat{\pi}_1^{(N)}$ is a product over primes $\ell$ of nilpotent pro-$\ell$-groups: $\hat{\pi}_1^{(N)} = \prod_\ell \hat{\pi}_1^{(N)}{}\!_\ell$.
Each $\hat{\pi}_1^{(N)}{}\!_\ell$ is an $\ell$-adic Lie group.
It admits a Lie algebra $\Lie\hat{\pi}_1^{(N)}{}\!_\ell$, which is a Lie algebra over $\QQ_\ell$.
If we choose a base point $x\in X(\QQ)=\QQ\setminus\{0,1\}$, then $\Gal(\bar{\QQ}/\QQ)$ acts on these Lie algebras.
The action, up to inner automorphism, does not depend on the choice of $x$.
We would like to understand these actions.

The nilpotent versions of $\pi_1$ are very close to cohomology.
This is most visible in the theory of D. Sullivan [@Su; @Mo].
_Notation:_ for $\Gamma$ a finitely generated group, let $Z^i\Gamma$ be the decreasing central series, let $\Gamma^{(N)}=\Gamma/Z^{N+1}\Gamma$, and let $\Gamma^{[N]}=\Gamma^{(N)}/\mathrm{torsion}$ [(9.3)](#chunk-9.3).
The theory of Malcev [@Mal] attaches a nilpotent Lie algebra over $\QQ$, denoted $\Lie\Gamma^{[N]}$, to $\Gamma^{[N]}$, such that $\Gamma^{[N]}$ is a congruence subgroup of the unipotent algebraic group over $\QQ$ of the Lie algebra $\Lie\Gamma^{[N]}$.
By D. Sullivan, if $X$ is a differentiable manifold, then $\Lie\pi_1(X)^{[N]}\otimes\RR$ is determined, up to inner automorphism, by the differential-graded algebra $\Omega_X^\bullet$, taken up to quasi-isomorphism.

\oldpage{4 (82)}

This close relation with cohomology hints that the study of nilpotent versions of $\hat{\pi}_1$ is far from the "anabelian" dream of A. Grothendieck.
It allows us, however, to use his philosophy of motives.

Let $k$ be a number field.
If $X$ is an algebraic variety over $k$, then we have a whole series of parallel cohomology theories for $X$: the classical cohomology of $X(\CC)$ (for each complex embedding of $k$), crystalline cohomology (which is equal to de Rham cohomology if $X$ is smooth), $\ell$-adic cohomology, ...
The groups thus obtained are endowed with various additional structures (mixed Hodge, Galois action, ...) and are linked by comparison isomorphism.
In [§1](#section-1), we axiomatise the situation by defining "realisation systems over $k$".
The exact definition is not to be taken seriously: considering the applications --- and what we are capable of doing --- it could be wise to either add or remove data as much as axioms.
The essential, for us, is that

i. The category of realisation systems is endowed with a $\otimes$ satisfying the usual properties: it is a Tannakian category over $\QQ$.

ii. Conjecturally, the category of motives is a full subcategory of the category of realisation systems.

Condition (ii) requires, in particular, that, for every variety $X$ over $k$ and for every $i$, the available cohomology theories, applied to $X$, give a realisation system $H^i(X)$ over $k$ (which we will denote by $H^i(X)_\mot$, and call the motivic $H^i$ of $X$).

Analogous ideas have been independently developed by U. Jannsen [@J].
In [@J], U. Jannsen defines (mixed) motives over $k$ as constituting the Tannakian subcategory (of the category of realisation systems) generated by the $H^i(X)$ for $X$ smooth and quasi-projective.
Here we are still being imprecise, saying that a motive over $k$ is a realisation system "of geometric origin".
For $X$ over $k$ and $x\in X(k)$, we want, for example, to regard $\Lie\pi_1(X(\CC),x)^{[N]}$ as a realisation of a motive over $k$.

This article owes much to an unpublished work of Z. Wojtkoviak.
For $X=\PP^1\setminus\{0,1,\infty\}$ and $x\in X(\CC)$, I proposed to him a definition of the mixed Hodge structure of $\Lie\pi_1(X(\CC),x)^{[N]}$.
He calculated it in part, for small $N$, and, to my extreme surprise, show that, for $N=4$, its description involves $\zeta(3)$.
A decanted form of the calculations appear in [§19](#section-19).
In fact, the whole article originates from my desire to understand the result of Z. Wojtkoviak.
\oldpage{5 (83)}
I have also been helped by the answer by O. Gabber to my question "How can we construct an extension of $\ZZ_\ell$ by $\ZZ_\ell(3)$, uniformly in $\ell$?": "By a class in $K_5(\QQ)$", as well as by the conjectures of A. Beilinson on the values of $L$-functions.

If $X$ is an algebraic variety over a number field $k$, $x\in X(k)$, and $N$ an integer, then we want to have a realisation system $\Lie\pi_1(X,x)_\mot^{(N)}$.
We can only succeed in constructing this under additional hypotheses on $X$: in the general case, certain realisations are missing.
The case of $\PP^1$ minus some points --- more generally, of smooth rational varieties --- is nonetheless covered.

Let $k=\QQ$, $X=\PP^1\setminus\{0,1,\infty\}$, and $x\in X(\QQ)$.
The associated graded algebra for the weight filtration of $\Lie\pi_1(X,x)_\mot^{(N)}$ is the free Lie algebra on $H_1(X)_\mot$, modulo its $Z^{N+1}$ (decreasing central series).
$H_1(X)_\mot$ is the sum of two copies of the Tate motive $\QQ(1)$.
We thus deduce that $\Lie\pi_1(X,x)_\mot^{(N)}$ is an iterated extension of Tate motives $\QQ(n)$.
The fact that non-trivial extensions appear is what gives it its charm.

I conjecture that, over a number field $k$, the group of motivic extensions of $\QQ$ by $\QQ(n)$ ($n>0$) is $K_{2n-1}(k)\otimes\QQ$.
For a general framework into which we can place this conjecture, see [@B, §5].
In particular, for $k=\QQ$, we want $\Ext^1(\QQ,\QQ(n))$ to be zero for $n$ even, and of dimension $1$ for $n\geq3$ odd.
This is the motivic $\Ext^1$: extensions as realisation systems that "come from algebraic geometry".
This conjecture places severe restrictions on $\Lie\pi_1(X,x)_\mot^{(N)}$, which are far from having been verified.
What we know concerns, up to now, only the quotient by the second derived group.
A large part of this article is dedicated to developing a language in which the consequences of the conjecture affecting $\Lie\pi_1(X,x)_\mot^{(N)}$ can be clearly stated.

We now go through this article, pointing out several shortcuts.

In [§1](#section-1), we describe the category of realisation systems over a base $S$.
The base $S$ can be: $\Spec(\QQ)$, $\Spec(\FF)$ for $\FF$ a number field, an open subset of the spectrum of the ring of integers of a number field, or smooth over $\Spec(\ZZ)$.
In this category, the $\Hom$ are $\QQ$-vector spaces.
We also define a notion of integer structure;
in the category of realisation systems with integer coefficients (= endowed with an integer structure), the $\Hom$ are free $\ZZ$-modules of finite type.
The definition has a crystalline component.
The reader is invited to ignore this for a first approximation.
The theory coincides with that of U. Jannsen [@J].
\oldpage{6 (84)}
The crystalline aspect will be neglected in the rest of the introduction.

In [§2](#section-2) we give examples.
We also explain what an extension of the unit realisation system $\ZZ$ by a realisation system $M$ with integer coefficients is.
_Terminology:_ $M$-torsor, or torsor under $M$.
_Example:_ the Kummer $\ZZ(1)$-torsor, where $\ZZ(1)$ is the Tate motive.

In [§3](#section-3) we describe certain remarkable torsors, which can be said to be cyclotomic, under the Tate motive $\ZZ(k)$.
[§16](#section-16) explains how these torsors naturally appear in the study of $\pi_1$ of $\PP^1\setminus\{0,1,\infty\}$.
The description here is direct, but unmotivated.
The claim that some of these torsors are of finite order ([(3.5)](#chunk-3.5), [(3.14)](#3.14)) lets us recover the known formulas expressing the Dirichlet $L$-functions in negative integers as integrals of distributions over $\hZZ$ with values in $\hZZ$: a version of Kummer congruences.
In [§18](#section-18), we prove [(3.5)](#chunk-3.5) and [(3.14)](#chunk-3.14) using the geometric interpretation of [§16](#section-16).
In [§3](#section-3), we give a direct proof, by using the known formulas for $L(\chi,1-k)$.

[§4](#section-4) is a pot-pourri of reminders on Ind-objects and pro-objects.
The reader is invited to consult this only when needed.

We want to give a motivic meaning to an assertion like the following: the fundamental group of $\PP^1(\CC)\setminus\{0,1,\infty\}$ (at base point $b$) is freely generated by the following loops:

**TO-DO**

<!--
$$
\label{figure1}
  \begin{tikzpicture}
    \node[label=below:{$b$}] at (0,0) {$\bullet$};
    \node[label={[label distance=-3mm]below right:{\scriptsize$1$}}] at (3,1) {$\bullet$};
    \node[label={[label distance=-3mm]below right:{\scriptsize$0$}}] at (-3,1) {$\bullet$};
    \draw[thick,domain=-20:110,->] plot ({0.5*cos(\x)-3}, {0.5*sin(\x)+1});
    \draw[thick,domain=110:310] plot ({0.5*cos(\x)-3}, {0.5*sin(\x)+1});
    \draw[thick,domain=-130:-70,->] plot ({0.5*cos(\x)+3}, {0.5*sin(\x)+1});
    \draw[thick,domain=-70:200] plot ({0.5*cos(\x)+3}, {0.5*sin(\x)+1});
    \draw[thick] (0,0.125) to (-2.52,0.84);
    \draw[thick] (0,0.125) to (2.52,0.84);
    \draw[thick] (0,-0.125) to (-2.69,0.61);
    \draw[thick] (0,-0.125) to (2.69,0.61);
  \end{tikzpicture}
\tag{1}
$$
-->

The purpose of [§5](#section-5), [§7](#section-7), and [§15](#section-15) is to construct the language which allows us to do this.
This consists of

a. giving a motivic meaning to $\pi_1(X,x)^{(N)}$, not only to its Lie algebra;

b. giving a motivic meaning to the torsor [(0.6)](#chunk-0.6) of homotopy classes of paths from $b_1$ to $b_2$;

c. in [(1)](#figure-1), the "monodromy around $0$" loop is only unambiguously determined for $b$ "close to $0$".
    We must define what it means for a base point to be "close to $0$".

\oldpage{7 (85)}

Our solution will be to define a motivic linear group as being an Ind-object in the category of motives, endowed with the structure of a commutative Hopf algebra.
To avoid speculation: consider the group in realisation systems, and replace "motive" by "realisation system".
There is an analogous definition for torsors under a group.
We separately define a notion of "integer" structures.
This definition has the advantage that the standard constructions in algebraic geometry (decreasing central series, quotients, pushing forward a $G$-torsor by $G\to H$, twisting by a torsor, ...) all translate automatically to the motivic case.
This, in an arbitrary Tannakian category, is explained in [§5](#section-5).

In [§7](#section-7), we reinterpret these definitions in a language that is closer to that of our applications.
The reader who is displeased by the general nonsense of [§5](#section-5) and [§7](#section-7) can take the interpretations given in [§7](#section-7) as the definition of groups, torsors, ... in realisation systems.
Drawback: every standard construction must be redefined in this case.

In the classical definition of $\pi_1$, the role of the base point $b$ can be played by a contractible subset $B$.
It can also be played by a filter $\mathcal{B}$ on $X$ whose base if given by contractible subsets.
For example, if $X$ is a Riemann surface $\overline{X}$ minus a point $s$, and $v$ is a non-zero tangent vector at $s$, with $z$ being a local coordinates centred at $s$, then we can take the contractible subsets

**TO-DO**

<!--
$$
  \begin{gathered}
    0<|z/v|<\varepsilon,
    \quad
    |\arg(z/v)|<\eta:
  \\\begin{tikzpicture}
      \node[label={below:{$s$}}] at (0,0) {$\bullet$};
      \draw[thick,-latex] (0,0) to (0,2) node [label={above:{$v$}}] {};
      \draw (0,0) to (50:1.5);
      \draw (0,0) to (130:1.5);
      \draw [domain=50:130] plot ({1.5*cos(\x)}, {1.5*sin(\x)});
    \end{tikzpicture}
  \end{gathered}
$$
-->

The filter $\mathcal{B}(v)$ that they generate is independent of the chosen coordinate.
By this construction, a non-zero tangent vector at $s$ can act as a base point in the definition of $\pi_1$ of $X$.

The same phenomenon occurs in the profinite theory of $\pi_1$, and in the "de Rham" theory.
Be aware that $\mathcal{B}(v)=\mathcal{B}(\lambda v)$ for real $\lambda>0$, but that this fact has no analogue in the other theories.
There constructions are explained in [§15](#section-15).
\oldpage{8 (86)}
They allow us, in the definition of the motivic $\pi_1$ of $X$, to take a base point "at infinity", like the tangent vector $v$ at $s$.

Let $X=\PP^1\setminus\{0,1,\infty\}$.
An algebraic meaning of "base point close to $0$" is "non-zero tangent vector at $0$".
For such a base point $b$, the monodromy around $0$ has a motivic meaning: it is a morphism of motivic groups
$$
  \ZZ(1) \to \pi_1(X,b)_\mot.
$$
Here and later on, $\pi_1$ is the pro-unipotent $\pi_1$, defined as the projective limit of the motivic groups $\pi_1(X,b)_\mot^{(N)}$.

We take the base point to be the tangent vector $1$ at $0$.
We have a good reduction $\mod p$ for every $p$, and $\pi_1(X,b)_\mot^{(N)}$ is a linear group in the Tannakian category of motives over $\Spec(\ZZ)$ that are iterated extensions of Tate motives.
[§8](#section-8) states a conjecture on the $\Ext^1(\QQ,\QQ(k))$ in this category, as well as some consequences.
At the end of [§16](#section-16), we make these explicit in the case of $\pi_1(X,b)_\mot^{(N)}$.
I hope that this places the $\zeta(3)$ discovered by Z. Wojtkoviak in its natural setting.
[§6](#section-6) is preliminary.
For the essential idea, see [(6.2)](#chunk-6.2).

To define the motivic $\pi_1$, we need to patch together the various theories of $\pi_1$ that we have at our disposal, guided by the goal of constructing a motivic group in the sense of [§5](#section-5), explained in [§7](#section-7).
This is done in [§10](#section-10) to [§13](#section-13), after a reminder ([§9](#section-9)) on the Malčev theory of nilpotent groups and their Lie algebras.
The result leaves much to be desired.
It is only completely studied for smooth algebraic varieties whose smooth compactifications $\overline{X}$ satisfy $H^1(\overline{X},\scr{O})=0$.
Another complaint: I sometimes only sketch the definition of structures that will be used in future calculations.

In [§16](#section-16), we finally explain what the $\ZZ(k)$-torsors from [§3](#section-3) have to do with the $\pi_1$ of the projective line minus three points.
The justifying calculations are given in [§19](#section-19).
We give, in [§17](#section-17) and [§18](#section-18), a geometric explanation of some of their properties.


# Terminology and notation {#section-0 .unnumbered}

\oldpage{9 (87)}

::: {.rmenv #chunk-0.1 title="0.1" latex="{0.1}"}
We denote inductive limits and projective limits by $\limind$ and $\limproj$.
:::

::: {.rmenv #chunk-0.2 title="0.2" latex="{0.2}"}
For a prime number $\ell$, we denote by $\ZZ_\ell$ and $\QQ_\ell$ the completions of $\ZZ$ and $\QQ$ for the $\ell$-adic topology:
$$
  \begin{aligned}
    \ZZ_\ell &= \limproj \ZZ/\ell^n\ZZ,
  \\\QQ_\ell &= \ZZ_\ell\otimes\QQ.
  \end{aligned}
$$
We denote by $\hZZ$ the profinite completion of $\ZZ$, and by $\AAf$ the ring of finite adeles:
$$
  \begin{gathered}
    \hZZ \xrightarrow{\sim} \prod_\ell \ZZ_\ell,
  \\\AAf = \hZZ\otimes\QQ.
  \end{gathered}
$$
We denote by $\bar{\QQ}$ the algebraic closure of $\QQ$ in $\CC$.
:::

::: {.rmenv #chunk-0.3 title="0.3" latex="{0.3}"}
For an abstract group, algebraic group, profinite group, or Lie algebra $A$, we denote by $Z^i(A)$ the descending central series.
We use the numbering for which $A=Z^1(A)$.
We denote by $A^{(N)}$ the quotient of $A$ by $Z^{N+1}(A)$.
In the case of abstract or profinite groups, we denote by $A^{[N]}$ the largest torsion-free quotient of $A^{(N)}$.
:::

::: {.rmenv #chunk-0.4 title="0.4" latex="{0.4}"}
We denote by $\otimes$ an extension of scalars.
For example, if $X$ is a scheme over $k$, and $k'$ is an extension of $k$, then we set
$$
  X\otimes k'
  \coloneqq X\times_{\Spec(k)}\Spec(k').
$$
:::

::: {.rmenv #chunk-0.5 title="0.5" latex="{0.5}"}
Let $G$ be a sheaf of groups on a site $\cal{S}$, or, equivalently, in a topos $T$.
Useful particular case: if $\cal{S}$ is a point, then a sheaf is a set and $G$ is a group.
A _$G$-torsor_, or _torsor under $G$_, is a sheaf $P$ endowed with a right $G$-action such that $P$ is locally isomorphic to $G$ acting on itself by translations on the right.
We also call such an object a _right $G$-principal homogeneous space_, or a _right principal homogeneous space under $G$_.
\oldpage{10 (88)}
If $P$ is a $G$-torsor, then a sheaf $X$ on which $G$ acts can be _twisted_ by $P$.
The twisting $X^P$ is the contracted product $P\times^G X=(P\times X)/G$, and is endowed with $\alpha\colon P\to\shIsom(X,X^P)$ satisfying $\alpha(pg)=\alpha(p)g$.

An _$(H,G)$-bitorsor_ (cf. SGA 7, VII.1, or Girard, _Cohomologie non abelienne_, III 1.5) is a space which is simultaneously a left principal homogeneous space under $H$ and a right principal homogeneous space under $G$, with the $G$- and $H$-actions commuting with one another.
If $P$ is a $G$-torsor, then the sheaf of automorphisms of $P$ is the twisting $G^P$ of $G$ by $P$ (under the action of $G$ on itself by inner automorphisms), and $P$ is a $(G^P,P)$-bitorsor.
By this construction, the data of an $(H,G)$-bitorsor $P$ is equivalent to the data of a $G$-torsor $P$ along with an isomorphism between $H$ and $G^P$.
_Notation:_ we will write ${}_HP_G$ to mean that $P$ is an $(H,G)$-bitorsor.

We will use the following operations on torsors and bitorsors.

- **Pushing forward:** (or **transporting**) a $G$-torsor $P$ by $\varphi\colon G\to H$ to obtain an $H$-torsor $\varphi(P)$.
    A _$\varphi$-morphism_ from the $G$-torsor $P$ to the $H$-torsor $Q$ is some $u\colon P\to Q$ such that $u(pg)=u(p)\varphi(g)$.
    A $\varphi$-morphism factors uniquely through an isomorphism of $H$-torsors between $\varphi(P)$ and $Q$.

- **Composition:** of a $(G_1,G_2)$-bitorsor $P$ and a $(G_2,G_3)$-bitorsor $Q$:
    the $(G_1,G_3)$-bitorsor $P\circ Q$ given by the contracted product $P\times^{G_2}Q=(P\times Q)/G_2$.

- **Inverse:** of ${}_{G_1}P_{G_2}$:
    the $(G_2,G_1)$-bitorsor $P^{-1}$, unique up to isomorphism, endowed with $(p\mapsto p^{-1})\colon P\to P^{-1}$ such that $(g_1pg_2)^{-1}=g_2^{-1}p^{-1}g_1^{-1}$.

    For $G$-torsors $P$ and $Q$, the sheaf $\shIsom(P,Q)$ of isomorphisms of $G$-torsors from $P$ to $Q$ is the $(G^Q,G^P)$-bitorsor $G\circ P^{-1}$.

If the site $\cal{S}$ is such that the representable functors $h_S$ are sheaves, then we can transport these operations to $\cal{S}$ via the fully faithful functor $S\mapsto h_S$, with each construction only being defined if it does not leave the collection of representable sheaves.
:::


# Mixed Motives {#section-1}

\oldpage{11 (89)}

:::: {.rmenv #chunk-1.1 title="1.1" latex="{1.1}"}
For algebraic varieties, we have various parallel cohomology theories.
The most important for us will be de Rham and $\ell$-adic cohomology.

- **De Rham cohomology.**
    Let $k$ be a field of characteristic $0$, and $X$ an algebraic variety over $k$.
    Suppose that $X$ is smooth.
    The de Rham cohomology groups $\HH_\DR^i(X)$ are the hypercohomology groups of the de Rham complex:
    $$
      \HH_\DR^i(X)
      \coloneqq \bHH^i(X,\Omega_{X/k}^\bullet)
    $$
    cf. [@G].
    These are vector spaces over $k$.
    If $k'$ is an extension of $k$, and $X'$ over $k'$ is given by extension of scalars of $X$, then
    $$
      \HH_\DR^i(X') = \HH_\DR^i(X)\otimes_k k'.
    $$
    If $X$ is not smooth, then the de Rham complex no longer gives a reasonable theory.
    We can define the $\HH_\DR^i(X)$ by reduction to the smooth case, by the methods of [@D3], or, if $X$ admits an embedding into a smooth variety $Z$, as the hypercohomology of the de Rham complex of the formal completion of $Z$ along $X$ (R. Hartshorne, _On the de Rham cohomology of algebraic varieties_, Publ. Math. IHES **45** (1975), p. 5--99);
    more intrinsically, it is the crystalline cohomology of $X$ (A. Grothendieck, _Crystals and the de Rham cohomology of schemes_, Notes by J. Coates and O. Jussila, in: "dix exposés sur la cohomologie des schémas", North Holland (1968)).

- **$\ell$-adic cohomology.**
    Let $\ell$ be a prime number;
    if $k$ is an algebraically closed field of characteristic $\neq\ell$, then we have the $\ell$-adic theory $X\mapsto\HH^i(X,\QQ_\ell)$ that associates, to $X$ over $k$, cohomology groups which are vector spaces over $\QQ_\ell$ (cf. SGA 5, VI).
    They are defined from the cohomology groups with coefficients in $\ZZ/(\ell^n)$, and we allow ourselves to give, as reference for a theorem in $\ell$-adic cohomology, the place where its $\ZZ/(\ell^n)$ analogue is proved.
    The $\HH^i(X,\QQ_\ell)$ depend only on $X$.
    In particular, if $k$ is the algebraic closure of $k_0$, and if $X$ is given by extension of scalars of some $X_0$ over $k_0$, then $\Gal(k/k_0)$ acts (semi-$k$-linearly) on $X$, and thus acts on the $\HH^i(X,\QQ_\ell)$.
    This action is continuous.
    If $k'$ is an algebraically closed extension of $k$, and if $X'$ is given by extension of scalars of $X$, then $\HH^i(X,\QQ_\ell)\xrightarrow{\sim}\HH^i(X',\QQ_\ell)$.
    \oldpage{12 (90)}
    This follows by passing to the limit in the base change theorem for a smooth morphism [SGA 4, XVI, 1.2]: $k'$ is the filtrant inductive limit of the $k$-algebras $A$ with $\Spec(A)$ smooth over $k$.

If $k=\CC$, then we have the topological space $X(\CC)$ of points of $X$, as well as its rational cohomology $\HH^\bullet(X(\CC),\QQ)$.
We have canonical isomorphisms from [@G] and [SGA4, XVI, 4.1]:

::: {.eqtag #equation-1.1.1}
$$
  \HH_\DR^i(X) = \HH^i(X(\CC),\QQ)\otimes_{\QQ}\CC
\tag{1.1.1}
$$
:::

::: {.eqtag #equation-1.1.2}
$$
  \HH^i(X,\QQ_\ell) = \HH^i(X(\CC),\QQ)\otimes_{\QQ}\QQ_\ell.
\tag{1.1.2}
$$
:::

If $k$ is a field of characteristic $0$, and $\sigma\colon k\to\CC$ a complex embedding, with $\bar{k}$ the algebraic closure of $k$ in $\CC$ via $\sigma$, then we obtain the isomorphisms

::: {.eqtag #equation-1.1.3}
$$
  \HH_\DR^i(X)\otimes_{k,\sigma}\CC = \HH^i(X(\CC),\QQ)\otimes_{\QQ}\CC
\tag{1.1.3}
$$
:::

::: {.eqtag #equation-1.1.4}
$$
  \HH^i(X\otimes\bar{k},\QQ_\ell) = \HH^i(X(\CC),\QQ)\otimes_{\QQ}\QQ_\ell
\tag{1.1.4}
$$
:::

where $X(\CC)$ is the topological space of points of the complex algebraic variety given by the extension of scalars via $\sigma$ of $X$.

The existence of parallel cohomology theories lead A. Grothendieck to conjecture the existence, for all base fields $k$, of a motivic theory $X\mapsto\HH_\mot^i(X)$, defined on algebraic varieties (i.e. schemes of finite type) over $k$ and with values in a category $\cal{M}(k)$ (to be defined) of motives over $k$.
The known theories would then be deduced from the motivic theory by applying _realisation_ functors.

The category $\cal{M}(k)$ should be an abelian category, with $\Hom$ groups of finite dimension over $\QQ$.
It should be endowed with a tensor product $\otimes\colon\cal{M}(k)\times\cal{M}(k)\to\cal{M}(k)$ and associativity and commutative data $(X\otimes Y)\otimes Z\simto X\otimes(Y\otimes Z)$ and $X\otimes Y\to Y\otimes X$ satisfying the usual properties
--- more precisely, making $\cal{M}(k)$ into a Tannakian category [@Sa; @DM; @D4].
By the theory of Tannakian categories, $\cal{M}(k)$ would be the category of representations of a gerbe whose band is affine over $\Spec(\QQ)$.
For $k$ of characteristic $0$, the category $\cal{M}(k)$ with its tensor product should be equivalent to the category of representations of an scheme in affine groups (i.e. a proalgebraically affine group) over $\QQ$.

Each $\HH_\mot^i(X)$ would be a contravariant functor in $X$.
We should also have Künneth isomorphisms

::: {.eqtag #equation-1.1.5}
$$
  \HH_\mot^i(X\times Y)
  \simeq \bigoplus_{i=j+k} \HH_\mot^j(X)\otimes\HH_\mot^k(Y)
\tag{1.1.5}
$$
:::

\oldpage{13 (91)}
giving rise to commutative diagrams
$$
  \begin{CD}
    \HH_\mot^i(X\times Y) @>\longleftarrow>> \HH_\mot^i(Y\times X)
  \\@VVV @VVV
  \\\HH_\mot^j(X)\otimes\HH_\mot^k(Y) @>>{(-i)^{jk}}> \HH_\mot^k(Y)\otimes\HH_\mot^j(X)
  \end{CD}
$$
$$
  \begin{CD}
    \HH_\mot^i((X\times Y)\times Z) @>\longleftarrow>> \HH_\mot^i(X\times(Y\times X))
  \\@VVV @VVV
  \\(\HH_\mot^j(X)\otimes\HH_\mot^k(Y))\otimes\HH_\mot^\ell(Z) @>>\longleftarrow> \HH_\mot^j(X)\otimes(\HH_\mot^k(Y)\otimes\HH_\mot^\ell(Z)).
  \end{CD}
$$

Each of the known cohomological theories should give rise to a "realisation" functor, compatible with the tensor product.
For example, for $k$ of characteristic $0$, we would have
$$
  \real_\DR\colon\cal{M}(k)
  \to \text{vector spaces over }k
$$
and, for $X$ an algebraic variety over $k$, a functorial isomorphism
$$
  \HH_\DR^i(X) = \real_\DR\HH_\mot^i(X)
$$
compatible with the Künneth isomorphisms.

The subcategory of $\cal{M}(k)$ _generated_ by a set $\cal{M}$ of motives is defined to be the smallest full subcategory of $\cal{M}(k)$ containing $\cal{M}$ that is stable under $\oplus$, $\otimes$, taking the dual, and sub-quotients.
If we only consider certain algebraic varieties $X$ over $k$, then it can be useful to consider, instead of $\cal{M}(k)$, the subcategory generated by the $\HH^i(X)$.
::::

::: {.rmenv #chunk-1.2 title="1.2" latex="{1.2}"}
If we only consider smooth and projective varieties over a field $k$, and we assume the "standard" conjectures on algebraic cycles, then Grothendieck has shown how to define the category of motives generated by the $\HH_\mot^i(X)$ (cf. [@Kl; @Man]);
it is a semi-simple abelian category.

If we do not restrict ourselves to the category generated by the $\HH_\mot^i(X)$ for $X$ smooth and projective over $k$, then we no longer have even a conjectural definition of what the category of motives over $k$ should be.
However, the philosophy of motives is not made any less useful by this fact:
it organises known facts, poses questions, and suggests precise conjectures.
:::

\oldpage{14 (92)}

::: {.rmenv #chunk-1.3 title="1.3" latex="{1.3}"}
In each of the known theories, the $\HH^i(X)$ are endowed with an increasing filtration $W$, known as the _weight filtration_ [@D5], as well as comparison isomorphisms such that [(1.1.1)](#equation-1.1.1) and [(1.1.2)](#equation-1.1.2) are compatible with $W$.
Furthermore, every natural map is strictly compatible with $W$.
From this, we get a new requirement for the category of motives:
every motive is endowed with a weight filtration $W$, compatible with the tensor product, and strictly compatible with every morphism $f\colon M\to N$, i.e.
$$
  f(M)\cap W_i(N)
  = f(W_i(M)).
$$

We say that a motive $M$ is _pure of weight $i$_ if $W_i(M)=M$ and $W_{i-1}(M)=0$.
For $X$ smooth and projective, $\HH_\mot^i(X)$ is pure of weight $i$.
We want for the $\otimes$-category generated by the $\HH_\mot^i(X)$, for $X$ smooth and projective over $k$, to be the sum of pure motives.
In terms of pure motives, the properties of $W$ can be written as follows:
every motive is the iterated extension of pure motives, and, for $M$ and $N$ pure of weights $m$ and $n$ (respectively),

a. $M\otimes N$ is pure of weight $m+n$;
b. for $m\neq n$, $\Hom(M,N)=0$; and
c. for $m\leq n$, $\Ext^1(M,N)=0$.

Often, pure motives (or direct sums of pure motives) are simply called _motives_, and their category admits the conjectural description [@Kl; @Man];
the more general motives, considered here, are then called _mixed motives_
:::

:::: {.rmenv #chunk-1.4 title="1.4" latex="{1.4}"}
If we cannot define the category of motives, we can at least describe a sequence of compatibilities between the $\HH^i(X)$ taken in the various cohomological theories, i.e. describe compatibilities that should exist between the various realisations of a motive.
We will explain the case of motives over $\QQ$:
a motive over $\QQ$ should give rise to a system [(M1)](#M1) to [(M10)](#M10) as below, satisfying axioms [(AM1)](#AM1) to [(AM5)](#AM5).

_Terminology:_
all the vector spaces are assumed to be of finite dimension;
"_almost every_ prime number" means "all, except for a finite number".

\oldpage{15 (93)}

::: {.trmenv #M1 title="(M1)" latex="{(M1)}"}
A vector space $M_\BB$ over $\QQ$, called the _Betti realisation_.
:::

::: {.trmenv #M2 title="(M2)" latex="{(M2)}"}
A vector space $M_\DR$ over $\QQ$, called the _de Rham realisation_.
:::

::: {.trmenv #M3 title="(M3)" latex="{(M3)}"}
A module $M_\AAf$ over $\AAf$, called the _étale cohomology realisation_, which is of finite type, by [(M5)](#M5).
:::

::: {.trmenv #M4 title="(M4)" latex="{(M4)}"}
For almost every prime number $p$, a vector space $M_{\crisp}$ over $\QQ_p$, called the _crystalline realisation_ of the mod-$p$ reduction.
:::

::: {.trmenv #M5 title="(M5)" latex="{(M5)}"}
Comparison isomorphisms
$$
  \begin{aligned}
    \comp_{\DR,\BB}\colon
    &M_\BB\otimes\CC \simto M_\DR\otimes\CC
  \\\comp_{\AAf,\BB}\colon
    &M_\BB\otimes\AAf \simto M_\AAf
  \\\comp_{\crisp,\DR}\colon
    &M_\DR\otimes\QQ_p \simto M_{\crisp}
  \end{aligned}
$$
:::

::: {.trmenv #M6 title="(M6)" latex="{(M6)}"}
$M_\BB$, $M_\DR$, $M_\AAf$, and $M_{\crisp}$ are endowed with a finite increasing filtration $W$, called the _weight filtration_.
We also denote by $W$ the filtrations that are induced by extension of scalars.
The comparison isomorphisms respect $W$.
:::

::: {.trmenv #M7 title="(M7)" latex="{(M7)}"}
$M_\BB$ is endowed with an involution $F_\infty$, called the _Frobenius at infinity_, which respects $W$.
:::

::: {.trmenv #M8 title="(M8)" latex="{(M8)}"}
$M_\DR$ is endowed with a finite decreasing filtration $F$, called the _Hodge filtration_.
We also denote by $F$ the filtrations that are induced by extension of scalars.
:::

::: {.trmenv #M9 title="(M9)" latex="{(M9)}"}
$M_\AAf$ is endowed with an action of $\Gal(\bar{\QQ}/\QQ)$ which respects $W$.
:::

::: {.trmenv #M10 title="(M10)" latex="{(M10)}"}
$M_{\crisp}$ is endowed with an automorphism
$$
  \phi_p\colon M_{\crisp}\to M_{\crisp},
$$
called the _crystalline Frobenius_, which respects $W$.
:::

::: {.trmenv #AM1 title="(AM1)" latex="{(AM1)}"}
$M_\BB$, endowed with $W$ and with the filtration $F$ of $M_\BB\otimes\CC=M_\DR\otimes\CC$, is a mixed Hodge $\QQ$-structure [@D2, Definition 2.3.8].
:::

::: {.trmenv #AM2 title="(AM2)" latex="{(AM2)}"}
We have two real structures on $M_\BB\otimes\CC$ (identified with $M_\DR\otimes\CC$ by the comparison isomorphism), namely $M_\BB\otimes\RR$ and $M_\DR\otimes\RR$;
these define antilinear involutions $c_\BB$ and $c_\DR$, of which $M_\BB\otimes\RR$ and $M_\DR\otimes\RR$ are (respectively) the fixed points.
These involutions, as well as the linear involution extending $F_\infty$, all commute with one another, and satisfy
$$
  F_\infty = c_\BB c_\DR.
$$
\oldpage{16 (94)}
In other words, $c_\DR$ respects $M_\BB\subset M_\BB\otimes\CC=M_\DR\otimes\CC$, and $c_\DR|M_\BB=F_\infty$.
:::

::: {.trmenv #AM3 title="(AM3)" latex="{(AM3)}"}
For each prime number $\ell$, let $M_\ell$ be given by extension of scalars of $M_\AAf$, so that $M_\AAf$ is then a restricted product of the $M_\ell$.
There exists a finite set $S$ of prime numbers such that, for each $\ell$, the representation $M_\ell$ of $\Gal(\bar{\QQ}/\QQ)$ is unramified outsied of $S$ and $\ell$.
:::

::: {.trmenv #AM4 title="(AM4)" latex="{(AM4)}"}
For large enough $S$, if $p\not\in S$, then, for all $\ell\neq p$, the eigenvalues of a geometric Frobenius at $p$ on the $\Gr_n^W(M_\ell)$, and those of $\phi_p$ on the $\Gr_n^W(M_{\crisp})$, are algebraic numbers whose complex conjugates are all of absolute value $p^{n/2}$, and are $\ell'$-adic units for $\ell'\neq p$.
:::

::: {.trmenv #AM5 title="(AM5)" latex="{(AM5)}"}
Let $c\in\Gal(\bar{\QQ}/\QQ)$ be complex conjugation.
Then $c$ acts on $M_\AAf$ respecting $M_\BB\subset M_\AAf$, and induces the involution $F_\infty$ on $M_\BB$.
:::
::::

::: {.rmenv #chunk-1.5 title="1.5 Remarks" latex="{1.5 Remarks}"}
—

i. If $M_\DR$ is given, then the data of $M_\BB$, $F_\infty$, and $\comp_{\DR,\BB}$ satisfying [(AM2)](#AM2) is equivalent to that of a new rational structure $M_\BB\subset M_\DR\otimes\CC$ that is stable under complex conjugation $c_\DR$ (set $F_\infty=c_\DR|M_\BB$).
    By [(M6)](#M6), the filtration $W$ of $M_\DR$ must remain rational for this new rational structure.

ii. The data of $M_\AAf$, $\comp_{\AAf,\BB}$, and the Galois action, all together, are equivalent to the data of a $\QQ_\ell$-vector space $M_\ell$ for all $\ell$, along with a Galois action on $M_\ell$ and comparison isomorphisms $\comp_{\ell,\BB}\colon M_\BB\otimes\QQ\simto M_\ell$.
    We have to assume the existence of a lattice $L\subset M_\BB$ such that the $\comp_{\ell,\BB}(L\otimes\ZZ_\ell)$ are Galois stable.
    We define $M_\AAf$ from the $M_\ell$ as the restricted product of the $M_\ell$ with respect to the $\comp_{\ell,\BB}(L\otimes\ZZ_\ell)$ for an arbitrary lattice $L$: this restricted product is Galois stable, and the $\comp_{\ell,\BB}$ induce $\comp_{\AAf,\BB}$.

    The data of $M_\ell$, $\comp_{\ell,\BB}$, and the Galois action (resp. $M_\AAf$, $\comp_{\AAf,\BB}$, and the action), all together, are also equivalent to the data of a Galois action on $M_\BB\otimes\QQ_\ell$ (resp. $M_\BB\otimes\AAf$).
    By [(M6)](#M6) and [(M9)](#M9), the filtration of $M_\BB\otimes\QQ_\ell$ (resp. $M_\BB\otimes\AAf$) induced by $W$ must be stable under $\Gal(\bar{\QQ}/\QQ)$.

iii. If $M_\DR$ is given, then the data of $M_{\crisp}$, along with its crystalline Frobenius and $\comp_{\crisp,\DR}$, is equivalent to the data of an automorphism $\phi_p$ of $M_\DR\otimes\QQ_p$.
    By [(M6)](#M6) and [(M10)](#M10), the filtration of $M_\DR\otimes\QQ_p$ induced by $W$ must be stable under $\phi_p$.

We will often tacitly use these remarks to describe a system [(M1)--(M10)](#chunk-1.4).
:::

::: {.rmenv #chunk-1.6 title="1.6" latex="{1.6}"}
A scheme $X$ of finite type over $\QQ$ should define, for each $i$, a motive $M\coloneqq \HH_\mot^i(X)$.
\oldpage{17 (95)}
In this section, we will partially describe the system [(M1)--(M10)](#chunk-1.4) of realisations of $M$ in the case where $X$ is separated and smooth over $\QQ$.

We have $M_\BB=\HH^i(X(\CC),\QQ)$, and $F_\infty$ is induced by the complex conjugation of $X(\CC)$;
$M_\DR=\HH_\DR^i(X)\coloneqq\bHH^i(X,\Omega_X^\bullet)$, and the Hodge filtration that that of the mixed Hodge theory [@D2, Section 3.2];
$M_\ell=\HH^i(X\otimes\bar{\QQ},\QQ_\ell)$ is the $\ell$-adic étale cohomology of the scheme over $\bar{\QQ}$ induced from $X$ by extension of scalars, and the action of $\Gal(\bar{\QQ},\QQ)$ is given by structure transport.
_Notation:_ $X\otimes\bar{\QQ}$, cf. [(0.4)](#chunk-0.4).

Suppose that $X$ is smooth and proper, and let $S$ be a finite set of prime numbers such that $X$ is the general fibre of $X^\sim$, which is smooth and proper over $\Spec(\ZZ)\setminus S$.
For $p\not\in S$, $M_\crisp$ is the crystalline cohomology of the reduction $X^\sim\otimes\FF_p$ of $X$ modulo $p$, tensored over $\ZZ_p$ with $\QQ_p$.
The crystalline Frobenius $\phi_p$ is induced by the inverse image morphism of the Frobenius $\Fr\colon X^\sim\otimes\FF_p\to X^\sim\otimes\FF_p$.

More generally, suppose that we have some smooth and proper $\overline{X}$ over $\Spec(\ZZ)\setminus S$, as well as a relative normal crossing divisor $D$;
let $X$ be the general fibre of $\overline{X}\setminus D$.
Then the realisation $M_\crisp$ is defined for $p\not\in S$;
its most natural definition is given by the generalisation of the crystalline theory, considered by Faltings in [@Fa, IV], to the "logarithmic poles" case.

The comparison isomorphism $\comp_{\DR,\BB}$ is [(1.1.3)](#equation-1.1.3), and the comparison isomorphism $\comp_{\ell,\BB}$ is [(1.1.4)](#equation-1.1.4).

In the smooth and proper case, the comparison isomorphism $\comp_{\crisp,\DR}$ comes from §7.26 of [P. Berthelot and A. Ogus, _Notes on crystalline cohomology_, Princeton University Press and Tokyo University Press, 1978].
For the general case, see [@Fa, IV].
Finally, the weight filtration $W$ is that of the mixed Hodge theory from [@D2, Section 3.2].
See also [@D5].
:::

::: {.rmenv #chunk-1.7 title="1.7" latex="{1.7}"}
An additional data that we have on the cohomology $M\coloneqq\HH_\mot^i(X)$ when $X$ is smooth over $\QQ$ is that of a comparison isomorphism, for almost all $p$, in the sense of Fontaine--Messing (cf. [@FM; @Fa]), relating $M_p$, endowed with the action of a decomposition group of $p$, to $M_\DR\otimes\QQ_p$, endowed with its Hodge filtration and its crystalline Frobenius.

For all $p$, we should also have a "crystalline" structure of the following type.

- **Semi-stable case.**
    Let $T_p$ be the Zariski tangent space of $\Spec(\ZZ_p)$ at its closed point.
\oldpage{18 (96)}
    We complete it to a projective line $\overline{T}_p$ over $\FF_p$, and we can lift $(\overline{T}_p,0,\infty)$ to a projective line endowed with two marked points over $\ZZ_p$: $(\overline{T}_p^\sim,0,\infty)$.
    We want an $F$-isocrystal with logarithmic poles on $(\overline{T}_p,0,\infty)$ (cf. [@Fa]).
    Such an object induces, on $\overline{T}_p^\sim\otimes\QQ_p$, a module with connection $\cal{V}$ with logarithmic poles at $0$ and at $\infty$, and we want for the residue of the connection at $0$ and at $\infty$ to be nilpotent.
    If $\varphi$ is a section of $\overline{T}_p^\sim$, over $\Spec(\ZZ_p)$, with derivative equal to $1$ at the closed point, then $\varphi^*\cal{V}$ is independent of the choice of $\varphi$, and $\comp_{\DR,\crisp}$ should then be identified with the de Rham realisation $\otimes\QQ_p$.

- **General case.**
    The data of the previous type, over a large-enough finite Galois extension $E$ of $\QQ_p$ that is $\Gal(E/\QQ_p)$-equivariant.

A Fontaine--Messing comparison isomorphism should again link this object and $M_p$ endowed with the action of a decomposition group of $p$.
:::

::: {.rmenv #chunk-1.8 title="1.8 Variant" latex="{1.8 Variant}"}
We should also have [(M1)--(M10)](#chunk-1.4) for $M\coloneqq\HH_\mot^i(X)$, where $X$ is not necessarily smooth.
The crystalline data pose a problem.

We would also like to have [(M1)--(M10)](#chunk-1.4) for cohomology with proper support.
:::

::: {.rmenv #chunk-1.9 title="1.9 Definition" latex="{1.9 Definition}"}
A _realisation system_ is a system [(M1)--(M10)](#chunk-1.4) that satisfies [(A1)--(A5)](#chunk-1.4).
:::

We understand [(M4)](#M4), $\comp_{\crisp,\DR}$, and [(M10)](#M10) as a germ --- in the filter of complements of finite sets of prime numbers --- of systems of automorphisms $\phi_p$ of the $M_\DR\otimes\QQ_p$

:::{.itenv #chunk-1.10 title="Proposition 1.10" latex="{Proposition 1.10}"}
Realisation systems form a Tannakian category.
:::

::: {.proof}
As in [@J], the key point is that a morphism of mixed Hodge $\QQ$-structures is strictly compatible with the filtrations $W$ and $F$, and that its kernel and cokernel are mixed Hodge $\QQ$-structures [@D2, Theorem 2.3.5].
We thus deduce that every morphism of realisation systems is strictly compatible with $W$ and $F$.
(For $W$, we can instead use [(AM4)](#AM4).)

So it is clear that the kernels and cokernels again form realisation systems, and that a bijective morphism is an isomorphism.
We have direct sums, and so the category is abelian.

We have an obvious tensor product, which is associative and commutative, and a way of taking duals.
We also have a fibre functor, or, indeed, two: ${}_\BB$ and ${}_\DR$, with values in $\QQ$-vector spaces.
The category of realisation systems is thus Tannakian and **TO-DO**: the fibre functor ${}_\BB$ (resp. ${}_\DR$) identifies it with the category of representations of the group scheme $G_\BB$ (resp. $G_\DR$) of its automorphisms (cf. [@Sa] or [@DM, Theorem 2.11]).
:::

\oldpage{19 (97)}

We hope that the realisation functors define a fully faithful functor from the category of motives over $\QQ$ to the category of realisation systems.
If this were not the case, then the philosophy of motives would lose much of its interest.
This leads to the following provisional "definition":

::: {.rmenv #chunk-1.11 title="1.11 Definition" latex="{1.11 Definition}"}
The _category of motives_ over $\QQ$ is the subcategory of the category of realisation systems [(1.9)](#chunk-1.9) generated (under $\oplus$, $\otimes$, dual, and sub-quotient) by the category of systems of geometric origin.
:::

This definition is not really a definition, since "of geometric origin" has not been defined.
Worse still, I do not have any definition to propose that I can confidently say is good.

::: {.rmenv #chunk-1.12 title="1.12 Remark" latex="{1.12 Remark}"}
We would hope that the realisations of motives have properties not included in the definition [(1.9)](#chunk-1.9) of realisation systems.
Some reasons for not including them:

a. we do not know how to verify them in practice;
b. we no longer know how to prove [(1.10)](#chunk-1.10) if we do include them.

Thus.

i. We would like that, for almost all $p$, the Frobenius characteristic polynomial $\det(1-F_pt,M_\ell)$ at $p$ have rational coefficients that are independent of $\ell\neq p$.
    It should also agree with $\det(1-\phi_pt,M_\crisp)$.
    We do not know how to verify this for $\HH_\mot^i(X)$ (with $X$ smooth), nor for a direct factor of $\HH_\mot^i(X)$ (with $X$ an abelian variety), and reason (b) above also applies.

ii. We would like to complete [(AM4)](#AM4) by a condition for all $p$, cf. 1.8.5 in [P. Deligne, "La conjecture de Weil II", _Publ. Math. IHES_ **52** (1980), 137--252].
    Reasons (a) and (b) above also apply.

iii. The Hodge structure $\Gr_n^W(M_\BB)$ should be polarisable.
    More precisely, there should exist, for all $n$, a morphism of realisation systems
    $$
      \Gr_n^W(M)\otimes\Gr_n^W(M) \to \QQ(-n)
    $$
    (see [(2.1)](#chunk-2.1) for the definition of $\QQ(-n)$) that induces a polarisation of the weight-$n$ Hodge structure $\Gr_n^W(M_\BB)=\Gr_n^W(M_\BB)$.
    Here, neither reason (a) nor reason (b) apply.
:::

\oldpage{20 (98)}

::: {.rmenv #chunk-1.13 title="1.13 Remark" latex="{1.13 Remark}"}
The treatment of crystalline structures is not satisfying.
In the definition of realisation systems, I have not included the data  given in [(1.7)](#chunk-1.7), for the want of verifying their existence in the case of Lie algebras of $\pi_1$ that interest us.
I have nevertheless included the data of $\phi_p$, despite its appearance as a bizarre addition, because the calculations in [§19](#section-19) give an interesting result.
:::

:::: {.rmenv #chunk-1.14 title="1.14" latex="{1.14}"}
Here is a variant of the statement of [(1.4)](#chunk-1.4).
This formulation, which is less elementary, highlights the role of $F_\infty$.

::: {.trmenv #Mp1 title="(M'1)" latex="{(M'1)}"}
To every algebraic closure $C$ of $\RR$ is attached, in a functorial way, $M_\BB(C)$.
:::

From [(M'1)](#Mp1) we deduce the data of [(M1)](#M1) and [(M7)](#M7) by setting $M_\BB\coloneqq M_\BB(\CC)$, and the taking $F_\infty$ induced by $z\mapsto\bar{z}\colon\CC\to\CC$.
For $M=\HH_\mot^i(X)$, we will have $M_\BB(C)=\HH^i(X(C),\QQ)$.

::: {.trmenv #Mp2 title="(M'2)" latex="{(M'2)}"}
The same as [(M2)](#M2).
:::

::: {.trmenv #Mp8 title="(M'8)" latex="{(M'8)}"}
The same as [(M8)](#M8).
:::

::: {.trmenv #Mp3 title="(M'3)" latex="{(M'3)}"}
An $\AAf$-sheaf $M_\AAf$ on $\Spec(\QQ)$.
:::

By "$\AAf$-sheaf" we mean the data, for all $\ell$, of a $\QQ_\ell$-sheaf $\cal{F}_\ell$, and, for almost all $\ell$, of a $\ZZ_\ell$-sheaf $\cal{F}_{\ZZ_\ell}\subset\cal{F}_\ell$ which generates $\cal{F}_\ell$: the germ of the system of the $\cal{F}_{\ZZ_\ell}$ is given.
On the spectrum of a field $k$, the data of $\cal{F}_\ell$ (resp. $\cal{F}_{\ZZ_\ell}$) is equivalent to that of, for every algebraic closure $\bar{k}$ of $k$, a $\QQ_\ell$-vector space $\cal{F}_\ell(\bar{k})$ (resp. a $\ZZ_\ell$-module $\cal{F}_{\ZZ_\ell}(\bar{k})$ of finite type), functorially in $\bar{k}$, and such that the action of $\Gal(\bar{k}/k)$ is continuous.
Note that $\cal{F}_\AAf(\bar{k})$ is the restricted product of the $\cal{F}_\ell(\bar{k})$ with respect to the $\cal{F}_{\ZZ_\ell}(\bar{k})$.

From [(M'3)](#Mp3), we deduce the data of [(M3)](#M3) and [(M9)](#M9) by setting $M_\AAf\coloneqq(M_\AAf)_\AAf(\bar{\QQ})$.
_Notation:_ we write $M_\ell$ (resp. $M_{\ZZ_\ell}$, $M_\AAf$) for $(M_\AAf)_\ell$ (resp. $(M_\AAf)_{\ZZ_\ell}$, $(M_\AAf)_\AAf$).

If $M=\HH_\mot^i(X)$, and $a$ is the morphism $X\to\Spec(\QQ)$, then $M_\ell=\RR^ia_*\QQ_\ell$, and $M_{\ZZ_\ell}$ is equal to the image of $\RR^ia_*\ZZ_\ell$ in $M_\ell$.
We have that $\RR^ia_*\ZZ_\ell(\bar{k})=\HH^i(X\otimes_\QQ\bar{k},\ZZ_\ell)$.

::: {.trmenv #Mp4 title="(M'4)" latex="{(M'4)}"}
For almost all primes $p$, an $F$-isocrystal $M_\crisp$ on $\FF_p$, i.e. a vector space $M_\crisp$ over $\QQ_p$ endowed with an automorphism $\phi_p$.
:::

\oldpage{21 (99)}

::: {.trmenv #Mp5 title="(M'5)" latex="{(M'5)}"}
Comparison isomorphisms
$$
  \begin{aligned}
    \comp_{\DR,\BB}&\colon M_\BB(C)\otimes C \simto M_\DR\otimes C
  \\\comp_{\AAf,\BB}&\colon M_\BB(C)\otimes\AAf \simto M_\AAf(\bar{\QQ}_C)
  \\\comp_{\crisp,\DR}&\colon M_\DR\otimes\QQ_p \simto M_\crisp
  \end{aligned}
$$
that are functorial in $C$, where $\bar{\QQ}_C$ is the algebraic closure of $\QQ$ in $C$.
The first is equivalent to the data of $\comp_{\DR,\BB}$ as in [(M5)](#M5) satisfying [(AM2)](#AM2);
the second is equivalent to the data of $\comp_{\AAf,\BB}$ as in [(M5)](#M5) satisfying [(AM5)](#AM5).
:::

In [(M'3)](#Mp3), instead of giving the $M_\AAf$, we could have given only the $\QQ_\ell$-sheaves $M_\ell$, replacing $\comp_{\AAf,\BB}$ by the $\comp_{\ell,\BB}\colon M_B(C)\otimes\QQ_\ell\simto M_\ell(\bar{\QQ}_C)$ and requiring the existence of an integer lattice $L\subset M_B(\CC)$ such that the $\comp_{\ell,\BB}(L\otimes\ZZ_\ell)$ be stable under $\Gal(\bar{\QQ}/\QQ)$.
They define the $M_{\ZZ_\ell}$ of [(M'3)](#Mp3).

::: {.trmenv #Mp6 title="(M'6)" latex="{(M'6)}"}
$W$ is a filtration of the objects of [(M'1)](#Mp1) to [(M'4)](#Mp4), respected by the comparison isomorphisms.
:::

A definition essentially equivalent to [(1.9)](#chunk-1.9) is then the following: a _realisation system_ is a system [(M'1)](#Mp1) to [(M'6)](#Mp6), and [(M'8)](#Mp8), satisfying axioms [(AM1)](#AM1), [(AM2)](#AM2), and [(AM4)](#AM4) (suitably modified in the evident way).

The data of [(M'1)](#Mp1) is equivalent to a sheaf of $\QQ$-vector spaces on the étale site of $\Spec\RR$.
From this point of view, $\comp_{\ell,\BB}$ is an isomorphism to $\Spec(\RR)_\et$ between the inverse image of $M_\ell$ and the $\QQ_\ell$-sheaf induced by $M_\BB$.

In the language of sheaves, [(AM3)](#AM3) implies that $M_\ell$ comes from a smooth $\QQ_\ell$-sheaf on $\Spec(\ZZ)\setminus S\setminus\{\ell\}$.
The language of sheaves makes it clear that, for all $p$, $M_\ell$ defines a $\QQ_\ell$-sheaf on $\Spec(\QQ_p)$ (cf. the analogous case of $\RR$ below).
The choice of a decomposition group is not required.
::::

::: {.rmenv #chunk-1.15 title="1.15 Variant" latex="{1.15 Variant}"}
Let $P$ be a finite set of prime numbers.
The category of *smooth realisation systems on $\Spec(\ZZ)\setminus P$* is defined as in [(1.9)](#chunk-1.9), taking $P$ to be the exceptional set $S$ in [(AM3)](#AM3), and replacing "almost all $p$" in [(M4)](#M4) and [(AM4)](#AM4) by "all $p\not\in P$".
This treatment of crystalline structures is not satisfying, cf. [(1.7)](#chunk-1.7).
The category [(1.9)](#chunk-1.9) of realisation systems on $\Spec(\QQ)$ is the inductive limit of these categories for $P$ growing larger and larger.

Instead of saying "smooth over $\Spec(\ZZ)\setminus P$", we also say "of good reduction outside of $P$".
This terminology is erroneous in that the categories in question are not subcategories of the category of realisation systems on $\Spec(\QQ)$ (cf. [(1.7)](#chunk-1.7) again).

\oldpage{22 (100)}

In the language of [(1.14)](#chunk-1.14), in [(M'3)](#Mp3) we need to give $M_\ell$ as a smooth $\QQ_\ell$-sheaf on $\Spec(\ZZ[1/\ell])\setminus P$ instead of on $\Spec(\QQ)$, and we need to modify [(M'4)](#Mp4) like [(M4)](#M4).

The objects [(1.15)](#chunk-1.15) belonging to the subcategory generated by the objects of geometric origin (cf. [(1.11)](#chunk-1.11)) will be called *smooth (mixed) motives on $\Spec(\ZZ)\setminus P$*.
We hope that this gives a full subcategory of the category of motives on $\Spec(\QQ)$.

We would like to have a notion of smooth motive on $S$ for more general base spaces than $\Spec(\ZZ)\setminus P$.
Our methods, where the Betti realisation plays a central role, require that $S_\QQ$ be dense in $S$.
We will outline a provisional definition of smooth realisation systems on $S$, for $S$ smooth over $\Spec(\ZZ)$.
The case where $S$ is open in the spectrum of the ring of integers of a number field can be dealt with using natural modifications of [(1.4)](#chunk-1.4) and [(1.15)](#chunk-1.15).
For $S$ finite and étale over an open of $\Spec(\ZZ)$, we can also reduce to [(1.15)](#chunk-1.15): see [(1.17)](#chunk-1.17).
:::

:::: {.rmenv #chunk-1.16 title="1.16 Example" latex="{1.16 Example}"}
(The motivic $\HH^0$ of the spectrum of a number field).

Let $E$ be a finite extension of $\QQ$, unramified outside of a finite set $P$ of prime numbers.
We are going to expand on [(1.6)](#chunk-1.6) for $\Spec(E)$ and, more precisely, define a realisation system $A\coloneqq\HH_\mot^0(\Spec(E))$ that is smooth over $\Spec(\ZZ)\setminus P$.
The motive $A$ is of Hodge type $(0,0)$.
This determines $W$ and $F$.
We have that $A_\DR=E$, viewed as a vector space over $\QQ$.

Let $\Hom(E,\CC)=\Spec(E)(\CC)$ be the set of homomorphisms (which are automatically embeddings) from $E$ to $\CC$.
We have that $A_\BB=\QQ^{\Hom(E,\CC)}$, with $F_\infty$ induced by the complex conjugation of $\CC$.
The comparison isomorphism $\DR/\BB$ from $A_\BB\otimes\CC=\CC^{\Hom(E,\CC)}$ to $A_\DR\otimes\CC=E\otimes\CC$ is the $\CC$-linear extension of the map
$$
  \begin{aligned}
    E &\longrightarrow \CC^{\Hom(E,\CC)}
  \\e &\longmapsto (\sigma\mapsto\sigma(e)).
  \end{aligned}
$$

Since every embedding of $E$ into $\CC$ factors through $\bar{\QQ}$, $\Gal(\bar{\QQ}/\QQ)$ acts on $\Hom(E,\CC)$,
This action induces the Galois action on $A_\AAf\coloneqq A_\BB\otimes\AAf$ (cf. [(1.5.ii)](#chunk-1.5)).

For $p\not\in P$, and $v$ running over the places of $E$ over $p$, we have that $E\otimes\QQ_p=\prod E_v$, and $\phi_p$ is the automorphism of $E\otimes\QQ_p$ that induces on each $E_v$ the unique lift of the Frobenius $x\mapsto x^p$ of the residue field (cf. [(1.5.iii)](#chunk-1.5)).

\oldpage{23 (101)}

The motive $A$ is endowed with a product

::: {.eqtag #equation-1.16.1}
$$
  A\otimes A\to A
\tag{1.16.1}
$$
:::

namely the cup product, which makes $A$ a commutative ring with unit in the Tannakian category of motives (cf. [(5.3)](#chunk-5.3)).
On $A_\DR=E$, it is the product.
On $A_\BB$, it is given by $(q_1(\sigma))(q_2(\sigma))=(q_1(\sigma)q_2(\sigma))$.
::::

::: {.rmenv #chunk-1.17 title="1.17 Definition" latex="{1.17 Definition}"}
Let $\OO$ be the ring of $P$-integers of $E$.
With the above notation, a _smooth realisation system on $\Spec(\OO)$_ is a realisation system $N$ on $\Spec(\ZZ)\setminus P$ (cf. [(1.15)](#chunk-1.15)) endowed with the structure of an $A$-module $A\otimes N\to N$ (cf. [(5.3)](#chunk-5.3)) over $A\coloneqq\HH_\mot^0(\Spec(E))$.
:::

Similarly for "motive" and "over $\Spec(E)$" (taking the limit over $P$).

:::: {.rmenv #chunk-1.18 title="1.18" latex="{1.18}"}
We will now show how a realisation system $N$, smooth over $S=\Spec(\OO)$ (as in [(1.17)](#chunk-1.17)), can be described in terms of a *realisation system over $E$*, of the following type.

::: {.trmenv #M17E title="(M1,7)E" latex="{(M1,7)\textsubscript{E}}"}
For each embedding $\sigma$ of $E$ into $\CC$, a vector space $M_\sigma$ over $\QQ$, the Betti realisation with respect to $\sigma$, and an involutive system of isomorphisms $F_\infty\colon M_\sigma\simto M_{\bar{\sigma}}$.
:::

We have $N_\BB=\bigoplus M_\sigma$, with the evident structure of a module over $A_\BB=\QQ^{\Hom(E,\CC)}$, and $F_\infty$ is the sum of the $F_\infty$.
As in [(1.14)](#chunk-1.14), we have a variant:

::: {.trmenv #Mp1E title="(M'1)E" latex="{(M'1)\textsubscript{E}}"}
For each embedding of $E$ into an algebraic closure $C$ of $\RR$, a vector space $M_\sigma$ over $\QQ$, functorial in $C$.
:::

::: {.trmenv #Mp2E title="(M'2)E" latex="{(M'2)\textsubscript{E}}"}
An $E$-vector space $M_\DR$.
:::

::: {.trmenv #Mp8E title="(M'8)E" latex="{(M'8)\textsubscript{E}}"}
A filtration $F$ of $M_\DR$, the Hodge filtration.
:::

We have $N_\DR=M_\DR$, with the structure of an $A_\DR$-module given by that of the vector space over $E$.

::: {.trmenv #Mp3E title="(M'3)E" latex="{(M'3)\textsubscript{E}}"}
(cf. [(M3)](#M3), [(M9)](#M9)) An $\AAf$-sheaf $M_\AAf$ on $\Spec(E)$ (cf. [(1.14)](#chunk-1.14)).
:::

We define $N_\AAf$ as its direct image over $\Spec(\QQ)$: $N_\AAf(\bar{\QQ})$ is the sum over the $\sigma\colon E\to\bar{\QQ}$ of the $M_AAf(\bar{\QQ})$.

::: {.trmenv #Mp4E title="(M'4)E" latex="{(M'4)\textsubscript{E}}"}
For each place $v$ of $E$ over $p\not\in P$, a vector space $M_\crisv$ over the completion $E_v$ of $E$ at $v$.
Let $F_v^*$ be the automorphism of $E_v$ that induces $x\mapsto x^p$ on the residue field.
We give an $F_v^*$-linear $\phi_v\colon M_\crisv\mapsto M_\crisv$.
:::

We have $E\otimes\QQ_p=\bigoplus_{v|p}E_v$, and $N_\crisp$ is the sum of the $M_\crisv$.

\oldpage{24 (102)}

::: {.trmenv #Mp5E title="(M'5)E" latex="{(M'5)\textsubscript{E}}"}
Comparison isomorphisms
$$
  \begin{aligned}
    \comp_{\DR,\sigma}\colon M_\sigma(C)\otimes C
    &\simto M_\DR\otimes_{E,\sigma}C
  \\\comp_{\AAf,\sigma}\colon M_{\sigma}\otimes\AAf
    &\simto M_\AAf(\bar{E}_C)
  \end{aligned}
$$
both functorial in $C$ (where $\bar{E}_C$ is the algebraic closure of $E$ in $C$, with respect to $\sigma$), as well as
$$
  \comp_{\crisv,\DR}\colon M_\DR\otimes_E E_v \simto M_\crisv.
$$
:::

By summing over $\sigma$ (resp. $v$), these give [(M'5)](#Mp5).

::: {.trmenv #Mp6E title="(M'6)E" latex="{(M'6)\textsubscript{E}}"}
A filtration $W$ of the objects [(M'1)E](#Mp1E), [(M'2)E](#Mp2E), [(M'3)E](#Mp3E), and [(M'4)E](#Mp4E), respected by the comparison isomorphisms.
:::

We leave to the reader the task of translating axioms [(AM1)](#AM1), [(AM3)](#AM3), and [(AM4)](#AM4), which remain to be imposed, into this language (cf. [(1.14)](#chunk-1.14)).
::::

::: {.rmenv #chunk-1.19 title="1.19" latex="{1.19}"}
With the definition [(1.17)](#chunk-1.17) of smooth realisation systems over $S=\Spec(\OO)$, the functor given by forgetting the $A$-module structure, which takes values in smooth realisation systems over $\Spec(\ZZ)\setminus P$, is called the "*direct image of $S$ in $\Spec(\ZZ)\setminus P$*".
In the various realisations of [(1.18)](#chunk-1.18), it corresponds to the direct image.
Its left adjoint, $M\mapsto A\otimes M$ (cf. [(5.3)](#chunk-5.3)), is the *inverse image*.
:::

::: {.rmenv #chunk-1.20 title="1.20" latex="{1.20}"}
If $S$ is an open of the spectrum of the ring of integers of a finite extension $E$ of $\QQ$, then we can modify the description in [(1.18)](#chunk-1.18) as follows to define smooth realisation systems over $S$.

- In [(AM3)](#AM3), we ask for each $\QQ_\ell$-sheaf $M_\ell$ induced by $M_\AAf$ to come from a smooth $\QQ_\ell$-sheaf on $S[1/\ell]$.
- In [(M'4)E](#Mp4E), for each residue field $k(v)$ of $S$, we ask for $M_\crisv$ over the field of fractions $K_v$ of Witt vectors over $k(v)$, endowed with a semi-linear $\phi_v$.
    The crystalline comparison isomorphism of [(M'5)E](#Mp5E) then becomes
    $$
      M_\DR\otimes E_v \simto M_\crisv\otimes_{K_v}E_v.
    $$
:::

:::: {.rmenv #chunk-1.21 title="1.21" latex="{1.21}"}
Let $S$ be smooth over $\Spec(\ZZ)$.
Here is a provisional definition of smooth realisation systems over $S$, inspired by [(1.18)](#chunk-1.18).
The data is as follows:

::: {.trmenv #Mp1S title="(M'1)S" latex="{(M'1)\textsubscript{S}}"}
For $C$ an algebraic closure of $\RR$, a locally constant sheaf $M_\BB(C)$ of $\QQ$-vector spaces on $S(C)$, functorial in $C$.
We set $M_\BB\coloneqq M_\BB(\CC)$.
:::

\oldpage{25 (103)}

::: {.trmenv #Mp2S title="(M'2)S" latex="{(M'2)\textsubscript{S}}"}
A vector bundle $M_\DR$ with integrable connection on $S_\QQ$, assumed to be regularly singular at infinity.
:::

::: {.trmenv #Mp8S title="(M'8)S" latex="{(M'8)\textsubscript{S}}"}
A filtration $F$ of $M_\DR$ by vector subbundles: the Hodge filtration.
We assume "transversality":
$$
  \nabla F^p \subset \Omega^1\otimes F^{p-1}.
$$
:::

::: {.trmenv #Mp3S title="(M'3)S" latex="{(M'3)\textsubscript{S}}"}
A smooth $\AAf$-sheaf $M_\AAf$ on $S_\QQ$.
:::

::: {.trmenv #Mp4S title="(M'4)S" latex="{(M'4)\textsubscript{S}}"}
For every prime number $p$, an $F$-isocrystal $M_\crisp$ on the reduction $S_p$ of $S$ $\mod p$.
:::

::: {.trmenv #Mp5S title="(M'5)S" latex="{(M'5)\textsubscript{S}}"}
Comparison isomorphisms
$$
  \begin{aligned}
    \comp_{\DR,\BB}\colon
    &M_\BB(C)\otimes C \simto (M_\DR\otimes C)^\nabla
  \\\comp_{\AAf,\BB}\colon
    &M_\BB^{(C)}\otimes\AAf \to \text{inverse image of }M_\AAf\text{ on }S(C)
  \end{aligned}
$$
that are functorial in $C$, where we denote by $M_\DR\otimes C$ the inverse image of $M_\DR$ on $S_C$, and by $(-)\nabla$ the sheaf of its horizontal sections on $S(C)$.
Instead of giving $M_\AAf$ in [(M'3)S](#Mp3S), we can only give the $\QQ_\ell$ sheaves $M_\ell$ that are deduced from it, along with the comparison isomorphisms $\comp_{\ell,\BB}$ from $M_\BB\otimes\QQ_\ell$ to the inverse image of $M_\ell$, and impose the existence of a lattice $L$ in $M_\BB(C)$ such that $L\otimes\ZZ_\ell$ corresponds to a $\ZZ_\ell$-sheaf $L_\ell$ with $L_\ell\otimes\QQ_\ell\simto M_\ell$, cf. [(1.14)](#chunk-1.14).

As for $\comp_{\crisp,\DR}$, let $S_{(p)}^\an$ be the rigid analytic space that is the general fibre of the formal scheme over $\ZZ_p$ given by the formal completion of $S$ along $S_p$;
we want an isomorphism between bundles with connection on $S_{(p)}^\an$ induced by $M_\DR$ and $M_\crisp$.
:::

::: {.trmenv #Mp6S title="(M'6)S" latex="{(M'6)\textsubscript{S}}"}
A filtration $W$ of the objects [(M'1)S](#Mp1S) to [(M'4)S](#Mp4S), respected by the comparison isomorphisms.
:::

The axioms are modified as follows.
In [(AM1)](#AM1), we want a variation of mixed Hodge structures;
[(AM3)](#AM3) becomes: $M_\ell$ comes from a smooth $\QQ_\ell$-sheaf on $S[1/\ell]$;
for [(AM4)](#AM4), a condition is imposed for every closed point of $S$.

As a catch-all, this category does the job (cf. [(1.13)](#chunk-1.13) nonetheless).
Additional axioms will always be natural, notably concerning the behaviour at infinity of the variation of mixed Hodge structures $H_\BB$ (cf. [@SZ]).
::::

\oldpage{26 (104)}

::: {.rmenv #chunk-1.22 title="1.22 Definition" latex="{1.22 Definition}"}
Let $E$ be a finite extension of $\QQ$.
Then a realisation system *with coefficients in $E$* is a realisation system $M$ endowed with the structure of an $E$-modules, $E\to\End(M)$.
:::

Up until now, our motives have been "isomotives": the $\Hom$ are vector spaces over $\QQ$.
For motives with integer coefficients, I propose the following definitions.

::: {.rmenv #chunk-1.23 title="1.23 Definition" latex="{1.23 Definition}"}
A realisation system $M$ over $\QQ$ (resp. $\Spec\ZZ\setminus P$) *with integer coefficients* is a realisation system, denoted by $M\otimes\QQ$, endowed with a lattice $M_\BB\subset(M\otimes\QQ)_\BB$ such that, for all $\ell$, $M_\ell\coloneqq M_\BB\otimes\ZZ_\ell\subset(M\otimes\QQ)_\ell$ is stable under $\Gal(\bar{\QQ}/\QQ)$.
:::

:::: {.rmenv #chunk-1.24 title="1.24" latex="{1.24}"}
On a more general base $S$, a realisation system *with integer coefficients* is a realisation system $M\otimes\QQ$ endowed with a local system of torsion-free $\ZZ$-modules $M_\BB\subset(M\otimes\QQ)_\BB$ satisfying $M_\BB\otimes\QQ\simto(M\otimes\QQ)_\BB$ (a "lattice") and such that the $\ZZ_\ell$-sheaf $M_\BB\otimes\ZZ_\ell$ on $S(\CC)$ corresponds, under $\comp_{\ell,\BB}$, to a smooth $\ZZ_\ell$-sheaf $M_\ell\subset(M\otimes\QQ)_\ell$ on $S[1/\ell]$.

This causes us to modify [(M'1)S](#Mp1S), [(M'3)S](#Mp3S), and [(M'5)S](#Mp5S) as follows.

::: {.trmenv #Mp1SZ title="(M'1)SZ" latex="{(M'1)\textsubscript{SZ}}"}
$M_\BB(C)$ is a local system of free $\ZZ$-modules.
:::

::: {.trmenv #Mp3SZ title="(M'3)SZ" latex="{(M'3)\textsubscript{SZ}}"}
The data of a $\ZZ_\ell$-sheaf $M_\ell$ on $S[1/\ell]$.
:::

::: {.trmenv #Mp5SZ title="(M'5)SZ" latex="{(M'5)\textsubscript{SZ}}"}
Replace $\comp_{\AAf,\BB}$ by isomorphisms $\comp_{\ell,\BB}$ from $M_\BB\otimes\ZZ_\ell$ to the inverse image of $M_\ell$ on $S(C)$.
:::
::::

::: {.rmenv #chunk-1.25 title="1.25" latex="{1.25}"}
In [(1.24)](#chunk-1.24), the data of the $M_\ell$ is equivalent to that of a projective system of sheaves of $\ZZ/(n)$-modules on the $S[1/n]$:
$$
  M_{\ZZ/(n)}\colon \prod_{\ell|n}M_\ell/n M_\ell
$$
and the data of the comparison morphisms is equivalent to that of an isomorphism of projective systems from $\comp_{\AA/n,\BB}\colon M_\BB\otimes\ZZ/(n)$ to the inverse image of $M_{\ZZ/(n)}$ on $S(C)$.

In the setting of [(1.23)](#chunk-1.23), we can prefer to think of the $M_{\ZZ/(n)}$ as representations of $\Gal(\bar{\QQ}/\QQ)$.
We again set $M_{\hZZ}=\limproj M_{\ZZ/(n)}=\prod M_\ell$.
:::

::: {.rmenv #chunk-1.26 title="1.26" latex="{1.26}"}
Combining the variants in [(1.22)](#chunk-1.22) and [(1.24)](#chunk-1.24), we similarly define motives over $S$ with coefficients in the ring of integers of a finite extension of $\QQ$.
:::



# Examples {#section-2}

\oldpage{27 (105)}

::: {.rmenv #chunk-2.1 title="2.1" latex="{2.1}"}
The *Tate motive* $\ZZ(1)$ is a motive over $\Spec(\ZZ)$ [(1.15)](#chunk-1.15) with integer coefficients [(1.23)](#chunk-1.23).
Here is its description as a realisation system, in the language of [(1.9)](#chunk-1.9) and [(1.14)](#chunk-1.14) (along with [(1.25)](#chunk-1.25)):

- [(M1)](#M1) and [(M7)](#M7): $\ZZ(1)_\BB=2\pi i\ZZ\subset\CC$ and $F_\infty=-1$.
- [(M'1)](#Mp1): $\ZZ(1)_\BB(C)=2\pi i\ZZ\subset C$.
- [(M2)](#M2) and [(M'2)](#Mp2): $\ZZ(1)_\DR=\QQ(1)_\DR=\QQ$.
- [(M3)](#M3) and [(M9)](#M9): $\ZZ(1)_{\ZZ/n}$ is the group $\mu_n\subset\CC^\times$ of $n$-th roots of unity.
    The transition morphisms are the $\mu_n\to\mu_m\colon x\mapsto x^{n/m}$ for $m|n$.
    The action of $\Gal(\bar{\QQ}/\QQ)$ is its action on the $\mu_n$.
    In the variant [(M'3)](#Mp3), we have $\ZZ(1)_{\ZZ/n}(\bar{k})=\mu_n(\bar{k})$.

    We thus have that $\ZZ(1)_\ell=\limproj\mu_{\ell^n}(\CC)$.
- [(M4)](#M4), [(M10)](#M10), and [(M'4)](#Mp4): $\ZZ(1)_\crisp=\QQ_p$ and $\phi_p=1/p$.
- [(M5)](#M5): The canonical comparison isomorphism $\comp_{\DR,\BB}$ is induced by the inclusions $\ZZ(1)_\BB=2\pi i\ZZ\subset\CC$ and $\ZZ(1)_\DR=\QQ\subset\CC$, i.e.
    $$
      \ZZ(1)_\BB\otimes\CC \simto \CC \simfrom \ZZ(1)_\DR\otimes\CC.
    $$
    The isomorphism $\comp_{\ZZ/n,\BB}$ [(1.25)](#chunk-1.25) is induced by
    $$
      \exp(x/n)\colon \ZZ(1)_\BB \to \ZZ/n(1)\subset\CC^\times.
    $$
    The isomorphism $\comp_{\crisp,\DR}$ is induced by the inclusion $\QQ\subset\QQ_p$.
- [(M'5)](#Mp5): Replace $\CC$ by $C$ in [(M5)](#M5).
- [(M6)](#M6) and [(M8)](#M8): $\ZZ(1)$ is of pure weight $-2$, and $\ZZ(1)_\DR$ is of pure Hodge filtration $-1$: the Hodge type is $(-1,-1)$.
:::

::: {.rmenv title="Notation" latex="{Notation}"}
$\ZZ(n)\coloneqq\ZZ(1)^{\otimes n}$, $\QQ(n)\coloneqq\ZZ(n)\otimes\QQ$, and, for any motive $M$, $M(n)\coloneqq M\otimes\ZZ(n)$.
Depending on the context, we also denote by $(n)$ taking the tensor product with a realisation of $\ZZ(n)$.

If $X$ is smooth and projective over $k$, and absolutely irreducible of dimension $n$, then $\HH_\mot^{2n}(X)$ is the motive over $k$ induced from $\QQ(-n)$ by change of base from $\QQ$ to $k$.
:::

::: {.rmenv #chunk-2.2 title="2.2" latex="{2.2}"}
For an abelian variety $A$ over $\QQ$, we denote by $T(A)\otimes\QQ$ the motive $\HH_1^\mot(A)$ that is dual to $\HH_\mot^1(A)$, and by $T(A)$ the motive with integer coefficients defined by the integer structure $\HH_1(A(\CC),\ZZ)\subset\HH_1(A(\CC),\QQ)=(T(A)\otimes\QQ)_\BB$.
\oldpage{28 (106)}
The functor $A\mapsto T(A)$ is fully faithful: from $T(A)$ we can recover $\Lie(A)=T(A)_\DR/F^0$ and the complex torus
$$
  A(\CC)
  = T(A)_\BB\setminus\Lie(A)
  = T(A)_\BB\setminus T(A)_\DR\otimes\CC/F^0.
$$
The complex torus $A(\CC)$ determines the abelian variety $A_\CC$ over $\CC$ induced by $A$, and the $\QQ$-structure is uniquely determined by that of the Lie algebra.

An abelian scheme $A$ over $S$ similarly defines a smooth motive with integer coefficients $T(A)$ over $S$.
:::

::: {.rmenv #chunk-2.3 title="2.3" latex="{2.3}"}
Recall that a *smooth $1$-motive* $X$ over a scheme $S$ consists of

a. a group scheme $L$ over $S$ that, locally, for the étale topology, is a constant group scheme defined by a free $\ZZ$-module of finite type;
    an abelian scheme $A$ over $S$, and a torus $T$ over $S$;
b. an extension $E$ of $A$ by $T$, and a morphism $\bar{u}\colon L\to A$;
c. a morphism $u\colon L\to E$ lifting $\bar{u}$.

We write $X=[L\xrightarrow{u}E]$.

A $1$-motive $X$ over $\QQ$ defines a motive over $\QQ$ with integer coefficients $T(X)$ (cf. [@D3, Section 10, but the crystalline aspect is missing]), and the functor $X\mapsto T(X)$ is fully faithful (cf. [@D3, both 10.1.3 and 2.2]).

For $X=[\ZZ\to0]$, $T(X)$ is the unit motive $\ZZ(0)$.
For $X=[0\to\Gm]$, $T(X)$ is the Tate motive $\ZZ(1)$.
For an abelian variety $A$ and $X=[0\to A]$, $T(X)=T(A)$.
Of course, here, as in [(2.2)](#chunk-2.2), we can take more general bases than $\Spec(\QQ)$.
:::

:::: {.rmenv #chunk-2.4 title="2.4" latex="{2.4}"}
I conjecture that the set of motives with integer coefficients of the form $T(X)$ for some $1$-motive $X$ is stable under extensions.
If $T'$ is a motive with integer coefficients, with $T'\otimes\QQ\simto T(X)\otimes\QQ$, then $T'$ is of the form $T(X')$ with $X'$ isogenous to $X$.
The conjecture is thus equivalent to the claim that the set of motives $T(X)\otimes\QQ$, for $1$-motives $X$, is stable under extensions.
The word "conjecture" is an abuse of terminology, since the statement itself is not precise.
What is conjectured is that every realisation system [(1.9)](#chunk-1.9) (or [(1.24)](#chunk-1.24), over $S$) that is an extension $T(X)$ by $T(Y)$ (for $1$-motives $X$ and $Y$), and "natural", "coming from geometry", is isomorphic to that defined by a $1$-motive $Z$ that is an extension of $X$ by $Y$.

\oldpage{29 (107)}
A point $a$ of an abelian variety $A$ over $\QQ$ defines a $1$-motive $[\ZZ\xrightarrow{u}A]$ with $u(1)=a$.
The motive $T([\ZZ\xrightarrow{u}A])$ is an extension of $\ZZ(0)$ by $T(A)$, and the conjecture, applied to $\ZZ(0)$ and $T(A)$, implies that
$$
  A(\QQ) \simto \Ext^1(\ZZ(0),T(A))
$$
or, equivalently,
$$
  A(\QQ)\otimes\QQ \simto \Ext^1(\QQ(0),T(A)\otimes\QQ)
$$
(where $\Ext^1$ is in the abelian category of motives).

More generally, if $E$ is an extension of an abelian variety by a torus, we want
$$
  E(\QQ) \simto \Ext^1(\ZZ(0),T(E))
$$
and similarly for more general bases that $\Spec(\QQ)$.

The case $E=\Gm$ is particularly interesting: for every smooth scheme $S$ over $\Spec(\ZZ)$, we want, in the category of motives with integer coefficients over $S$,

::: {.eqtag #equation-2.4.1}
$$
  \Gamma(S,\OO_S^\times) \simto \Ext^1(\ZZ(0),\ZZ(1)).
\tag{2.4.1}
$$
:::
::::

:::: {.rmenv #chunk-2.5 title="2.5" latex="{2.5}"}
Let $M$ be a realisation system [(1.9)](#chunk-1.9).
We spell out what a realisation system $E$ given by an extension of $\QQ(0)$ by $M$ is, when $M$ is of weight $\leq-1$ (i.e. $M=W_{-1}(M)$).

::: {.trmenv #M1P title="(M1)P" latex="{(M1)P}"}
$E_\BB$ is an extension $M_\BB\to E_\BB\xrightarrow{u}\QQ$ of $\QQ$ by $M_\BB$.
Its data is equivalent to that of $P_\BB\coloneqq u^{-1}(1)$, endowed with its structure as a torsor (principal homogeneous space) under $M_\BB$, i.e. $m\in M_\BB$ acts on $P_\BB$ via $p\mapsto p+m$.
:::

::: {.trmenv #M234P title="(M2,3,4)P" latex="{(M2,3,4)P}"}
Similarly, the data of $E_\DR$ (resp. $E_\AAf$, $E_\crisp$) is equivalent to that of a torsor $P_\DR$ (resp. $P_\AAf$, $P_\crisp$) under $M_\DR$ (resp. $M_\AAf$, $M_\crisp$).
:::

::: {.trmenv #M5P title="(M5)P" latex="{(M5)P}"}
The comparison morphisms for $E$ can be identified with comparison morphisms $P_\BB\otimes\CC\simto P_\DR\otimes\CC$, $P_\BB\otimes\AAf\simto P_\AAf$, and $P_\DR\otimes\QQ_p\simto P_\crisp$ that are compatible with the analogous morphisms for $M$.
*Notation:* $\otimes$, see [(0.4)](#chunk-0.4).
:::

::: {.trmenv #M6P title="(M6)P" latex="{(M6)P}"}
Since $M$ is, by hypothesis, of weight $\leq-1$, and $\QQ(0)$ is of pure weight $0$, the weight filtration of $E$ is determined by that of $M$, i.e. $W_0(E)=E$, and $W_i(E)=W_i(E)$ for $i<0$.
:::

\oldpage{30 (108)}

::: {.trmenv #M7P title="(M7)P" latex="{(M7)P}"}
The data of $F_\infty$ for $E$ is equivalent to that of an involution of $P_\BB$ that is compatible with that of $M_\BB$.
Axiom [(AM2)](#AM2) for $E$ is that this involution is induced by the $\CC$-antilinear involution of $P_{\BB,\CC}=\PP_{\DR,\CC}$ with fixed points $P_{\DR,\RR}$.
:::

::: {.trmenv #M8P title="(M8)P" latex="{(M8)P}"}
The data of the Hodge filtration of $E_\DR$ is equivalent to that of the intersection $F^0P_\DR$ of $F^0E_\DR$ over $P_\DR$, which is a torsor under $F^0M_\DR$: for $p>0$, $F^pE_\DR=F^pM_\DR$; for $p=0$, $F^0E_\DR$ is generated by $F^0P_\DR$; and for $p<0$, $F^pE_\DR$ is the sum of $F^0E_\DR$ and $F^pM_\DR$.
In other words, the data [(M8)](#M8) for $E_\DR$ is that of a reduction of the structure group of $P_\DR$, from $M_\DR$ to $F^0M_\DR$.

The data of [(M1)](#M1), [(M2)](#M2), $\comp_{\DR/\BB}$, and [(M8)](#M8) are equivalent to the data of a torsor $F^0P_\DR$ under $F^0M_\DR$ and, in the $M_\DR\otimes\CC=M_\BB\otimes\CC$ torsor $P_{\DR,\CC}$ which is induced by $F^0M_\DR\to M_\DR\otimes\CC$, a $\QQ$-structure $P_\BB\subset P_{\DR,\CC}$ that is an $M_\BB$ torsor.
:::

::: {.trmenv #M9P title="(M9)P" latex="{(M9)P}"}
The data of the action of $\Gal(\bar{\QQ}/\QQ)$ on $E_\AAf$ is equivalent to that of an action of $\Gal(\bar{\QQ}/\QQ)$ on $P_\AAf$, which makes $P_\AAf$ an equivariant $M_\AAf$-torsor.
:::

::: {.trmenv #M10P title="(M10)P" latex="{(M10)P}"}
Similarly, the automorphism $\phi_p$ of $E_\DR\otimes\QQ_p$ corresponds to an automorphism $\phi_p$ of $P_\DR\otimes\QQ_p$ such that
$$
  \phi_p(x+m) = \phi_p(x) + \phi_p(m).
$$
:::

We leave to the reader the task of translating axioms [(AM1)](#AM1) to [(AM5)](#AM5) for $P$.
We note only that [(AM1)](#AM1) and [(AM4)](#AM4) follow from the same axioms for $M$, and that [(AM2)](#AM2) and [(AM5)](#AM5) can be expressed at best as functoriality in $\CC$, cf. [(1.14)](#chunk-1.14).
::::

::: {.rmenv #chunk-2.6 title="2.6 Definition" latex="{2.6 Definition}"}
—

i. A system of torsors, [(M1)P](#M1P) to [(M10)P](#M10P) in [(2.5)](#chunk-2.5), that satisfies the conditions required in order to define an extension $E$ of $\QQ(0)$ by a realisation system $M$ is called a *torsor in realisation systems*.

ii. If $M$ is a motive, then the torsor $P$ under $M$ is *motivic* (or a *torsor in motives*) if the extension $E$ is a motive.
:::

:::: {.rmenv #chunk-2.7 title="2.7" latex="{2.7}"}
Let $M$ be a realisation system with integer coefficients.
An *extension* $E$ of $\ZZ(0)$ by $M$ is an extension $E\otimes\QQ$ of $\QQ(0)$ by $M\otimes\QQ$, endowed with an integer structure such that the sequence $0\to M_\BB\to E_\BB\to\ZZ\to0$ is exact.

As in [(2.5)](#chunk-2.5), such an extension is described by a system of torsors.
\oldpage{31 (109)}
As in [(1.24)](#chunk-1.24) and [(1.25)](#chunk-1.25), this corresponds to modifying [(2.5)](#chunk-2.5) as follows:

::: {.trmenv #M1PZ title="(M1)PZ" latex="{(M1)P$\ZZ$}"}
$P_\BB$ is an $M_\BB$-torsor.
:::

::: {.trmenv #M3t9PZ title="(M3,9)PZ" latex="{(M3,9)P$\ZZ$}"}
$P_\ell$ is, for each $\ell$, a $\Gal(\bar{\QQ}/\QQ)$-equivariant $M_\ell$-torsor.
It is equivalent to give a projective system of equivariant $M_{\ZZ/(n)}$-torsors $P_{\ZZ/(n)}$, or their projective limit $P_{\hZZ}$, which is an equivariant $M_{\hZZ}$-torsor.
:::

::: {.trmenv #M5PZ title="(M5)PZ" latex="{(M5)P$\ZZ$}"}
Replace $\comp_{\AAf,\BB}$ by $\comp_{\ell,\BB}$ for each $\ell$, or $\comp_{\ZZ/(n),\BB}$, or $\comp_{\hZZ,\BB}$.
:::

Such a system of torsors, which defines an extension of $\ZZ(0)$ by $M$, is also called a *torsor under $M$*.
It is said to be *motivic* if the corresponding extension is, i.e. if the torsor under $M\otimes\QQ$ that it defines is motivic.
::::

:::: {.rmenv #chunk-2.8 title="2.8" latex="{2.8}"}
We leave to the reader the task of understanding the constructions with bases $S$ more general than $\Spec(\QQ)$.
We note only that, in the de Rham realisation, $P_\DR$ is an $M_\DR$-torsor on $S_\QQ$.
It is endowed with a restriction of the structure group $F^0P_\DR\subset P_\DR$ to $F^0M_\DR$.
It is also endowed with an integrable connection $\nabla$.
Along each section $p$ of $P_\DR$, the vertical tangent space can be identified with $M_\DR$;
the connection $\nabla$ is thus a morphism
$$
  \nabla\colon P_\DR\to\Omega^1\otimes M_\DR.
$$
It satisfies $\nabla(p+m)=\nabla p+\nabla m$.
Transversality becomes the following:

::: {.trmenv #chunk-2.8.1 title="2.8.1" latex="{2.8.1}"}
For a local section $p$ of $F^0P_\DR$, $\nabla p\in\Omega^1\otimes F^{-1}(M_\DR)$.
:::
::::

::: {.rmenv #chunk-2.9 title="2.9" latex="{2.9}"}
We explicitly describe the torsor in motives $K(x)$ under $\ZZ(1)$ (the *Kummer torsor*) corresponding to $x\in\QQ^\times$ as in [(2.4.1)](#chunk-2.4.1).

The $\ZZ(1)_\BB$-torsor $K(x)_\BB$ is the torsor under $2\pi i\ZZ$ of logarithms of $x$.
Since $F^0\ZZ(1)_\DR=0$, we have $K(x)_\DR=\ZZ(1)_\DR=\QQ$.
The $\ZZ/(n)(1)$-torsor $K(x)_{\ZZ/(n)}$ is the torsor of $n$-th roots of unity of $x$.
The transition morphisms $K(x)/_{\ZZ(nm)}\to K(x)_{\ZZ/(n)}$ are given by $y\mapsto y^m$.
The Galois action is evident.

The morphism $\comp_{\DR,\BB}$ is induced by the inclusion of $K(x)_\BB$ into $\CC$.
The morphism $\comp_{\ZZ/(n),\BB}$ is induced by $K(x)_\BB\to K(x)_{\ZZ/(n)}$ given by $z\mapsto\exp(z/n)$.

The crystalline Frobenius $\phi_p\colon K(x)_\DR\otimes\QQ_p\to K(x)_\DR\otimes\QQ_p$, i.e. $\QQ_p\to\QQ_p$, is defined for $x$ a unit at $p$.
We denote by $\log$ the $p$-adic logarithm, which is characterised by
$$
  \phi_p^{-1}(0) = \log(x^{1-p}).
$$
:::

\oldpage{32 (110)}

::: {.rmenv #chunk-2.10 title="2.10" latex="{2.10}"}
On $\Gm=\Spec\ZZ[q,q^{-1}]$, the universal section $q$ of $\Gm$ also defines a torsor in motives $K(q)$ under $\ZZ(1)$, on the base $\Gm$.
We now describe it.

The $\ZZ(1)_\BB$-torsor $K(q)_\BB$ on $C^\times$ is the local system of logarithms of $q$.
Since $F^0\ZZ(1)_\DR=0$, $K(q)_\DR$ is trivial: $K(n)_\DR=\OO$ (on ${\Gm}_\QQ$).
It is endowed with the integrable connection $\nabla\colon K(q)_\DR\to\Omega^1\otimes\ZZ(1)_\DR=\Omega^1$ given by
$$
  \nabla u = \dd u - \frac{\dd q}{q}.
$$
The $\ZZ/(n)(1)$-torsor $K(q)_{\ZZ/(n)}$ is that of the $n$-th roots of $q$.
This is a locally constant sheaf on $(\Gm\otimes\ZZ[1/n])_\et$.
Transition and comparison morphisms are defined as in [(2.9)](#chunk-2.9).

We now explain what the $F$-crystal structure is at $p$.
Let $\hGm$ be the completion of $\Gm$ along its fibre of characteristic $p$, and $\hGm\otimes\QQ_p$ the corresponding rigid analytic space.
For a Frobenius lifting $\widetilde{F}\colon\hGm\to\hGm$, the crystalline Frobenius is a morphism $\phi_p[\widetilde{F}]$, over $\hGm\otimes\QQ_p$, from $\widetilde{F}^\bullet K(q)_\DR$ to $K(q)_\DR$ that is horizontal and compatible with the torsor structures.
If we change $\widetilde{F}$ to $\widetilde{F}'$, then $\widetilde{F}$ and $\widetilde{F}'$ have the same reduction modulo $p$, the connection $\nabla$ gives an isomorphism of $\widetilde{F}^\bullet K(q)_\DR$ with $\widetilde{F}'^{\bullet} K(q)_\DR$, and the diagram
$$
  \begin{CD}
    \widetilde{F}^\bullet K(q)_\DR @>{\phi_p[\widetilde{F}]}>> K(q)_\DR
  \\@| @|
  \\\widetilde{F}'^{\bullet} K(q)_\DR @>>{\phi_p[\widetilde{F}']}> K(q)_\DR
  \end{CD}
$$
commutes.

In terms of $\phi_p^{-1}\colon K(q)_\DR\to\widetilde{F}'^{\bullet} K(q)_\DR$, and via the identifications $K(q)_\DR=\ZZ(1)_\DR=\OO$, whence $\widetilde{F}'^{\bullet}=\OO$, the compatibility with the torsor structures and with the connections can be written as
$$
  \begin{aligned}
    \phi_p^{-1}(k+m)
    &= \phi_p^{-1}(k) + pm
  \\\dd\phi_p^{-1}(0)
    &= \widetilde{F}^\bullet\left(\frac{\dd q}{q}\right) - p\frac{\dd q}{q}.
  \end{aligned}
$$
When we change the Frobenius lifting, we have
$$
  \phi_p^{-1}[\widetilde{F}'](0) - \phi_p^{-1}[\widetilde{F}](0)
  = \log(\widetilde{F}'/\widetilde{F}).
$$
For $\widetilde{F}\colon q\mapsto q^p$, we have
$$
  \phi_p^{-1}[q\mapsto q^p](0) = 0.
$$
\oldpage{32 (111)}
For $x\in\QQ$ a unit at $p$, and $\widetilde{F}$ such that $\widetilde{F}(x)=x$, we thus have $\phi_p^{-1}[\widetilde{F}](0)=\log(x/x^p)$ at $x$, as required by [(2.9)](#chunk-2.9)
:::



# Torsors under $\ZZ(n)$ {#section-3}

\oldpage{33 (112)}
The study
