--- 
title: "Automorphisms of holomorphic foliations on rational surfaces"
author: "Percy Fernández Sánchez"
date: "1971"
original: 'Sánchez, PF. "Automorfismo de foliaciones holomorfas sobre superficies racionales". _Pro Mathematica_ **16** (2002), 47--59. [revistas.pucp.edu.pe/index.php/promathematica/article/view/8182/8478](https://revistas.pucp.edu.pe/index.php/promathematica/article/view/8182/8478).'
bibliography: PM-16-2002-47.bib
nocite: '@*'
link-citations: true
csl: maths-translations.csl
reference-section-title: "Bibliography"
github-repo: "thosgood/translations"
favicon: "favicon.ico"
---

```{js, echo = FALSE}
$(document).ready(function(e) {gitbook.sidebar.toggle(false, false)});
```

```{r, child = '_translator-note.Rmd'}
```

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\ZZ}{\mathbb{Z}}
\providecommand{\QQ}{\mathbb{Q}}
\providecommand{\CC}{\mathbb{C}}
\providecommand{\PP}{\mathbb{P}}
\providecommand{\id}{\mathrm{id}}
\providecommand{\dd}{\mathrm{d}}

\providecommand{\Sing}{\operatorname{Sing}}
\providecommand{\tang}{\operatorname{tang}}
\providecommand{\Aut}{\operatorname{Aut}}
\providecommand{\CS}{\operatorname{CS}}
\providecommand{\Kod}{\operatorname{Kod}}
\providecommand{\PGL}{\operatorname{PGL}}
\providecommand{\GL}{\operatorname{GL}}
\providecommand{\PSL}{\operatorname{PSL}}
\providecommand{\gl}{\operatorname{gl}}

<!-- Content -->


::: {.rmenv #abstract title="Abstract" latex="{Abstract}"}
In this work, we classify the holomorphic foliations with infinite automorphism group on a rational surface.
As a consequence of this result, we prove that the automorphism group of a foliation of general type with singularities on a rational surface is finite.
:::

# Introduction {#introduction}

\oldpage{48}
Schwarz proved that the automorphism group of a Riemann surface of genus greater than 2 is finite.
Andreotti, in [@1], generalised this result, proving that the group of bimeromorphisms of an algebraic variety of general type is finite, these being analogous to Riemann surfaces of genus greater than 2.
In the case of algebraic surfaces, there is even a bound for this number, see [@14].

In this work we first classify the holomorphic foliations with singularities on rational surfaces.

::: {.itenv #theorem-A title="Theorem A" latex="{Theorem A}"}
Let $\cal{F}$ be a foliation on a rational surface $M$.
If $\#\Aut(\cal{F})=+\infty$ then $\cal{F}$ is bimeromorphic to a Riccati foliation or to a rational fibration.
:::

We then prove a result analogous to that of Andreotti for holomorphic foliations on rational surfaces (surfaces bimeromorphic to the projective plane).

::: {.itenv #theorem-B title="Theorem B" latex="{Theorem B}"}
The automorphism group of a holomorphic foliation of general type with singularities on a rational surface is finite.
:::


# Preliminaries {#preliminaries}

For the basic notions of holomorphic foliations, we recommend the books [@4], [@13], and [@2].
A holomorphic foliation $\cal{F}$ with isolated singularities on an algebraic surface $M$ can be defined by a family of holomorphic vector fields $\{X_i\}$ defined on an open cover $\{U_i\}$ of $M$ satisfying the cocycle condition $X_i=g_{ij}X_j$ whenever $U_i\cap U_j\neq\varnothing$, where the $\{g_{ij}\}$ are nowhere-zero holomorphic functions defined on the $U_i\cap U_j$.
In this case, the $\{g_{ij}\}$ define a line bundle $T_\cal{G}^*$ on $M$ called the *cotangent*, or *canonical*, *bundle*.
The set of singularities $\Sing(\cal{G})$ of $\cal{G}$ is defined as $\Sing(\cal{G})/_{U_i}=\{X_i=0\}$, and it is always possible to suppose that $\dim\Sing(\cal{G})=0$.

Let $\cal{F}$ be a holomorphic foliation on a complex surface $M$.
Consider a compact curve $C$ on $M$.
\oldpage{49}
Let $p\in C$ and let $\{f=0\}$ be a reduced local equation of $C$ around $p$.
Suppose that $\cal{F}$ is represented in a coordinate neighbourhood $(U,(x,y))$ of $p=(0,0)$ by the holomorphic $1$-form
$$
  \omega
  = a(x,y)\dd{x} + b(x,y) \dd{y}.
$$
When $C$ is not $\cal{F}$-invariant, we define the *tangency* between $\cal{F}$ and $C$ at $p$ by
$$
  \tang_p(\cal{F},C)=\dim_\CC\cal{O}_p/I
$$
where $I$ is the ideal generated by $f$ and $-b\frac{\partial f}{\partial x}+a\frac{\partial f}{\partial y}$.
Define $\tang(\cal{F},C)=\sum_{p\in C}\tang_p(\cal{F},C)$.
It is proven in [@2] that
$$
  T_\cal{F}^*C
  = \tang(\cal{F},C) - C^2.
$$

::: {.rmenv #example-1 title="Example 1" latex="{Example 1}"}
If $M=\CC P(2)$ and $C$ is a non-$\cal{F}$-invariant line, then we have
$$
  T_\cal{F}^*
  = \cal{O}_{\CC P(2)}(\tang(\cal{F},C)-1).
$$
:::

Now suppose that $C$ is $\cal{F}$-invariant, so that $\omega\wedge\dd{f}=f\Theta$, where $\Theta$ is a holomorphic $2$-form.
Then there exist relatively prime holomorphic functions $g$ and $h$ defined on $U$, along with a holomorphic $1$-form $\eta$, such that
$$
  g\omega
  = h\dd{f} + f\eta.
$$

We define the *Camacho--Sad index* at $p$ by
$$
  \CS_p(\cal{F},C)
  = \frac{-1}{2\pi i}\int_\gamma\frac{\eta}{h}
$$
where $\gamma$ is a loop around $p$ on $\{f=0\}$.
Define $\CS(\cal{F},C)=\sum_{p\in\Sing\cal{F}\cap C}\CS_p(\cal{F},C)$.
The *Camacho--Sad index theorem* [@5] says that
$$
  \CS(\cal{F},C)
  = C^2.
$$
Recall that a *reduced foliation* is a foliation $\cal{F}$ such that every singularity $p$ is reduced in the sense of Seidenberg, i.e. for every vector field $X$ that generates $\cal{F}$, and every singular point $p$ of $X$, the eigenvalues of the linear part of $X$ are not both zero, and their quotient, when it is defined, is not a positive rational number.
If one of the values is zero and the other non-zero, then the singularity is said to be a *saddle node*.

\oldpage{50}
::: {.rmenv #definition-1 title="Definition 1" latex="{Definition 1}"}
Let $\cal{F}$ be a foliation on the complete surface $S$, and $\cal{G}$ an arbitrary reduced foliation that is bimeromorphically equivalent to $\cal{F}$.
The *Kodaira dimension* of $\cal{F}$ is given by
$$
  \Kod(\cal{F})
  = \limsup_{n\to\infty} \frac{\log h^0(S,K_\cal{G}^{\otimes n})}{\log n}.
$$
:::

The concept of Kodaira dimension for holomorphic foliations was introduced independently by L.G. Mendes and M. McQuillan, see [@2], [@12], and [@11].

It has been proven that the Kodaira dimension is well defined and is a bimeromorphic invariant of $\cal{F}$, see [@12].

When the foliation has Kodaira dimension $2$, we say that the foliation is of *general type*.
This terminology is justified since there exists a partial classification of foliations of Kodaira dimension less than $2$.
For more details, see [@11] and [@2].

A *fibration* at $M$ on a compact Riemann surface $B$ is a surjective holomorphic map $f\colon M\to B$.
A *generic* fibre of $f$ is the preimage of a regular value of $f$.
If all the generic fibres are connected then the fibration $f$ is said to be *connected*.
If all the fibres are rational curves then the fibration $f$ is said to be a *rational* fibration.

A foliation $\cal{F}$ at $M$ is said to be a *Riccati* foliation if there exists a rational fibration whose fibres are transversal to $\cal{F}$.

In [@12], it was proven that Riccati foliations and rational fibrations have dimension at most $1$.

The *bimeromorphism* (resp. *automorphism*) *group* of the foliation $\cal{F}$ is the maximal subgroup of the bimeromorphisms (resp. automorphisms) of $M$ that leave the foliation invariant.

In the case of $\PP_\CC^2$, a foliation $\cal{F}$ can be defined in affine coordinates $z=1$ by a $1$-form $\omega=A\dd{x}+B\dd{y}$, where $A$ and $B$ are complex polynomials in the variables $x,y$.
In this case, we can show that:

\oldpage{51}
::: {.itenv #proposition-1 title="Proposition 1" latex="{Proposition 1}"}
The automorphism group of a holomorphic foliation on $\PP_\CC^2$ is a Lie group.
Furthermore, it is quasi-projective, and thus has a finite number of connected components.
:::

::: {.proof}
By definition, $\Aut(\cal{F})$ is the set of elements $g$ of $\PGL(3,\CC)$ that leave $\cal{F}$ invariant.
So if $\cal{F}$ is given by a homogeneous $1$-form $\omega=\sum P_i\dd{x}_i$ then, by definition, $\omega$ and $g^*\omega$ define the same foliation, and are thus linearly dependent.
Thus
$$
  \Aut(cal{F})
  = \PP(\{ g\in\GL(3,\CC) \mid g^*\omega\wedge\omega = 0 \})
$$
where $\PP(A)$ denotes the projectivisation of $A$.
It is clear that $\Aut(\cal{F})$ is a Lie group.
Since $\GL(3,\CC)$ is quasi-projective, the proof is complete.
:::

::: {.rmenv #example-2 title="Example 2" latex="{Example 2}"}
Suppose that a foliation $\cal{F}$ is defined on $\PP_\CC^2$ by the $1$-form $\omega=P(x,y)\dd{x}+(Q(x,y)-yP(x,y))\dd{y}$, where $P,Q\in\CC[x+\frac{1}{2\alpha}y-\frac{1}{2}y^2]$ for some $\alpha\in\CC^*$.
Such foliations are invariant under $T(x,y)=(x+\frac{1}{\alpha}y,y+\frac{1}{\alpha})$.
So $\Aut(\cal{F})$ contains infinitely many elements of $\{T^n\mid n\in\ZZ\}$.
Since the flow of $X=(y-\frac{1}{2\alpha})\frac{\partial}{\partial x}+\frac{\partial}{\partial y}$
$$
  X_t(x,y)
  = \left(\begin{smallmatrix}1&t\\0&1\end{smallmatrix}\right)\left(\begin{smallmatrix}x\\y\end{smallmatrix}\right) + \left(\begin{smallmatrix}\frac{1}{2}t^2-\frac{1}{2\alpha}t\\t\end{smallmatrix}\right)
$$
satisfies $X_t^*\omega=\omega$, we see that $X_t$ belongs to the Lie algebra of $\Aut(\cal{F})$.
Note that $X_{1/\alpha}=T$.
:::

The following result shows that this example is general.

::: {.itenv #corollary-1 title="Corollary 1" latex="{Corollary 1}"}
If $\Aut(\cal{F})$ has an infinite number of elements then the dimension of $\Aut(\cal{F})$ is not zero.
:::

::: {.proof}
Suppose, for contradiction, that $\dim\Aut(\cal{F})=0$.
Then, by [Proposition 1](#proposition-1), $\Aut(\cal{F})$ has only a finite number of elements, which contradicts the hypothesis.
:::

To obtain a holomorphic vector field in the Lie algebra of $\Aut(\cal{F})$, as in [Example 2](#example-2), we apply the Martinelli--Bochner theorem [@10] which says the following: the automorphism group of a compact complex variety is a Lie group whose Lie algebra consists of globally defined holomorphic vector fields on the variety.


# Automorphisms of holomorphic foliations on the projective plane {#section-3}

\oldpage{52}

::: {.itenv #theorem-1 title="Theorem 1" latex="{Theorem 1}"}
Let $\cal{F}$ be a holomorphic foliation on $\PP_\CC^2$.
If $\#\Aut(\cal{F})=+\infty$ in a suitable affine coordinate system, then either $\cal{F}$ is induced by one of the following $1$-forms:

1. $\omega=P\dd{x}+(Q-yP)\dd{y}$, where $P,Q\in\CC[x-\frac{y^2}{2}]$;
2. $\omega=yp(y)\dd{x}+(xp(y)-q(y))\dd{y}$, where $p,q\in\CC[t]$;
3. $\omega=yp(y^m/x^n)\dd{x}+xq(y^m/x^n)\dd{y}$

or $\cal{F}$ is linear.
:::

::: {.proof}
Recall that the automorphism group of $\PP_\CC^2$ is isomorphic to $\PSL(3,\CC)$.
Since $\#\Aut(\cal{F})=+\infty$, [Corollary 1](#corollary-1) tells us that $\Aut(\cal{F})$ is a linear algebraic subgroup of $\PSL(3,\CC)$.
In particular, $\Aut(\cal{F})$ has a non-trivial Lie algebra, and so, by the Martinelli--Bochner theorem, there exists a global vector field $X$ on $\PP_\CC^2$ whose flow is in $\Aut(\cal{F})$.

Any global holomorphic vector field $X$ on $\PP_\CC^2$ can be represented in homogeneous coordinates $(x,y,z)$ in the form
$$
  X(x,y,z)
  = M\cdot(x,y,z)^t
$$
where $M\in\gl(3,\CC)$.
Analysing the possible canonical Jordan forms, we have essentially three distinct cases.

Firstly, suppose that the canonical Jordan form of $M$ is
$$
  M
  = \begin{bmatrix}
    \alpha & 1 & 0
  \\0 & \alpha & 1
  \\0 & 0 & \alpha
  \end{bmatrix}
$$
where $\alpha\in\CC^*$.
In this case, the action $\phi_t$ induced by $X$ can be written in the affine plane $\{z=1\}$ as
$$
  \phi_t(x,y)
  = (x+ty+\frac{t^2}{2}, y+t).
$$
\oldpage{53}
Therefore the orbits of $X$ are rational curves, and $X$ admits a rational first integral $x-y^2/2$.
If $\cal{F}$ is defined by the $1$-form $\omega=P(x,y)\dd{x}+Q(x,y)\dd{y}$ then $\phi_t^*\omega=\lambda(t)\omega$.
Thus $\lambda\equiv1$ and
$$
  \begin{cases}
    P = P\circ\phi_t
  \\Q = tP\circ\phi_t + Q\circ\phi_t.
  \end{cases}
$$
Thus $\omega=P\dd{x}+(R-yP)\dd{y}$, where $P=P\circ\phi_t$ and $R=R\circ\phi_t$.
In other words, $R$ and $P$ are integrals for the foliation defined by $X$.
Since $x-y^2/2$ is also a first integral and its fibres are connected, the Stein factorisation theorem [@8] implies that $P,R\in\CC[x-y^2/2]$.

Now consider $M$ of the form
$$
  M
  = \begin{bmatrix}
    \alpha & 1 & 0
  \\0 & \alpha & 0
  \\0 & 0 & \beta
  \end{bmatrix}
$$
where $\alpha,\beta\in\CC^*$.
Here the induced action $\phi_t$ is, in affine coordinates $\{z=1\}$,
$$
  \phi_t(x,y)
  = e^{t(\alpha-\beta)}(x+ty,y).
$$
As in the previous cases, $\cal{F}$ at $\{z=1\}$ is defined by $\omega=P(x,y)\dd{x}+Q(x,y)\dd{y}$.
Since $\phi_t^*\omega=\lambda(t)\omega$, we see that
$$
  \begin{aligned}
    \lambda(t)P(x,y)
    &= e^{t(\alpha-\beta)}P\circ\phi_t
    \tag{1}
  \\\lambda(t)Q(x,y)
    &= e^{t(\alpha-\beta)}(Q\circ\phi_t + tP\circ\phi_t).
    \tag{2}
  \end{aligned}
$$
Write $P(x,y)$ as a sum of its homogeneous components $P(x,y)=\sum_j P_j(x,y)$.
From (1) we deduce that, if $P_j(x,y)$ is not zero, then $\lambda(t)=e^{t(\alpha-\beta)(j+1)}$.
Comparing again with (1), we see that $P_j(x,y)=P_j(x+ty,y)$.
This implies that $P_j$ does not depend on $x$, and so $P(x,y)=p_jy^j$.
Using a similar argument with $Q(x,y)$, we can show that $Q(x,y)=-p_jxy^{j-1}+q_jy^j$.
Then the $1$-form $\omega$ can be written as
$$
  \omega
  = yp(y)\dd{x} + (q(y)-xp(y))\dd{y}.
$$

The remaining case is when $M$ is diagonalisable, i.e.
$$
  M
  = \begin{bmatrix}
    \alpha & 0 & 0
  \\0 & \beta & 0
  \\0 & 0 & \gamma
  \end{bmatrix}
$$
where $\alpha,\beta,\gamma\in\CC^*$.
\oldpage{54}
As in the previous cases, we can choose an affine coordinate system in which the foliation $\cal{F}$ is described by $\omega=P\dd{x}+Q\dd{y}$ and the action $\phi_t$ induced by $X$ is of the form
$$
  \phi_t(x,y)
  = (e^{t(\alpha-\gamma)}x,e^{t(\beta-\gamma)y}).
$$
Proceeding as before, we obtain the following relations:
$$
  \begin{aligned}
    \lambda(t)P(x,y)
    &= e^{t(\alpha-\gamma)}P\circ\phi_t
    \tag{3}
  \\\lambda(t)Q(x,y)
    &= e^{t(\beta-\gamma)}Q\circ\phi_t.
    \tag{4}
  \end{aligned}
$$
If we write $P(x,y)=\sum_{i,j}p_{ij}x^iy^j$ and $Q(x,y)=\sum_{i,j}q_{ij}x^iy^j$ then we can deduce from (3) the relations
$$
  \begin{aligned}
    \lambda(t)
    &= e^{t(\alpha-\gamma)(i+1)+t(\beta-\gamma)j}
    \quad\text{if }p_{ij}\neq0
    \tag{5}
  \\\lambda(t)
    &= e^{t(\alpha-\gamma)i+t(\beta-\gamma)(j+1)}
    \quad\text{if }q_{ij}\neq0.
    \tag{6}
  \end{aligned}
$$
Note that $X$ admits a rational first integral if and only if $(\alpha-\gamma)/(\beta-\gamma)=m/n\in\QQ$.

Suppose that $X$ has an rational first integral, and consider the group
$$
  G
  = \{ (l,k)\in\ZZ\oplus\ZZ \mid e^{t(\alpha-\gamma)l}=e^{t(\beta-\gamma)k}\text{ for all }t\in\CC \}.
$$
Since $G$ is cyclic and generated by $(n,m)$, let $(l_0,k_0)\in\ZZ\oplus\ZZ$ be such that $\lambda(t)=e^{t(\alpha-\gamma)l_0+t(\beta-\gamma)k_0}$.
Then
$$
  \omega
  = x^{l_0}y^{k_0}(yp(y^m/x^n)\dd{x} + xq(y^m/x^n)\dd{y}).
$$

Finally, assume that $(\alpha-\gamma)/(\beta-\gamma)\not\in\QQ$.
Then there exists $t_0\in\CC^*$ such that $e^{t_0(\alpha-\gamma)n}\neq e^{t_0(\beta-\gamma)m}$ for any integers $n$ and $m$ that are not both zero.
This implies that there exists a unique pair of integers $(k,l)$ such that $\lambda(t_0)=e^{t_0(\alpha-\gamma)l+t_0(\beta-\gamma)k}$.
As a consequence of (3), we conclude that $P(x,y)=p_{lk}x^{l-1}y^k$ and $Q(x,y)=q_{lk}x^ly^{k-1}$.
Thus
$$
  \omega
  = x^{l-1}y^{k-1}(p_{lk}y\dd{x} + q_{lk}x\dd{y})
$$
and clearly $\cal{F}$ is a linear foliation.
:::

\oldpage{55}

::: {.itenv #corollary-2 title="Corollary 2" latex="{Corollary 2}"}
Let $\cal{F}$ be a holomorphic foliation defined on $\PP_\CC^2$.
Suppose that $\#\Aut(\cal{F})=+\infty$.
Then $\cal{F}$ is birationally equivalent to a Riccati foliation.
:::

::: {.proof}
From the proof of the [previous theorem](#theorem-1) we have that the foliation defined by $X$ has no rational first integral, and so $\cal{F}$ is linear.
In particular, $\cal{F}$ is a Riccati foliation after a blow-up.

Now suppose that the foliation $\cal{G}$ defined by $X$ has a first integral, i.e. is a pencil of rational curves.
Let $\sigma\colon M\to\PP_\CC^2$ be the minimal resolution of $\cal{G}$.
As we blow-up the singular points of $X$, we obtain a holomorphic field of vectors of $\widetilde{X}$ defined on all of $M$ that belong to the Lie algebra of $\Aut(\sigma^*\cal{F})$.

Thus the geometric place of the tangencies of $\sigma^*\cal{F}$ and $\widetilde{X}$ must be invariant under $\sigma^*\cal{F}$, see [@6] and [@7].
So $\sigma^*\cal{G}$ is a rational fibration, and we thus obtain that $\sigma^*\cal{F}$ is a Riccati foliation.
:::

::: {.itenv #proposition-2 title="Proposition 2" latex="{Proposition 2}"}
Let $\cal{F}$ be a holomorphic foliation of general type on a compact complex surface $M$.
Then $\Aut(\cal{F})$ is isomorphic to a linear algebraic group.
:::

::: {.proof}
Since $\cal{F}$ is of general type, for a sufficiently large integer $m$, the $m$-th pluricanonical map $\phi_m$ is a bimeromorphism between $M$ and the closure of its image, denoted by $N$.

Note that the group $\Aut(\cal{F})$ acts naturally on the projectivisation of $\mathrm{H}^0(M,K_\cal{F}^{\otimes m})$.
If $\sigma$ is a section of $K_\cal{F}^{\otimes m}$ and $\alpha$ is an automorphism of $\cal{F}$, then the action is given by $\alpha(\sigma)=\alpha^*\sigma$.

Since $\phi_m$ is a bimeromorphism between $M$ and $N$, this action induces a monomorphism of groups
$$
  \psi\colon \Aut(\cal{F}) \to \PSL(k,\CC)
$$
where $k=\dim_\CC\mathrm{H}^0(M,K_\cal{F}^{\otimes m})-1$.

\oldpage{56}
Note that the image of $\psi$ is precisely the automorphism of $\PP_\CC^{k-1}$ that leaves $N$ and $\cal{G}$ invariant, and so we can conclude that $\Aut(\cal{F})\cong\Aut(\cal{G})$ is a linear algebraic subgroup of $\PSL(k,\CC)$.
:::

In the proof of our principal result, we approximately follows the arguments of Brunella in [@2, pp.86--88].

::: {.rmenv title="Proof of Theorem A" latex="{Proof of Theorem A}"}
If
:::
