--- 
title: "Hodge Theory II"
author: "Pierre Deligne"
date: "1971"
original: 'Deligne, P. "Théorie de Hodge II". _Publ. math. IHÉS_ **40** (1971), 5--57. [publications.ias.edu/node/361](https://publications.ias.edu/node/361).'
bibliography: PMIHES-40-1971-5.bib
nocite: '@*'
link-citations: true
csl: maths-translations.csl
reference-section-title: "Bibliography"
github-repo: "thosgood/translations"
favicon: "favicon.ico"
---

```{js, echo = FALSE}
$(document).ready(function(e) {gitbook.sidebar.toggle(false, false)});
```

```{r, child = '_translator-note.Rmd'}
```

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\ZZ}{\mathbb{Z}}
\providecommand{\QQ}{\mathbb{Q}}
\providecommand{\CC}{\mathbb{C}}
\providecommand{\PP}{\mathbb{P}}
\providecommand{\id}{\mathrm{id}}

\providecommand{\Gr}{\operatorname{Gr}}
\providecommand{\Ker}{\operatorname{Ker}}
\providecommand{\HH}{\operatorname{H}}
\renewcommand{\Im}{\operatorname{Im}}
\providecommand{\Coim}{\operatorname{Coim}}
\renewcommand{\Ker}{\operatorname{Ker}}
\providecommand{\Coker}{\operatorname{Coker}}
\providecommand{\simto}{\xrightarrow{\sim}}
\providecommand{\op}{\circ}
\providecommand{\Hom}{\operatorname{Hom}}
\providecommand{\Dec}{\operatorname{Dec}}

<!-- Content -->

# Introduction {.unnumbered #introduction}

\oldpage{5}
*Work presented as a doctoral thesis at l'Université d'Orsay.*

By Hodge, the cohomology space $\HH^n(X,\CC)$ of a compact Kähler variety $X$ is endowed with a "Hodge structure" of weight $n$, i.e. a natural bigrading
$$
  \HH^n(X,\CC)
  = \bigoplus_{p+q=n} \HH^{p,q}
$$
that satisfies $\overline{\HH^{p,q}}=\HH^{q,p}$.
We will show here that the complex cohomology of a non-singular, not necessarily compact, algebraic variety is endowed with a structure of a slightly more general type, which presents $\HH^n(X,\CC)$ as a "successive extension" of Hodge structures of decreasing weights, contained between $2n$ and $n$, whose Hodge numbers $h^{p,q}=\dim\HH^{p,q}$, are zero for both $p>n$ and $q>n$.

The reader will find an explanation in [@14] of the yoga that underlies this construction.

\oldpage{6}
The proof, which is essentially algebraic, relies on one hand on Hodge theory, and on the other on Hironaka's resolution of singularities, which allows us, via a spectral sequence, "to express" the cohomology of a non-singular quasi-projective algebraic variety in terms of the cohomology of non-singular projective varieties.

[Section 1](#section-1) contains, apart from reminders on filtrations gathered together for the ease of the reader, two key results:

a) [Theorem 1.2.10](#theorem-1.2.10), which will only be used via its corollary, [Theorem 2.3.5](#theorem-2.3.5), which gives the fundamental properties of "mixed Hodge structures".
b) The "two filtrations lemma", [Lemma 1.3.16](#lemma-1.3.16).

[Section 2](#section-2) recalls Hodge theory and introduces mixed Hodge structures.

The heart of this work is [§3.2](#subsection-3.2), which defines the mixed Hodge structure of $\HH^n(X,\CC)$, and establishes some degenerations of spectral sequences.

[Section 4](#section-4) gives diverse applications, all following from [Theorem 4.1.1](#theorem-4.1.1) and the theory of the $(K/k)$-trace, for the resulting Hodge structures ([Corollary 4.1.2](#corollary-4.1.2)).
The principal ones are [Theorem 4.2.6](#theorem-4.2.6) and [Corollary 4.4.15](#corollary-4.4.15).


# Filtrations {#section-1}

## Filtered objects {#section-1.1}

::: {.rmenv #chunk-1.1.1 title="1.1.1" latex="{1.1.1}"}
Let $\scr{A}$ be an abelian category.
:::

We will be considering $\ZZ$-filtrations, finite, in general, on the objects of $\scr{A}$:

::: {.rmenv #definition-1.1.2 title="1.1.2" latex="{1.1.2}"}
A *decreasing* (resp. *increasing*) *filtration* $F$ of an object $A$ of $\scr{A}$ is a family $(F^n(A))_{n\in\ZZ}$ (resp. $(F_n(A))_{n\in\ZZ}$) of sub-objects of $A$ satisfying
$$
  \forall n,m
  \quad n\leq m \implies F^m(A)\subset F^n(A)
$$
(resp. $n\leq m\implies F_n(A)\subset F_m(A)$).

A *filtered object* is an object endowed with a filtration.
When there is no chance of confusion, we often denote by the same letter filtrations on different objects of $\scr{A}$.

If $F$ is a decreasing (resp. increasing) filtration on $A$, then we set $F^\infty(A)=0$ and $F^{-\infty}(A)=A$ (resp. $F_{-\infty}(A)=0$ and $F_\infty(A)=A$).

The *shifted filtrations* of a decreasing filtration $W$ are defined by
$$
  W[n]^p(A)
  = W^{n+p}(A)
$$
for $n\in\ZZ$.
:::

::: {.rmenv #chunk-1.1.3 title="1.1.3" latex="{1.1.3}"}
If $R$ is a decreasing (resp. increasing) filtration of $A$, then the $F_n(A)=F^{-n}(A)$ (resp the $F^n(A)=F_{-n}(A)$) form an increasing (resp. decreasing) filtration of $A$.
\oldpage{7}
This allows us in principal to consider only decreasing filtrations;
*unless otherwise explicitly mentioned, when we say "filtration" we always mean "decreasing filtration"*.
:::

::: {.rmenv #chunk-1.1.4 title="1.1.4" latex="{1.1.4}"}
A filtration $F$ of $A$ is said to be *finite* if there exist $n$ and $m$ such that $F^n(A)=A$ and $F^m(A)=0$.
:::

::: {.rmenv #chunk-1.1.5 title="1.1.5" latex="{1.1.5}"}
A *morphism* from a filtered object $(A,F)$ to a filtered object $(B,F)$ is a morphism $f$ from $A$ to $B$ that satisfies $f(F^n(A))\subset F^n(B)$ for all $n\in\ZZ$.

Filtered objects (resp. finite filtered objects) of $\scr{A}$ form an additive category in which inductive limits and finite projective limits exist (and thus kernels, cokernels, images, and coimages of a morphism).

A morphism $f\colon(A,F)\to(B,F)$ is said to be *strict*, or *strictly compatible with the filtrations*, if the canonical arrows from $\Coim(f)$ to $\Im(f)$ is an isomorphism of filtered objects (cf. [(1.1.11)](#proposition-1.1.11)).
:::

::: {.rmenv #chunk-1.1.6 title="1.1.6" latex="{1.1.6}"}
Let $(-)^\op$ be the contravariant identity functor from $\scr{A}$ to the dual category $\scr{A}^\op$.
If $(A,F)$ is a filtered object of $\scr{A}$, then the $(A/F^n(A))^\op$ can be identified with sub-objects of $A^\op$.
The *dual* filtration on $A^\op$ is defined by
$$
  F^n(A^\op)
  = (A/F^{1-n})^\op.
$$

The double dual of $(A,F)$ can be identified with $(A,F)$.
This construction identifies the dual of the category of filtered objects of $\scr{A}$ with the category of filtered objects of $\scr{A}^\op$.
:::

::: {.rmenv #chunk-1.1.7 title="1.1.7" latex="{1.1.7}"}
If $(A,F)$ is a filtered object of $\scr{A}$, then its *associated graded* is the object of $\scr{A}^\ZZ$ defined by
$$
  \Gr^n(A)
  = F^n(A)/F^{n+1}(A).
$$
The convention [(1.1.6)](#chunk-1.1.6) is justified by the simple formula
$$
  \Gr^n(A^\op)
  = \Gr^{-n}(A)^\op
$$
which follows from the self-dual diagram
**!!TO-DO: diagram (1.1.7.1)!!**
:::

::: {.rmenv #chunk-1.1.8 title="1.1.8" latex="{1.1.8}"}
Let $(A,F)$ be a filtered object, and $j\colon X\hookrightarrow A$ a sub-object of $A$.
The *filtration induced by $F$* (or simply *induced filtration*) on $X$ is the unique filtration on $X$ such that $j$ is strictly compatible with the filtrations;
we have
$$
  F^n(X)
  = j^{-1}(F^n(A))
  = X\cap F^n(A).
$$

Dually, the *quotient filtration* on $A/X$ (the unique filtration such that $p\colon A\to A/X$ is strictly compatible with the filtrations) is given by
$$
  F^n(A/X)
  = p(F^n(A))
  \cong (X+F^n(A))/X
  \cong F^n(A)/(X\cap F^n(A)).
$$
:::

::: {.itenv #lemma-1.1.9 title="Lemma 1.1.9" latex="{Lemma 1.1.9}"}
\oldpage{8}
If $X$ and $Y$ are sub-objects of $A$, with $X\subset Y$, then on $Y/X\simto\Ker(A/X\to A/Y)$ the quotient filtration of $Y$ agrees with that induced by that of $A/X$.
In the diagram
**!!TO-DO: diagram!!**
the arrows are strict.
:::

::: {.rmenv #chunk-1.1.10 title="1.1.10" latex="{1.1.10}"}
We call the filtration [(1.1.9)](#lemma-1.1.9) on $Y/X$ the *filtration induced by that of $A$* (or simply the *induced filtration*).
By [(1.1.9)](#lemma-1.1.9), its definition is self-dual.

In particular, if $\Sigma\colon A\xrightarrow{f}B\xrightarrow{G}C$ is a **!!TO-DO: o-suite?!!** sequence, and if $B$ is filtered, then $\HH(\Sigma)=\Ker(g)/\Im(f)=\Ker(\Coker(f)\to\Coim(g))$ is endowed with a canonical induced filtration.
:::

The reader can show that:

::: {.itenv #proposition-1.1.11 title="Proposition 1.1.11" latex="{Proposition 1.1.11}"}
—

i. Let $f\colon(A,F)\to(B,F)$ be a morphism of filtered objects with finite filtrations.
  For $f$ to be strict, it is necessary and sufficient that the sequence
  $$
    0
    \to \Gr(\Ker(f))
    \to \Gr(A)
    \to \Gr(B)
    \to \Gr(\Coker(f))
    \to 0
  $$
  be exact.

ii. Let $\sigma\colon(A,F)\to(B,F)\to(C,F)$ be a **!!TO-DO: o-suite?!!** sequence of strict morphisms.
  We then have
  $$
    \HH(\Gr(\Sigma))
    \cong \Gr(\HH(\Sigma))
  $$
  canonically.
  In particular, if $\Sigma$ is exact in $\scr{A}$, then $\Gr(\Sigma)$ is exact in $\scr{A}^\ZZ$.
:::

In a category of modules, to say that a morphism $f\colon(A,F)\to(B,F)$ is strict implies that every $b\in B$ of filtration $\geq n$ (i.e. $b\in F^n(B)$) that is in the image of $A$ is already in the image of $F^n(A)$:
$$
  f(F^n(A))
  = f(A)\cap F^n(B).
$$

::: {.rmenv #chunk-1.1.12 title="1.1.12" latex="{1.1.12}"}
If $\otimes\colon\scr{A}_1\times\ldots\times\scr{A}_n\to\scr{B}$ is a multiadditive right-exact functor, and if $A_i$ is an object of finite filtration of $\scr{A}_i$ (for $1\leq i\leq n$), then we define a filtration on $\bigotimes_{i=1}^n A_i$ by
$$
  F^k(\bigotimes_{i=1}^n A_i)
  = \sum_{\sum k_i=k} \Im(\bigotimes_{i=1}^n F^{k_i}(A_i)\to\bigotimes_{i=1}^n A_i)
$$
(a sum of sub-objects).

Dually, if $H$ is left-exact, then we set
$$
  F^k(H(A_i))
  = \bigcap_{\sum k_i=k} \Ker(H(A_i)\to H(A_i/F^{k_i}(A_i))).
$$

\oldpage{9}
If $H$ is exact, then the two definitions are equivalent.

We extend these definitions to contravariant functors in certain variables by [(1.1.6)](#chunk-1.1.6).
In particular, for the left-exact functor $\Hom$, we set
$$
  F^k(\Hom(A,B))
  = \{f\colon A\to B \mid f(F^n(A))\subset F^{n+k}(B)\,\,\forall n\}.
$$
We thus have
$$
  \Hom((A,F),(B,F))
  = F^0(\Hom(A,B)).
$$

Under the above hypotheses, we have obvious morphisms
$$
  \begin{aligned}
    \bigotimes_{i=1}^n \Gr(A_i)
    &\to \Gr(\bigotimes_{i=1}^n A_i)
  \\\Gr H(A_i)
    &\to H(\Gr(A_i)).
  \end{aligned}
$$
If $H$ is exact, then these are isomorphisms and inverse to one another.

These constructions are compatible with composition of functors, in a sense whose details we leave to the reader.
:::


## Opposite filtrations {#section-1.2}

::: {.rmenv #chunk-1.2.1 title="1.2.1" latex="{1.2.1}"}
Let $A$ be an object of $\scr{A}$ endowed with filtrations $F$ and $G$.
By definition, $\Gr_F^n(A)$ is a quotient of a sub-object of $A$ and, as such, is endowed with a filtration induced by $G$ [(1.1.10)](#chunk-1.1.10).
Passing to the associated graded defines a bigraded object $(\Gr_G^n\Gr_F^m(A))_{n,m\in\ZZ}$.
By a lemma of Zassenhaus, $\Gr_G^n\Gr_F^m(A)$ and $\Gr_F^m\Gr_G^n(A)$ are canonically isomorphic: if we define the induced filtrations [(1.1.10)](#chunk-1.1.10) as quotient filtrations of the induced filtrations on a sub-object, then we have
$$
  \begin{aligned}
    \Gr_G^n\Gr_F^m(A)
    \cong (F^m(A)\cap G^n(A)) &/ ((F^{m+1}(A)\cap G^n(A)) + (F^m(A)\cap G^{n+1}(A)))
  \\&=
  \\\Gr_F^m\Gr_G^n(A)
    \cong (G^n(A)\cap F^m(A)) &/ ((G^{n+1}(A)\cap F^m(A)) + (G^n(A)\cap F^{m+1}(A)))
  \end{aligned}
$$
:::

::: {.rmenv #chunk-1.2.2 title="1.2.2" latex="{1.2.2}"}
Let $H$ be a third filtration of $A$.
It induces a filtration on $\Gr_F(A)$, and thus on $\Gr_G\Gr_F(A)$.
It also induces a filtration on $\Gr_F\Gr_G(A)$.
We note that these filtrations do not in general correspond to one another under the isomorphism [(1.2.1)](#chunk-1.2.1).
In the expression $\Gr_H\Gr_G\Gr_F(A)$, $G$ and $H$ thus play a symmetric role, but not $F$ and $G$.
:::

::: {.rmenv #definition-1.2.3 title="1.2.3" latex="{1.2.3}"}
Two *finite* filtrations $F$ and $\overline{F}$ on $A$ are said to be *$n$-opposite* if $\Gr_F^p\Gr_{\overline{F}}^q(A)=0$ for $p+q\neq n$.
:::

::: {.rmenv #chunk-1.2.4 title="1.2.4" latex="{1.2.4}"}
If $A^{p,q}$ is a bigraded object of $\scr{A}$ such that

a. $A^{p,q}=0$ except for a finite number of pairs $(p,q)$, and
b. $A^{p,q}=0$ for $p+q\neq n$

\oldpage{10}
then we define two $n$-opposite filtrations of $A=\sum_{p,q}A^{p,q}$ by setting
$$
  F^p(A)
  = \sum_{p'\geq p} A^{p',q'}
\tag{1.2.4.1}
$$
$$
  \overline{F}^q(A)
  = \sum_{q'\geq q} A^{p',q'}.
\tag{1.2.4.2}
$$
We have
$$
  \Gr_F^p\Gr_{\overline{F}}^q(A)
  = A^{p,q}.
\tag{1.2.4.3}
$$
:::

Conversely:

::: {.itenv #proposition-1.2.5 title="Proposition 1.2.5" latex="{Proposition 1.2.5}"}
—

i. Let $F$ and $\overline{F}$ be finite filtrations on $A$.
  For $F$ and $\overline{F}$ to be $n$-opposite, it is necessary and sufficient that, for all $p,q$,
  $$
    [p+q=n+1]
    \implies [F^p(A)\oplus\overline{F}^q(A) \simto A].
  $$

ii. If $F$ and $\overline{F}$ are $n$-opposite, and if we set
  $$
    \begin{cases}
      A^{p,q} = 0
      &\text{for }p+q\neq n
    \\A^{p,q} = F^p(A)\cap\overline{F}^q(A)
      &\text{for }p+q=n
    \end{cases}
  $$
  then $A$ is the direct sum of the $A^{p,q}$, and $F$ and $\overline{F}$ come from the bigrading $A^{p,q}$ of $A$ by the procedure of [(1.2.4)](#chunk-1.2.4).
:::

**!!TO-DO: why is the following proof not appearing in the PDF version?!!**

::: {.proof}
—

i. The condition $\Gr_F^p\Gr_{\overline{F}}^q(A)=0$ for $p+q>n$ implies that $F^p\cap\overline{F}^q=(F^{p+1}\cap\overline{F}^q)+(F^p\cap\overline{F}^{q+1})$ for $p+q>n$.
  By hypothesis, $F^p\cap\overline{F}^q$ is zero for large enough $p+q$;
  by decreasing induction, we thus deduce that the condition $\Gr_F^p\Gr_{\overline{F}}^q(A)=0$ for $p+q>n$ is equivalent to the condition $F^p(A)\cap\overline{F}^q(A)=0$ for $p+q>n$.
  Dually ([(1.1.6)](#chunk-1.1.6), [(1.1.7)](#chunk-1.1.7), [(1.1.10)](#chunk-1.1.10)), the condition $\Gr_F^p\Gr_{\overline{F}}^q(A)=0$ for $p+q<n$ is equivalent to the condition $A=F^p(A)+\overline{F}^q(A)$ for $(1-p)+(1-q)>-n$, i.e. for $p+q\leq n+1$, and the claim then follows.

ii. If $F$ and $\overline{F}$ are $n$-opposite, then we can prove by decreasing induction on $p$ that
  $$
    \bigoplus_{p'\geq p} A^{p',q'}
    \simto F^p(A).
  \tag{1.2.5.1}
  $$
    a. For $F^p(A)=0$, the claim is evident.
    b. The decomposition $A=F^{p+1}(A)\oplus\overline{F}^{n-p}(A)$ induces on $F^p(A)\supset F^{p+1}(A)$ a decomposition
    $$
      F^p(A)
      = F^{p+1}(A)\oplus(F^p(A)\cap\overline{F}^{n-p}(A))
    $$
    and we conclude by induction.
  For $p$ small enough, we have $F^p(A)=A$.
  By (1.2.5.1), the $A^{p,q}$ thus form a bigrading of $A$, and $F$ satisfies (1.2.4.1).
  The fact that $\overline{F}$ satisfies (1.2.4.2) then follows by symmetry.
:::

::: {.rmenv #chunk-1.2.6 title="1.2.6" latex="{1.2.6}"}
The constructions [(1.2.4)](#chunk-1.2.4) and [(1.2.5)](#proposition-1.2.5) establish equivalences of categories that are quasi-inverse to one another between objects of $\scr{A}$ endowed with two finite $n$-opposite filtrations and bigraded objects of $\scr{A}$ of the type considered in [(1.2.4)](#chunk-1.2.4).
:::

::: {.itenv #definition-1.2.7 title="Definition 1.2.7" latex="{Definition 1.2.7}"}
\oldpage{11}
Three *finite* filtrations $W$, $F$, and $\overline{F}$ on $A$ are said to be *opposite* if
$$
  \Gr_F^p\Gr_{\overline{F}}^q\Gr_W^n(A)
  = 0
$$
for $p+q+n\neq0$.
:::

This condition is symmetric in $F$ and $\overline{F}$.
It implies that $F$ and $\overline{F}$ induce on $W^n(A)/W^{n+1}(A)$ two $(-n)$-opposite filtrations.
We set
$$
  A^{p,q}
  = \Gr_F^p\Gr_{\overline{F}}^q\Gr_F^{-p-q}(A)
$$
whence decompositions [(1.2.4)](#chunk-1.2.4), [(1.2.5)](#proposition-1.2.5)
$$
  W^n(A)/W^{n+1}(A)
  = \bigoplus_{p+q=-n} A^{p,q}
\tag{1.2.7.1}
$$
which makes $\Gr_W(A)$ into a bigraded object.

::: {.itenv #lemma-1.2.8 title="Lemma 1.2.8" latex="{Lemma 1.2.8}"}
Let $W$, $F$, and $\overline{F}$ be three finite opposite filtrations, and $\sigma$ a sequence $(p_i,q_i)_{i\geq0}$ pairs of integers satisfying

a. $p_i\leq p_j$ and $q_i\leq q_j$ for $i\geq j$, and
b. $p_i+q_i=p_0+q_0-i+1$ for $i>0$.

Set $p=p_0$, $q=q_0$, $n=-p-q$, and
$$
  A_\sigma
  = \left( \sum_{0\leq i}(W^{n+i}(A)\cap F^{p_i}(A)) \right)
  \cap \left( \sum_{0\leq i}(W^{n+i}(A)\cap\overline{F}^{q_i}(A)) \right).
$$
Then the projection from $W^n(A)$ to $\Gr_W^n(A)$ induces an isomorphism
$$
  A_\sigma
  \simto A^{p,q} \subset \Gr_W^n(A).
$$
:::

::: {.proof}
We will prove by induction on $k$ the following claim:

($*_k$) The projection from $W^n(A)/W^{n+k}$ to $\Gr_W^n(A)$ induces an isomorphism from
$$
  \left(
  \left( \sum_{i<k} (W^{n+i}(A)\cap F^{p_i}(A)) + W^{n+k}(A) \right)
  \cap \left( \sum_{i<k} (W^{n+i}(A)\cap\overline{F}^{q_i}(A)) + W^{n+k}(A) \right)
  \right) / W^{n+k}(A)
  $$
to $A^{p,q}\subset\Gr_W^n(A)$.

For $k=1$, this is exactly the definition of $A^{p,q}$.

By [(1.2.5), (i)](#proposition-1.2.5) we have
$$
  F^{p_k}(\Gr_W^{n+k}(A)) \oplus \overline{F}^{q_k}(\Gr_W^{n+k}(A))
  \simto \Gr_W^{n+k}(A).
\tag{1.2.8.1}
$$
Set
$$
  \begin{aligned}
    B &= \sum_{i<k} (W^{n+i}(A)\cap F^{p_i}(A))
  \\C &= \sum_{i<k} (W^{n+i}(A)\cap\overline{F}^{q_i}(A))
  \\B' &= (W^{n+k}(A)\cap F^{p_k}(A)) + W^{n+k+1}(A)
  \\C' &= (W^{n+k}(A)\cap\overline{F}^{q_k}(A)) + W^{n+k+1}(A)
  \\D &= W^{n+k}(A)
  \\E &= W^{n+k+1}(A).
  \end{aligned}
$$

\oldpage{12}
Equation (1.2.8.1) can then be written as
$$
  \begin{aligned}
    B'+C' &= D
  \\B'\cap C' &= E.
  \end{aligned}
$$
We also have, since $p_k\leq p_i$ (for $i\leq k$),
$$
  B\cap D
  \subset F^{p_k}(A) \cap W^{n+k}(A)
  \subset B'
$$
and, since $q_k\leq q_i$ (for $i\leq k$),
$$
  C\cap D
  \subset \overline{F}^{q_k}(A)\cap W^{n+k}(A)
  \subset C'.
$$

The claim ($*_{k+1}$) and then follows from ($*_k$) and the following lemma.
:::

::: {.itenv #lemma-1.2.9 title="Lemma 1.2.9" latex="{Lemma 1.2.9}"}
Let $B$, $C$, $B'$, $C'$, $D$, and $E$ be sub-objects of $A$.
Suppose that
$$
  \begin{gathered}
    B'+C' = D
    \qquad B'\cap C' = E
  \\B\cap D \subset B'
    \qquad C\cap D \subset C'.
  \end{gathered}
$$
Then
$$
  ((B+B')\cap(C+C'))/E
  \simto ((B+D)\cap(C+D))/D.
$$
:::

::: {.proof}
To prove surjectivity, we write
$$
  \begin{aligned}
    ((B+B')\cap(C+C'))+D
    &= (((B+B')\cap(C+C'))+B')+C'
  \\&= ((B+B')\cap(C+C'+B'))+C'
  \\&= (B+B'+C')\cap(C+C'+B')
  \\&= (B+D)\cap(C+D).
  \end{aligned}
$$

To prove injectivity, we write
$$
  (B+B')\cap(C+C')\cap D
  = ((B+B')\cap D)\cap((C+C')\cap D).
$$
Since $B'\subset D$, we have
$$
  \begin{aligned}
    (B+B')\cap D
    &= (B\cap D)+B'
  \\&= B'
  \end{aligned}
$$
and similarly
$$
  (C+C')\cap D
  = C'
$$
and
$$
  \begin{aligned}
    (B+B')\cap(C+C')\cap D
    &= B'\cap C'
  \\&= E.
  \end{aligned}
$$
:::

This finishes the proof of [(1.2.8)](#lemma-1.2.8), noting that [(1.2.8)](#lemma-1.2.8) is equivalent to ($*_k$) for large $k$.

::: {.itenv #theorem-1.2.10 title="Theorem 1.2.10" latex="{Theorem 1.2.10}"}
Let $\scr{A}$ be an abelian category, and provisionally denote by $\scr{A}'$ the category of objects of $\scr{A}$ endowed with three opposite filtrations $W$, $F$, and $\overline{F}$.
The morphisms in $\scr{A}'$ are the morphisms of $\scr{A}$ that are compatible with the three filtrations.

i. $\scr{A}'$ is an abelian category.
ii. The kernel (resp. cokernel) of an arrow $f\colon A\to B$ in $\scr{A}'$ is the kernel (resp. cokernel) of $f$ in $\scr{A}$, endowed with the filtrations induced by those of $A$ (resp. the quotients of those of $B$).
iii. Every morphism $f\colon A\to B$ in $\scr{A}'$ is strictly compatible with the filtrations $W$, $F$, and $\overline{F}$;
  the morphism $\Gr_W(f)$ is compatible with the bigradings of $\Gr_W(A)$ and $\Gr_W(B)$;
  the morphisms $\Gr_F(f)$ and $\Gr_{\overline{F}}(f)$ are strictly compatible with the filtration induced by $W$.
iv. The "forget the filtrations" functors, $\Gr_W$, $\Gr_F$, and $\Gr_{\overline{F}}$, and
  $$
    \begin{gathered}
      \Gr_W\Gr_F
      \simeq \Gr_F\Gr_W
    \\\simeq \Gr_{\overline{F}}\Gr_F\Gr_W
    \\\simeq \Gr_{\overline{F}}\Gr_W
      \simeq \Gr_W\Gr_{\overline{F}}
    \end{gathered}
  $$
  from $\scr{A}'$ to $\scr{A}$ are exact.
:::

\oldpage{13}
Denote by $\sigma_0(p,q)$ and $\sigma_1(p,q)$ the sequences
$$
  \begin{aligned}
    \sigma_0(p,q)
    &= (p,q), (p,q), (p,q-1), (p,q-2), (p,q-3), \ldots
  \\\sigma_0(p,q)
    &= (p,q), (p,q), (p-1,q), (p-2,q), (p-3,q), \ldots
  \end{aligned}
$$
and, with the notation of [(1.2.8)](#lemma-1.2.8), set
$$
  A_i^{p,q}
  = A_{\sigma_i(p,q)}
  \qquad\text{(for }i=0,1\text{)}.
$$

If $f\colon A\to B$ is compatible with $W$, $F$, and $\overline{F}$, then we have
$$
  f(A_i^{p,q})
  \subset B_i^{p,q}
  \qquad\text{(for }i=0,1\text{)}.
\tag{1.2.10.1}
$$
Claim (iii) then follows from the following lemma:

::: {.itenv #lemma-1.2.11 title="Lemma 1.2.11" latex="{Lemma 1.2.11}"}
The $A_i^{p,q}$ give a bigrading of $A$.
We have
$$
  W^n(A)
  = \sum_{n+p+q\leq 0} A_i^{p,q}
  \qquad\text{(for }i=0,1\text{)}
\tag{1.2.11.1}
$$
$$
  F^p(A)
  = \sum_{p'\geq p} A_0^{p',q'}
\tag{1.2.11.2}
$$
$$
  \overline{F}^q(A)
  = \sum_{q'\geq q} A_1^{p',q'}.
\tag{1.2.11.3}
$$
:::

::: {.proof}
By symmetry, it suffices to prove the claims concerning $i=0$.
Set $A_0=\bigoplus A_0^{p,q}$ and define filtrations $W$ and $F$ on $A_0$ by the equations of [(1.2.11)](#lemma-1.2.11).
The canonical map $i$ from $A_0$ to $A$ is compatible with the filtrations $W$ and $F$.
Furthermore, by [(1.2.8)](#lemma-1.2.8), $\Gr_W(i)$ is an isomorphism, and induces isomorphisms of graded objects
$$
  \sum_{p+q=n} A_0^{p,q}
  \simto \Gr_W^{-n}(A)
  = \sum_{p+q=n} A^{p,q}.
\tag{1.2.11.4}
$$
The morphism $i$ is thus an isomorphism, and the $A_0^{p,q}$ give a bigrading of $A$.

Equation (1.2.11.1) then says that $\Gr_W(i)$ is an isomorphism.
By (1.2.11.4), $\Gr_F\Gr_W(i)$ is an isomorphism, and thus so too are $\Gr_W\Gr_F(i)$ and $\Gr_F(i)$.
Equation (1.2.11.2) then follows.
:::

::: {.rmenv #chunk-1.2.12 title="1.2.12" latex="{1.2.12}"}
We now prove [(1.2.10)](#theorem-1.2.10).
Let $f\colon A\to B$ in $\scr{A}'$ and endow $K=\Ker(f)$ with the filtrations induced by those of $A$.
By [(1.2.11)](#lemma-1.2.11), $\Gr_W(K)\hookrightarrow\Gr_W(A)$;
furthermore, the filtration $F$ (resp. $\overline{F}$) on $K$ induces on $\Gr_W(K)$ the inverse image filtration of the filtration $F$ on $\Gr_W(A)$.
The sub-object $\Gr_W(K)$ of $\Gr_W(A)$ is then compatible with the bigrading of $\Gr_W(A)$:
$$
  \Gr_W(K)
  = \bigoplus_{p,q}(\Gr_W(K)\cap A^{p,q}).
$$

We thus deduce that
$$
  \Gr_F^p\Gr_{\overline{F}}^q\Gr_W^n(K)
  \hookrightarrow \Gr_F^p\Gr_{\overline{F}}^q\Gr_W^n(A);
$$
\oldpage{14}
the filtrations of $W$, $F$, and $\overline{F}$ on $K$ are thus opposite, and $K$ is a kernel of $f$ in $\scr{A}'$.
This, combined with the dual result, proves (ii).

If $f$ is an arrow of $\scr{A}'$, then the canonical morphism from $\Coim(f)$ to $\Im(f)$ is an isomorphism in $\scr{A}$;
by (iii), it is also an isomorphism in $\scr{A}'$, which is thus abelian.

The "forget the filtrations" functor is exact by (ii).
The exactness of the other functors in (iv) follows immediately from (ii), (iii), and [(1.1.11), (i) or (ii)](#proposition-1.1.11).
:::

::: {.rmenv #chunk-1.2.13 title="1.2.13" latex="{1.2.13}"}
Let $A$ be an object of $\scr{A}$ endowed with a finite *increasing* filtration $W_\bullet$, and two finite decreasing filtrations $F$ and $\overline{F}$.
The construction [(1.1.3)](#chunk-1.1.3) associates to $W_\bullet$ a decreasing filtration $W^\bullet$.
We say that the filtrations $W_\bullet$, $F$, and $\overline{F}$ are *opposite* if the filtrations $W^\bullet$, $F$, and $\overline{F}$ are, i.e. if, for all $n$, the filtrations induced by $F$ and $\overline{F}$ on
$$
  \Gr_n^W(A)
  = W_n(A)/W_{n-1}(A)
$$
are $n$-opposite.

Theorem [(1.2.10)](#theorem-1.2.10) translates trivially to this variation.
:::


## The two filtrations lemma {#section-1.3}

::: {.rmenv #chunk-1.3.1 title="1.3.1" latex="{1.3.1}"}
Let $K$ be a differential complex of objects of $\scr{A}$, endowed with a filtration $F$.
The filtration is said to be *biregular* if it induces a finite filtration on each component of $K$.

We recall the definition of the terms $E_r^{pq}(K,F)$, or simply $E_r^{pq}$, of the spectral sequence defined by $F$.
We set
$$
  Z_r^{pq}
  = \Ker(d\colon F^p(K^{p+q})\to F^{p+q+1}/F^{p+r}(K^{p+q+1}))
$$
and dually we define $B_r^{pq}$ by the formula
$$
  K^{p+q}/B_r^{pq}
  = \Coker(d\colon F^{p-r+1}(K^{p+q+1})\to K^{p+q}/F^{p+1}(K^{p+q})).
$$
These formulas still make sense for $r=\infty$.

We note that the use here of the notation $B_r^{pq}$ is different to that of Godement [@15].

We have, by definition:
$$
  E_r^{pq}
  = \Im(Z_r^{pq}\to K^{p+q}/B_r^{pq})
\tag{1.3.1.1}
$$
$$
  = Z_r^{pq}/(B_r^{pq}\cap Z_r^{pq})
\tag{1.3.1.2}
$$
$$
  = \Ker(K^{p+q}/B_r^{pq}\to K^{p+q}/(Z_r^{pq}+B_r^{pq})).
\tag{1.3.1.3}
$$
We can thus write
$$
  \begin{aligned}
    B_r^{p\bullet}\cap Z_r^{p\bullet}
    &\coloneqq (dF^{p-r+1}+F^{p+1}) \cap (d^{-1}F^{p+r}\cap F^p)
  \\&= (dF^{p-r+1}\cap F^p) + (F^{p+1}\cap d^{-1}F^{p+r})
  \end{aligned}
\tag{1.3.1.4}
$$
since $dF^{p-r+1}\subset d^{-1}F^{p+r}$ and $F^{p+1}\subset F^p$.

\oldpage{15}
For $r<\infty$, the $E_r$ form a complex graded by the degree $p-r(p+q)$, and $E_{r+1}$ can be expressed as the cohomology of this complex:
$$
  E_{r+1}^{pq}
  = \HH(E_r^{p-r,q+r-1} \xrightarrow{d_r} E_r^{pq} \xrightarrow{d_r} E_r^{p+r,q-r+1}).
\tag{1.3.1.5}
$$

For $r=0$, we have
$$
  E_0^{\bullet\bullet}
  = \Gr_F^\bullet(K^\bullet).
\tag{1.3.1.6}
$$
:::

::: {.itenv #proposition-1.3.2 title="Proposition 1.3.2" latex="{Proposition 1.3.2}"}
Let $K$ be a complex endowed with a biregular filtration $F$.
The following conditions are equivalent:

i. The spectral sequence defined by $F$ degenerates ($E_1=E_\infty$).
ii. The morphisms $d\colon K^i\to K^{i+1}$ are strictly compatible with the filtrations.
:::

::: {.proof}
We will prove this in the case where $\scr{A}$ is a category of modules.
For fixed $p$ and $q$, the hypothesis that the arrows $d_r$ with domains $E_r^{pq}$ be zero for $r\geq1$ implies that, if $x\in F^p(K^{p+q})$ satisfies $dx\in F^{p+1}(K^{p+q+1})$, then there exists $y\in K^{p+q}$ such that $dy=0$ and such that $x$ and $y$ have the same image in $E_1^{pq}$.
Modifying $y$ by a boundary, and setting $z=x-y$, we then have
$$
  \forall x\in F^p(K^{p+q})
  \left[
    dx\in F^{p+1}(K^{p+q+1})
    \implies \exists z\text{ s.t. } z\in F^{p+1}(K^{p+q}) \text{ and } dz=dx
  \right]
$$
or, in other words,
$$
  F^{p+1}(K^{p+q+1}) \cap dF^p(K^{p+q})
  = dF^{p+1}(K^{p+q}).
\tag{1}
$$

If this condition is satisfied for arbitrary $p$ and $q$, then by induction on $r$ we have
$$
  F^{p+r} \cap dF^p
  = dF^{p+r}
$$
which, for large $p+r$, can be written as
$$
  F^p \cap dK
  = dF^p.
\tag{2}
$$

Claim (2) trivially implies (1), and is equivalent to (ii), which proves the proposition.
:::

::: {.rmenv #chunk-1.3.3 title="1.3.3" latex="{1.3.3}"}
If $(K,F)$ is a filtered complex, we denote by $\Dec(K)$ the complex $K$ endowed with the *shifted filtration*
$$
  \Dec(F)^p K^n
  = Z_1^{p+n,-p}.
$$

This filtration is compatible with the differentials:
$$
  \begin{aligned}
    dZ_1^{p+n,-p}
    &\subset F^{p+n+1}(K^{n+1}) \cap \Ker(d)
  \\&\subset Z_\infty^{p+n+1,-p}
  \\&\subset Z_1^{p+n+1,-p}.
  \end{aligned}
$$

Since
$$
  \begin{aligned}
    Z_1^{p+1+n,-p-1}
    &\subset F^{p+1+n}(K^n)
  \\&\subset B_1^{p+n,-p}
  \\&\subset Z_1^{p+n,-p}
  \end{aligned}
\tag{1.3.3.1}
$$
the evident arrow from $Z_1^{p+n,-p}/Z_1^{p+1+n,-p-1}$ to $Z_1^{p+n,-p}/B_1^{p+n,-p}$ is a morphism
$$
  u\colon E_0^{p,n-p}(\Dec(K)) \to E_1^{p+n,-p}(K).
\tag{1.3.3.2}
$$
:::

::: {.itenv #proposition-1.3.4 title="Proposition 1.3.4" latex="{Proposition 1.3.4}"}
—

i. The morphisms (1.3.3.2) form a morphism of graded complexes from $E_0(\Dec(K))$ to $E_1(K)$.
ii. This morphism induces an isomorphism on cohomology.
iii. It induces step by step (via (1.3.1.5)) isomorphisms of graded complexes $E_r(\Dec(K))\simto E_{r+1}(K)$ (for $r\geq1$).
:::

::: {.proof}
\oldpage{16}
Let $F'$ be the filtration on $K$ defined by
$$
  {F'}^p(K^n)
  = \Dec(F)^{p-n}(K^n)
  = Z_1^{p,n-p}.
$$
We trivially have isomorphisms
$$
  E_r^{p,n-p}(\Dec(K))
  = E_{r+1}^{p+n,-p}(K,F')
\tag{1.3.4.1}
$$
that are compatible with the $d_r$ and with (1.3.1.5).
The map $u$ comes from (1.3.4.1) and from the identity map
$$
  (K,F') \to (K,F).
$$
This proves (i), and it remains to show that, for $r\geq2$,
$$
  E_r^{pq}(K,F')
  \simto E_r^{pq}(K,F).
$$
We have
$$
  \begin{aligned}
    Z_r^{pq}(K,F')
    &= Z_r^{pq}(K,F)
    \qquad\text{(for }r\geq1\text{)}
  \\Z_r^{pq}(K,F') \cap B_r^{pq}(K,F')
    &= Z_r^{pq}(K,F) \cap B_r^{pq}(K,F)
    \qquad\text{(for }r\geq2\text{)}
  \end{aligned}
$$
and we can then apply (1.3.1.2).
:::

::: {.rmenv #chunk-1.3.5 title="1.3.5" latex="{1.3.5}"}
The construction [(1.3.3)](#chunk-1.3.3) is not self-dual.
The dual construction consists of defining
$$
  \Dec^\bullet(F)^pK^n
  = B_1^{p+n-1,-p+1}.
$$
We then have morphisms
$$
  E_0^{p,n-p}(\Dec(K))
  \to E_1^{p+n,p}(K)
  \to E_0^{p,n-p}(\Dec^\bullet(K))
$$
and, for $r\geq1$, isomorphisms
$$
  E_r^{p,n-p}(\Dec(K))
  \simto E_{r+1}^{p+n,p}(K)
  \simto E_{r}^{p,n-p}(\Dec^\bullet(K)).
$$
:::

Recall that a morphism of complexes is said to be a *quasi-isomorphism* if it induces an isomorphism on cohomology.

::: {.rmenv #definition-1.3.6 title="Definition 1.3.6" latex="{Definition 1.3.6}"}
—

i. A morphism $f\colon(K,F)\to(K',F')$ of filtered complexes with biregular filtrations is a *filtered quasi-isomorphism* if $\Gr_F(f)$ is a quasi-isomorphism, i.e. if the $E_1^{pq}(f)$ are isomorphisms.
ii. A morphism $f\colon(K,F,W)\to(K,F',W')$ of biregular bifiltered complexes is a *bifiltered quasi-isomorphism* if $\Gr_F\Gr_W(f)$ is a quasi-isomorphism.
:::

::: {.rmenv #chunk-1.3.7 title="1.3.7" latex="{1.3.7}"}
Let $K$ be a differential complex of objects of $\scr{A}$, endowed with two filtrations $F$ and $W$.
Let $E_r^{pq}$ be the spectral sequence defined by $W$.
The filtration $F$ induces on $E_r^{pq}$ various filtrations, which we will compare.
:::

::: {.rmenv #chunk-1.3.8 title="1.3.8" latex="{1.3.8}"}
Equation (1.3.1.2) identifies $E_r^{pq}$ with a quotient of a sub-object of $K^{p+q}$.
The $E_r^{pq}$ term is thusly given by endowing with a filtration $F_d$ induced by $F$, called the *first direct filtration*.
:::

::: {.rmenv #chunk-1.3.9 title="1.3.9" latex="{1.3.9}"}
Dually, Equation (1.3.1.3) identifies $E_r^{pq}$ with a sub-object of a quotient of $K^{p+q}$, whence a new filtration $F_{d^*}$ induced by $F$, called the *second direct filtration*.
:::

::: {.itenv #lemma-1.3.10 title="Lemma 1.3.10" latex="{Lemma 1.3.10}"}
\oldpage{17}
On $E_0$ and $E_1$, we have $F_d=F_{d^*}$.
:::

::: {.proof}
For $r=0,1$, we have $B_r^{pq}\subset Z_r^{pq}$, and we apply (1.1.9).
:::

::: {.rmenv #chunk-1.3.11 title="1.3.11" latex="{1.3.11}"}
Equation (1.3.1.5) identifies $E_{r+1}^{pq}$ with a quotient of a sub-object of $E_r^{pq}$.
We define the *recurrent filtration* $F_r$ on the $E_r^{pq}$ by the conditions

i. On $E_0^{pq}$, $F_r=F_d=F_{d^*}$.
ii. On $E_{r+1}^{pq}$, the recurrent filtration is that induced by the recurrent filtration of $E_r^{pq}$.
:::

::: {.rmenv #chunk-1.3.12 title="1.3.12" latex="{1.3.12}"}
Definitions [(1.3.8)](#chunk-1.3.8) and [(1.3.9)](#chunk-1.3.9) still make sense for $r=\infty$.
If the filtration on $K$ is biregular, then the direct filtrations on $E_\infty^{pq}$ coincide with those on $E_r^{pq}=E_\infty^{pq}$ for large enough $r$, and we define the recurrent filtration on $E_\infty^{pq}$ as agreeing with that on $E_r^{pq}$ for large enough $r$.

The filtrations $F$ and $W$ each induce a filtration on $H^\bullet(K)$, and $E_\infty^{\bullet\bullet}=\Gr_W^\bullet(\HH^\bullet(K))$.
The filtration $F$ on $\HH^\bullet(K)$ then induces on $E_\infty^{pq}$ a new filtration.
:::

::: {.itenv #proposition-1.3.13 title="Proposition 1.3.13" latex="{Proposition 1.3.13}"}
—

i. For the first direct filtration, the morphisms $d_r$ are compatible with the filtrations.
  If $E_{r+1}^{pq}$ is considered as a quotient of a sub-object of $E_r^{pq}$, then the first direct filtration on $E_{r+1}^{pq}$ is finer than the filtration $F'$ induced by the first direct filtration on $E_r^{pq}$Y we have $F_d(E_{r+1}^{pq})\subset F'(E_{r+1}^{pq})$.
ii. Dually, the morphisms $d_r$ are compatible with the second direct filtration, and the second direct filtration on $E_{r+1}^{pq}$ is less fine than the filtration induced by that of $E_r^{pq}$.
iii. $F_d(E_r^{pq})\subset F_r(E_r^{pq})\subset F_{d^*}(E_r^{pq})$.
iv. On $E_\infty^{pq}$, the filtration induced by the filtration $F$ of $\HH^\bullet(K)$ [(1.3.12)](#chunk-1.3.12) is finer than the first direct filtration and less fine than the second.
:::

::: {.proof}
Claim (i) is evident, (ii) is its dual, and (iii) follows by induction.
The first claim of (iv) is easy to verify, and the second is its dual.
:::

::: {.rmenv #chunk-1.3.14 title="1.3.14" latex="{1.3.14}"}
We denote by $\Dec(K)$ (resp. $\Dec^\bullet(K)$) the complex $K$ endowed with the filtrations $\Dec(W)$ and $F$ (resp. $\Dec^\bullet(W)$ and $F$).

It is clear by (1.3.4.1) that the isomorphism [(1.3.4)](#proposition-1.3.4) sends the first direct filtration on $E_r(\Dec(K))$ to the second direct filtration on $E_{r+1}(K)$ (for $r\geq1$).
The dual isomorphism [(1.3.5)](#chunk-1.3.5) sends the second direct filtration on $E_r(\Dec^\bullet(K))$ to the second direct filtration on $E_{r+1}(K)$.
:::

::: {.itenv #lemma-1.3.15 title="Lemma 1.3.15" latex="{Lemma 1.3.15}"}
If the filtration $F$ is biregular, and if, on the $\Gr_W^p(K)$, the morphisms $d$ are strictly compatible with the filtration induced by $F$, then

i. The morphism (1.3.3.2) of graded complexes filtered by $F$
  $$
    u\colon \Gr_{\Dec(W)}(K)
    \to E_1(K,W)
  $$
  is a filtered quasi-isomorphism.
ii. Dually, the morphism [(1.3.5)](#chunk-1.3.5)
  $$
    u\colon E_1(K,W)
    \to \Gr_{\Dec^\bullet(W)}(K)
  $$
  is a filtered quasi-isomorphism.
:::

::: {.proof}
\oldpage{18}
It suffices, by duality, to prove (i).
:::
