--- 
title: "What are motives used for?"
author: "Pierre Deligne"
date: "1994"
original: 'Deligne, P. "A quoi servent les motifs?". _Proc. Symp. in Pure Math._ **55** (1994), 143--161.'
bibliography: PSPM-55-1994-143.bib
nocite: '@*'
link-citations: true
csl: maths-translations.csl
reference-section-title: "Bibliography"
github-repo: "thosgood/translations"
favicon: "favicon.ico"
---

```{js, echo = FALSE}
$(document).ready(function(e) {gitbook.sidebar.toggle(false, false)});
```

```{r, child = '_translator-note.Rmd'}
```

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\newcommand{\pr}{\mathrm{pr}}
\newcommand{\ZZ}{\mathbb{Z}}
\newcommand{\QQ}{\mathbb{Q}}
\newcommand{\CC}{\mathbb{C}}
\newcommand{\RR}{\mathbb{R}}
\renewcommand{\AA}{\mathbb{A}}
\newcommand{\GG}{\mathbb{G}}
\newcommand{\PP}{\mathbb{P}}
\newcommand{\FF}{\mathbb{F}}
\newcommand{\mot}{\mathrm{mot}}
\newcommand{\ab}{\mathrm{ab}}
\newcommand{\abs}{\mathrm{abs}}
\newcommand{\un}{\mathrm{un}}
\newcommand{\GL}{\mathrm{GL}}

\newcommand{\Pic}{\operatorname{Pic}}
\newcommand{\Hom}{\operatorname{Hom}}
\newcommand{\End}{\operatorname{End}}
\newcommand{\Lie}{\operatorname{Lie}}
\newcommand{\Ext}{\operatorname{Ext}}
\newcommand{\real}{\operatorname{real}}
\newcommand{\Gr}{\operatorname{Gr}}
\newcommand{\Aut}{\operatorname{Aut}}
\newcommand{\Rep}{\operatorname{Rep}}
\newcommand{\ind}{\operatorname{ind}}
\newcommand{\Spec}{\operatorname{Spec}}
\newcommand{\Ker}{\operatorname{Ker}}
\newcommand{\Gal}{\operatorname{Gal}}
\newcommand{\cl}{\operatorname{cl}}
\newcommand{\ch}{\operatorname{ch}}
\newcommand{\Ch}{\operatorname{Ch}}

<!-- Content -->

\oldpage{143}
The first of the "standard conjectures" (Grothendieck [@19], Kleiman [@20]), the Lefschetz-style one, says that certain cohomology classes are algebraic.
Anyway, if motives are the "direct factors" of algebraic varieties $X$ defined by projectors (algebraic cycles on $X\times X$), then their definition is only reasonable if we have enough algebraic cycles.
On this problem --- the construction of interesting algebraic cycles --- progress has been sparse.

Grothendieck tried to establish a catalogue of projective constructions of cycles, cf. [@19, p. 197].
For those for which we have calculated their cohomology class, the class can be expressed in terms of Chern classes of obvious vector bundles.
Even though I do not know of any counterexamples, it seems unlikely to me that the ring of cycle classes on $X\times X$ generated by the diagonal, the divisors, and the inverse images of the Chern classes of $X$ by the $\pr_i$ (for $i=1,2$) will always contain the cycles required by the first standard conjecture (for example, the Künneth components of the diagonal).

Instead of trying to construct cycles, we can try to construct vector bundles, and then take their Chern classes.
It is, in fact, like this that K. Kodaira and D.C. Spencer (1953) prove the Hodge conjecture for divisors (a theorem of Lefschetz), with the group $\Pic(X)=H^1(X,\scr{O}^*)$ being accessible, over $\CC$, by the exponential exact sequence
$$
  0 \to 2\pi i\ZZ \to \scr{O} \to \scr{O}^* \to 0.
$$
Similarly, on an abelian variety, it is easier to write the functional equation of the $\Theta$ functions (a cocycle for a line bundle) than to define a $\Theta$ function, itself giving the divisor $\Theta=0$.

\oldpage{144}
Unfortunately, in higher rank, we do not know how to construct vector bundles whose Chern classes are interesting any more than we know how to construct interesting cycles.

Over $\CC$, the Hodge conjecture would give the desired cycles.
Two difficulties in proving this conjecture have been found.
The first: Atiyah and Hirzebruch have shown that it could only be true rationally (cf. Atiyah-Hirzebruch [@1]).

The second: from the point of view of Hodge theory, the class of a cycle $Z$ of codimension $d$ on a smooth projective $X$ lives naturally, not in $H_\ZZ^{d,d}\coloneqq H^{d,d}\cap H_\ZZ$, but in an extension $E_d$ of this group by the intermediate Jacobian:
$$
  J^d(X) \coloneqq H^{2d-1}(X,\CC)/F^d + H^{2d-1}(X,\ZZ),
$$
where $F^d$ denotes the $d$-th term of the Hodge filtration of $H^{2d-1}(X,\CC)$.
In the category of mixed Hodge structures, this is, respectively, $\Hom(\ZZ(d),H^{2d}(X))$ and $\Ext^1(\ZZ(d),H^{2d-1}(X))$.
The Hodge conjecture says that the group of cycle classes is sent to a subgroup of finite index of the quotient $H_\ZZ^{d,d}$.
However, we have no idea what should be the image in $E_d$.
Furthermore, the aesthetic awkwardness that causes this ignorance renders the methods of P.A. Griffiths, to prove the Hodge conjecture by induction on the dimension of the variety $X$, generally inapplicable.
This method is inspired by that which Lefschetz [@24] uses for surfaces.
The idea is that, if $(H_t)_{t\in\PP^1}$ is a pencil of hyperplane sections, then constructing the cycle $Z$ on $X$ reduces to constructing the cycles $Z_i=Z\cap H_t$.
In good cases:

a. the cohomology class $c\in H_\ZZ^{d,d}(X)$ that we wish to be that of a cycle $Z$ restricts to zero on the $H_t$ ;
b. if $Z$ exists, then its cohomology class $c$ determines the class of the $Z_t$ in the intermediate Jacobians $J^d(H_t)$ ; and
c. the construction of $Z$ reduces to constructing the cycles $Z_t$ of classes defining a given section of the family of the $J^d(H_t)$.

We can thus conclude that every element of $J^d(H_t)$ is the class of a cycle of codimension $d$ that is cohomologous to zero.
Using this method, Zucker [@32] proves the Hodge conjecture for cubic hypersurfaces in $\PP^5$.
Note, however, that, if every element of $J^d(H_t)$ is the class of a cycle that is cohomologous to zero, then $H^{2d-1}(H_t)$ is of Hodge type $\{(d,d-1),(d-1,d)\}$ (see [§1.6](#section-1.6)), and the converse is a consequence of the Hodge conjecture applied to the product of $H_t$ with a suitable abelian variety.
Furthermore, this surjectivity implies the existence of a curve $C_t$ and an algebraic cycle $W_t$ on $H_t\times C_t$ that sends $H^1(C_t)$ to $H^{2d-1}(H_t)$.
We can then expect that $H^{2d}(X)$ is controlled by the $H^2$ of the surface fibred over $\PP^1$ with fibres given by the $C_t$, and, for an $H^2$, we can use the Hodge conjecture anyway.

\oldpage{145}
The aim of these notes is to show that, despite this lack of progress on the problem of constructing cycles, the philosophy of motives is a powerful tool.

I thank S. Bloch for his comments on a first version of these notes.


# Motives {#section-1}

According to what we can and want to do, we have various definitions of motives available to us --- or even none.
We need to distinguish pure motives, typically given by the cohomology of non-singular projective varieties, and mixed motives, where open and singular varieties are allowed.
The notion of a motive over $S$ (a family of motives parameterised by $S$) poses yet more problems.


## 1.1 {.unnumbered #section-1.1}

For a field $k$, we always want the category of motives over $k$ to be a $\QQ$-linear abelian category $\scr{M}(k)$ with finite-dimensional $\Hom$ groups.
In the pure case, we want it to be semi-simple and graded (by weights).
In the mixed case, every motive $M$ should admit a finite increasing filtration $W$, with $\Gr_n^W(M)$ pure of weight $n$.
Some other essential structures are the following:

a. Every algebraic variety $X$ on $k$ should have motivic cohomology groups $H_\mot^i(X)$, which are objects of $\scr{M}(k)$.
    In the pure case, we restrict to non-singular projective varieties $X$, and $H_\mot^i(X)$ should then be a pure motive of weight $i$.
b. For each of the usual cohomology theories $H$, we should have a "realisation" functor $\real$, and isomorphisms
    $$
      H^i(X) = \real H_\mot^i(X).
    $$
c. There should be a tensor product $\otimes$, with which the realisation functors are compatible.


## 1.2 {.unnumbered #section-1.2}

The tensor product structure described above allows us to apply the theory of Tannakian categories, invented by Grothendieck to study the formalism of motives.
References: Saavedra [@28], Deligne--Milne [@12], Deligne [@15].

For $k$ of characteristic $0$, this theory says that the category of motives over $k$, with its tensor product, should be equivalent to the category of linear representations of a scheme $G$ of affine groups over $\QQ$.
Note that any two groups $G_1$ and $G_2$ that are inner forms of one another have the same category of representations.
The *motivic Galois group* $G$ is thus not uniquely determined by $\scr{M}(k)$.
The theory tells us that a choice of $G$ and of an equivalence $\scr{M}(k)\simeq\Rep(G)$ is equivalent to the choice of an exact functor to $\QQ$-vector spaces that is compatible with the tensor product of $\scr{M}(k)$: a *fibre functor* $\omega$.
To such an $\omega$ corresponds $G\coloneqq \underline{\Aut}^\otimes(\omega)$, the group scheme of $\otimes$-automorphisms of $\omega$.
We can think of $\omega$, or, rather, $\omega\circ H_\mot$, as a cohomology theory with values in $\QQ$-vector spaces.

\oldpage{146}
If we have an embedding of $k$ into $\CC$, then a possible cohomology theory is: "singular cohomology of the topological space of complex points".
For $k=\QQ$, another possible choice is "de Rham cohomology".

In characteristic $p$, an example by Serre shows that there cannot be any reasonable cohomology theory with values in $\QQ$-vector spaces: if $E$ is a supersingular elliptic curve, then the algebra $\End(E)\otimes\QQ$ is a quaternion algebra, and thus has no linear representation of dimension $2$ over $\QQ$.
From the existence of a cohomology theory with values in vector spaces over an extension of $\QQ$ it follows, however, that $\scr{M}(k)$ should be the category of representations of a suitable gerbe.

The Tannakian theory is a *linear* analogue of a *set-theoretic* theory, namely that of the profinite $\pi_1$, also due to Grothendieck ([@SGA1]).
The analogy is as follows: if $\scr{R}$ is the category of finite étale covers of a connected scheme $S$ (resp. a Tannakian category over $K$), and $\omega$ is a fibre functor, with values in finite sets (resp. in finite-dimensional $K$-vector spaces), then $\scr{R}$ is naturally equivalent to the category of finite $G$-sets (resp. of representations of $G$), where $G$ is the profinite group $\Aut(\omega)$ (resp. the affine group scheme $\underline{\Aut}^\otimes(\omega)$).
From here we get the terminology "motivic Galois group", with the $\pi_1$ theory, in the case of spectra of fields, becoming the Galois version.


## 1.3 {.unnumbered #section-1.3}

In general, the motivic Galois group $G$ is enormous.
For example, except for when $k$ is algebraic over a finite field, we expect $G$ to admit $\mathrm{PGL}(2)^{\operatorname{card}(k)}$ as a quotient.
It "doesn't know" that motives $M_t$ can form a family that depends algebraically on $t$.

Even though $G$ is enormous, its existence facilitates the handling of "motivic" objects.

::: {.rmenv title="Example" latex="{Example}"}
The category $\ind\scr{M}(k)$ of ind-objects of the category $\scr{M}(k)$ of motives over $k$ inherits the tensor product from $\scr{M}(k)$.
This allows us to define a commutative Hopf algebra in $\ind\scr{M}(k)$ as being an object $H$ endowed with a product $H\otimes H\to H$ and coproduct $H\to H\otimes H$, as well as a unit $1\to H$, counit $H\to 1$, and antipode $H\to H$, satisfying suitable axioms.
We define the category of *motivic affine group schemes* as being the opposite of the category of commutative Hopf algebras in $\ind\scr{M}(k)$.
If $\omega$ is a fibre functor, with values in $\QQ$-vector spaces, from the motivic Galois group $G:=\underline{\Aut}^\otimes(\omega)$, then the functor $\omega$ induces an equivalence between $\ind\scr{M}(k)$ and the category of linear representations --- not necessarily of finite dimension --- of $G$, and $H\mapsto\Spec\omega(H)$ is an equivalence between the category of motivic affine group schemes and the category of affine group schemes over $\QQ$ endowed with an action of $G$.
:::

Here are three examples of such objects.


### 1.3.1 {.unnumbered #section-1.3.1}

The motivic version of $\pi_1(X,x)$ made unipotent, cf. Deligne [@14], especially §5, §7, and §§10--13.


### 1.3.2 {.unnumbered #section-1.3.2}

\oldpage{147}
The motivic Galois group: there exists a motivic version $G_\mot$ such that, for every fibre functor $\omega$, the corresponding motivic Galois group is given by the application of $\omega$ to $G_\mot$.
This gives a construction that works in any Tannakian category, cf. Deligne [@15, Section 8].
In the analogy with the profinite-$\pi_1$ theory, its analogue is the following: for varying $x$, the $\pi_1(X,x)$ form a local system on $X$, or, more precisely, an group object in the category of pro-objects of the category of étale covers of $X$.
The $\pi_1$ at $x$ is obtained by taking its fibre at $x$.


### 1.3.3 {.unnumbered #section-1.3.3}

Let $\scr{M}$ be a full subcategory of the category of mixed motives over $k$, stable under $\otimes$, taking duals, and sub-quotients, and let $\scr{M}_\mathrm{pur}$ be the full subcategory of direct sums of pure motives in $\scr{M}$.
We have an exact functor that is compatible with the tensor product, given by $M\mapsto\Gr^W(M)$, from $\scr{M}$ to $\scr{M}_\mathrm{pur}$.
In $\scr{M}_\mathrm{pur}$ there exists a motivic pro-unipotent group scheme $U$, acting functorially on $\Gr^W(M)$ for $M$ in $\scr{M}$, and such that $M\mapsto\Gr^W(M)$ is an equivalence between $\scr{M}$ and the category of representations (in $\scr{M}_\mathrm{pur}$) of $U$.
This is a consequence of Deligne [@§5, Section 8.17].

We can similarly define and work with motivic schemes, motivic torsors, ... .


## 1.4 {.unnumbered #section-1.4}

The abelianisation $G^\ab$ of the motivic Galois group $G$ is of a more reasonable size.
It is independent of the chosen realisation functor (and of its existence).
Conjecturally, if $k_1\subset k_2$ are algebraically closed fields, then $G^\ab$ is the same for $k_1$ and $k_2$, and the corresponding subcategory of motives is generated by the $H_\mot^1$ of CM-type abelian varieties.

In characteristic $0$, if we take "motives" to mean absolute Hodge cycles, and we restrict to the subcategory generated by the $H^1$ of abelian varieties, then we know how to calculate $G^\ab$.
For $\scr{M}(\QQ)$, we even know how to calculate the quotient of $G$ by the derived group of $\Ker(G\to\Gal(\overline{\QQ}/\QQ))$.
See Deligne [@13] or the talk by Schappacher at this conference.

For $\scr{M}(\FF_q)$, every motive should be a direct sum of pure motives, and the motivic Galois group should contain an element $F$, the Frobenius, whose powers are dense in $G$.
In particular, $G$ should be commutative.
The conjectural calculation of $\scr{M}(\FF_q)$ was made by Grothendieck (unpublished).
See Langlands--Rapoport [@23] and the talk by Milne at this conference.


## 1.5 {.unnumbered #section-1.5}

One source of [§1.1](#section-1.1) (a) and (b) is the following example.
A smooth projective curve $X$ defines its Jacobian via $J(X)=\Pic^0(X)$.
Abelian varieties, up to isogeny, over $k$ form a semi-simple abelian category, with the $\Hom(A,B)$ being finite-dimensional over $\QQ$, and, for every usual cohomology theory $H$, the dual $H_1(X)$ of $H^1(X)$ is given by applying a "realisation" functor to $J(X)$.
Note that $H_1(X)$ is also the Tate twist $H^1(X)(1)$ of $H^1(X)$.
For $\ell$-adic cohomology, $\real_\ell(A)$ is the Tate module $V_\ell(A)=T_\ell(A)\otimes\QQ_\ell$.
\oldpage{148}
For $k$ of characteristic $0$, and de Rham cohomology, $\real_{\mathrm{DR}}(A)$ is the Lie algebra given by the universal additive extension of $A$.

We thus wish to be able to identify abelian varieties with certain motives of weight $-1$.
For some applications (for example, the study of Shimura varieties), we would be content with even having a category of motives that contains abelian varieties and is stable under $\otimes$.
In characteristic $0$, the theory of absolute Hodge cycles gives us such a theory (Deligne--Brylinksi [@11], Deligne--Milne [@12], or the talk by Panschishkin at this conference).
If we do not restrict ourselves to pure motives, then another key example is that of smooth curves that are not necessarily complete.
More generally, we can consider a smooth projective curve $\overline{X}$, disjoint $S$ and $T$ in $\overline{X}$, and the cohomology $H^1(\overline{X}\setminus S,\operatorname{rel}T)$.
A *$1$-motive* $K^\bullet$ is a complex of group schemes concentrated in degrees $-1$ and $0$, such that, over the algebraic closure, $K^{-1}$ is a free $\ZZ$-module of finite type, and $K^0$ is an extension of an abelian variety by a torus.
Suppose, for simplicity, that $k$ is algebraically closed.
For every usual cohomology theory, the $H^1$ in question, or even its Tate twist $H^1(\overline{X}\setminus S,\operatorname{rel}T)(1)$, is then given by applying a realisation functor to the following $1$-motive.

Let $J_T(\overline{X})$ be the generalised Jacobian classifying invertible sheaves of degree $0$ over $\overline{X}$ that are trivialised over $T$.
This is an extension of the abelian variety $\Pic^0(\overline{X})$ by the character group torus $\Ker(\ZZ^T\xrightarrow{\Sigma}\ZZ)$.
Each $s\in S$ defines an invertible sheaf $\scr{O}(s)$, trivialised over $T$ and of degree $1$, whence
$$
  \Ker(\ZZ^S\to\ZZ) \to J_T(\overline{X}).
\tag{1.5.1}
$$
This is the aforementioned $1$-motive.
See Deligne [@9, Section 10].

::: {.rmenv title="Remark" latex="{Remark}"}
For $S,T\neq\varnothing$, the $1$-motive in (1.5.1) also determines the category of invertible sheaves on $\overline{X}\setminus S$, trivialised over $T$: a point $x\in J_T(\overline{X})$ defines such an invertible sheaf $\scr{L}_x$, and an isomorphism from $\scr{L}_x$ to $\scr{L}_y$ which is the identity on $T$ is identified with $k\in\Ker(\ZZ^S\to\ZZ)$, with $y-x=\delta k$.
:::

Again, we wish to be able to identify $1$-motives with certain (mixed) motives.
For some applications (the study at infinity of Shimura varieties), we would be content with even having a category of motives that contains the $1$-motives and is stable under $\otimes$.
In characteristic $0$, we know how to do this (Brylinksi [@7]).


## 1.6 {.unnumbered #section-1.6}

Abelian varieties have spaces of modules, and these allow us to view certain quotients of symmetric Hermitian spaces by arithmetic groups in an algebraic way.
The case of motives is more complicated.
If $S$ is a scheme over $\CC$, and $M$ is a family of pure motives parameterised by $S$, then $M$ gives a variation of Hodge structures $M_h$ over $S(\CC)$, which is polarised if $M$ is, via Hodge realisation.
From this, we get a map $\varphi$ from $S(\CC)$ to the space $\mathscr{C}$ that classifies polarised Hodge structures with the same Hodge numbers as $M$.

The variation $M_h$ gives, in particular, a local system of complex vector spaces $M_\CC$ endowed with a Hodge filtration $F$ that varies continuously.
\oldpage{149}
The holomorphicity of $F$ and the "transversality" condition discovered by Griffiths [@17] (see also Griffiths [@18]) can be expressed as follows.
Let $T$ be the tangent bundle of $S$, where $S$ is thought of as a $C^\infty$ manifold.
The complex structure of $S$ endows $T$ with a complex structure.
Let $\varphi\colon T\otimes_\RR\CC\to T$ be the $\CC$-linear extension of the identity on $T$, and $T''\subset T\otimes_\RR\CC$ be the kernel of $\varphi$.
We define a Hodge filtration on $T\otimes\CC$ by
$$
  F^{-1}=T\otimes\CC,
  \quad
  F^0=T'',
  \quad
  F^1=0.
$$
If $t$ and $m$ are $C^\infty$ sections of $T\otimes\CC$ and $M_\CC$ (respectively), then the flat structure of $M_\CC$ allows us to define $\nabla_t m$.
Then the condition is that $(t,m)\mapsto\nabla_t m$ be compatible with the Hodge filtrations:

- $t$ in $T''$, $m$ in $F^i$, $\nabla_t m$ in $F^i$: holomorphicity;
- $t$ in $T$, $m$ in $F^i$, $\nabla_t m$ in $F^{i-1}$: transversality.

There exists a complex structure on the classifying space $\mathscr{C}$, and a distribution $\tau\subset T$ such that the holomorphicity and transversality conditions become holomorphicity of the classifying map $\varphi\colon S(\CC)\to\mathscr{C}$ and tangency of $\varphi(S)$ to $\tau$.

The distribution $\tau$ is, in general, not integrable.
The set of points of $\mathscr{C}$ that corresponds to a direct factor some $H^i(X)$, where $X$ is non-singular and projective, is the countable union of the subvarieties that are tangent to $\tau$.
When $\tau$ is not equal to the entire tangent bundle, then we have no description of it, even conjecturally.

An analogous argument, also due to Griffiths, explains why the points of the intermediate Jacobian $J^d(X)$ can not all be algebraic cycle classes, except for when $H^{2d-1}(X)$ is of type $\{(d-1,d)\},(d,d-1)$.
Let $f\colon X\to S$ be a family of non-singular projective varieties.
Set $X_s=f^{-1}(s)$.
The intermediate Jacobians
$$
  J^d(X_s) = H^{2d-1}(X_s,\CC)/H^{2d-1}(X_s,\ZZ) + F^d
$$
form a holomorphic bundle $J^d$ of complex toruses, and the transversality axiom ensures that the Gauss--Manin connection (expressing that the $H^{2d-1}(X_s,\CC)$ form a local system) passes to the quotient to define a differential operator $D$, defined on the sheaf of sections of $J^d$ and with values in the sheaf of $1$-forms with values in the holomorphic bundle of the $H^{2d-1}(X_s,\CC)/F^{d-1}$.
An algebraic family $(Z_s)_{s\in S}$ of algebraic cycles that are cohomologous to zero on the $X_s$ defines a holomorphic section $z$ of $J^d$.
The result of Griffiths is that $Dz=0$.
The section $z$ defines a holomorphic family of mixed Hodge structures that is an extension of $\ZZ$ (of type $(0,0)$) by $H^{2d-1}(X)(d)$, and $Dz=0$ is equivalent to saying that this family satisfies the transversality axiom.


## 1.7 {.unnumbered #section-1.7}

When the distribution $\tau$ is the entire tangent bundle, $\mathscr{C}$ is an arithmetic quotient of a symmetric Hermitian domain.
This description of complex points of Shimura varieties as modules of Hodge structures suggests that these varieties are spaces of modules of motives.

\oldpage{150}
Let $S$ be the algebraic $\RR$-group $\CC^*$, i.e. $S=R_{\CC/\RR}(\GG_m)$.
Giving an action of $S$ on the real vector space $V$ is equivalent to giving a decomposition of $V\otimes\CC$ as a direct sum of $V^{p,q}$ with $\overline{V^{p,q}}=V^{q,p}$, with $z\in S(\RR)=\CC^*$ acting on $V^{p,q}$ via multiplication by $z^{-p}\overline{z}^{-q}$.
We define $w\colon\GG_m\to S$ (resp. $\mu\colon\GG_m\to S$, defined over $\CC$) by the condition that, for all $V$, $w(\lambda)$ (resp. $\mu(\lambda)$) acts on $V^{p,q}$ via multiplication by $\lambda^{p+q}$ (resp. $\lambda^p$).

The data defining a Shimura variety $\mathrm{Sh}_K(G,X)$ consists of a reductive group $G$ over $\QQ$, a $G(\RR)$-conjugation class of morphisms $h\colon S\to G_\RR$, with $w_X:= h\circ w$ central (and thus independent of $h$), and a compact open subgroup $K$ of $G(\AA^f)$.
We consider the case where $w_X$ is defined over $\QQ$, and where $\operatorname{int}h(i)$ is a Cartan involution of the quotient $G/w_X(\GG_m)$.
The *dual field* $E(G,X)$ is the field of definition of the conjugacy class of $h\mu$ (for arbitrary $h$ in $X$).
This is a subfield of $\CC$.
The Shimura variety is defined over $E(G,X)$, with complex points $K\setminus X\times G(\AA^f)/G(\QQ)$.
Its construction in the general case is due to Borovoi [@6].

A point of the Shimura variety over a field $\FF$ containing $E(G,X)$ should correspond to

a. an exact $\otimes$-functor $x$ from the category $\Rep(G)$ of representations of $G$ to the category of pure motives over $\FF$ ; and
b. an integer structure.
    In terms of finite adelic realisations (the restriction of the product of $\ell$-adic realisations), we can describe this as an isomorphism of $\otimes$-functors
    $$
      x(V)_{\AA^f} \xrightarrow{\sim} V\otimes\AA^f,
    $$
    given up to composition with an element of $K$.

The following condition should be satisfied.
For simplicity, we suppose that $\FF$ can be embedded in $\CC$.

c. Let $\iota$ be an embedding of $\FF$ into $\CC$, extending the identity embedding of $E(G,X)$ into $\CC$.
    There should exist $h\in X$ such that the following $\otimes$-functors from $\Rep(G)$ to Hodge structures are isomorphic:

    1. $(V,\rho)\mapsto V$, endowed with the Hodge structure defined by $\rho\circ h$;
    2. $(V,\rho)\mapsto$ the Hodge realisation of $x(V)$, after extending the base field to $\CC$ by $\iota$.

The fact that condition (c) is independent of the chosen complex embedding $\iota$ --- assumed to be an extension of the inclusion of $E(G,X)$ into $\CC$ --- is not obvious.
Sometimes, however, it follows from (b) and more algebraic conditions (d) and (e), consequences of (c), that follow.

d. The de Rham realisation defines a fibre functor $V\mapsto x(V)_{\mathrm{DR}}$ on $\Rep(G)$ that corresponds to a $G$-torsor $P$ over $F$.
    \oldpage{151}
    The Hodge filtration of the $X(V)_{\mathrm{DR}}$ is exact and compatible with the tensor product,
    and thus comes from a parabolic $Q$ of $G^P$ and from $\mu_{\mathrm{DR}}\colon\GG_m\to Z(Q/\mathscr{R}_uQ)$, where $Z$ denotes the centre, that lifts to a conjugation class of morphisms from $\GG_m$ to $Q$, Saavedra [@28, IV, 2.4, p. 229].
    Since $\FF$ contains $E(G,X)$, it makes sense to ask for the conjugation class corresponding to maps from $\GG_m$ to $G$ to coincide with that of $h\circ\mu$ (for $h\in X$).
    Condition (c) implies this.
    This explains the appearance of the dual field.
e. For a representation $(V,\rho)$ of weight $0$: $\rho\circ w$ trivial and $V\otimes V\to\QQ$ a symmetric invariant bilinear form such that, on $V_\RR$, $B(v,h(i)w)$ is positive-definite and symmetric, we ask for $x(V)\otimes x(V)\to 1$ to be positive, for the desired polarisation (*loc. cit.* V, 2.4, p. 276) of the category of motives.


## 1.8 {.unnumbered #section-1.8}

This motivic interpretation of Shimura varieties has been a guide for how to elaborate the axioms that characterise them, as well as for the determination of their conjugates (Borovoi [@6]).

Let $p$ be a prime number such that $G_{\QQ_p}$ extends to a reductive group over $\ZZ_p$, and let $K$ be the product of $G(\ZZ_p)$ with a subgroup of the restriction of the product of the $G(\QQ_\ell)$, for $\ell\neq p$.
The dual field $E(G,X)$ is then unramified at $p$.
We hope that the Shimura variety has a natural reduction $\mod p$, and that we can try to paraphrase the conjectural motivic description above in order to conjecture the structure of the set of its points over a finite field of characteristic $p$.
There have been difficulties: how can we interpret (c) and the $p$-part of (b) to work together with (d)?
For progress in this direction, see Langlands--Rapoport [@23].


# Cohomology theories {#section-2}
