--- 
title: "Distribution of current in a conductive network. (Introduction to combinatorial analysis)"
author: "H. Weyl"
date: "1923"
original: 'Weyl, H. "Repartición de corriente en una red conductora. (Introducción al análisis combinatorio)". _Revista Matematica Hispano-Americana_ **5** (1923), 153–164.'
github-repo: "thosgood/translations"
favicon: "favicon.ico"
---

```{js, echo = FALSE}
$(document).ready(function(e) {gitbook.sidebar.toggle(false, false)});
```

```{r, child = '_translator-note.Rmd'}
```

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->



<!-- Content -->

The science of the continuous, _Analysis situs_, has a purely combinatorial part that can now, thanks most of all to the fundamental works of H. Poincaré^[_Analysis situs_, J. de l'École Politech, 1895. _Complément à l'Analysis situs_, Rend. Palermo, 1899. _Second complément à l'Analysis situs_, Proc. London Math. Soc., 1900. _Cinquième complément à l'Analysis situs_, Rend. Palermo, 1904.], be its own subject of study, and is amenable to a systemic and complete exposition.
It was this subject that occupied me in the 1918 lectures at the Federal Institute of Technology (ETH) Zurich.
Since then, works in the same vein have been published by O. Veblen^[The Cambridge Colloquium, 1916, part II. *Analysis situs*, American Math. Soc. New York, 1922.] and, limited to the 2-dimensional case, by Chuard^[Rend. Palermo, 1922.].
Extremely appropriate as an introduction to this subject is the (1-dimensional) problem of the distribution of current in an arbitrarily complicated conductive network, since it highlights the importance of the fundamental concepts that can then be extended to the higher-dimensional case.

The conductive network that we will consider consists of a finite number of homogeneous wires, which meet at a finite number of nodes.
The geometric picture will be called the *complex of segments*, the nodes will be called the *points* of the complex, and the various bits of wires between nodes will be called the *segments*.

More rigorously:

> *A complex of segments* consists of a finite number of "points", or elements of dimension zero, and a number of "segments", or elements of dimension one.
> Each segment connects two of the nodes, and this data constitutes the diagram of the complex.

Instead of an equation:
