--- 
title: "The work of Koszul"
author: "Henri Cartan"
date: "1948--49"
original: 'Cartan, H. "Les travaux de Koszul". _Séminaire Bourbaki_ **1** (1952), I: Talk no. 1, 7--12 [[PDF]](http://www.numdam.org/book-part/SB_1948-1951__1__7_0); II: Talk no. 8, 45--52 [[PDF]](http://www.numdam.org/book-part/SB_1948-1951__1__45_0); III: Talk no. 12, 71--74 [[PDF]](http://www.numdam.org/book-part/SB_1948-1951__1__71_0).'
github-repo: "thosgood/translations"
favicon: "favicon.ico"
---

```{js, echo = FALSE}
$(document).ready(function(e) {gitbook.sidebar.toggle(false, false)});
```

```{r, child = '_translator-note.Rmd'}
```

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\llp}{\mathbin{\llcorner}}
\providecommand{\lrp}{\mathbin{\lrcorner}}
\providecommand{\dd}{\mathrm{d}}
\providecommand{\RR}{\mathbb{R}}
\providecommand{\HH}{\operatorname{H}}
\providecommand{\tr}{\operatorname{tr}}

<!-- Content -->

# Part I (December 1948)

\oldpage{7}
The homology and cohomology of a _compact_ Lie group can be directly studied via the Lie algebra of the group (cf. Chevalley and Eilenberg, "Cohomology theory of Lie groups and Lie algebras", _Trans. Amer. Math. Soc_ **63** (1948), 85--124).
Proceeding like so, we can study Lie algebras over an arbitrary field (most often of characteristic zero);
the compactness hypotheses are then replaced with _semi-simplicity_ hypotheses.
The current conference aims to explain certain algebraic tools that are useful for this study, and to prove the first results obtained (notably the theorem on the third Betti number).
In a later conference, we will introduce notions concerning a sub-algebra of a Lie algebra, and its corresponding "homogeneous space".

## General notions {#I.1}

Denoting an operator on a set $A$ (that is, a transformation from $A$ to $A$) by an arbitrary letter, such as $T$, we write $T\cdot x$ to mean the transformation of $x\in A$ under $T$, and $TU$ to mean the composition of operators $T$ and $U$, so that $TU\cdot x = T\cdot (U\cdot x)$.

## Notions concerning the exterior algebra {#I.2}

(cf. Bourbaki, _Algèbre_, Chap. III).

Let $E$ be a vector space over a commutative field $K$ (or, equivalently, a unital module over a commutative ring).
Let $\Lambda(E)$ be the exterior algebra of $E$, given by the direct sum of the $\Lambda^p(E)$ (with $\Lambda^0(E)=K$ and $\Lambda^1(E)=E$).
We use lowercase _Latin_ letters to denote elements of $E$, and _Greek_ for those of $\Lambda(E)$.
We write $a\wedge b$ for the product;
in particular, for a product of elements of degree $1$, we write $x_1\wedge x_2\wedge\ldots\wedge x_p$.

The bilinear form that defines the duality between $E$ and its _dual_ $E'$ is denoted by $\langle x,x'\rangle$.
The _interior product_ of some $\alpha\in\Lambda^p(E)$ with some $x'\in E$ is an element of $\Lambda^{p-1}(E)$, denoted by $a\llp x'$, and defined by
$$
  (x_1\wedge x_2\wedge\ldots\wedge x_p) \llp x'
  = \sum_{i=1}^p (-1)^{i+1} \langle x_i,x' \rangle x_1\wedge\ldots\wedge\widehat{x_i}\wedge\ldots\wedge x_p
$$
(where the hat $\;\widehat{\,}\;$ over $x_i$ indicates that the $x_i$ term should be omitted).
The operator on $\Lambda(E)$ given by $\alpha\mapsto\alpha\llp x'$ is denoted by $i(x')$;
we have $i(x')i(x')=0$.
We define $i(\alpha')$ for $\alpha'\in\Lambda(E)'$ by
$$
  i(x'_1\wedge\ldots\wedge x'_p)
  = i(x'_p)\ldots i(x'_1).
$$
\oldpage{8}
We write $\alpha\llp\alpha'$ to mean $i(\alpha')\cdot\alpha$.
We similarly define $i(\alpha)$, which acts on $\Lambda(E')$;
we denote $i(\alpha)\cdot\alpha'$ by $\alpha\lrp\alpha'$.
We have $i(\alpha\wedge\beta)=i(\beta)i(\alpha)$.
The scalar components of $\alpha\llp\alpha'$ and of $\alpha\lrp\alpha'$ are equal;
we denote this scalar component by $\langle\alpha,\alpha'\rangle$: this "scalar product" extends $\langle x,x'\rangle$ and defines the duality between $\Lambda(E)$ and $\Lambda(E')$.
We have $\langle\alpha,\alpha'\rangle=0$ if $\alpha$ and $\alpha'$ are homogeneous of different degrees, and
$$
  \langle x_1\wedge\ldots\wedge x_p,x'_1\wedge\ldots\wedge x'_p\rangle = \det(\langle x_i,x'_j\rangle).
$$

Let $e(\beta)$ be the exterior multiplication $\alpha\mapsto\beta\wedge\alpha$, and $e(\beta')$ the exterior multiplication $\alpha'\mapsto\beta'\wedge\alpha'$.
The equation
$$
  \langle \beta\wedge\alpha, \alpha' \rangle
  = \langle \alpha, \beta\lrp\alpha' \rangle
$$
tells us that $e(\beta)$ and $i(\beta)$ are _transpose_ to one another (the former acts on $\Lambda(E)$, and the latter on $\Lambda(E')$).
Similarly, $e(\beta')$ and $i(\beta')$ are transpose.


## Notions concerning endomorphisms of algebras in general {#I.3}

We now study a _graded_ algebra $\Lambda$.
We denote by $\alpha\mapsto\overline{\alpha}$ the automorphism that sends a homogeneous element $\alpha$ of degree $n$ to the element $(-1)^n\alpha$.
An endomorphism $\theta$ (of the vector structure) is said to be a _derivation_ if
$$
  \begin{aligned}
    \theta\cdot\overline{\alpha}
    &= \overline{\theta\cdot\alpha}
  \\\theta\cdot(\alpha\beta)
    &= (\theta\cdot\alpha)\beta + \alpha(\theta\cdot\beta),
  \end{aligned}
$$
and an _antiderivation_ if
$$
  \begin{aligned}
    \theta\cdot\overline{\alpha}
    &= -\overline{\theta\cdot\alpha}
  \\\theta\cdot(\alpha\beta)
    &= (\theta\cdot\alpha)\beta + \overline{\alpha}(\theta\cdot\beta).
  \end{aligned}
$$

If $\theta$ an antiderivation, then $\theta\theta$ is a derivation;
if $\theta_1$ and $\theta_2$ are antiderivations, then  $\theta_1\theta_2+\theta_2\theta_1$ is a derivation.

The "bracket" $[\theta_1,\theta_2]$ of two operators is, by definition, $\theta_1\theta_2-\theta_2\theta_1$.
The bracket of two derivations is again a derivation;
the bracket of a derivation and an antiderivation is an antiderivation.

If $\Lambda$ is generated by its degree $0$ and degree $1$ elements, then every derivation (resp. antiderivation) that is zero on the degree $0$ and degree $1$ elements is identically zero.

If $\Lambda$ is the exterior algebra $\Lambda(E)$ of a vector space $E$, then $i(x')$ (for $x'\in E'$) is an antiderivation.
If $\theta$ is a derivation of $\Lambda(E)$, then $e(x)\theta$ is an antiderivation.


## Notions concerning differentiable manifolds {#I.4}

For simplicity, we will restrict our study to that of infinitely differentiable manifolds;
all the "functions" that we consider will be infinitely differentiable.

\oldpage{9}
At each point $M$ of the manifold $V$, we have a duality between the space $E(m)$ of _tangent vectors_ (at $M$) and the space $E'(M)$ of differentials of real-valued functions (to $\RR$) at the point $M$.
They are both $n$-dimensional vector spaces over the field $\RR$ of real numbers (where $n$ is the dimension of $V$).
A _vector field_ $X$ is a function that, to each point $M$ of $V$, associates a tangent vector at $M$;
vector fields form a module $E$ (over the ring of real-valued functions) whose dual $E'$ is the module of degree $1$ differential forms.
We denote by $\langle X,\omega\rangle$ the bilinear form defining this duality.
The differential $\dd f$ of a real-valued function is a differential form (an element of $E'$).
The algebra of "exterior differential forms" can be identified with the exterior algebra $\Lambda(E')$ (where $E'$ is considered as a module over the ring of real-valued functions);
the operator $\dd$ (_exterior differentiation_) is characterised by the following three properties:

1. for a function $f$ (an element of $\Lambda^0(E')$), $\dd f$ is the differential of $f$ ;
2. $\dd\dd=0$ ; and
3. $\dd$ is an _antiderivation_.

Every vector field $X$ defines an _infinitesimal_ transformation, which we denote by $\theta(X)$, and which acts on $\Lambda(E)$ and $\Lambda(E')$.
We first define $\theta(X)$ on $\Lambda^0(E)=\Lambda^0(E')$ by setting $\theta(X)\cdot f=\langle X,\dd f\rangle$.
There then exists a kernel of the automorphism group of $V$, depending on a real parameter $t$, say $M\mapsto\varphi(M,t)$, such that, for every function $f$,
$$
  \frac{\partial}{\partial t} f(\varphi(M,t))
  = \theta(X)\cdot f(\varphi(M,t)).
$$
This group acts on $\Lambda(E)$ and $\Lambda(E')$, and, by differentiating with respect to $t$ at $t=0$, we recover the operator $\theta(X)$.
It can be calculated using the following rules (which don't need explicit knowledge of the automorphism group):

1. $\theta(X)$ _commutes_ with $\dd$ (on $\Lambda(E')$); to take $\theta(X)$ of a _product_ (either exterior, interior, or scalar), we apply the classical formula for taking the derivative of a product; and, in particular, on $\Lambda(E)$ and $\Lambda(E')$, $\theta(X)$ is a _derivation_.

::: {.eqref #equation-I.1}
2. If we apply $\theta(X)$ to a vector field $Y$, then we obtain $\theta(X)\cdot Y$; we have the fundamental formula
    $$
      \theta(\theta(X)\cdot Y) = \theta(X)\theta(Y) - \theta(Y)\theta(X),
    \tag{1}
    $$
    which leads us to denote by $[X,Y]$ the vector field $\theta(X)\cdot Y$, and [(1)](#equation-I.1) then gives the _Jacobi identity_
:::

\oldpage{10}

::: {.eqref #equation-I.2}
3. Finally, we have the "fundamental formula of the calculation of variations":
    on the space $\Lambda(E')$ of exterior differential forms,
    $$
      \theta(X) = i(X)\dd + \dd\cdot i(X),
    \tag{2}
    $$
    where $i(X)$ denotes, as in [§I.2](#I.2), the interior product.
    (Proof: both sides of the equation are derivations that commute with $\dd$ and that are equal on functions).
:::


## Lie groups {#I.5}

Let $V$ denote the manifold of a Lie group $G$, and denote by $\frak{a}$ the subspace of $E$ given by vector fields that are _invariant under left-translations_ by $G$;
we denote by $\frak{a}'$ the subspace of $E'$ given by _left-invariant_ differential forms (of degree $1$).
Then $\frak{a}$ and $\frak{a}'$ are $n$-dimensional vector spaces over the field $\RR$ of reals, and are in duality.
The exterior algebra $\Lambda(\frak{a}')$ can be identified with the sub-algebra of $\Lambda(E')$ given by _left-invariant_ exterior differential forms, and it is _stable_ under the operator $\dd$ of exterior differentiation.
(In particular, $\Lambda^0(\frak{a}')$ is the field of constant functions, identified with $\RR$).

If $X\in\frak{a}$, then the automorphism group of $V$ defined by $X$ (cf. [§I.4](#I.4)) is the group of _right_-translations by elements of the subgroup of $G$;
the orbit of the identity element.
Thus $\Lambda(\frak{a})$ and $\Lambda(\frak{a}')$ are _stable_ under $\theta(X)$ if $X\in\frak{a}$.
In particular, if $X$ and $Y$ are in $\frak{a}$, then $[X,Y]$ is in $\frak{a}$.
The elements upon which $\theta(X)$ acts as zero (for _all_ $X\in\frak{a}$) are those that are simultaneously invariant under left- and right-translations, and are simply called _invariant elements_.

Since $\theta(X)$ is zero on the scalars (constant functions), we have:

::: {.eqref #equation-I.3}
$$
  \langle \theta(X)\cdot Y,\omega \rangle + \langle Y,\theta(X)\cdot\omega \rangle
  = 0
  \qquad\text{for }Y\in\frak{a}\text{ and }\omega\in\frak{a}'.
\tag{3}
$$
:::

In other words, $\theta(X)$ (acting on forms) is the _transpose_ of $-\theta(X)$ (acting on vector fields).

The vector space $\frak{a}$, endowed with the structure defined by the map $(X,Y)\mapsto[X,Y]$ from $\frak{a}\times\frak{a}$ to $\frak{a}$, is the _Lie algebra_ of the group $G$.


## Lie algebras {#I.6}

We start with an abstract Lie algebra $\frak{a}$ (under the classical definition), taken over a field $K$ that is, for now, arbitrary.
Let $n$ be the dimension of the vector space $\frak{a}$ over $K$.
We will construct everything from the structure of $\frak{a}$, by taking the relations established above (in the case of the field $\RR$) as our definitions.

\oldpage{11}
Let $\frak{a}'$ be the dual vector space of $\frak{a}$.
From now on, we denote elements of $\frak{a}$ by $x,y,\ldots$;
the elements of $\frak{a}'$ by $x',y',\ldots$;
the elements of $\Lambda(\frak{a})$ by $\alpha,\beta,\ldots$;
and the elements of $\Lambda(\frak{a}')$ by $\alpha',\beta',\ldots$.
We _define_ $\theta(x)$, for $x\in\frak{a}$, by
$$
  \begin{aligned}
    \theta(x)\cdot y
    &= [x,y];
  \\\langle y,\theta(x)\cdot x'\rangle
    &= -\langle[x,y],x'\rangle.
  \end{aligned}
$$
With $\theta(x)$ defined on $\frak{a}$ and $\frak{a}'$, we extend it to $\Lambda(\frak{a})$ and $\Lambda(\frak{a}')$ by imposing the condition that $\theta(x)$ be a _derivation_.
The $\theta(x)$ that acts on $\Lambda(\frak{a})$ is the _transpose_ of the $-\theta(x)$ that acts on $\Lambda(\frak{a}')$.
The elements of $\Lambda(\frak{a})$ (resp. of $\Lambda(\frak{a}')$) for which $\theta(x)$ acts as zero (for _all_ $x\in\frak{a}$) are called _invariant_ (or _bi-invariant_) elements.
The invariant elements of $\Lambda(\frak{a})$ form a _sub-algebra_ $\frak{J}$, and those of $\Lambda(\frak{a}')$ form a sub-algebra $\frak{J}'$.

Equation [(2)](#equation-I.2) leads us to define an endomorphism $\delta$ of $\Lambda(\frak{a}')$ that is zero on the scalars, and such that

::: {.eqref #equation-I.4}
$$
  \theta(x) = i(x)\delta + \delta i(x).
\tag{4}
$$
:::

Furthermore, such an operator is unique, commutes with the $\theta(x)$, and satisfies $\delta\delta=0$;
it is an _antiderivation_, characterised by
$$
  \langle x\wedge y,\delta x'\rangle
  = -\langle[x,y],x'\rangle,
$$
and it maps $\Lambda^p(\frak{a}')$ to $\Lambda^{p+1}(\frak{a}')$.

We define, on $\Lambda(\frak{a})$, the endomorphism $\partial$ that is the _transpose_ of $-\delta$ by
$$
  \langle\partial\alpha,\alpha'\rangle
  = -\langle\alpha,\delta\alpha'\rangle.
$$
Then $\partial$ commutes with the $\theta(x)$, satisfies $\partial\partial=0$, maps $\Lambda^p(\frak{a})$ to $\Lambda^{p+1}(\frak{a})$, and is _zero on $\frak{a}$_;
finally, we have that
$$
  \begin{aligned}
    \partial(x\wedge y)
    &= [x,y]
  \\\theta(x)
    &= e(x)\partial + \partial e(x),
  \end{aligned}
$$
whence, by induction, we have the explicit formula
$$
  \partial(x_1\wedge x_2\wedge\ldots\wedge x_p)
  = \sum_{i<j} (-1)^{i+j+1} [x_i,x_j] x_1\wedge\ldots\wedge\widehat{x_i}\wedge\ldots\wedge x_p.
$$

The operator $\delta$ on $\Lambda(\frak{a}')$ (the _algebra of cochains_) defines a _cohomology algebra_, denoted by $\HH(\frak{a}')$.
The operator $\partial$ on $\Lambda(\frak{a})$ (the _algebra of chains_) defines a _homology group_, denoted by $\HH(\frak{a})$;
there is not, in general, a multiplication in $\HH(\frak{a})$, since $\partial$ is _not_ an antiderivation.

We have that $\HH(\frak{a})$ and $\HH(\frak{a}')$ are naturally in duality;
for each degree $p$, $\HH^p(\frak{a})$ and $\HH^p(\frak{a}')$ are in duality, and thus of the same dimension.
If $\frak{a}$ is the Lie algebra of a _compact connected group_, then $\HH(\frak{a}')$ can be identified with the cohomology algebra of the (topological) space of the group, by the de Rham theorem.
\oldpage{12}
This proves that any two compact connected groups that are locally isomorphic have the same Betti number.
In all cases, the common dimension of $\HH^p(\frak{a})$ and $\HH^p(\frak{a}')$ is called the _$p$-th Betti number_ of the Lie algebra $\frak{a}$.

::: {.rmenv #I-unimodularity title="Unimodularity" latex="{Unimodularity}"}
We say that $\frak{a}$ is _unimodular_ if $\theta(x)$ (for _all_ $x\in\frak{a}$), considered as an endomorphism of $\frak{a}$ (the _adjoint_ representation) has _zero trace_;
an equivalent condition is that the chain $\omega$ of degree $n$ is a _cycle_;
another equivalent condition is that $\omega$ is _invariant_.

If $\frak{a}$ is unimodular, then $\alpha\mapsto\omega\llp\alpha'$ defines an isomorphism from $\HH^p(\frak{a}')$ to $\HH^{n-p}(\frak{a})$;
this corresponds to the "Poincaré duality theorem" for the Betti numbers of a manifold.
:::

::: {.rmenv #I-expansions title="Expansions in a basis" latex="{Expansions in a basis}"}
We can express $\delta$ and $\partial$ in terms of a basis $(x_k)$ of $\frak{a}$ and the dual basis $(x'_k)$ of $\frak{a}'$ (when $K$ is of characteristic $\neq2$):
$$
  \begin{aligned}
    2\delta
    &= \sum_k e(x'_k)\theta(x_k)
    \qquad\text{always,}
  \\2\partial
    &= \sum_k i(x'_k)\theta(x_k)
    \qquad\text{if }\frak{a}\text{ is unimodular.}
  \end{aligned}
$$
:::

::: {.rmenv #I-semisimple title="Semi-simple Lie algebras" latex="{Semi-simple Lie algebras}"}
We say that a Lie algebra is _semi-simple_ if it has no radical, or, equivalently (at least if $K$ is of characteristic $0$), if all its representations are completely reducible.
If $\frak{a}/\frak{c}$ is semi-simple (where $\frak{c}$ is the centre of $\frak{a}$), then we have a canonical isomorphism from $\HH(\frak{a}')$ to $\frak{J}'$, and from $\HH(\frak{a})$ to $\frak{J}$ (and thus a multiplicative structure on $\HH(\frak{a})$ in this case).

If $\frak{a}$ is semi-simple, then its centre is trivial, the Betti numbers in dimensions $1$ and $2$ are zero, and the Betti number in dimension $3$ is equal to the dimension of the vector space of _invariant quadratic forms_ (where an invariant quadratic form is a bilinear map $f(x,y)$ such that $f(y,x)=f(x,y)$ and $f(\theta(z)\cdot x,y)+f(x,\theta(z)\cdot y)=0$).
:::

::: {.rmenv title="Corollary" latex="{Corollary}"}
If $K$ is maximal and quasi-real, and $\frak{a}$ is _simple_, then the third Betti number is equal to $1$.
:::


# Part II (March 1949)

## Reminder of notation {#II.1}

\oldpage{45}

|  |  |  |
|-:|:-|:-|
| $\frak{a}$ | Lie algebra over a field $K$ | elements $x,y,\ldots$ |
| $\frak{a}'$ | dual vector space of $\frak{a}$ | elements $x',y',\ldots$ |
| $\Lambda(\frak{a})$ | exterior algebra of $\frak{a}$ | elements $\alpha,\beta,\ldots$ |
| $\Lambda(\frak{a}')$ | exterior algebra of $\frak{a}'$ | elements $\alpha',\beta',\ldots$ |

1. The operator $\theta(x)$ is the _infinitesimal transformation defined by $x\in\frak{a}$_ on $\Lambda(\frak{a})$;
    from now on, we denote by $\theta^*(x)$ (instead of $\theta(x)$) the operator that is the transpose of $-\theta(x)$ acting on $\Lambda(\frak{a}')$.

2. The operator $e(x)$ is the _(left) exterior product with $x\in\frak{a}$_ on $\Lambda(\frak{a})$;
    the operator $i(x)$ is the _interior product with $x\in\frak{a}$_ on $\Lambda(\frak{a}')$;
    $i(x)$ and $e(x)$ are the transpose of one another.

3. The operator $\partial$ is the _boundary_ operator on $\Lambda(\frak{a})$;
    the operator $\delta$ is the _coboundary_ operator on $\Lambda(\frak{a}')$;
    $\delta$ is the transpose of $-\partial$.


These operators satisfy the following relations:

::: {.eqref #equation-II.1}
$$
  \begin{aligned}
    \partial\partial &= 0,
  \\\delta\delta &= 0,
  \\\theta(x) &= e(x)\partial+\partial e(x),
  \\\theta^*(x) &= i(x)\delta+\delta i(x),
  \\\partial\theta(x) &= \theta(x)\partial,
  \\\delta\theta^*(x) &= \theta^*(x)\delta.
  \end{aligned}
\tag{1}
$$
:::

The _homology vector space $\HH(\frak{a})$_ is defined by $\partial$ acting on $\Lambda(\frak{a})$;
the _cohomology algebra $\HH(\frak{a}')$_ is defined by $\delta$ acting on $\Lambda(\frak{a'})$.
There is a multiplicative structure on $\HH(\frak{a}')$ because $\delta$ is an _antiderivation_.
The vector spaces $\HH(\frak{a})$ and $\HH(\frak{a}')$ are canonically in duality.


## Direct sum of two Lie algebras {#II.2}

We say that $\frak{a}$ is the _direct sum_ of two sub-algebras $\frak{b},\frak{c}\subseteq\frak{a}$, and we write $\frak{a}=\frak{b}\oplus\frak{c}$, if

1. the vector space $\frak{a}$ is the direct sum of the subspaces $\frak{b}$ and $\frak{c}$ ; and
2. $[x,y]=0$ for $x\in\frak{b}$ and $y\in\frak{c}$.

If this is the case, then $\Gamma(\frak{a})$ is canonically isomorphic to the tensor product $\Gamma(\frak{b})\otimes\Gamma(\frak{c})$;
\oldpage{46}
if we transport the multiplicative structure of $\Gamma(\frak{a})$ to this tensor product, then we see that
$$
  (\beta_1\otimes\gamma_1)\cdot(\beta_2\otimes\gamma_2)
  = (-1)^{pq}(\beta_1\wedge\beta_2)\otimes(\gamma_1\otimes\gamma_2)
$$
(where $p=\deg\beta_2$ and $q=\deg\gamma_1$), which describes the notion of the _tensor product of graded algebras_.
Finally, the boundary operator $\partial$ on $\Gamma(\frak{b})\otimes\Gamma(\frak{c})$ satisfies
$$
  \partial(\beta\otimes\gamma)
  = (\partial\beta)\otimes\gamma + \overline{\beta}\otimes(\partial\gamma)
$$
(where $\overline{\beta}=(-1)^p\beta$ for $\beta$ of degree $p$).
It thus follows that the vector space $\HH(\frak{a})$ can be identified with the tensor product $\HH(\frak{b})\otimes\HH(\frak{c})$.

Similarly, $\Gamma(\frak{a}')$ can be identified with the tensor product $\Gamma(\frak{b}')\otimes\Gamma(\frak{c}')$ of graded algebras.
The duality between $\Gamma(\frak{b})\otimes\Gamma(\frak{c})$ and $\Gamma(\frak{b}')\otimes\Gamma(\frak{c}')$ is defined by
$$
  \langle\beta\otimes\gamma,\beta'\otimes\gamma'\rangle
  = \langle\beta,\beta'\rangle \cdot \langle\gamma,\gamma'\rangle.
$$
The operator $\delta$ on $\Gamma(\frak{b}')\otimes\Gamma(\frak{c}')$ satisfies
$$
  \delta(\beta'\otimes\gamma')
  = (\delta\beta')\otimes\gamma' + \overline{\beta'}\otimes(\delta\gamma'),
$$
and the cohomology algebra $\HH(\frak{a}')$ can be identified with the tensor product $\HH(\frak{b}')\otimes\HH(\frak{c}')$ of _graded algebras_.

If $\frak{b}$ and $\frak{c}$ are the Lie algebras of _compact connected Lie groups_ $G_1$ and $G_2$ (respectively), then $\frak{a}=\frak{b}\oplus\frak{c}$ is the Lie algebra of the product group $G_1\times G_2$;
we recover the following theorem:
_the cohomology algebra (with real coefficients) of $G_1\times G_2$ is canonically identified with the tensor product of the cohomology algebras of $G_1$ and $G_2$_.


## Semi-simple Lie algebras {#II.3}

Every time that we speak of semi-simplicity, the field $K$ will be assumed to be of characteristic $0$.
We have the following equivalent characterisations of semi-simple Lie algebras

a. every square-zero ideal (i.e. giving rise to an invariant abelian subgroup) is the ideal $\{0\}$;

b. the quadratic form $\tr(\theta(x)\theta(y))$ is regular;

c. $\frak{a}$ is the direct sum of _simple_ algebras (i.e. algebras of dimension $>1$ with only trivial ideals, namely $\{0\}$ and the whole algebra itself);
    such a decomposition is then unique.
    (In principal, determining $\HH(\frak{a})$ and $\HH(\frak{a}')$ for semi-simple $\frak{a}$ thus reduces to determining the homology and cohomology of the simple algebras) ; and

d. every _representation_ of $\frak{a}$ in the endomorphism algebra of a vector space $E$ (of finite dimension over $K$) is _completely reducible_ (i.e. every invariant subspace admits an invariant complement).

\oldpage{47}

Every quotient algebra of a semi-simple algebra is semi-simple.
We thus deduce:
if $\frak{a}$ is semi-simple, then $\frak{a}$ is identical to the "derived" algebra $\frak{a}^2$.
In particular, a semi-simple algebra is _unimodular_ (cf. [§I](#I)).

For every Lie algebra $\frak{a}$, the map $x\mapsto\theta(x)$ is a representation of $\frak{a}$ in the endomorphism algebra of the vector space $\Gamma(\frak{a})$;
similarly, $x\mapsto\theta^*(\frak{a})$ is a representation in the endomorphism algebra of $\Gamma(\frak{a}')$.
These representations vanish on the centre $\frak{c}$ of $\frak{a}$;
we will be sure that they are completely reducible if the algebra $\frak{a}/\frak{c}$ is semi-simple, or, in other words, if $\frak{a}$ is the direct sum of a semi-simple algebra and an abelian algebra.
Such a Lie algebra is said to be _reductive_;
we are particularly interested in the homology and cohomology of reductive Lie algebras.
The Lie algebra of a compact group is always reductive.


## Homology of reductive Lie algebras {#II.4}

In the representation $x\mapsto\theta(x)$ of $\frak{a}$ in the endomorphism algebra of $\Gamma(\frak{a})$, by [(1)](#equation-II.1), the $\theta(x)$ is a of a cycle is a boundary;
similarly, the $\theta^*(x)$ of a cocycle is a coboundary.

::: {.itenv #lemma-1 title="Lemma 1" latex="{Lemma 1}"}
Let $x\mapsto\tau(x)$ be a completely reducible representation of a Lie algebra $\frak{a}$ in the endomorphism algebra of a finite-dimensional vector space $E$ endowed with an operator $d$ such that $dd=0$;
suppose that $\tau(x)d=d\tau(x)$, and that $\tau(x)$ sends cycles to boundaries.
Let $F$ be the subspace of "invariant" elements of $E$ (i.e. elements $\alpha$ such that $\tau(x)\cdot\alpha=0$ for all $x\in\frak{a}$).
Then $F$ is stable under $d$, and the canonical homology from the homology group $\HH(F)$ to the homology group $\HH(E)$ is an _isomorphism_ from the former to the latter.
:::

We can apply this to the representation $x\mapsto\theta(x)$ (resp. $x\mapsto\theta^*(x)$) of a _reductive_ algebra $\frak{a}$;
then $F$ becomes $\frak{J}$ (resp. $\frak{J}'$), the sub-algebra of _invariant_ chains (resp. _invariant_ cochains).
But $\partial$ is zero for every element of $\frak{J}$, and $\delta$ is zero for every element of $\frak{J}'$, thanks to the formulas
$$
  \begin{aligned}
    2\delta
    &= \sum_k e(x'_k)\theta(x_k)
  \\2\partial
    &= \sum_k i(x'_k)^*\theta(x_k)
  \end{aligned}
$$
(where $(x_k)$ and $(x'_k)$ are dual bases; see [§I](#I)).
So $\HH(\frak{J})$ can be identified with $\frak{J}$,
and $\HH(\frak{J}')$ with $\frak{J}'$, and the lemma shows that $\frak{J}\to\HH(\frak{a})$ and $\frak{J}'\to\HH(\frak{a})$ are _onto isomorphisms_ (i.e there is one and only one invariant chain in each homology class; id. for cochains and cohomology).
\oldpage{48}
Furthermore, $\frak{J}'\to\HH(\frak{a}')$ is an isomorphism for the _algebra_ structure;
we can not say the same of $\frak{J}\to\HH(\frak{a})$, since $\HH(\frak{a})$ has no multiplicative structure, but the identification of $\HH(\frak{a})$ with $\frak{J}$, which does have an algebra structure, precisely defines a multiplicative structure on $\HH(\frak{a})$, and allows us to speak about the _homology algebra_ of a reductive Lie algebra.
We will prove that, if $\frak{a}$ is the Lie algebra of a compact connected group, then the multiplicative structure of $\HH(\frak{a})$ is precisely that which is defined by the "Pontrjagin product".

::: {.rmenv title="Remark" latex="{Remark}"}
On any reductive $\frak{a}$, there exists at least one _regular_ invariant quadratic form;
it defines an isomorphism from the algebra $\Gamma(\frak{a})$ to the algebra $\Gamma(\frak{a})$, and from $\frak{J}$ to $\frak{J}'$;
thus $\HH(\frak{a})$ and $\HH(\frak{a}')$ are (non-canonically) _isomorphic algebras_.
:::


## The first three Betti numbers of a semi-simple Lie algebra {#II.5}

A preliminary remark:
for $\alpha'$ to be an _invariant_ cochain, it is necessary and sufficient that it be a cocycle, _and_ that the $i(x)\cdot\alpha'$ be cocycles for _all_ $x\in\frak{a}$ (by [(1)](#equation-II.1)).

::: {.rmenv title="The first Betti number is zero" latex="{The first Betti number is zero}"}
The equation
$$
  \langle x\wedge y,\delta x'\rangle
  = -\langle[x,y],x'\rangle
$$
shows that, if $x'$ is a cocycle, then $x'$ is orthogonal to the derived algebra $\frak{a}^2$, and is thus zero if $\frak{a}$ is semi-simple.
:::

::: {.rmenv title="The second Betti number is zero" latex="{The second Betti number is zero}"}
Every invariant cochain $\alpha'$ of degree $2$ is zero, since $i(x)\cdot\alpha'$ is a cocycle of degree $1$ for all $x$, and is thus zero.
:::

:::: {.rmenv title="The third Betti number is equal to the dimension of the vector space of invariant quadratic forms" latex="{The third Betti number is equal to the dimension of the vector space of invariant quadratic forms}"}
In particular, it is always $\geq1$.
An invariant quadratic form is a _symmetric_ bilinear form $f(x,y)$ such that $f(\theta(z)\cdot x,y)+f(x,\theta(z)\cdot y)=0$ for all $z\in\frak{a}$.
We define, as follows, an isomorphism from the vector space $(\frak{J}')^{(3)}$ of invariant cochains of degree $3$ to the space of invariant quadratic forms:
let $\alpha'$ be invariant and of degree $3$;
for every $x\in\frak{a}$, we know that $i(x)\cdot\alpha'$ is a cocycle of degree $2$, and thus cohomologous to $0$;
there thus exists a unique cochain $x'$ of degree $1$ such that $\delta x'=i(x)\cdot\alpha'$;
the map $x\mapsto x'$ from $\frak{a}$ to $\frak{a}'$ defines a bilinear form $f(x,y)=\langle y,x'\rangle$.
\oldpage{49}
We have

::: {.eqref #equation-II.2}
$$
  f(x,[y,z])
  = -\langle x\wedge y\wedge z,\alpha'\rangle,
\tag{2}
$$
:::

and $f$ is symmetric and invariant.
Conversely, if $f$ is a symmetric invariant bilinear form, then there exists a unique cochain $\alpha'$ such that [(2)](#equation-II.2) holds, and this cochain is invariant.
QED.
::::


::: {.rmenv title="Remark" latex="{Remark}"}
This converse holds even without the semi-simplicity assumption.
In particular, the invariant symmetric bilinear form $\tr\theta(x)\theta(y)$ defines an invariant cochain of degree $3$, called the _Cartan cochain_.
:::

::: {.itenv title="Corollary" latex="{Corollary}"}
If $\frak{a}$ is a Lie algebra such that the _uniqueness_ (up to a scalar multiple) of an invariant quadratic form is assured, then the third Betti number of $\frak{a}$ is equal to $1$.
This is notably the case for the algebra of a compact connected Lie group, or for a simple Lie algebra over an algebraically closed field.
:::


## Homomorphisms from one Lie algebra to another {#II.6}

Let $\frak{b}$ and $\frak{a}$ be arbitrary Lie algebras (over the same field $K$), and let $\varphi$ be a homomorphism from $\frak{b}$ to $\frak{a}$;
then $\varphi$ extends to a homomorphism, again denoted by $\varphi$, from the _algebra_ $\Gamma(\frak{b})$ to the _algebra_ $\Gamma(\frak{a})$.
The transpose $\varphi^*$ (a homomorphism from $\frak{a}'$ to $\frak{b}'$) can be extended to a homomorphism, again denoted by $\varphi^*$, from the algebra $\Gamma(\frak{a}')$ to the algebra $\Gamma(\frak{b}')$;
furthermore, the extensions of $\varphi$ and $\varphi^*$ are _transpose to one another_.
We have $\partial\varphi=\varphi\partial$ and $\delta\varphi^*=\varphi^*\delta$, whence a homomorphism $\widetilde{\varphi}$ from $\HH(\frak{b})$ to $\HH(\frak{a})$, and a homomorphism $\widetilde{\varphi}^*$ from $\HH^(\frak{a}')$ to $\HH(\frak{b}')$, with $\widetilde{\varphi}^*$ being the transpose of $\widetilde{\varphi}$.
The homomorphism $\widetilde{\varphi}^*$ is also a homomorphism for the multiplicative structures.

::: {.itenv #theorem-1 title="Theorem 1" latex="{Theorem 1}"}
If the algebras $\frak{a}$ and $\frak{b}$ are _reductive_, then $\widetilde{\varphi}$ is a homomorphism for the multiplicative structures of $\HH(\frak{b})$ and $\HH(\frak{a})$.
:::

This can be proved by using:

::: {.itenv #lemma-2 title="Lemma 2" latex="{Lemma 2}"}
Let $\frak{a}$ be an arbitrary Lie algebra;
then, for any chains $\alpha$ and $\beta$ of $\Gamma(\frak{a})$, the chain
$$
  \partial(\alpha\wedge\beta) + (\partial\alpha)\wedge\beta - \overline{\alpha}\wedge(\partial\beta)
$$
is orthogonal to the invariant cochains.
:::

With this, we consider a reductive Lie algebra, and we will show that, if $\alpha$ and$\overline{\alpha}\wedge\partial\gamma$ are cycles, then $\overline{\alpha}\wedge\partial\gamma$ is a boundary:
\oldpage{50}
indeed, by [Lemma 2](#lemma-2),
$\partial(\alpha\wedge\gamma)-\overline{\alpha}\wedge\partial\gamma$ is orthogonal to the invariant cochains, and, since it is a cycle, it is orthogonal to the coboundaries;
it is thus orthogonal to all the cocycles, and thus is a boundary;
so $\overline{\alpha}\wedge\partial\gamma$ is indeed a boundary.
Now let $\alpha$ and $\beta$ be invariant cycles, and $\alpha_1$ and $\beta_1$ cycles that are homologous to $\alpha$ and $\beta$ (respectively);
we will show that, if $\alpha_1\wedge\beta_1$ is a cycle, then this cycle is homologous to $\alpha\wedge\beta$:
we have
$$
  \alpha\wedge\beta - \alpha_1\wedge\beta_1
  = \alpha\wedge(\beta-\beta_1) + (\alpha-\alpha_1)\wedge\beta,
$$
and, by what we have just shown, both of the terms on the right-hand side are boundaries.

From this it follows that, in a reductive Lie algebra, if $\alpha_1$ and $\alpha_2$ are cycles such that $\alpha_1\wedge\beta_1$ is a cycle, then the homology class of $\alpha_1\wedge\beta_1$ is the product of the homology classes of $\alpha_1$ and $\beta_1$.

The proof of [Theorem 1](#theorem-1) goes as follows:
$\beta_1$ and $\beta_2$ are _invariant_ chains of $\Gamma(\frak{b})$, and so $\varphi(\beta_1)$, $\varphi(\beta_2)$, and $\varphi(\beta_1\wedge\beta_2)$ are all cycles in $\Gamma(\frak{a})$, and so the class of $\varphi(\beta_1\wedge\beta_2)=\varphi(\beta_1)\wedge\varphi(\beta_2)$ is the product of the classes of $\varphi(\beta_1)$ and $\varphi(\beta_2)$.


## The Hopf--Samelson theorem {#II.7}

This theorem is proven for reductive Lie algebras, using [Theorem 1](#theorem-1) above.
First, let $\frak{a}$ be an arbitrary Lie algebra, and $\varphi$ the "diagonal map" from $\frak{a}$ to $\frak{a}\oplus\frak{a}\subset\Gamma(\frak{a})\otimes\Gamma(\frak{a})$:
$$
  \varphi(x) = x\oplus x = x\otimes1 + 1\otimes x.
$$
From this, we obtain a homomorphism $\varphi$ from $\Gamma(\frak{a})$ to $\Gamma(\frak{a})\otimes\Gamma(\frak{a})$, such that
$$
  \varphi(\alpha) = \alpha\times1 + \ldots + 1\otimes\alpha.
$$
The transpose map $\varphi^*$ from $\Gamma(\frak{a}')\otimes\Gamma(\frak{a}')$ to $\Gamma(\frak{a}')$ is an _algebra_ homomorphism ([§II.6](#II.6));
it easily follows that
$$
  \varphi^*(\alpha'\otimes\beta') = \alpha'\wedge\beta'.
$$

The homomorphism $\widetilde{\varphi}$ from $\HH(\frak{a})$ to $\HH(\frak{a})\otimes\HH(\frak{a})$ satisfies
$$
  \widetilde{\varphi}(\widetilde{\alpha})
  = \widetilde{\alpha}\otimes1 + \ldots + 1\otimes\widetilde{\alpha}
$$
where $\widetilde{\alpha}$ denotes a homology class.
The transpose homomorphism $\widetilde{\varphi}^*$ is an _algebra homomorphism_, and satisfies
$$
  \widetilde{\varphi}^*(\widetilde{\alpha}'\otimes\widetilde{\beta}')
  = \widetilde{\alpha}'\cdot\widetilde{\beta}'
$$
(where the product $\cdot$ is in $\HH(\frak{a}')$).

If $\frak{a}$ is now a _reductive_ algebra, then the homomorphism $\widetilde{\varphi}$ is also a homomorphism _for the multiplicative structures_ of $\HH(\frak{a})$ and $\HH(\frak{a})\otimes\HH(\frak{a})$.
\oldpage{51}
We thus find ourselves in the following algebraic situation:

$K$ is a field of characteristic $0$;
$A$ is a graded algebra of finite rank over $K$ whose multiplication law satisfies the usual commutativity and anticommutativity conditions for an exterior algebra;
$A'$ is a graded algebra that is (non-canonically) isomorphic to $A$, in canonical duality with $A$;
the degree $0$ elements of $A$ (resp. of $A'$) are given by multiples of the unit, and can be identified with the elements of $K$.
The duality between $A\otimes A$ and $A'\otimes A'$ is defined by $\langle\alpha\otimes\beta,\alpha'\otimes\beta'\rangle = \langle\alpha,\alpha'\rangle\cdot\langle\beta,\beta'\rangle$, and the transpose of the canonical homomorphism $\widetilde{\varphi}^*$ from $A'\otimes A'$ to $A'$ (such that $\widetilde{\varphi}^*(\alpha'\otimes\beta')=\alpha'\cdot\beta'$) is $\widetilde{\varphi}$, which is a homomorphism from $A$ to $A\otimes A$ _that respects the multiplicative structures_.
In such a situation, we say that the homogeneous elements of degree $\geq1$ of $A$ (resp. of $A'$) that are orthogonal to the products $\alpha'\cdot\beta'$ with $\alpha'$ and $\beta'$ of degree $\geq1$ (resp. to the products $\alpha\cdot\beta$ etc.) are _primitive_.
We can then prove the following theorem of algebra:

::: {.itenv #HS-theorem title="The Hopf--Samelson theorem" latex="{The Hopf--Samelson theorem}"}
The _primitive_ elements of are _odd degree_;
they generate a vector subspace $P$ of $A$ (resp. $P'$ of $A'$);
the canonical map $P\to A$ (resp. $P'\to A'$) can be extended to give an _isomorphism from the exterior algebra $\Gamma(P)$ onto $A$_ (resp. an isomorphism from $\Gamma(P')$ onto $A'$);
when restricted to $P$ and $P'$, the duality between $A$ and $A'$ defines a duality between $P$ and $P'$;
this duality can be extended in the usual way to give a duality between $\Gamma(P)$ and $\Gamma(P')$ that, by identifying $\Gamma(P)$ with $A$, and $\Gamma(P')$ with $A'$, recovers the existing duality between $A$ and $A'$.
:::

The above statement thus applies if we take $A$ to be the homology algebra $\HH(\frak{a})$ of a reductive Lie algebra, and $A'$ to then be the cohomology algebra $\HH(\frak{a}')$.

::: {.rmenv title="Remark" latex="{Remark}"}
In the case where $\frak{a}$ is the Lie algebra of a compact connected group, the dimension of the space $P$ of primitive elements is equal to the _rank_ of the group, that is, to the maximal dimension of the abelian sub-algebras of $\frak{a}$.
We still do not have an algebraic proof of this fact, which would prove this statement for a reductive Lie algebra.
:::


## Homomorphisms from a reductive algebra to a reductive algebra {#II.8}

Let $\frak{a}$ and $\frak{b}$ be reductive algebras, and $\varphi$ a homomorphism from $\frak{b}$ to $\frak{a}$;
we keep the notation form [§II.6](#II.6).
Then every _primitive_ element of $\HH(\frak{b})$ is sent, by $\widetilde{\varphi}$, to a _primitive_ element of $\HH(\frak{a})$;
every _primitive_ element of $\HH(\frak{a}')$ is sent, by $\widetilde{\varphi}^*$, to a _primitive_ element of $\HH(\frak{b}')$.
Taking [Theorem 1](#theorem-1) into account (from [§II.6](#II.6)), we thus deduce:

\oldpage{52}

::: {.itenv #theorem-2 title="Theorem 2" latex="{Theorem 2}"}
_(cf. Samelson)._
The ideal of zeros of $\widetilde{\varphi}$ is the _ideal_ of $\HH(\frak{b})$ generated by the _primitive_ elements of $\HH(\frak{b})$ whose image under $\widetilde{\varphi}$ is zero;
the sub-algebra given by the image of $\widetilde{\varphi}$ is the _sub-algebra_ of $\HH(\frak{a})$ generated by the unit and by the _primitive_ elements of $\HH(\frak{a})$ that belong to the image of $\widetilde{\varphi}$.
The analogous properties hold for cohomology algebras.
:::

::: {.itenv title="Corollary" latex="{Corollary}"}
Let $n$ denote the dimension of $\frak{b}$.
For $\widetilde{\varphi}$ to be _bijective_, it suffices that $\widetilde{\varphi}(\omega)\neq0$, where $\omega$ is the generating element of $\HH_n(\frak{b})$.
:::

The next talk will be dedicated to the study of _relative_ homology and cohomology:
given a sub-algebra $\frak{b}$ of $\frak{a}$, we define the homology (resp. cohomology) of the "homogeneous space" $\frak{a}/\frak{b}$, and we study the relations between the homology (resp. cohomology) of $\frak{a}$, of $\frak{b}$, and of $\frak{a}/\frak{b}$.


# Part III (May 1949) {#III}

We keep the notation from the previous talk.
However, we now write $\Gamma^*(\frak{a})$ (instead of $\Gamma(\frak{a}')$) to denote the exterior algebra of the dual of $\frak{a}$, which is in duality with $\Gamma(\frak{a})$ (the exterior algebra of $\frak{a}$).
We denote by $\HH^*(\frak{a})$ (instead of $\HH(\frak{a}')$) the _cohomology algebra_ of $\frak{a}$, and by $\HH^p(\frak{a})$ the subspace of homogeneous elements of degree $p$ of $\HH^*(\frak{a})$.
We keep the notation $\HH(\frak{a})$ for the homology _space_ of $\frak{a}$, and $\HH_p(\frak{a})$ for the subspace of elements of degree $p$ of $\HH(\frak{a})$.
If $\frak{a}$ is a _reductive_ Lie algebra, then, as we have seen, $\HH(\frak{a})$ is endowed with a _multiplicative structure_:
we denote by $\HH_*(\frak{a})$ the _homology algebra_ of $\frak{a}$ (i.e. the space $\HH(\frak{a})$ endowed with this multiplicative structure).

Recall that a Lie algebra $\frak{a}$ (over a field $K$) is said to be _reductive_ if the representation $x\mapsto\theta(x)$ of $\frak{a}$ in the endomorphism algebra of the vector space $\Gamma(\frak{a})$ is completely reducible;
such an algebra $\frak{a}$ is the direct sum of a semi-simple Lie algebra and an abelian algebra, and the converse is true if $K$ is of _characteristic $0$_.
More generally, let $\frak{b}$ be a sub-algebra of a Lie algebra $\frak{a}$;
we say that $\frak{b}$ is _reductive in $\frak{a}$_ if the representation $x\mapsto\theta(x)$ of $\frak{b}$ in the endomorphism algebra of $\Gamma(\frak{a})$ is completely reducible;
the $\frak{b}$ is also reductive (i.e. reductive in itself).

If $\frak{a}$ is a Lie algebra of a _compact_ group (an algebra over the field of reals), then every sub-algebra of $\frak{a}$ is reductive in $\frak{a}$.


## Relative chains and cochains {#III.1}

Let $\frak{b}$ be a sub-algebra of a Lie algebra $\frak{a}$;
this gives a bijective homomorphism $\varphi\colon\Gamma(\frak{b})\to\Gamma(\frak{a})$, and its transpose $\varphi^*\colon\Gamma^*(\frak{a})\to\Gamma^*(\frak{b})$ (which is _onto_).
A subspace of $\Gamma(\frak{a})$ (resp. of $\Gamma^*(\frak{a})$) is said to be _$\frak{b}-stable$_ if it is stable under the endomorphisms $\theta(x)$ (resp. $\theta^*(x)$) for all $x\in\frak{b}$.
We denote by $I(\frak{a},\frak{b})$ the subspace of chains of $\frak{a}$ that are _invariant under $\frak{b}$_, that is, the $\alpha\in\Gamma(\frak{a})$ such that $\theta(x)\cdot\alpha=0$ for all $x\in\frak{b}$.
There is the analogous definition of the subspace $I^*(\frak{a},\frak{b})$ of $\frak{b}$-invariant cochains of $\frak{a}$.

\oldpage{72}
Let $N(\frak{a},\frak{b})$ be the ideal of $\Gamma(\frak{a})$ generated by $\varphi(\frak{b})$;
the subspace of $\Gamma^*(\frak{a})$ that is orthogonal to $N(\frak{a},\frak{b})$ is the _sub-algebra_ $N^(\frak{a},\frak{b})$ generated by the unit and the degree $1$ cochains that are orthogonal to $\frak{b}$.
We write $N^p(\frak{a},\frak{b})$ to mean the subspace of degree $p$ elements of $N^*(\frak{a},\frak{b})$.
The subspaces $N(\frak{a},\frak{b})$ and $N^*(\frak{a},\frak{b})$ are $\frak{b}$-stable.

We first study the particular case where $\frak{b}$ is an _invariant_ sub-algebra (an ideal of the Lie algebra $\frak{a}$), that is, the case where $\frak{b}$ is $\frak{a}$-stable, in which case we have the Lie algebra $\frak{a}/\frak{b}$.
Then $N(\frak{a},\frak{b})$ is _stable under $\partial$_, and $\Gamma(\frak{a})/N(\frak{a},\frak{b})$, endowed with the operator induced by $\partial$ by passing to the quotient, can be identified with $\Gamma(\frak{a}/\frak{b})$;
by duality, $N^(\frak{a},\frak{b})$ endowed with $\delta$ (under which it is stable) can be identified with $\Gamma^*(\frak{a}/\frak{b})$, and is contained inside $I^*(\frak{a},\frak{b})$.

In the general case of an arbitrary sub-algebra $\frak{b}$, the subspace $N(\frak{a},\frak{b})+\partial N(\frak{a},\frak{b})$ is stable under $\partial$, and is generated by $N(\frak{a},\frak{b})$ and by the $\theta(x)\cdot\alpha$ (where $\alpha\in\Gamma(\frak{a})$ and $x\in\frak{b}$);
then $\partial$ acts on the quotient $L(\frak{a},\frak{b})$ of $\Gamma(\frak{a})$ by $N(\frak{a},\frak{b})+\partial N(\frak{a},\frak{b})$, and we call this quotient the _space of relative chains_.
By duality, the intersection $N^*(\frak{a},\frak{b})\cap I^*(\frak{a},\frak{b}) = L^*(\frak{a},\frak{b})$ consists of the cochains $\alpha'$ of $N^*(\frak{a},\frak{b})$ such that $\delta\alpha'\in N^*(\frak{a},\frak{b})$;
this is a _sub-algebra_ of $\Gamma^*(\frak{a})$, called the _algebra of relative cochains_.

Endowing $L(\frak{a},\frak{b})$ with $\partial$ defines a _relative homology space_, denoted by $\HH(\frak{a},\frak{b})$;
it is graded.
The algebra $L^*(\frak{a},\frak{b})$ endowed with $\delta$ defines a _relative cohomology algebra_, denoted by $\HH^*(\frak{a},\frak{b})$;
this is a graded algebra.
In the particular case where $\frak{b}$ is an invariant sub-algebra of $\frak{a}$, we can identify $\HH(\frak{a},\frak{b})$ (resp. $\HH^*(\frak{a},\frak{b})$) with $\HH(\frak{a}/\frak{b})$ (resp. $\HH^*(\frak{a}/\frak{b})$).

In the case where $\frak{a}$ is the Lie algebra of a _compact connected group_ $G$, and $\frak{b}$ is the sub-algebra of a _closed subgroup_ $U$, then $L^*(\frak{a},\frak{b})$ can be identified with the algebra of exterior differential forms of the _homogeneous space_ $W=G/U$ that are invariant under $G$, and $H^*(\frak{a},\frak{b})$ is then the cohomology algebra of the (compact) topological space $W$.
The following results (some of which are new) explain the relations between the cohomology algebras of the spaces $G$, $U$, and $W=G/U$.
We note that $G$ is the fibre bundle with fibre $U$ and base $W$.


## Canonical homomorphisms {#III.2}

We have
$$
  \begin{gathered}
    \Gamma(\frak{b}) \xrightarrow{\varphi} \Gamma(\frak{a}) \xrightarrow{\pi} L(\frak{a},\frak{b})
  \\L^*(\frak{a},\frak{b}) \xrightarrow{\pi^*} \Gamma^*(\frak{a}) \xrightarrow{\varphi^*} \Gamma^*(\frak{b}).
  \end{gathered}
$$
These define
\oldpage{73}
$$
  \begin{gathered}
    \HH(\frak{b}) \xrightarrow{\widetilde{\varphi}} \HH(\frak{a}) \xrightarrow{\widetilde{\pi}} \HH(\frak{a},\frak{b})
  \\\HH^*(\frak{a},\frak{b}) \xrightarrow{\widetilde{\pi}^*} \HH^*(\frak{a}) \xrightarrow{\widetilde{\varphi}^*} \HH^*(\frak{b}).
  \end{gathered}
$$
The homomorphisms $\pi^*$, $\varphi^*$, $\widetilde{\pi}^*$, and $\widetilde{\varphi}^*$ are _algebra homomorphisms_.
The image of $\widetilde{\varphi}$ is contained inside the kernel of $\widetilde{\pi}$;
the image of $\widetilde{\varphi}^*$ is contained inside the kernel of $\widetilde{\pi}^*$.

If $\frak{a}$ is a _reductive_ algebra, then the kernel of $\HH(\frak{a})\to\HH(\frak{a},\frak{b})$ is a two-sided _ideal_ of the _algebra_ $\HH_*(\frak{a})$.
If, furthermore, $K$ is of characteristic $0$, then the Hopf theorem applies to $\HH^*(\frak{a})$, which can be identified with the exterior algebra of the subspace of its _primitive_ elements;
then the image of $\HH^*(\frak{a},\frak{b})\to\HH^*(\frak{a})$ is a sub-algebra of $\HH^*(\frak{a})$ that is _generated by the unit and by the primitive elements of $\HH^*(\frak{a})$_.

If $\frak{b}$ is a _reductive sub-algebra of $\frak{a}$_, then we have a homology algebra $\HH_*(\frak{b})$, and the kernel of $\HH(\frak{b})\to\HH(\frak{a})$ is a two-sided _ideal_ of $\HH_*(\frak{b})$.
If, furthermore, $K$ is of characteristic $0$, then the image of $\HH^*(\frak{a})\to\HH^*(\frak{b})$ is a sub-algebra of $\HH^*(\frak{b})$ that is _generated by the unit and by the primitive elements of $\HH^*(\frak{b})$_.


## Poincaré duality for relative homology and cohomology {#III.3}

Let $n$ (resp. $m$) be the dimension of $\frak{a}$ (resp. $\frak{b}$).
Let $\omega$ be the image in $\Gamma(\frak{a})$ of the $m$-dimensional chain of $\Gamma(\frak{b})$ (defined up to a constant factor).
Then $N(\frak{a},\frak{b})$ is the kernel of the endomorphism $\alpha\mapsto\omega\wedge\alpha$ of $\Gamma(\frak{a})$.
Let $\tau\in\Gamma^{n-m}(\frak{a})$ be such that $\omega\wedge\tau\neq0$;
then, in $\Gamma(\frak{a})/N(\frak{a},\frak{b})$, every element of degree $>(n-m)$ is zero, and the elements of degree $(n-m)$ are proportional to the class $\dot{\tau}$ of $\tau$.
So $\alpha'\mapsto i(\alpha')\cdot\tau$ defines an _isomorphism_ from $N^*(\frak{a},\frak{b})$ _onto_ $\Gamma(\frak{a})/N(\frak{a},\frak{b})$ which depends only on $\dot{\tau}$.

From now on, suppose that $\frak{a}$ and $\frak{b}$ are _unimodular_;
then $\dot{\tau}$ is a $\frak{b}$-invariant element of $\Gamma(\frak{a})/N(\frak{a},\frak{b})$, and so $\alpha'\mapsto i(\alpha')\cdot\lambda$ defines an isomorphism from $N^*(\frak{a},\frak{b})\cap I^*(\frak{a},\frak{b}) = L^*(\frak{a},\frak{b})$ onto the subspace of $\frak{b}$-invariant elements of $\Gamma(\frak{a})/N(\frak{a},\frak{b})$.

If, furthermore, $\frak{b}$ is _reductive in $\frak{a}$_, then this subspace can be identified with $L(\frak{a},\frak{b}) = \Gamma(\frak{a})/N(\frak{a},\frak{b})+\partial N(\frak{a},\frak{b})$.
This gives an isomorphism $f$ from $L^*(\frak{a},\frak{b})$ onto $L(\frak{a},\frak{b})$.
Furthermore,
$$
  \partial i(\alpha')\cdot\tau
  = i(\delta\overline{\alpha}')\cdot\tau + i(\overline{\alpha}')\cdot\partial\tau.
$$
But the fact that $\frak{b}$ is reductive in $\frak{a}$ implies that $\partial\tau\in N+\partial N$, and since $i(\overline{\alpha}')\cdot(N+\partial N)\subset N+\partial N$, we have that $\partial f(\alpha')=f(\delta\overline{\alpha}')$.
By passing to quotients, $f$ thus defines an _isomorphism from $\HH(\frak{a},\frak{b})$ onto $\HH^*(\frak{a},\frak{b})$_ that sends degree $p$ elements to degree $(n-m-p)$ elements.
\oldpage{74}
We thus deduce that the "relative" Betti numbers are equal for dimensions $p$ and $(n-m-p)$ ("Poincaré duality"), and that _every non-zero ideal of $\HH^*(\frak{a},\frak{b})$ contains $\HH^{n-m}(\frak{a},\frak{b})$_.


## Sub-algebras that are not homologous to zero {#III.4}

From now on, we also suppose that the sub-algebra $\frak{b}$ of $\frak{a}$ is _reductive in $\frak{a}$_.
Let $m$ be the dimension of $\frak{b}$.

For $\HH(\frak{b})\xrightarrow{\widetilde{\varphi}}\HH(\frak{a})$ to be _bijective_, it _suffices_ for $\HH_m(\frak{b})$ (which consists of multiples of a single element) to not be contained in the kernel of $\widetilde{\varphi}$ (since every two-sided ideal of $\HH_*(\frak{b})$ that does not contain $\HH_m(\frak{b})$ is zero).
We then say that $\frak{b}$ is _not homologous to zero in $\frak{a}$_.

If $\frak{b}$ is not homologous to zero in $\frak{a}$, then $\HH^*(\frak{a},\frak{b})\to\HH^*(\frak{a})$ is _bijective_ (and the converse is also true).
So, if $\frak{a}$ is further assumed to be reductive, and the base field to be of characteristic $0$, then $\HH^*(\frak{a},\frak{b})$ has a subspace whose homogeneous components are of _odd degree_, and that can be identified with the _exterior algebra of this subspace_.

If $\frak{b}$ is not homologous to zero in $\frak{a}$, then $\HH^*(\frak{a})\to\HH^*(\frak{b})$ is evidently _onto_.
If, furthermore, the field is of characteristic $0$, then we can define an isomorphism from the algebra $\HH^*(\frak{b})$ to the algebra $\HH^*(\frak{a})$, such that, by composing with the canonical map $\HH^*(\frak{a})\to\HH^*(\frak{b})$, we obtain the identity automorphism of $\HH^*(\frak{b})$.
This map $\HH^*(\frak{b})\to\HH^*(\frak{a})$, along with the canonical map $\HH^*(\frak{a},\frak{b})\to\HH^*(\frak{a})$, define a _homomorphism of (graded) algebras_
$$
  \HH^*(\frak{b})\otimes\HH^*(\frak{a},\frak{b}) \to \HH^*(\frak{a}),
$$
and we can show that this is an _onto isomorphism_ ("Samelson's theorem").

The case of _sub-algebras that are homologous to zero_ will not be examined here (see instead the Koszul's thesis: _Bull. Soc. Math. France_ **78** (1950), 65--127).
