--- 
title: "On coherent algebraic and analytic sheaves"
author: "A. Grothendieck"
date: "4th and 11th of February, 1957"
original: 'Grothendieck, A. "Sur les faisceaux algébriques et les faisceaux analytiques cohérents". _Séminaire Henri Cartan_ **9** (1956--1957), Talk no. 2. [`numdam.org/item/SHC_1956-1957__9__A2_0/`](http://www.numdam.org/item/SHC_1956-1957__9__A2_0/)'
bibliography: SHC-9-2.bib
nocite: '@*'
link-citations: true
csl: maths-translations.csl
reference-section-title: "Bibliography"
github-repo: "thosgood/translations"
favicon: "favicon.ico"
---

```{js, echo = FALSE}
$(document).ready(function(e) {gitbook.sidebar.toggle(false, false)});
```

```{r, child = '_translator-note.Rmd'}
```

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\newcommand{\shHom}{\underline{\operatorname{Hom}}}
\newcommand{\shExt}{\underline{\operatorname{Ext}}}
\newcommand{\HH}{\mathrm{H}}
\newcommand{\EE}{\mathrm{E}}
\newcommand{\RR}{\mathrm{R}}
\newcommand{\supp}{\operatorname{supp}}
\newcommand{\Ext}{\operatorname{Ext}}

<!-- Content -->

\oldpage{2-01}The aim of this talk is to generalise certain theorems of Serre.
It makes fundamental use of the techniques of Serre [@1; @2; @3].


# Generalities on coherent algebraic sheaves {#section-1}

Let $X$ be a topological space endowed with a sheaf of rings $\scr{O}$.
A sheaf of $\scr{O}$-modules $\scr{A}$ (or simply an $\scr{O}$-module) is said to be *of finite type* if, on every small-enough open subset, it is isomorphic to a quotient of $\scr{O}^n$ (for some finite integer $n\geq0$), and *coherent* if it is of finite type and if, for every homomorphism $\scr{O}^m\to\scr{A}$ on an open subset $U$ of $X$, the kernel is of finite type.
If $0\to\scr{A}'\to\scr{A}\to\scr{A}''\to0$ is an exact sequence of $\scr{O}$-modules, and if two of the modules are coherent, then so too is the third;
the kernel, cokernel, image, and coimage of a homomorphism of coherent $\scr{O}$-modules is a coherent $\scr{O}$-module.
If $\scr{A}$ and $\scr{B}$ are coherent $\scr{O}$-modules, then so too is the sheaf $\shHom_\scr{O}(\scr{A},\scr{B})$ of germs of homomorphisms from $\scr{A}$ to $\scr{B}$.
If $\scr{O}$ itself is coherent, then coherent $\scr{O}$-modules are exactly the $\scr{O}$-modules that, on small-enough open subsets, are isomorphic to the cokernel of some homomorphism $\scr{O}^m\to\scr{O}^n$.
For all of this, and other elementary properties, see [@1, chapitre 1, paragraphe 2].

Let $X$ be an algebraic set (over an algebraically closed field $k$, to illustrate the idea; but the results of this talk still hold true for schemes, and even for general arithmetic schemes...).
We denote by $\scr{O}_X$ the structure sheaf of $X$, with its sections over an open subset $U\subset X$ being the regular functions on $U$.
This is a sheaf of rings, and even of $k$-algebras.

::: {.itenv #theorem-1 title="Theorem 1" latex="{Theorem 1}"}
—

a. $\scr{O}_X$ is a coherent sheaf of rings.
b. If $X$ is affine with coordinate ring $A(X)$, then, for every coherent $\scr{O}$-module $\scr{A}$ on $X$, the stalks $\scr{A}_x$ are generated by the canonical image of $\Gamma(X,\scr{A})$.
    Furthermore, $\Gamma(X,\scr{A})$ is an $A(X)$-module of finite type, and every $A(X)$-module of finite type comes from an essentially unique coherent $\scr{O}$-module.
    (Recall that $\Gamma(X,\scr{A})$ denotes the module of sections of $\scr{A}$ over $X$).
c. Under the conditions of b), we have that $\HH^i(X,\scr{A})=0$ for $i>0$.
:::

::: {.proof}
\oldpage{2-02}For the proofs, which are very elementary, see [@1, chapitre 2, paragraphes 2,3,4], or a talk of Cartier in the 1957 *Séminaire Grothendieck*.
:::


# A dévissage theorem {#section-2}

::: {.rmenv #definition-1 title="Definition 1" latex="{Definition 1}"}
Let $\cal{C}$ be an abelian category, and $\cal{C}'$ a subclass of $\cal{C}$.
We say that $\cal{C}'$ is an *exact subcategory* if, for every exact sequence $0\to\scr{A}'\to\scr{A}\to\scr{A}''\to0$ in $\cal{C}$ with two (non-zero) terms in $\cal{C}'$, the third term is also in $\cal{C}'$, and if every direct factor of any $\scr{A}\in\cal{C}'$ is also in $\cal{C}'$.
:::

::: {.itenv #theorem-2 title="Theorem 2" latex="{Theorem 2}"}
Let $X$ be an algebraic set;
suppose that, for every irreducible subset $Y$ of $X$, we are given a coherent $\scr{O}_Y$-module $\scr{F}_Y$ on $Y$ that has support equal to $Y$.
Let $K(X)$ be the abelian category of coherent algebraic sheaves on $X$.
Then every *exact* subcategory $\cal{K}$ of $K(X)$ containing the $\scr{F}_Y$ is identical to $K(X)$.
:::

:::: {.proof}
The proof is done by induction on $n=\dim X$, with the case $n=0$ being immediate, by the second condition of [Definition 1](#definition-1).
So suppose that $n>0$, and that the theorem is true in dimension $<n$.
We can consider $K(Y)$ as a subcategory of $K(X)$ (where $Y$ is some given closed subset of $X$), and then $\cal{K}\cap K(Y)$ is a subcategory of $K(Y)$ satisfying the conditions of [Theorem 2](#theorem-2), and so, if $\dim Y<n$, then the induction hypothesis implies that $K(Y)=K(Y)\cap\cal{K}$, i.e. $K(Y)\subset\cal{K}$.

::: {.itenv #lemma-1 title="Lemma 1" latex="{Lemma 1}"}
Let $Y$ be a closed subset of $X$, and $\scr{A}$ a coherent $\scr{O}_X$-module such that $\supp\scr{A}\subset Y$.
Let $\scr{I}_Y$ be the sheaf of ideals of $\scr{O}_X$ defined by $Y$.
Then there exists an integer $k$ such that $\scr{I}_Y^k\scr{A}=0$.
:::

::: {.proof}
By "compactness" reasons, we can restrict to the case where $X$ is affine, and then apply part (b) of [Theorem 1](#theorem-1), noting that, if $\scr{A}$ is defined by the $A(X)$-module $M=\Gamma(X,\scr{A})$, then the ideal of $\supp\scr{A}$ is the intersection of the minimal prime ideals associated to the annihilator of $M$, whence the result.
:::

::: {.itenv #corollary-1 title="Corollary" latex="{Corollary}"}
Under the above conditions, $\scr{A}$ admits a composition series with each composition factor $\scr{A}_i/\scr{A}_{i+1}$ lying in $K(Y)$.
:::

This implies that $\scr{A}_i/\scr{A}_{i+1}$ is annihilated by $\scr{I}_Y$;
we take $\scr{A}_i=\scr{I}_Y^i\scr{A}$.
In the case where $\dim Y<n$, by induction on the length of
this composition series, using [Definition 1](#definition-1) and the fact that $K(Y)\subset\cal{K}$, we see that, *if $\dim\supp\scr{A}<n$, then $\scr{A}\in\cal{K}$.*

\oldpage{2-03}Suppose first of all that $X$ is irreducible.
For $\scr{A}\in K(X)$, let $T(\scr{A})$ be the torsion submodule of $\scr{A}$ (whose stalks are the torsion submodules of $\scr{A}_x$).

::: {.itenv #lemma-2 title="Lemma 2" latex="{Lemma 2}"}
If $\scr{A}\in K(X)$, then the torsion submodule $T(\scr{A})$ is also in $K(X)$, and $\scr{A}=T(\scr{A})$ if and only if $\supp\scr{A}\neq X$.
:::

::: {.proof}
We can immediately restrict to the case where $X$ is affine, where it is evident, by the interpretation of coherent $\scr{O}$-modules as $A(X)$-modules of finite type.
:::

Using the exact sequence $0\to T(\scr{A})\to \scr{A}\to \scr{A}_0\to 0$, and that $T(\scr{A})\in\cal{K}$, we see that $\scr{A}\in\cal{K}$ if and only if $\scr{A}_0\in\cal{K}$.

Let $\scr{R}$ be the sheaf of fields over $X$ given by the fields of fractions of the $\scr{O}_{X,x}$, i.e. the sheaf of germs of rational functions, which is a constant sheaf, and we have an injective homomorphism $\scr{A}_0\to\scr{A}_0\otimes_{\scr{O}_X}\scr{R}$
Representing $\scr{A}_0$ locally as the cokernel of a homomorphism $\scr{O}_X^m\to\scr{O}_X^{m'}$, we see that the tensor product $\scr{A}_0\otimes_{\scr{O}_X}\scr{R}$ is locally isomorphic (as sheaves of $\scr{R}$-modules) to a sheaf of the form $\scr{R}^k$, and thus conclude that it is *globally* isomorphic to $\scr{R}^k$ thanks to:

::: {.itenv #lemma-3 title="Lemma 3" latex="{Lemma 3}"}
On any irreducible algebraic set $X$, every locally constant sheaf is constant.
:::

::: {.proof}
This is an easy consequence of the fact that every open subset of $X$ is connected (consider a maximal open subset where the sheaf in question is constant!).
:::

We will thus identify $\scr{A}_0\otimes_{\scr{O}_X}\scr{R}$ with some $\scr{R}^k$, which contains the sub-$\scr{O}_X$-module $\scr{O}_X^k$.
Consider the exact sequence
$$
  0 \to \scr{A}_0 \to \scr{A}_0+\scr{O}_X^k \to \scr{Q} \to 0
$$
where $\scr{Q}$ is defined as the cokernel of the injection homomorphism.
We immediately see that $\scr{Q}\otimes_{\scr{O}}\scr{R}=0$, and so $\scr{Q}$ is a torsion module, and so $\supp\scr{Q}\neq X$ ([Lemma 2](#lemma-2)), whence $\scr{Q}\in\cal{K}$.
(We implicitly make use of the fact that $\scr{A}_0+\scr{O}_X^k$ is a coherent $\scr{O}$-module, which can be easily verified).
Then $\scr{A}_0\in\cal{K}$ *if and only if* $\scr{A}_0+\scr{O}_X^k\in\cal{K}$.
\oldpage{2-04}Similarly, the analogous exact sequence $0\to\scr{O}_X^k\to\scr{A}_0+\scr{O}_X^k\to\scr{Q}'\to0$, where $\supp\scr{Q}\neq X$, and whence $\scr{Q}'\in\cal{K}$, implies that $\scr{A}_0+\scr{O}_X^k\in\cal{K}$ *if and only if* $\scr{O}_X^k\in\cal{K}$.
Finally, suppose that $k>0$, i.e. that $\scr{A}$ is not a torsion $\scr{O}$-module, i.e. that $\supp\scr{A}=X$;
then $\scr{O}_X^k\in\cal{K}$ *if and only if* $\scr{O}_X\in\cal{K}$, as follows immediately from [Definition 1](#definition-1).
So the above "if and only if"s imply that, if $\scr{A}$ is such that $\supp\scr{A}\neq X$, then $\scr{A}\in\cal{K}$ *if and only if* $\scr{O}_X\in\cal{K}$.
Taking $\scr{A}=\scr{F}_X$, we thus see that $\scr{O}_X\in\cal{K}$, whence every $\scr{A}\in K(X)$ with support equal to $X$ is in $\cal{K}$, and since the same is true for the $\scr{A}\in K(X)$ with suppose not equal to $X$, we indeed have that $K(X)\subseteq\cal{K}$.

Now, if $X$ is not necessarily irreducible, let $X_i$ be its irreducible components.
For every coherent algebraic sheaf $\scr{A}$ on $X$, let $A_i$ be the sheaf that agrees with $\scr{A}$ on $X_i$, and with $0$ on $X\setminus X_i$;
then $\scr{A}_i$ is a coherent $\scr{O}$-module that can be identified with a quotient of $\scr{A}$.
We have a natural homomorphism $\scr{A}\to\coprod_i\scr{A}_i$ from $\scr{A}$ to the direct sum of the $\scr{A}_i$ that is *injective*;
let $\scr{Q}$ be its cokernel;
we thus have an exact sequence $0\to\scr{A}\to\coprod_i\scr{A}_i\to\scr{Q}\to0$.
Since $\supp\scr{Q}\subset\bigcup_{i\neq j}X_i\cap X_j$, we have that $\scr{Q}\in\cal{K}$;
to prove that $\scr{A}\in\cal{K}$, it suffices to prove that $\coprod_i\scr{A}_i\in\cal{K}$, or even that each $\scr{A}_i$ is in $\cal{K}$.
But, by what we have already seen, applied to $X_i$, we have that $K(X_i)\in\cal{K}$, whence we again conclude that $\supp\scr{A}_i\subset X_i$ implies that $\scr{A}_i\in\cal{K}$, by using the [Corollary of Lemma 1](#corollary-1).
This proves [Theorem 2](#theorem-2).
::::

::: {.rmenv title="Remark" latex="{Remark}"}
We say that the subcategory $\cal{K}$ of $K(X)$ is *left exact* if, for every exact sequence $0\to\scr{A}'\to\scr{A}\to\scr{A}''\to0$ in $K(X)$, we have that $\scr{A}'$ (respectively $\scr{A}$) is in $\cal{K}$ provided that the two other terms are in $\cal{K}$.
The proof of [Theorem 2](#theorem-2) proves that the conclusion still holds true if we suppose that $\cal{K}$ is only left exact, *provided that* the $\scr{F}_Y$ considered as $\scr{O}_Y$-modules are torsion free.
This suffices to prove that, if $X$ is complete, then the $\Gamma(X,\scr{A})$, for $\scr{A}\in K(X)$, are vector spaces of finite dimension (since the category $\cal{K}$ of $\scr{A}\in K(X)$ having this property is left exact, and contains the $\scr{O}_Y$): this is the proof by Serre.
:::


# Complements on sheaf cohomology {#section-3}

Let $X$ be a topological space, and write $\cal{C}^X$ to denote the category of abelian sheaves on $X$.
We define, in the usual manner, injective sheaves, and we can prove the existence, for all $\scr{A}\in\cal{C}^X$, of a resolution $C(\scr{A})$ of $\scr{A}$ by injective sheaves, which allows us to develop the theory of right-derived functors.
\oldpage{2-05}In particular, consider the left-exact functor $\Gamma(X,\scr{A})$ from $\cal{C}^X$ to the category $\cal{C}$ of abelian groups;
its derived functors are denoted $\HH^i(X,\scr{A})$.
So
$$
  \HH^i(X,\scr{A}) = \HH^i\big(\Gamma(X,C(\scr{A}))\big).
$$
The $\HH^i(X,\scr{A})$ form a "cohomological functor" in $\scr{A}$ that is zero for $i<0$, and satisfies
$$
  \HH^0(X,\scr{A}) = \Gamma(X,\scr{A}).
$$

If $f\colon X\to Y$ is a continuous map from $X$ to a space $Y$, then we can define, for any abelian sheaf $\scr{B}$ on $Y$, the abelian sheaf $f^{-1}(\scr{B})$ on $X$, which we call the *inverse image of $\scr{B}$*, as well as the canonical homomorphism
$$
  \HH^0(Y,\scr{B}) \to \HH^0(X,f^{-1}(\scr{B}))
$$
which extends uniquely to give functorial, compatible (with the coboundary operators) homomorphisms
$$
  \HH^i(Y,\scr{B}) \to \HH^i(X,f^{-1}(\scr{B})).
$$

Now let $\scr{A}$ be an abelian sheaf on $X$, and define its *direct image* $f_*(\scr{A})$ to be the abelian sheaf on $Y$ whose sections over any open subset $V$ are the sections of $\scr{A}$ over $f^{-1}(V)$.
Clearly $f_*$ is a covariant additive left-exact functor from $\cal{C}^X$ to $\cal{C}^Y$, and, if $\Gamma_X$ (resp. $\Gamma_Y$) denotes the "sections" functor on $\cal{C}^X$ (resp. $\cal{C}^Y$), then, by definition
$$
  \Gamma_X = \Gamma_Y\circ f_*.
$$
Furthermore, it is trivial to show that $f_*$ sends injective sheaves to injective sheaves.
From this, we easily obtain the *Leray spectral sequence of the continuous map $f$*, i.e. there is a cohomological spectral sequence starting with
$$
  \EE_2^{p,q} = \HH^p(Y,\RR^qf_*(\scr{A}))
$$
that abuts to $\HH^\bullet(X,\scr{A})$, where the $\RR^qf_*(\scr{A})$ are the sheaves on $Y$ given by taking the right-derived functors of the functor $f_*\colon\cal{C}^X\to\cal{C}^Y$, i.e. $\RR^qf_*(\scr{A}) = \HH^q(f_*C(\scr{A}))$.
We immediately see that $\RR^qf_*(\scr{A})$ is *the sheaf on $Y$ associated to the presheaf $V\mapsto\HH^q(f^{-1}(V),\scr{A})$*.

From the Leray spectral sequence, we get homomorphisms
$$
  \HH^p(Y,f_*(\scr{A})) \to \HH^p(X,\scr{A})
\tag{1}
$$
whose direct definition is evident (noting that we have a natural homomorphism $f^{-1}(f_*(\scr{A}))\to A$).
\oldpage{2-06}Furthermore, *if $\RR^qf_*(\scr{A})=0$ for $q>0$, then the homomorphisms in Equation (1) are isomorphisms*.
This follows immediately from the spectral sequence, or, even more simply, from the fact that $f_*(C(\scr{A}))$ is an injective resolution of $f_*(\scr{A})$.

For the results of this section, see the 1957 *Séminaire Grothendieck*.


# Supplementary results on algebraic sheaves on projective space {#section-4}

Let $V$ be a finite-dimensional $k$-vector space, and $\mathbf{P}$ the associated projective space, the quotient of $V\setminus\{0\}$ by the algebraic group $k^\times=k\setminus\{0\}$.
We see that $V\setminus\{0\}$ is a principal algebraic $k^\times$-bundle on $\mathbf{P}$, and so it defines an associated vector bundle on $\mathbf{P}$, with fibres of dimension $1$;
the sheaf of germs of regular sections of the *dual* bundle is denoted $\scr{O}(1)$, and we denote by $\scr{O}(n)$ the $n$-fold tensor product of $\scr{O}(1)$ with itself if $n\geq0$, and the $(-n)$-fold tensor product of the dual sheaf if $n<0$ (in particular then, $\scr{O}(0)=\scr{0}_\mathbf{P}$).
If $\scr{A}$ is an algebraic sheaf on $\mathbf{P}$, then we let $\scr{A}(n)=\scr{A}\otimes_{\scr{O}_\mathbf{P}}\scr{O}_n$, and so $\scr{A}(m)(n)=\scr{A}(m+n)$.
The definitions of $\scr{O}(n)$ and of the operation $\scr{A}\mapsto\scr{A}(n)$ can immediately be extended to sheaves on a product $\mathbf{P}\times Y$, where $Y$ is an arbitrary algebraic set.

::: {.itenv #theorem-3 title="Theorem 3" latex="{Theorem 3}"}
—

a. Let $Y$ be an affine algebraic set, and $\scr{A}$ a coherent algebraic sheaf on $\mathbf{P}\times Y$.
    Then, for every $n$ large enough, $\scr{A}(n)$ is generated by the module of its sections, i.e. $\scr{A}(n)$ is isomorphic to some quotient of $\scr{O}_{\mathbf{P}\times Y}^k$, for some integer $k$.
b. For $n$ large enough, $\HH^i(\mathbf{P},\scr{O}(n))=0$.
:::

::: {.proof}
The proof is elementary;
for (a), see [@1, page 247, théorème 1] (where the proof is given for the case where $Y$ is a single point, but the same method works for arbitrary $Y$), and for (b) see [@1, page 259, théorème 2].
We could also give a direct proof of (b) by calculating $\HH^i(\mathbf{P},\scr{O}(n))$ using the Čech method, which can be applied here, by part (c) of [Theorem 1](#theorem-1) (see the *Séminaire Grothendieck* for more on this point), and using the well-known cover of $\mathbf{P}$ by $(r+1)$ affine open subsets, each isomorphic to $k^r$.
:::

Now suppose that $k=\mathbf{C}$ is the field of complex numbers, so that $\mathbf{P}$ is also endowed with the structure of an analytic space, which we denote by $\mathbf{P}^h$;
this is itself endowed with a sheaf of analytic local rings, which we denote by $\scr{O}^h$;
finally, we can define, as above, the sheaves $\scr{O}^h(n)$.
\oldpage{2-07}With this, we have:

::: {.itenv #corollary-3 title="Corollary" latex="{Corollary}"}
—

a. Let $\scr{A}^h$ be a coherent $\scr{O}^h$-module on $\mathbf{P}^h$.
    Then, for all $n$ large enough, $\scr{A}^h(n)$ is isomorphic to a quotient of $(\scr{O}^h)^k$, for some integer $k$.
b. For $n$ large enough, $\HH^i(\mathbf{P}^h,\scr{O}^h(n))=0$.
:::

::: {.proof}
The proof is distinctly deeper: see [@2, lemme 5, page 12, and lemma 8, page 24].
It works by induction on the dimension, and makes essential use of the fact that the cohomology $\mathbf{P}^h$ with values in a coherent $\scr{O}^h$-module is of finite dimension.
:::


# The finiteness theorem: statement {#section-5}

Let $f\colon X\to Y$ be a regular map of algebraic sets, and let $\scr{A}$ be an algebraic sheaf, i.e. an $\scr{O}_X$-module, on $X$.
Then its direct image by $f$, and, more generally, by the $\RR^qf_*(\scr{A})$ (see [§3](#section-3)), are $\scr{O}_Y$-modules.
In the case where $\scr{A}$ is coherent (or, more generally, "quasi-coherent", in the sense of Cartier, *Séminaire Grothendieck*), we can easily show that, for every *affine* open subset $V$ of $Y$,
$$
  \Gamma(V,\RR^qf_*(\scr{A})) = \HH^q(f^{-1}(V),\scr{A})
$$
and that the sheaves $\RR^qf_*(\scr{A})$ are "quasi-coherent".
We will given sufficient conditions for them to be coherent.

::: {.rmenv #definition-2 title="Definition 2" latex="{Definition 2}"}
A morphism $f\colon X\to Y$ of algebraic sets is said to be *proper* if, for every irreducible component $X_i$ of $X$, the scheme $X_i$ is complete over the scheme $f(X_i)$ (see the 1955--56 *Séminaire Cartan-Chevalley*).
:::

A more geometric definition is the following: $f$ is proper if, for every algebraic set $Z$, the corresponding map $X\times Z\to Y\times Z$ is *closed*.
Let $f\colon X\to Y$ and $g\colon Y\to Z$ be morphisms of algebraic sets;
if $f$ and $g$ are proper, then $gf$ is proper;
if $gf$ is proper, then $f$ is proper, and $g$ is proper if further the image of $f$ is dense in $Y$.
For $X$ to be complete, it is necessary and sufficient for the morphism from $X$ to an algebraic set consisting of a single point to be proper.
If $X$ is a locally closed subset of a complete variety $X'$, then for $f\colon X\to Y$ to be proper, it is necessary and sufficient for its graph to be closed.
Combining this with Chow's lemma ([§7](#section-7), [Lemma 4](#lemma-4)), the fact that an algebraic subset of an algebraic set over the complex numbers is closed if and only it is closed for the topology of the underlying space [@2, proposition 7, page 12], and the fact that a complex projective space is compact, we easily conclude, from the
above criterion that, in the "classical case", a morphism is proper if and only if the map of underlying analytic spaces is proper in the usual sense (i.e. the inverse image of a compact subset being compact);
\oldpage{2-08}compare with [@2, proposition 12, proposition 6], where a particular case is proven: $X$ is complete if and only if it is compact.


::: {.itenv #theorem-4 title="Theorem 4" latex="{Theorem 4}"}
Let $f\colon X\to Y$ be a proper morphism of algebraic sets.
For any coherent algebraic sheaf $\scr{A}$ on $X$, the algebraic sheaves $\RR^qf_*(\scr{A})$ on $Y$ (and, in particular, the direct image $f_*(\scr{A})$) are coherent.
:::

::: {.proof}
The proof will be given in [§7](#section-7).
:::

We state here the following corollary, obtained by taking $Y$ to be a single point:

::: {.itenv #corollary-4 title="Corollary" latex="{Corollary}"}
Let $\scr{A}$ be a coherent algebraic sheaf on a complete algebraic set.
Then the $\HH^i(X,\scr{A})$ are vector spaces of finite dimension.
:::


# An algebraic-analytic comparison theorem: statement {#section-6}

Let $X$ be an algebraic set over the field of complex numbers, and denote by $X^h$ the underlying analytic set (see [@2] for proper definitions), and by $\scr{O}^h$ or $\scr{O}_X^h$ the sheaf of (analytic) local rings of $X^h$.
The identity map $i_X\colon X^h\to X$ is continuous, and we can thus consider the inverse image $i^{-1}(\scr{O}_X)$, and we have a natural homomorphism of sheaves of rings $i^{-1}(\scr{O}_X)\to\scr{O}_X^h$, which allows us to consider $\scr{O}_X^h$ as a sheaf of algebras over $i^{-1}(\scr{O}_X)$.
If now $\scr{A}$ is an $\scr{O}_X$-module, then $i^{-1}(\scr{A})$ is an $i^{-1}(\scr{O}_X)$-module, and we set
$$
  \scr{A}^h = i^{-1}(\scr{A})\otimes_{i^{-1}(\scr{O}_X)}\scr{O}_X^h
$$
where $\scr{A}^h$ is called the *analytic sheaf associated to $\scr{A}$*.
It is shown in [@2] that the covariant functor $\scr{A}\to\scr{A}^h$ is *exact*.
We have a functorial homomorphism
$$
  i^{-1}(\scr{A}) \to \scr{A}^h
$$
which is injective, and gives homomorphisms (see [§3](#section-3))
$$
  \HH^i(X,\scr{A}) \to \HH^i(X^h,\scr{A}^h).
\tag{2}
$$

We will see that, if $X$ is complete, then the homomorphisms in Equation (2) are isomorphisms.
However, we will actually prove a more general result.
\oldpage{2-09}Let
$$
  f\colon X\to Y
$$
be a morphism of algebraic sets;
consider the map $f^h\colon X^h\to Y^h$.
From the commutative diagram
$$
  \begin{CD}
    X @>f>> Y
  \\@V{i_X}VV @VV{i_Y}V
  \\X^h @>>{f^h}> Y^h
  \end{CD}
$$
we easily obtain a functorial homomorphism
$$
  i_Y^{-1}(f_*(\scr{A})) \to f_*(i_X^{-1}(\scr{A}))
$$
for any sheaf $\scr{A}$ on $X$;
if $\scr{A}$ is an $\scr{O}_X$-module, then the canonical homomorphism $i_X^{-1}(\scr{A})\to\scr{A}^h$ also defines a homomorphism
$$
  f_*^h(i_X^{-1}(\scr{A})) \to f_*^h(\scr{A}^h).
$$
The composition $i_Y^{-1}(f_*(\scr{A}))\to f_*^h(\scr{A}^h)$ of these homomorphisms is compatible with the canonical homomorphism $i_Y^{-1}(\scr{O}_Y)\to\scr{O}_Y^h$ of rings of operators, whence, by tensoring with a canonical homomorphism, we obtain
$$
  f_*(\scr{A})^h \to f_*^h(\scr{A}^h).
\tag{3}
$$

This functorial homomorphism can be extended, in a unique way, to functorial homomorphisms (that commute with the coboundary operators):
$$
  (\RR^qf_*(\scr{A}))^h \to \RR^qf_*^h(\scr{A}^h).
\tag{4}
$$

These homomorphisms have all the functorial properties that we might desire, but whose precise statements will not be given here (even though they will, of course, be essential in the proofs.)

::: {.itenv #theorem-5 title="Theorem 5" latex="{Theorem 5}"}
Suppose that the morphism of algebraic sets $f\colon X\to Y$ is proper.
Then the homomorphisms in Equation (4) are isomorphisms.
:::

::: {.proof}
The proof will be given in [the following section](#section-7).
:::

Taking $Y$ to be a single point, we obtain the following:

::: {.itenv #corollary1-5 title="Corollary 1" latex="{Corollary 1}"}
If $X$ is a complete algebraic set, then the homomorphisms in Equation (2) are isomorphisms.
:::

Since $A\to A^h$ sends coherent algebraic sheaves to coherent analytic sheaves (an immediate consequence of the exactness of the functor), the combination of [Theorem 4](#theorem-4) and [Theorem 5](#theorem-5) gives:

::: {.itenv #corollary2-5 title="Corollary 2" latex="{Corollary 2}"}
Under the conditions of [Theorem 5](#theorem-5), the $f^h(\scr{A}^h)$ are coherent analytic sheaves.
:::

\oldpage{2-10}It is very plausible that, more generally, if $g\colon V\to W$ is a proper holomorphic map of analytic spaces, and if $\scr{F}$ is a coherent analytic sheaf on $V$, then $g_*(\scr{F})$ is a coherent analytic sheaf.
This is indeed true if the sets $f^{-1}(y)$ (for $y\in W$) are finite (as we can see by a classical theorem of Oka; see the 1953/54 *Séminaire Cartan*), or if $W$ consists of a single point (by a result of Serre-Cartan, *loc. cit.*).

::: {.itenv #corollary3-5 title="Corollary 3" latex="{Corollary 3}"}
Under the conditions of [Theorem 5](#theorem-5), suppose further that $Y$ is an *affine* algebraic set, and let $A(Y)$ (resp. $A^h(Y)$) be the ring of regular functions on $Y$ (resp. the ring of holomorphic functions on $Y^h$).
Then there is a canonical isomorphism
$$
  \HH^q(X^h,\scr{A}^h) = \HH^q(X,\scr{A})\otimes_{A(Y)}A^h(Y).
\tag{5}
$$
:::

::: {.proof}
We have already said that $\HH^q(X,\scr{A})$ can be identified with the module of sections of $\RR^qf_*(\scr{A})$ over $Y$, and, similarly, we say that $\HH^q(X^h,\scr{A}^h)$ can be identified with the module of sections of $\RR^qf_*^h(\scr{A}^h)$ over $Y$.
To prove this, it suffices to use the Leray spectral sequence of $f^h$ (see [§3](#section-3)), and to note that, identifying $Y^h$ with a closed analytic subset of some $\mathbf{C}^n$, its cohomology with values in the coherent analytic sheaves $\RR^qf_*^h(\scr{A}^h)$ is zero in dimensions $>0$, by a fundamental theorem of Cartan (see the 1951/52 *Séminaire Cartan*).
It thus suffices, by [Theorem 5](#theorem-5), to prove that, if $\scr{B}$ is a coherent $\scr{O}_Y$-module on an affine variety $Y$, then
$$
  \HH^0(Y^h,\scr{B}) = \HH^0(Y,\scr{B})\otimes_{A(Y)}\scr{A}^h(Y).
\tag{6}
$$
But we note that both sides of this equation are exact functors in $\scr{B}$, which means we only need to verify Equation (6) in the case where $\scr{B}=\scr{O}_Y$, but then it is trivial.
:::


# Proof of Theorems 4 and 5 {#section-7}

The proofs follow mainly from [Theorem 3](#theorem-3), the "dévissage" of [Theorem 2](#theorem-2) (which is necessary since there is no reason for $X$ to be isomorphic to a locally closed subset of a projective space), and the following:

::: {.itenv #lemma-4 title="Lemma 4" latex="{Lemma 4}"}
*(Chow's lemma.) ---*
Let $X$ be a an irreducible algebraic set
Then there exists an algebraic set $X'$ that is locally closed in some projective space $\mathbf{P}$, and a proper birational morphism $g\colon X'\to X$.
:::

\oldpage{2-11}Recall ([§5](#section-5)) that "proper implies, in this case, that the graph of $g$ is a *closed* subset of $\mathbf{P}\times X$.
Here we only make use of the fact that $g$ is *proper* and *surjective*.

:::: {.proof}
We cover $X$ by affine open subsets $X_i$, with each $X_i$ locally closed in some projective space $\mathbf{P}_i$, whence we have a diagonal map $\bigcap X_i\to\coprod\mathbf{P}_i$.
We take $X'$ to be the closure in $X\times\coprod\mathbf{P}_i$ of the graph of this diagonal map (or, really, $X'$ is its normalisation).

[Theorem 4](#theorem-4) and [Theorem 5](#theorem-5) say that every coherent algebraic sheaf $\scr{A}$ on $X$ satisfies a certain property.
But we immediately see that, in both cases, the class $\cal{K}$ of the $\scr{A}\in K(X)$ having the property in question is an *exact* subcategory ([§2](#section-2), [Definition 1](#definition-1)), by using the exact sequence of the $\RR^qf_*$ (and the $\RR^qf_*^h$) corresponding to an exact sequence of sheaves $0\to\scr{A}'\to\scr{A}\to\scr{A}''\to0$, and by using either the fact that, if in an exact sequence of $\scr{O}_X$-modules $\scr{A}\to\scr{B}\to\scr{C}\to\scr{D}\to\scr{E}$, the four outer terms are coherent, then so too is $\scr{C}$, or (in the case of [Theorem 5](#theorem-5)) the classical 5 lemma.
By [Theorem 2](#theorem-2), it thus suffices to find, for every irreducible closed subset $Z$ of $X$, a coherent algebraic sheaf *on $Z$*, with support equal to $Z$, and belonging to $K$.
Note that the restriction of $f$ to $Z$ is again proper, and so we can assume that $Z=X$, which means it suffices to find *one* coherent $\scr{O}_Y$-module $\scr{A}$, with support equal to $X$, such that $\scr{A}\in\cal{K}$.
Consider the morphism $f'\colon X'\to X$ described in [Lemma 4](#lemma-4).
Since $X'$ is embedded into $\mathbf{P}$, we can consider the sheaves $\scr{O}_{X'}(n)$ on $X'$ given by reducing the $\scr{O}_\mathbf{P}(n)$ (see [§4](#section-4)) modulo the sheaf of ideals defined by $X'$ in $\mathbf{P}$.
We claim that, for $n$ large enough, the sheaf $\scr{A}=f(\scr{O}_{X'}(n))$ is in $\cal{K}$ (which will finish the proof, since the support of this sheaf is clearly equal to $X$).
This will follow from:

::: {.itenv #lemma-5 title="Lemma 5" latex="{Lemma 5}"}
Let $g\colon V\to W$ be a *proper* morphism of algebraic sets, with $V$ a locally closed subset of a projective space $\mathbf{P}$.
Let $\scr{G}$ be a coherent algebraic sheaf on $V$.
Then, for $n$ large enough,
$$
  \RR^pf_*(\scr{G}(n))=0
$$
for $p>0$, and $f_*(\scr{G}(n))$ is coherent.
Furthermore, if $k=\mathbf{C}$, then
$$
  \RR^pf_*^h(\scr{G}(n)^h)=0
$$
for $p>0$, and
$$
  (f_*(\scr{G}(n)))^h\to f_*^h(\scr{G}(n)^h)
$$
is an isomorphism.
:::

First we will show how this lemma will imply the previous one.
Applying the lemma to $f'\colon X'\to X$, we immediately see, from the definitions, and from the fact that $\RR^pf_*(\scr{O}(n))=0$ for $p>0$, that
$$
  \RR^p(ff')_*(\scr{O}(n)) = \RR^pf_*(f'(\scr{O}(n))) = \RR^pf_*(\scr{A}).
$$
\oldpage{2-12}But the first object is zero for $p>0$ and large enough $n$, by [Lemma 5](#lemma-5) applied to $ff'\colon X'\to Y$, and so $\RR^pf_*(\scr{A})=0$ for $p>0$, and, a fortiori, $\RR^pf_*(\scr{A})$ is coherent for $p>0$;
similarly, $f_*(\scr{A})$ is coherent, since $f_*(\scr{A})=(ff')_*(\scr{O}(n))$, and so it suffices to apply [Lemma 5](#lemma-5) to $ff'$.
This thus proves that $\scr{A}\in\cal{K}$ in the setting of [Theorem 4](#theorem-4).
In the setting of [Theorem 5](#theorem-5), the same argument proves that, if $n$ is large enough, $\RR^pf_*^h(\scr{A}^h)=0$ for $p>0$, and, a fortiori, the homomorphisms in Equation (4) are isomorphisms for $q>0$;
similarly, the homomorphism $(f_*(\scr{A}))^h\to f_*^h(\scr{A}^h)$ is an isomorphism, since both the domain and codomain can be identified (respectively) with $((ff')_*(\scr{O}(n)))^h$ and $f^h(\scr{A}^h)=f_*'^h(\scr{O}(n)^h)$ (since $\scr{A}^h=(f'(\scr{O}(n)))^h=f_*'^h(\scr{O}(n)^h)$, by [Lemma 5](#lemma-5) applied to $ff'\colon X'\to Y$).

It thus remains only to prove [Lemma 5](#lemma-5).
Since the graph $V'$ of $g$ is a closed subset of $\mathbf{P}\times W$, isomorphic to $V$, we can, by identifying sheaves on $V$ with sheaves on $V'$ (and thus on $\mathbf{P}\times W$), suppose that $V=\mathbf{P}\times W$, and that $g$ is the projection homomorphism.
Furthermore, we can suppose that $W$ is affine, and even that $W=k^m$.

We first prove [Lemma 5](#lemma-5) in the case where $\scr{F}=\scr{O}_k$.
For an arbitrary field $k$, this thus implies that $\HH^p(\mathbf{P}\times W,\scr{O}(n))=0$ for $p>0$ and $n$ large enough, and that $\HH^0(\mathbf{P}\times W,\scr{O}(n))$ is a module of finite type over the coordinate ring $A(W)$ of $W$.
Since $\scr{O}_{\mathbf{P}\times W}(n)$ is the "tensor product" (in the sense of algebraic sheaves) of the sheaves $\scr{O}_\mathbf{P}(n)$ on $\mathbf{P}$ and $\scr{O}_W$ on $W$, the Künneth formula (whose proof, in this setting, is elementary) applies, and we thus obtain the stated result, taking into account the fact that $\HH^i(W,\scr{O})=0$ for $i>0$ (part (c) of [Theorem 1](#theorem-1)) and part (b) of [Theorem 3](#theorem-3), since then
$$
  \HH^i(\mathbf{P}\times W,\scr{O}_{\mathbf{P}\times W}(n))
  = \HH^i(\mathbf{P},\scr{O}_\mathbf{P}(n))\otimes_\scr{F} A(W)
$$
is zero for $i>0$ and $n$ large enough, and is of finite type over $A(W)$ when $i=0$, since $\HH^0(\mathbf{P},\scr{O}_\mathbf{P}(n))$ is clearly of finite dimension.
When $k=\mathbf{C}$, we must prove that, for $n$ large enough,
$$
  \HH^i(\mathbf{P}^h\times W',\scr{O}(n)^h)=0
$$
for $i>0$ and $W'$ any Stein open subset of $W^h$, and also that $f_*(\scr{O}(n)^h)$ can be identified with $(f_*(\scr{O}(n)))^h$, i.e. with $\HH^0(\mathbf{P},\scr{O}(n))\otimes\scr{O}_W^h$;
or, in other words, that
$$
  \HH^i(\mathbf{P}^h\times W',\scr{O}(n))
  = \HH^0(\mathbf{P},\scr{O}(n))\otimes\HH^0(X',\scr{O}_W^h)
$$
for every Stein open subset $W'$ of $W$.
\oldpage{2-13}But $H^\bullet(\mathbf{P}^h\times W',\scr{O}(n)^h)$ can be calculated by a *vectorial-topological variant of the Künneth theorem* (using the fact that the space $\HH^0(W',\scr{O}_{W'}^h)$ is \emph{nuclear};
see the 1953/54 \emph{Séminaire Schwartz});
taking into account the fact that $\HH^i(W',\scr{O}_W)=0$ for $i>0$, we see that it is equal to $\HH^i(\mathbf{P}^h,\scr{O}(n)^h)\otimes\HH^0(W',\scr{O}_w)$, by a fundamental theorem of Cartan concerning Stein varieties (which, for our purposes here, it suffices to know for a polycylinder and the structure sheaf. where it is an easy consequence of the aforementioned vectorial-topological Künneth theorem).
The above claims then follow from corollary (b) of [Theorem 3](#theorem-3), taking into account the fact that $\HH^0(\mathbf{P}^h,\scr{O}(n)^h)=\HH^0(\mathbf{P},\scr{O}(n))$ (which is proven in the proof of that corollary).

To prove [Lemma 5](#lemma-5) in the general case, we proceed by induction on $p$, since the lemma is trivial for $p$ large enough, for dimension reasons.
By part (a) of [Theorem 3](#theorem-3), $\scr{A}$ is isomorphic to a quotient of some $\scr{O}(m)^k=\scr{L}$, i.e. we have an exact sequence $0\to\scr{A}'\to\scr{L}\to\scr{A}\to0$, whence, for all $n$, an exact sequence
$$
  0 \to \scr{A}'(n) \to \scr{L}(n) \to \scr{A}(n) \to 0
$$
which gives an exact sequence
$$
  \RR^pf_*(\scr{A}'(n))
  \to \RR^pf_*(\scr{L}(n))
  \to \RR^pf_*(\scr{A}(n))
  \to \RR^{p+1}f_*(\scr{A}'(n)).
$$
By the induction hypothesis, the last term in this sequence is zero for $n$ large enough, and so too is $\RR^pf_*(\scr{L}(n))$ when $p>0$, by what we have already proven, whence $\RR^pf_*(\scr{A}(n))=0$ for $n$ large enough and $p>0$.
If $p=0$, then the same exact sequence proves that, for $n$ large enough, $f_*(\scr{A}(n))$ is coherent, since $f_*(\scr{L}(n))$ is coherent, and $f_*(\scr{A}'(n))$ is anyway quasi-coherent.
In the case where $k=\mathbf{C}$, we can prove, in the same way, that $\RR^pf_*^h(\scr{A}(n)^h)=0$ for $n$ large enough and $p>0$.
It remains only to show that, for $n$ large enough, $(f_*(\scr{A}(n)))^h\to f^h(\scr{A}^h)$ is bijective.
For this, we write $\scr{A}$ as the cokernel of a homomorphism $\scr{L}'\to\scr{L}$, where $\scr{L}$ and $\scr{L}'$ are isomorphic to direct sums of sheaves of the form $\scr{O}(m)$ for various $m$ (which is possible by part (a) of [Theorem 3](#theorem-3)).
By the above, for $n$ large enough $f_*(\scr{A}(n))$ and $f_*^h(\scr{A}(n)^h)$ can be identified (respectively) with the cokernel of $f_*(\scr{L}'(n))\to f(\scr{L}(n))$ and the cokernel of $f^h(\scr{L}'(n)^h)\to f^h(\scr{L}(n)^h)$;
taking into account the fact that the functor $\scr{B}\to\scr{B}^h$ is exact, we thus obtain a homomorphism of exact sequences
$$
  \begin{CD}
    (f_*(\scr{L}'(n)))^h @>>> (f_*(\scr{L}(n)))^h @>>> (f_*(\scr{A}(n)))^h @>>> 0
  \\@VVV @VVV @VVV
  \\f_*^h*(\scr{L}'(n)^h) @>>> f_*^h*(\scr{L}(n)^h) @>>> f_*^h*(\scr{A}(n)^h) @>>> 0
  \end{CD}
$$
\oldpage{2-14}Since, for $n$ large enough, the first two vertical arrows are isomorphisms, so too is the third, by the five lemma, which finishes the proof.
::::

::: {.rmenv title="Remark" latex="{Remark}"}
The last paragraph of this proof can be simplified if we use the fact that $\scr{A}$ admits a finite resolution by sheaves that are direct sums of sheaves of the form $\scr{O}(m)$ for various $m$;
but this fact is less elementary than part (a) of [Theorem 3](#theorem-3), and so we wanted to avoid using it.
:::


# Algebraic and analytic sheaves on a compact algebraic variety {#section-8}

We are going to complete [Corollary 1 of Theorem 5](#corollary1-5):

::: {.itenv #theorem-6 title="Theorem 6" latex="{Theorem 6}"}
Let $X$ be a complete algebraic set over $\mathbf{C}$.
Then every coherent analytic sheaf $\scr{F}$ on $X^h$ is isomorphic to a sheaf $\scr{A}^h$, where $\scr{A}$ is an essentially unique coherent algebraic sheaf on $X$.
:::

The uniqueness of $\scr{A}$ follows from:

::: {.itenv #corollary1-6 title="Corollary 1" latex="{Corollary 1}"}
With $X$ as above, let $\scr{A}$ and $\scr{B}$ be coherent algebraic sheaves on $X$.
Then the natural homomorphism
$$
  \shHom_{\scr{O}_X}(\scr{A},\scr{B}) \to \shHom_{\scr{O}_X^h}(\scr{A}^h,\scr{B}^h)
\tag{7}
$$
is bijective.
:::

::: {.proof}
This homomorphism comes from, by taking sections, the monomorphism of sheaves
$$
  i_X^{-1}(\shHom_{\scr{O}_X}(\scr{A},\scr{B})) \to \shHom_{\scr{O}_X^h}(\scr{A},\scr{B})
$$
(where $\shHom$ denotes the sheaf of germs of homomorphisms), but we already know that
$$
  (\shHom_{\scr{O}_X}(\scr{A},\scr{B}))^h = \shHom_{\scr{O}_X^h}(\scr{A}^h,\scr{B}^h)
\tag{8}
$$
(an almost immediate consequence of the fact that $\cal{C}\to\cal{C}^h$ is exact), and so, by applying [Corollary 1 of Theorem 5](#corollary1-5) to the sheaf $\shHom_{\scr{O}_X}(\scr{A},\scr{B})$ with $i=0$, the result follows.
:::

From [Corollary 1](#corollary1-6) and the exactness of the functor $\cal{C}\to\cal{C}^h$ also follows the fact that, if $\scr{F}$ and $\scr{G}$ are coherent analytic sheaves on $X$ that come from algebraic sheaves, and if $u$ is a homomorphism from $\scr{F}$ to $\scr{G}$, then the kernel, cokernel, image, and coimage of $u$ all also come from algebraic sheaves.
\oldpage{2-15}In particular, if $X$ is embedded into a projective space $\mathbf{P}$, then every coherent analytic sheaf on $X$ is isomorphic to the cokernel of a homomorphism $\scr{L}^h\to\scr{L}'^h$, where $\scr{L}$ and $\scr{L}'$ are direct sums of finitely many sheaves of the form $\scr{O}(k)$ (part (a) of the [Corollary of Theorem 3](#corollary-3));
it thus follows that [Theorem 6](#theorem-6) is also true if $X$ is *projective* (Serre).

Let $0\to\scr{F}'\to\scr{F}\to\scr{F}''\to0$ be an exact sequence of coherent analytic sheaves on $X^h$, and suppose that $\scr{F}'$ and $\scr{F}''$ come from coherent algebraic sheaves;
we then claim that so too does $\scr{F}$.
Suppose that $\scr{F}'=\scr{A}'^h$ and $\scr{F}''=\scr{A}''$, where $\scr{A}'$ and $\scr{A}''$ are coherent algebraic sheaves;
it suffices to show that the set $\Ext_{\scr{O}_X}^1(X;\scr{A}'',\scr{A}')$ of classes of $\scr{O}$-module extensions of $\scr{A}''$ by $\scr{A}'$ can be identified with the analogous set $\Ext_{\scr{O}_X^h}^1(X^h;\scr{A}''^h,\scr{A}'^h)$.
But, more generally, we have canonical homomorphisms
$$
  \Ext_{\scr{O}_X}^i(X;\scr{A}'',\scr{A}')
  \to 
  \Ext_{\scr{O}_X^h}^i(X;\scr{A}''^h,\scr{A}'^h)
\tag{9}
$$
(defined without any restrictions on $X$, $\scr{A}'$, or $\scr{A}''$), which are here isomorphisms, as follows from the spectral sequence of $\Ext$ of sheaves of modules (see the 1957 *Séminaire Grothendieck*), from the elementary local relations
$$
  (\shExt_{\scr{O}_X}^i(\scr{A},\scr{B}))^h
  = \shExt_{\scr{O}_X^h}^i(\scr{A}^h,\scr{B}^h)
\tag{10}
$$
that generalise Equation (8) (with $\shExt$ denoting the *sheaf* $\Ext$s), and from [Corollary 1 of Theorem 5](#corollary1-5);
this implies that the initial pages of the spectral sequences of both the domain and codomain of the morphism in Equation (9) are identical.

::: {.proof}
*(Proof of [Theorem 6](#theorem-6).) ---*
We can now prove [Theorem 6](#theorem-6), by induction on $n=\dim X$, with the theorem being trivial when $n=0$.
So suppose that $n>0$, and that the theorem is true in dimensions $<n$.
Proceeding as in the end of the proof of [Theorem 2](#theorem-2), we can restrict to the case where $X$ is irreducible.
So consider the map $f\colon X'\to X$ considered in Chow's lemma ([Lemma 4](#lemma-4)), with $X'$ a *projective* variety, and $f$ a *birational* morphism.
For every analytic sheaf $\scr{F}$ on $X$, let
$$
  \scr{F}' = f^{-1}(\scr{F})\otimes_{f^{-1}(\scr{O}_X^h)}\scr{O}_X^h
$$
(where the tensor product makes sense, since $\scr{O}_X^h$ is a module over $f^{-1}(\scr{O}_X^h)$, which can be identified with a subsheaf (of rings) of $\scr{O}_X^h$).
It is easy to prove that, if $\scr{F}$ is coherent, then so too is $\scr{F}'$.
\oldpage{2-16}Furthermore, there is a natural homomorphism
$$
  \scr{F} \to f_*^h(\scr{F}')
$$
and, in the current setting, this homomorphism is bijective outside of an algebraic set $Y$ of dimension $<n$ (where $Y$ is the set of points of $X$ over which $f$ is not biregular).
We thus have an exact sequence
$$
  0 \to \scr{T} \to \scr{F} \to f_*^h(\scr{F}') \to \scr{T}' \to 0
$$
where $\scr{T}$ and $\scr{T'}$ have support contained inside $Y$.
Using the analogue of [Lemma 1](#lemma-1) from [§2](#section-2) (thanks to the compactness of $X$), we find that $\scr{T}$ (and even $\scr{T}'$) admits a composition series with composition factors that are coherent analytic sheaves *on $Y$*.
These quotients are in fact "algebraic", by the induction hypothesis;
thus so too are their extensions $\scr{T}$ and $\scr{T}'$.
Furthermore, since $X'$ is projective, $\scr{F}'$ is also "algebraic", by what we have already said, and thus so too is $f_*^h(\scr{F}')$, by [Theorem 5](#theorem-5) applied to $f\colon X'\to X$ and $\scr{F}'=\scr{B}^h$.
Thus the kernel of $f_*^h(\scr{F}')\to\scr{T}'$ is also algebraic, and thus so too is $\scr{F}$, which is an extension of this kernel by $\scr{T}$.
Thus we have proved [Theorem 6](#theorem-6).
:::
