--- 
title: "Mixed manifolds and mixed spaces"
author: "Adrien Douady"
date: "7th of November, 1960"
original: 'Douady, A. "Variétés et espaces mixtes". _Séminaire Henri Cartan_ **13 (1)** (1960--61), Talk no. 2. [`http://www.numdam.org/item/SHC_1960-1961__13_1_A1_0`](http://www.numdam.org/item/SHC_1960-1961__13_1_A1_0)'
bibliography: SHC-13(1)-2.bib
nocite: '@*'
link-citations: true
csl: maths-translations.csl
reference-section-title: "Bibliography"
github-repo: "thosgood/translations"
favicon: "favicon.ico"
---

```{js, echo = FALSE}
$(document).ready(function(e) {gitbook.sidebar.toggle(false, false)});
```

```{r, child = '_translator-note.Rmd'}
```

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\RR}{\mathbb{R}}
\providecommand{\CC}{\mathbb{C}}
\providecommand{\DD}{\mathrm{D}}
\providecommand{\HH}{\mathrm{H}}

<!-- Content -->

# I. Category of models {.unnumbered #section-I}

\oldpage{2-01}
Let $B$ be a topological space.
We define the category $\mathscr{S}_B^n$ in the following manner: the objects of $\mathscr{S}_B^n$ are the open subsets of $B\times\CC^n$, and a morphism $f\colon U\to U'$ from an open subset $U\subset B\times\CC^n$ to an open subset $U'\subset B\times\CC^n$ is a continuous map $f\colon U\to U'$ satisfying the following two conditions:

1. the diagram
    $$
      \begin{CD}
        U @>f>> U'
      \\@V{\pi_1}VV @VV{\pi_1}V
      \\B @= B
      \end{CD}
    $$
    commutes, where $\pi_1$ denotes the projection of $B\times\CC^n$ to $B$; and
2. for all $x\in B$, the map $f_x\colon U_x\to U'_x$ is holomorphic, where
    $$
      U_x = \{z\in\CC^n \mid (x,z)\in U\}
    $$
    (and similarly for $U'$).

If $B$ is endowed with the structure of a $\mathscr{C}^\infty$ manifold (resp. an $\RR$-analytic manifold, resp. $\CC$-analytic manifold), then we obtain a category $\mathscr{C}^\infty\mathscr{S}_B$ (resp. $\RR\mathscr{S}_B$, resp. $\CC\mathscr{S}_B$) by requiring the morphisms to be $\mathscr{C}^\infty$ (resp. $\RR$-analytic, resp. $\CC$-analytic).

More generally, if $f_1\colon B\to B'$ is a continuous map from one topological space to another, then a *morphism of $\mathscr{S}_{f_1}$* is a continuous map $f$ from an object $U$ of $\mathscr{S}_B$ to an object $U'$ of $\mathscr{S}_{B'}$ such that

1. the diagram
    $$
      \begin{CD}
        U @>f>> U'
      \\@V{\pi_1}VV @VV{\pi_1}V
      \\B @>>{f_1}> B'
      \end{CD}
    $$
    commutes; and
2. $f_x\colon U_x\to U'_{f_1(x)}$ is holomorphic for all $x\in B$.

\oldpage{2-02}
If $f_1$ is a $\mathscr{C}^\infty$ map from one $\mathscr{C}^\infty$ manifold to another, then $f$ will be a morphism of $\mathscr{C}^\infty\mathscr{S}_{f_1}$ if, further, it is a $\mathscr{C}^\infty$ map (resp. ...).
We thus obtain, for every category of topological spaces, a fibred category $\mathscr{S}^n$ (resp. $\mathscr{C}^\infty\mathscr{S}^n$, resp. ...).


# II. The definition of mixed spaces and mixed varieties {.unnumbered #section-II}

## 1. First definition {.unnumbered #section-II.1}

Let $B$ and $V$ be separated spaces, and let $\pi\colon V\to B$ be a continuous map.
The structure of a *mixed space* over $B$ is defined on $V$ by a system of charts $\varphi_i\colon U_i\to V$, where the $(U_i)$ are objects of $\mathscr{S}_B^n$;
for each $i$, $\varphi_i$ is a homeomorphism from $U_i$ to an open subset of $V$ such that the diagram
$$
  \begin{CD}
    U_i @>{\varphi_i}>> V
  \\@V{\pi_1}VV @VV{\pi}V
  \\B @= B
  \end{CD}
$$
commutes;
finally, for all $i$ and all $j$, the "change of chart" $\varphi_j^{-1}\circ\varphi_i$ is an isomorphism of $\mathscr{S}_B$ from an open subset of $U_i$ to an open subset of $U_j$.

The structure thus defined is that of a *$(\mathscr{C}^0,\CC)$-mixed space*.
If $B$ is a $\CC$-analytic space, and if the change of chart maps are all $\CC$-analytic, then we have a *$\CC$-analytic mixed space*.
In this case, $V$ itself is a $\CC$-analytic space, and the fibres $V_x=\pi^{-1}(x)$ are $\CC$-analytic sub-manifolds.

If $B$ is a $\mathscr{C}^\infty$ manifold (resp. $\RR$-analytic, resp. $\CC$-analytic), and if the change of chart maps are all $\mathscr{C}^\infty$ (resp. ...), then we have a *$(\mathscr{C}^\infty,\CC)$-mixed manifold* (resp. $(\RR,\CC)$, resp. $(\CC,\CC)$).
In this case, $V$ itself is a manifold.
Note that the notion of a $(\CC,\CC)$-mixed manifold, or a $\CC$-analytic mixed manifold, reduces to simply having a $\CC$-analytic manifold $V$ endowed with a projection $\pi\colon V\to B$ onto another $\CC$-analytic manifold such that $\pi$ is of maximal rank at every point.^[*[Trans.] The more common modern nomenclature is to simply call such an object a* family of complex manifolds*.*]

Let $\pi\colon V\to B$ and $\pi'\colon V'\to B'$ be mixed spaces, and let $f_1\colon B\to B'$ be a continuous (resp. ...) map.
Then a *morphism from $V$ to $V'$ over $f_1$* is a continuous map $f\colon V\to V'$ such that the diagram
$$
  \begin{CD}
    V @>f>> V'
  \\@V{\pi}VV @VV{\pi'}V
  \\B @>>{f_1}> B'
  \end{CD}
$$
commutes, and such that, for any charts $\varphi_i\colon U_i\to V$ and $\varphi'_j\colon U'_j\to V'$, the map ${\varphi'_j}^{-1}\circ f\circ\varphi_i$ is a morphism of $\mathscr{S}_{f_1}$ (resp. ...) from an open subset of $U_i$ to $U_j$.
\oldpage{2-03}


## 2. An equivalent definition {.unnumbered #section-II.2}

We now give another way of defining mixed spaces, equivalent to the above.

Given separated spaces $B$ and $V$, along with a continuous map $\pi\colon V\to B$, the structure of a *pre-mixed space* consists of the structure of a $\CC$-analytic manifold on each fibre $V_x=\pi^{-1}(x)$.
Given pre-mixed spaces $\pi\colon V\to B$ and $\pi'\colon V'\to B'$, along with a continuous map $f_1\colon B\to B'$, a *morphism of pre-mixed spaces over $f_1$* is a continuous map $f\colon V\to V'$ such that the diagram
$$
  \begin{CD}
    V @>f>> V'
  \\@V{\pi}VV @VV{\pi'}V
  \\B @>>{f_1}> B'
  \end{CD}
$$
commutes and induces a $\CC$-analytic map on each fibre.

A *mixed space* is a pre-mixed space $\pi\colon V\to B$ such that every point $y\in V$ admits a neighbourhood $W$ in $V$ that is isomorphic as a pre-mixed space to an open subset of $B\times\CC^n$, via an isomorphism over the identity.
The morphisms of mixed spaces are the same: mixed spaces form a *full subcategory*.


## 3. Deformations {.unnumbered #section-II.3}

A mixed space $\pi\colon V\to B$ is said to be *proper* if $B$ is locally compact and the map $\pi$ is proper (i.e. the inverse image of any compact subset is compact).
If it is a mixed manifold, then we can show that it is a fibred manifold that is locally trivial with respect to the underlying $\mathscr{C}^\infty$ structure, but the previous talk shows that, in general, any two fibres are not isomorphic as $\CC$-analytic manifolds.

::: {.rmenv title="Definition" latex="{Definition}"}
Let $V_0$ be a compact $\CC$-analytic manifold, $B$ a locally compact space, and $b_0\in B$.
\oldpage{2-04}
Then a *$\CC$-analytic deformation of $V_0$ over $(B,b_0)$* consists of a proper $\CC$-analytic mixed space $\pi\colon V\to B$ along with an isomorphism of $\CC$-analytic manifolds $i\colon V_0\to\pi^{-1}(b_0)$.
:::

The goal of this seminar is the study, at least local, and an attempt at a classification of, $\CC$-analytic deformations of a given compact $\CC$-analytic manifold $V_0$.

::: {.rmenv title="Definition" latex="{Definition}"}
Let $V_0$ be a compact $\CC$-analytic manifold.
A *$\CC$-analytic deformation $(\pi\colon V\to B,i\colon V_0\to V)$ of $V_0$* is said to be *locally complete* if, for any other deformation $(\pi'\colon V'\to B',i'\colon V_0\to V')$ of $V_0$, there exists a neighbourhood $B'_1$ of $b'_0$ in $B'$, an analytic map $f_1\colon B'_1\to B$ with $f_1(b'_0)\to b_0$, and a morphism of $\CC$-analytic mixed spaces $f\colon {\pi'}^{-1}(B'_1)\to V$ over $f_1$ such that $f\circ i'=i$.
The deformation is said to be *locally universal* is furthermore the germ of $f_1$ at $b'_0$ is determined uniquely by this condition.
:::

It seems that every compact $\CC$-analytic manifold $V_0$ admits a locally complete $\CC$-analytic deformation, and a locally universal one if the group of automorphisms of $V_0$ is discrete.


# III. Vector fields {.unnumbered #section-III}

# 1. Study on models {.unnumbered #section-III.1}

Let $B$ be a space, $U$ an object of $\mathscr{S}_B$ (i.e. an open subset of $B\times\CC^n$), $b_0$ a point of $B$, and set $U_0=\pi^{-1}(b_0)$.

A holomorphic field of tangent vectors on $U_0$ (i.e. a holomorphic map from $U_0$ to $\CC^n$) is said to be a *vertical holomorphic field* on $U_0$.
A *vertical holomorphic field on $U$* is a continuous (resp. ...) map $\theta\colon U\to\CC^n$ that induces a vertical holomorphic field on each fibre $U_x$.
If $f\colon U\to U'$ is an isomorphism in $\mathscr{S}_B$, then the *transport $f_*\theta$ of $\theta$ by $f$* is defined by
$$
  f_*\theta(f(x,z)) = \DD_2 f_{x,z}\cdot\theta(x,z)
$$
where $\DD_2 f_{x,z}$ is the linear map from $\CC^n$ to itself that is tangent to $f_x$ at the point $z\in U_x$.
This is again a vertical holomorphic field, since it follows from a Cauchy integral that the matrix $\DD f_{x,z}$ depends continuously on the pair $(x,z)$.

Now suppose that $B$ is a $\mathscr{C}^\infty$ manifold, just for simplicity, and let $T_0$ be the tangent space to $B$ at $b_0$.
\oldpage{2-05}
A field of tangent vectors to $U$ defined on $U_0$, i.e. a map $\omega\colon U_0\to T_0\times\CC^n$, is said to be a *projectable holomorphic field* if $\omega(b_0,z)=(t_0,\theta(z))$ (where $t_0\in T_0$ is a vector that does not depend on $z$, called the *projection* of the field $\omega$) and $\theta(z)$ is a holomorphic vector field.
If $B$ is a $\CC$-analytic space, possibly with a singularity at $b_0$, then we give the same definition, but with $T_0$ then being the *Zariski* tangent space to $B$ at $b_0$, i.e. the dual of $\mathfrak{m}/\mathfrak{m}^2$, where $\mathfrak{m}$ is the ideal of germs at $b_0$ of holomorphic functions on $B$ that vanish at $b_0$.

If $f\colon U\to U'$ is an isomorphism of $\mathscr{C}^\infty\mathscr{S}_B$ (resp. ...), then then transport $f_*\omega$ is defined by
$$
  f_*\omega(f(b_0,z)) = \DD f_{b_0,z}\omega(b_0,z)
$$
where $\DD f_{b_0,z}\colon T_0\times\CC^n\to T_0\times\CC^n$ is now the linear map that is tangent to $f$ at the point $(b_0,z)$.
This is a projectable holomorphic field.
Indeed, the matrix $\DD f_{b_0,z}$ can be written as
$$
  \begin{pmatrix}
    I & 0
  \\\DD_1f & \DD_2f
  \end{pmatrix}
$$
and
$$
  \begin{aligned}
    \DD_1f\colon T &\to \CC^n
  \\\DD_2f\colon \CC^n &\to \CC^n
  \end{aligned}
$$
both depend holomorphically on $z$ (for $\DD_1f$, this follows from the fact that $f_x$ is holomorphic for every $x$).
By setting $f_*\omega(b_0,z')=(t_0,\theta'(z'))$, we have
$$
  \begin{gathered}
    \theta'(z') = \DD_1f_{b_0,z}(t_0) + \DD_2f_{b_0,z}(\omega(z))
  \\\mbox{if $z'=f_{b_0}(z)$}
  \end{gathered}
$$
which shows that $f_*\omega$ is indeed a projectable holomorphic field.

A *projectable holomorphic field on $U$* is a $\mathscr{C}^\infty$ field of vectors tangent to $U$ that induces a projectable holomorphic field on each fibre.


## 2. Vector fields on a mixed manifold {.unnumbered #section-III.2}

Let $\pi\colon V\to B$ be a $(\mathscr{C}^\infty,\CC)$-mixed manifold (resp. ..., resp. a $\CC$-analytic mixed space).
By transporting along the charts, we define the notions of

- vertical holomorphic fields on an open subset of a fibre;
- vertical holomorphic fields on a open subset of $V$;
- projectable holomorphic fields on an open subset of a fibre; and
- projectable holomorphic fields on an open subset of $V$.

\oldpage{2-06}
Let $\xi$ be a $\mathscr{C}^\infty$ vector field (resp. ...) on $V$.
By integrating $\xi$, we obtain a $\mathscr{C}^\infty$ map, denoted by $e^\xi$, from an open subset $W\subset\RR\times V$ containing $\{0\}\times V$ (resp. $\CC$-analytic map from an open subset $W\subset\CC\times V$) to $V$, characterised by

1. $e^\xi(t_1+t_2,y) = e^\xi(t_1,e^\xi(t_2,y))$, with the left-hand side being defined whenever the right-hand side is; and
2. $\frac{\partial}{\partial t}e^\xi(t,y)|_{0,y} = \xi(y)$.

Note that $W$ is a mixed manifold over $\RR\times B$ (resp. a mixed space over $\CC\times B$).

::: {.itenv #proposition title="Proposition" latex="{Proposition}"}
For $e^\xi\colon W\to V$ to be a morphism of mixed spaces over the projection $\RR\times B\to B$, it is necessary and sufficient for $\xi$ to be a vertical holomorphic field.
For $e^\xi\colon W\to V$ to be a morphism of mixed spaces over a map from an open subset of $\RR\times B$ containing $\{0\}\times B$ to $B$, it is necessary and sufficient for $\xi$ to be a projectable holomorphic field.
:::

The proof is left to the reader.


## IV. The Spencer--Kodaira map {.unnumbered #section-IV}

Let $\pi\colon V\to B$ be a mixed manifold (resp. a $\CC$-analytic mixed space), $b\in B$, and $V_0=\pi^{-1}(b_0)$.
Let $T_0$ be the tangent space to $B$ at $b_0$ (resp. the Zariski tangent space).
We introduce the following sheaves on $V_0$:

- $\Theta_0$: the sheaf of germs of vertical holomorphic fields on $V_0$ ;
- $\Pi_0$: the sheaf of germs of locally projectable holomorphic fields on $V_0$ ; and
- $\Lambda_0$: the sheaf $\pi^*T_0$, i.e. the sheaf of germs of locally constant maps from $V_0$ to $T_0$.

We have an exact sequence of sheaves on $V_0$
$$
  0 \to \Theta_0 \to \Pi_0 \to \Lambda_0 \to 0
$$
that gives rise to the long exact sequence in cohomology
$$
  \ldots \to \HH^0(V_0;\Pi_0) \to \HH^0(V_0;\Lambda_0) \xrightarrow{\delta} \HH^1(V_0;\Theta_0) \to \ldots.
$$
We also have a canonical map
\oldpage{2-07}
$$
  \iota\colon T_0 \to \HH^0(V_0;\Lambda_0)
$$
that is injective if $V_0$ is non-empty, and surjective if $V_0$ is connected.

::: {.rmenv #definition title="Definition" latex="{Definition}"}
The *Spencer--Kodaira map* is the composition
$$
  \rho_0 = \delta\circ\iota\colon T_0 \to \HH^1(V_0;\Theta_0).
$$
:::

This map is an essential tool in the local study of deformations of $\CC$-analytic varieties.
Note that $\Theta_0$ is exactly the sheaf of germs of holomorphic fields of tangent vectors to $V_0$, and thus depends only on $V_0$, while $T_0$ depends only on the base.
Also, $\Theta_0$ is a coherent analytic sheaf on $V_0$, and, if $V_0$ is compact, then $\HH^1(V_0;\Theta_0)$ is a finite-dimensional vector space over $\CC$ [@1].
We thus see that, in this case (which is the only case where we can say anything non-trivial), $\rho_0$ might be possible to calculate.

It is clear that, if the given mixed manifold is trivial (i.e. if $V=B\times V_0$, with $\pi$ being the projection to $B$), then the map $\rho_0$ is zero.
The next talk aims to show that, in a certain sense, $\rho$ indicates the non-triviality of $V$ in a neighbourhood of $V_0$.
