--- 
title: "The primary obstruction to deformation"
author: "Adrien Douady"
date: "21st of November, 1960"
original: 'Douady, A. "Obstruction primaire à la déformation". _Séminaire Henri Cartan_ **13 (1)** (1960--61), Talk no. 4. [`http://www.numdam.org/item/SHC_1960-1961__13_1_A3_0`](http://www.numdam.org/item/SHC_1960-1961__13_1_A3_0)'
bibliography: SHC-13(1)-4.bib
nocite: '@*'
link-citations: true
csl: maths-translations.csl
reference-section-title: "Bibliography"
github-repo: "thosgood/translations"
favicon: "favicon.ico"
---

```{js, echo = FALSE}
$(document).ready(function(e) {gitbook.sidebar.toggle(false, false)});
```

```{r, child = '_translator-note.Rmd'}
```

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\ZZ}{\mathbb{Z}}
\providecommand{\RR}{\mathbb{R}}
\providecommand{\CC}{\mathbb{C}}
\providecommand{\PP}{\mathbb{P}}
\providecommand{\DD}{\mathrm{D}}
\providecommand{\HH}{\mathrm{H}}
\providecommand{\dd}{\mathrm{d}}

\providecommand{\Hom}{\operatorname{Hom}}
\providecommand{\GL}{\operatorname{GL}}
\providecommand{\SL}{\operatorname{SL}}

<!-- Content -->

# Introduction {.unnumbered #introduction}

\oldpage{4-01}
Let $V_0$ be a compact complex-analytic manifold, and let $\Theta$ be the sheaf of germs of holomorphic fields of tangent vectors.
We ask the following question: given an element $a\in\HH^1(V_0,\Theta)$, does there exists a deformation of $V_0$, with a non-singular base (i.e. a fibred mixed manifold $\pi\colon V\to B$, with $b_0\in B$, along with an isomorphism $V_0\xrightarrow{\cong}\pi^{-1}(b_0)$), such that $a$ is the image, under the map $\rho$ defined in [Talk no. 2], of a vector $v$ that is tangent to $B$ at $b_0$?
An element $a\in\HH^1(V_0,\Theta)$ for which the answer is positive is called a *deformation vector*.
We will give a necessary condition for $a$ to be a deformation vector;
this condition is written $[a\smile a]=0$.
We will then give an example where this condition is not satisfied.


# I. Exact sequences of sheaves of algebras {.unnumbered #section-I}

Let $K$ be a commutative ring, and let $\Phi$, $\Phi_1$, and $\Phi_2$ be sheaves of $K$-modules on some space $X$, and suppose that we have some given homomorphism $\Phi_1\otimes\Phi_2\to\Phi$, written as a product.
We define, for any cover $\scr{U}$ of $X$, the *cup product*
$$
  \smile\colon C^p(X,\scr{U};\Phi_1) \otimes C^q(X,\scr{U};\Phi_2)
  \to C^{p+q}(X,\scr{U};\Phi)
$$
by the formula
$$
  (\alpha\smile\beta)_{i_0,\ldots,i_{p+q}}
  = \alpha_{i_0,\ldots,i_p}\cdot\beta_{i_p,\ldots,i_{p+q}}.
$$
We have the relation
$$
  \dd(\alpha\smile\beta) = \dd\alpha\smile\beta + (-1)^p\alpha\smile\dd\beta.
$$
This induces a cup product on the cohomology of the cover $\scr{U}$, and, by passing to the inductive limit over open covers, a cup product
$$
  \smile\colon \HH^p(X;\Phi_1) \otimes \HH^q(X;\Phi_2)
  \to \HH^{p+q}(X;\Phi).
$$
\oldpage{4-02}

::: {.rmenv title="Definition" latex="{Definition}"}
A *sheaf of algebras* on $X$ is a sheaf of modules $\Phi$ on $X$ endowed with a product $\Phi\otimes\Phi\to\Phi$ (which we do not assume to be either commutative nor associative).
:::

If $f\colon\Phi\to\Psi$ is a homomorphism of sheaves of algebras, then the kernel $\Phi'$ of $f$ is a sheaf of two-sided ideals of $\Phi$, i.e. we have products $\Phi'\otimes\Phi\to\Phi'$ and $\Phi\otimes\Phi'\to\Phi'$ such that the two diagrams
$$
  \begin{CD}
    \Phi'\otimes\Phi @>>> \Phi'
  \\@VVV @VVV
  \\\Phi\otimes\Phi @>>> \Phi
  \end{CD}
  \qquad
  \begin{CD}
    \Phi\otimes\Phi' @>>> \Phi'
  \\@VVV @VVV
  \\\Phi\otimes\Phi @>>> \Phi
  \end{CD}
$$
both commute.

::: {.itenv #proposition-1 title="Proposition 1" latex="{Proposition 1}"}
Let $0\to\Phi'\to\Phi\to\Phi''\to0$ be an exact sequence of sheaves of algebras on $X$;
let $a\in\HH^p(X;\Phi'')$.
Then $\delta a\in\HH^{p+1}(X;\Phi')$, and, for any class $b\in\HH^q(X;\Phi')$, we have $\delta a\smile b=0$.
:::

::: {.proof}
Let $\scr{U}$ be a cover of $X$ such that $a$ and $b$ are represented by cocycles $\alpha$ and $\beta$ (respectively), and such that $\alpha$ lifts to a cochain $\eta\in C^p(X,\scr{U};\Phi)$.
Then $\delta\eta$ is a cocycle in $C^{p+1}(X,\scr{U};\Phi')$ whose class in $\HH^{p+1}(X;\Phi')$ is, by definition, $\delta a$, and $\delta a\smile b$ is the class of $\delta\eta\smile\beta$.
But $\delta(\eta\smile\beta)=\delta\eta\smile\beta$, and $\eta\smile\beta$ is a cochain in $C^{p+q}(X,\scr{U};\Phi')$, since $\Phi'$ is a sheaf of ideals.
So the cocycle $\delta\eta\smile\beta$ is cohomologous to $0$ in $\HH^{p+q+1}(X;\Phi')$, which proves the proposition.
:::


# II. The primary obstruction {.unnumbered #section-II}

Let $V_0$ be a complex-analytic manifold, and $\Theta_0$ the sheaf of germs of holomorphic fields of tangent vectors.
Then $\Theta_0$ is a sheaf of Lie algebras, and, if $a,b\in\HH^\bullet(V_0,\Theta_0)$, then we denote by $[a\smile b]$ the cup product defined by the bracket $[-,-]\colon\Theta_0\otimes\Theta_0\to\Theta_0$.
It satisfies
$$
  [b\smile a] = (-1)^{pq+1}[a\smile b]
$$
for $a\in\HH^p(V_0,\Theta_0)$ and $b\in\HH^q(V_0,\Theta_0)$.
\oldpage{4-03}

::: {.itenv #theorem-1 title="Theorem 1" latex="{Theorem 1}"}
Let $\pi\colon V\to B$ be a mixed manifold, $b_0$ a point of $B$, $V_0=\pi^{-1}(b_0)$, and let $\rho_0\colon T_0\to\HH^1(V_0,\Theta_0)$ be Spencer--Kodaira map.
Then, if $u$ and $v$ are tangent vectors of $B$ at $b_0$, we have
$$
  [\rho_0(u)\smile\rho_0(v)] = 0.
$$
:::

::: {.itenv title="Corollary" latex="{Corollary}"}
Let $V_0$ be a complex-analytic manifold, and $\Theta$ the sheaf of germs of holomorphic fields of tangent vectors of $V_0$.
If $a\in\HH^1(V_0,\Theta)$ is a deformation vector, then
$$
  [a\smile a]=0.
$$
:::

::: {.proof}
*(Proof of the Corollary).*
This is simply a particular case of [Theorem 1](#theorem-1);
note that $[a\smile b]$ is a symmetric bilinear map from $\HH^1\otimes\HH^1$ to $\HH^2$, and that we are in characteristic $0\neq2$.
:::

::: {.proof}
*(Proof of Theorem 1).*
Consider the following sheaves on $V_0$:

- $\Theta_0$: the sheaf of germs of vertical holomorphic fields on $V_0$;
- $\widetilde{\Theta}_0$: the sheaf of germs of vertical holomorphic fields on $V$;
- $\Pi_0$: the sheaf of germs of locally projectable holomorphic fields on $V_0$;
- $\widetilde{\Pi}_0$: the sheaf of germs of locally projectable holomorphic fields on $V$;
- $\Lambda_0$: the sheaf $\pi^*T_0$, where $T_0$ is the tangent space of $B$ at $b_0$; and
- $\widetilde{\Lambda}_0$: the sheaf $\pi^*\widetilde{T}_0$, where $\widetilde{T}_0$ is the space of germs at $b_0$ of fields on $B$ of tangent vectors of $B$.

We have the following diagram:
$$
  \begin{CD}
    0 @>>> \widetilde{\Theta}_0 @>>> \widetilde{\Pi}_0 @>>> \widetilde{\Lambda}_0 @>>> 0
  \\@. @V{\varepsilon}VV @V{\varepsilon}VV @V{\varepsilon}VV @.
  \\0 @>>> \Theta_0 @>>> \Pi_0 @>>> \Lambda_0 @>>> 0
  \end{CD}
$$
\oldpage{4-04}
whence we obtain the following commutative diagram:
$$
  \begin{CD}
    \widetilde{T}_0 @>{\widetilde{\rho}}>> \HH^1(V_0;\widetilde{\Theta})
  \\@V{\varepsilon}VV @VV{\varepsilon}V
  \\T_0 @>>{\rho}> \HH^1(V_0;\Theta_0)
  \end{CD}
$$

Let $u,v\in T_0$ be fixed tangent vectors of $B$ at $b_0$.
We can always find vector fields $\widetilde{u}$ and $\widetilde{v}$ on $B$ that take the values $u$ and $v$ (respectively) at $b_0$;
$\epsilon(\widetilde{u})=u$ and $\epsilon(\widetilde{v})=v$.
The exact sequence
$$
  0 \to
  \widetilde{\Theta}_0 \to
  \widetilde{\Pi}_0 \to
  \widetilde{\Lambda}_0 \to
  0
$$
is a sequence of homomorphisms of sheaves of Lie algebras, and so
$$
  [\widetilde{\rho}(\widetilde{u})\smile\widetilde{\rho}(\widetilde{v})] = 0
$$
by [Proposition 1](#proposition-1).
But $\epsilon\colon\widetilde{\Theta}_0\to\Theta_0$ is also a homomorphism of sheaves of Lie algebras, and the diagram
$$
  \begin{CD}
    \HH^1(V_0,\widetilde{\Theta}_0)\otimes\HH^1(V_0,\widetilde{\Theta}_0) @>{[-\smile-]}>> \HH^2(V_0,\widetilde{\Theta}_0)
  \\@V{\varepsilon\otimes\varepsilon}VV @VV{\varepsilon}V
  \\\HH^1(V_0,\Theta_0)\otimes\HH^1(V_0,\widetilde{\Theta}_0) @>>{[-\smile-]}> \HH^2(V_0,\Theta_0)
  \end{CD}
$$
commutes.
We thus deduce that $[\rho(u)\smile\rho(v)]=0$.
:::

\oldpage{4-05}

::: {.rmenv title="Remarks" latex="{Remarks}"}
—

1. We make essential use of the fact that $\epsilon\colon\widetilde{T}_0\to T_0$ is surjective, and thus of the fact that $B$ has no singularities.
2. We actually have $[\rho(u)\smile b]=0$ for all $u\in T_0$, for any class $b\in\HH^1(V_0,\Theta_0)$ that is in the image of $\HH^1(V_0,\widetilde{\Theta}_0)$ under $\epsilon$.
    In particular, for an element $a\in\HH^1(V_0,\Theta_0)$ to be a regular deformation vector (in the sense of [Talk no. 3]), it is necessary and sufficient for $[a\smile b]=0$ for all $b\in\HH^1(V_0,\Theta_0)$.
:::

If $V_0$ is a compact complex-analytic manifold, and $a\in\HH^1(V_0,\Theta)$, then we call $[a\smile a]\in\HH^2(V_0,\Theta)$ the *primary obstruction* to the deformation of $V_0$ along $a$.
For $a$ to be a deformation vector, it is necessary that this primary obstruction be zero;
but it is not sufficient: we can define a sequence of set-theoretic maps $\omega_n$, called *obstructions*, with $\omega_1\colon\HH^1(V_0,\Theta)\to\HH^2(V_0,\Theta)$ given by $\omega_1(a)=[a\smile a]$, and with $\omega_{k+1}$ defined on the subset of $\HH^1(V_0,\Theta)$ where $\omega_k$ vanishes, with values in varying quotients^[See the [Appendix](#appendix).] of $\HH^2(V_0,\Theta)$, and a necessary condition for $a$ to be a deformation vector is that all the $\omega_k(a)$ be defined and real.
I do not know if *this* condition is sufficient.
Kodaira, Spencer, and Nijenhuis [@4] have shown that, if $\HH^2(V_0,\Theta)=0$, then every element of $\HH^1(V_0,\Theta)$ is a deformation vector.
In this case, we even have a locally universal deformation whose base is a manifold, and $\rho$ is an isomorphism from the tangent space of this manifold to $\HH^1(V_0,\Theta)$


# III. An example of obstruction {.unnumbered #section-III}

## 1. The manifold $V_0$ {.unnumbered #section-III.1}

Let $X=E/\Gamma$ be a $2$-dimensional complex torus, i.e. $E\cong\CC^2$ and $\Gamma\cong\ZZ^4$, and let $D$ the be projective line $\PP^1\CC$.
Set $V_0=X\times D$.
The sheaf $\Theta$ of holomorphic fields of tangent vectors of $V_0$ is the direct sum of the sheaves of Lie algebras $\Theta_1$ and $\Theta_2$, where
$$
  \begin{aligned}
    \Theta_1 &= \cal{O}\otimes_{\cal{O}_X}\pi_1^*\Theta_X
  \\\Theta_2 &= \cal{O}\otimes_{\cal{O}_D}\pi_2^*\Theta_D
  \end{aligned}
$$
where $\pi_1\colon V_0\to X$ and $\pi_2\colon V_0\to D$ are the projections, $\cal{O}$, $\cal{O}_X$, and $\scr{D}$ are the structure sheaves (sheaves of local rings), and $\Theta_X$ and $\Theta_D$ are the sheaves of germs of holomorphic fields of tangent vectors of $X$ and $D$ (respectively).
We are mostly interested in $\Theta_2$.
\oldpage{4-06}
Also, $\HH^1(V_0,\Theta_2)$ is given by the Künneth exact sequence:
$$
  0 \to
  \HH^0(X,\cal{O}_X)\otimes\HH^1(D,\Theta_D) \to
  \HH^1(V_0,\Theta_2) \to
  \HH^1(X,\cal{O}_X)\otimes\HH^0(D,\Theta_D) \to
  0.
$$
But we know that $\HH^0(D,\Theta_D)$ is the Lie algebra $\fk{a}$ of the group
$$
  A = \GL(2,\CC)/\CC^* = \SL(2,\CC)/\{\pm1\}
$$
of automorphisms of $D$, and that $\HH^1(D,\Theta_D)=0$, as we can easily see by taking a cover of $D$ by two open subsets.
We have already seen (in [Talk no. 1]) that, if $X=E/\Gamma$, then $\HH^1(X,\cal{O})=\Hom(\Gamma,\CC)/\Hom_{\CC}(E,\CC)$ is of dimension $2$.
So $\HH^1(V_0,\Theta_2)=\HH^1(X,\cal{O})\otimes\fk{a}$ is of dimension $6$.
The cup product
$$
  \HH^1(V_0,\Theta_2)\otimes\HH^1(V_0,\Theta_2) \to \HH^2(V_0,\Theta_2)
$$
is given by the formula
$$
  [(\gamma\otimes\alpha)\smile(\gamma'\otimes\alpha')]
  = (\gamma\smile\gamma')\otimes[\alpha,\alpha'].
$$
The cone of elements $\varphi\in\HH^1(V_0,\Theta_2)$ such that $[\varphi\smile\varphi]=0$ can be identified with the cone of rank $1$ tensors in $\HH^1(X,\cal{O})\otimes\fk{a}$.
Indeed, if $\varphi=\gamma\otimes\alpha$, then
$$
  [\varphi\smile\varphi]
  = (\gamma\smile\gamma)\otimes[\alpha,\alpha]
  = 0\otimes0
  = 0
$$
and, if $\varphi$ is not a simple tensor, then we have
$$
  \varphi = \gamma\otimes\alpha + \gamma'\otimes\alpha'
$$
with $\gamma$ and $\gamma'$ independent, and $\alpha$ and $\alpha'$ independent, so
$$
  [\varphi\smile] = 2(\gamma\smile\gamma')\otimes[\alpha,\alpha'] \neq 0.
$$


## 2. The mixed space $V$ {.unnumbered #section-III.2}

In this example, every element of $\HH^1(V_0,\Theta_2)$ whose primary obstruction is zero is a deformation vector.
More precisely:
\oldpage{2-07}


::: {.itenv #proposition-2 title="Proposition 2" latex="{Proposition 2}"}
There exists a mixed space $\pi\colon V\to B$ and a point $b_0\in B$ such that

1. $\pi^{-1}(b_0)=V_0$ (the manifold defined in [§III.1](#section-III.1));
2. there exists an isomorphism $\sigma$ from a $\CC$-analytic space $B$ to the cone of elements $\varphi\in\HH^1(V_0,\Theta_2)$ such that $[\varphi\smile\varphi]=0$; and
3. for every subspace $B'$ of $B$ that has no singularities at $b_0$, the Spencer--Kodaira map $\rho$ from the tangent space of $B'$ at $b_0$ to $\HH^1(V_0,\Theta)$ agrees with $\sigma\colon B'\to\HH^1(V_0,\Theta_2)$.
:::

Let $H$ be the analytic space of homomorphisms from $\Gamma$ to $\fk{a}$ whose images are contained in a vector subspace of $\fk{a}$ that is $1$-dimensional over $\CC$ (i.e. $(4\times2)$ matrices of rank $1$ with coefficients in $\CC$).
For every $h\in H$, $e\circ h$ is a homomorphism from $\Gamma$ to $A$, where $e\colon\fk{a}\to A$ denotes the exponential map, and we construct a manifold $V_h$ that is fibred over $X$ with fibre $D$ as follows: $V_h$ is the quotient of $E\times D$ by the equivalence relation defined by $\Gamma$ acting via
$$
  \gamma\star(x,y) = (x+\gamma,((e\circ h)(\gamma))\cdot y).
$$
These manifolds are the fibres of a mixed space $W\to H$, where $W$ is the quotient of $H\times E\times D$ by the equivalence relation defined by $\Gamma$ acting via
$$
  \gamma\star(h,x,y) = (h,x+y,(e\circ h(y))\cdot y).
$$
We now place the following equivalence relation on $H$: we have $h'\sim h$ if and only if $(h'-h)$ extends to an $\CC$-linear map $f\colon E\to\fk{a}$.
Note that, if $h'(\Gamma)$ and $h(\Gamma)$ are contained in the same subspace $L$ of $\fk{a}$ of dimension $1$ over $\CC$ (or if $h'\sim h$), then we also have $f(E)\subset L$ (or $h\sim0$ and $h'\sim0$).
In both cases, $V_h$ and $V_{h'}$ are isomorphic, and we have an isomorphism $i_{h',h}\colon V_h\to V_{h'}$ defined by
$$
  i_{h',h}(x,y) = (x,e\circ f(x)\cdot y)
$$
(in the first case), or
$$
  i_{h',h} = i_{h',0}\circ i_{0,h}
$$
(in the second case).
\oldpage{4-08}
If $h$, $h'$, and $h''$ are in the same class, then we have $i_{h''h}=i_{h''h'}\circ i_{h'h}$, and we can place on $W$ the equivalence relation
$$
  (h',z') \sim (h,z) \iff \mbox{$h'\sim h$ or $z'=i_{h'h}z$}
$$
for $h,h'\in H$, $z\in V_h$, and $z'\in V_{h'}$.

Let $B$ and $V$ be the quotients of $H$ and $W$ (respectively) by these equivalence relations.
We have a projection $V\to B$.
To show that the structures of a $\CC$-analytic space on $H$ and $W$ induce structures of a $\CC$-analytic space on their quotients $B$ and $V$, it suffices to remark that we can lift $B$ to a analytic subspace of $H$: let, for example, $(\gamma_1,\gamma_2,\gamma_3,\gamma_4)$ be a basis of $\Gamma$ such that $(\gamma_1,\gamma_2)$ is a basis of $E$ over $\CC$; then each class $b\in B$ contains exactly one element $h\in H$ such that
$$
  h(\gamma_1) = h(\gamma_2) = 0.
$$


## 3. Calculating $\rho_0$ {.unnumbered #section-III.3}

Let $T$ be the Zariski tangent space of $B$ at $b_0$, i.e. the dual of $\fk{I}/\fk{I}^2$, where $\fk{I}$ is the ideal of germs at $b_0$ of analytic functions on $B$ that are zero at $b_0$.
Then $T_0$ can be identified with $\Hom(\Gamma,a)/\Hom_{\CC}(E,a)$.
Also,
$$
  \begin{aligned}
    \HH^1(V_0,\Theta)
    &= \HH^1(V_0;\Theta_1) \oplus \HH^1(V_0;\Theta_2)
  \\&= \big(\HH^1(X;\cal{O}) \otimes E\big) \oplus \big(\HH^1(X;\cal{O})\otimes a\big),
  \end{aligned}
$$
and the second term of this term can be identified with the quotient $\Hom(\Gamma,a)/\Hom_{\CC}(E,a)$.
We are going to show that the map $\rho_0\colon T_0\to\HH^1(V_0;\Theta)$ is exactly the canonical injection defined by these identifications.

Let $u\in T_0=\Hom(\Gamma,\alpha)/\Hom(E,\alpha)$ be the class of an element $h\in\Hom(\Gamma,\alpha)$, which we suppose to be of rank $1$.
Then we can write $h$ in the form $\eta\otimes\sigma$, where $\eta\in\Hom(\Gamma,\CC)$, $\sigma\in\alpha$, and we can consider $h$ as a tangent vector to $H$ at $0$.
Let $\overline{h}$ be the field of tangent vectors to $H\times E\times D$ at $0\times E\times D$ that projects onto $h$, and thus whose components over $E\times D$ are zero.
\oldpage{4-09}
Let $(U_i)$ be a cover of $X=E/\Gamma$ by simply connected open subsets, and choose, for each $i$, a component $\widetilde{U}_i$ of the inverse image of $U_i$ in $E$.
We will denote by $v_i$ the image over $U_i\times D$ of the field $\overline{h}|\widetilde{U}_i\times D$.
This is a projectable holomorphic field on $0\times U_i\times D$ of tangent vectors of $H\times U_i\times D$, and we set $w_{ij}=v_j-v_i$, so that $w_{ij}$ is a vertical holomorphic field on $U_{ij}\times D$, and these fields form a cocycle whose cohomology class will be, by definition, $\rho_0(u)$.

Let $x\in U_{ij}$, and let $\widetilde{x}_i$ and $\widetilde{x}_j$ be its inverse image in $\widetilde{U}_i$ and $\widetilde{U}_j$ (respectively).
We have that $\widetilde{x}_j=\widetilde{x}_i+\gamma_{ij}(x)$, where $\gamma_{ij}(x)\in\Gamma$, and
$$
  w_{ij}(x)
  = \overline{h}(\widetilde{x}_j) - [\gamma_{ij}(x)]_*(\overline{h}(\widetilde{x}_i))
  = -h(\gamma_{ij}(x)) \in\alpha.
$$
Now $w_{ij}$ is a vector field on $D$, and so
$$
  (w_{ij}) \in \mathrm{Z}^1(V_0,(U_i\times D);\Theta_2),
$$
and $w_{ij}$ is of the form $\zeta\otimes\alpha$, where $\zeta\in\mathrm{Z}^1(V_0,(U_i\times D);\cal{O})$ is the cocycle defined by $\zeta_{ij}(x)=-\eta(\gamma_{ij}(x))$.
This is a cocycle whose cohomology class is (up to a sign) the element of $\HH^1(V_0,\cal{O})$ that is identified with the class $\eta$ in $\Hom(\Gamma,\CC)/\Hom_{\CC}(E,\CC)$.
QED.


# (PART) Appendix: Higher obstructions {.unnumbered #appendix}

# I. Definition of obstructions {.unnumbered #appendix-I}

## 1. The sheaf of germs of vertical automorphisms {.unnumbered #appendix-I.1}

Let $V_0$ be a $\CC$-analytic manifold, which we assume to be compact, and $B$ a $\CC$-analytic space, and let $b_0\in B$.
\oldpage{4-10}
We are going to define a sheaf $\Gamma$ of non-abelian groups on $V_0$.
For every open subset $U$ of $V_0$, consider the isomorphisms of analytic varieties $\gamma\colon W\to W'$, where $W$ and $W'$ are open subsets of $B\times V_0$ that contain $\{b_0\}\times U$, such that the following conditions are satisfied:
