--- 
title: "Regular deformations"
author: "Adrien Douady"
date: "14th of November, 1960"
original: 'Douady, A. "Déformations régulières". _Séminaire Henri Cartan_ **13 (1)** (1960--61), Talk no. 3. [`http://www.numdam.org/item/SHC_1960-1961__13_1_A2_0`](http://www.numdam.org/item/SHC_1960-1961__13_1_A2_0)'
bibliography: SHC-13(1)-3.bib
nocite: '@*'
link-citations: true
csl: maths-translations.csl
reference-section-title: "Bibliography"
github-repo: "thosgood/translations"
favicon: "favicon.ico"
---

```{js, echo = FALSE}
$(document).ready(function(e) {gitbook.sidebar.toggle(false, false)});
```

```{r, child = '_translator-note.Rmd'}
```

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\ZZ}{\mathbb{Z}}
\providecommand{\RR}{\mathbb{R}}
\providecommand{\CC}{\mathbb{C}}
\providecommand{\DD}{\mathrm{D}}
\providecommand{\HH}{\mathrm{H}}

\providecommand{\Hom}{\operatorname{Hom}}

<!-- Content -->

All throughout this talk, $B$ is a $\mathscr{C}^\infty$ manifold (resp. $\RR$-analytic, resp. $\CC$-analytic); $\pi\colon V\to B$ denotes a proper mixed manifold; $b_0$ is a point of $B$; and $V_0=\pi^{-1}(b_0)$ is thus a compact $\CC$-analytic manifold.
\oldpage{3-01}


## I. The map $\widetilde{\rho}$ {.unnumbered #section-I}

Let $\widetilde{\Theta}$ (resp. $\widetilde{\Pi}$) be the sheaf of germs of vertical holomorphic (resp. locally projectable holomorphic) vector fields on $V$.
The quotient sheaf $\widetilde{\Lambda}=\widetilde{\Pi}/\widetilde{\Theta}$ is exactly the inverse image under $\pi$ of the sheaf $\widetilde{T}$ of germs of $\mathscr{C}^\infty$ fields (resp. ...) of tangent vectors on $B$.

For every open subset $U$ of $B$, set $V_U=\pi^{-1}(U)$.
The exact sequence
$$
  0 \to \widetilde{\Theta} \to \widetilde{\Pi} \to \widetilde{\Lambda} \to 0
$$
of sheaves on $V_U$ gives rise to a homomorphism
$$
  \widetilde{\rho}_U\colon
  \HH^0(U;\widetilde{T})
  \xrightarrow{\pi_*} \HH^0(V_U;\widetilde{\Lambda})
  \xrightarrow{\delta} \HH^1(V_U;\widetilde{\Theta}).
$$
Let $\mathrm{R}^1\pi_*\widetilde{\Theta}$ be the sheaf on $B$ defined by the presheaf $U\mapsto\HH^1(V_U;\widetilde{\Theta})$.
Then $\widetilde{\rho}$ becomes a homomorphism of sheaves on $B$:
$$
  \widetilde{\rho}\colon \widetilde{T} \to \mathrm{R}^1\pi_*\widetilde{\Theta}.
$$
In particular, we have a homomorphism
$$
  \widetilde{\rho}_0\colon
  \widetilde{T}_0
  \to \mathrm{R}^1\pi_*\widetilde{\Theta}
  = \HH^1(V_0;\widetilde{\Theta})
$$
where $\widetilde{T}_0$ is the vector space of germs at $b_0$ of fields of tangent vectors to $B$.
\oldpage{3-02}
Finally, we have a commutative diagram
$$
  \begin{CD}
    \widetilde{T}_0 @>{\widetilde{\rho}_0}>> \HH^1(V_0;\widetilde{\Theta})
  \\@V{\varepsilon}VV @VV{\varepsilon}V
  \\T_0 @>>{\rho_0}> \HH^1(V_0;\Theta_0)
  \end{CD}
$$
where $\rho_0$ is the Spencer--Kodaira map \cite{2}.

::: {.itenv #theorem-1 title="Theorem 1" latex="{Theorem 1}"}
For the proper mixed manifold $\pi\colon V\to B$ to be locally trivial in a neighbourhood of the point $b_0\in B$, it is necessary and sufficient for the map $\widetilde{\rho}_0\colon\widetilde{T}_0\to\HH^1(V_0;\widetilde{\Theta})$ to be zero.
:::

::: {.proof}
—

a. *(Necessity).*
    If $\pi\colon V\to B$ is locally trivial at $b_0$, then, for every open subset $U$ of $B$ over which $V$ is trivial, we have $\widetilde{\Pi}=\widetilde{\Lambda}\oplus\widetilde{\Theta}$ on $V_U$, and so $\delta\colon\HH^0(V_U;\widetilde{\Lambda})\to\HH^0(V_U;\widetilde{\Theta})$ is zero.

b. *(Sufficiency).*
    Let $(\eta_1,\ldots,\eta_p)$ be $\mathscr{C}^\infty$ vector fields (resp. ...) on a neighbourhood of $b_0$ in $B$, such that $(\eta_1(b_0),\ldots,\eta_p(b_0))$ forms a basis of the tangent space $T_0$ to $B$ at $b_0$.
    It then follows from the hypothesis that the map
    $$
      \HH^0(V_0;\widetilde{\Pi}) \to \HH^0(V_0;\widetilde{\Lambda})
    $$
    is surjective.
    So let $(\xi_1,\ldots,\xi_p)$ be projectable holomorphic vector fields on a neighbourhood of $V_0$ in $V$, that project to $(\eta_1,\ldots,\eta_p)$.
    Let $f$ be the map defined on a neighbourhood of $\{0\}\times V_0$ in $\RR^p\times V_0$ (resp. $\CC^p\times V_0$) by
    $$
      f(t_1,\ldots,t_p,y) = e^{\xi_1}(t_1,e^{\xi_2}(\ldots,e^{\xi_p}(t_p,y)\ldots)).
    $$
    It follows from the proposition stated in [@1, Section III.2] that $f$ induces an isomorphism of mixed manifolds from $U\times V_0$ to $\pi^{-1}(f_1(U))$ over $f_1$, where $U$ is a sufficiently small cubical neighbourhood of $0$ in $\RR^p$, and $f_1$ is the map from $U$ to $B$ defined by
    $$
      f_1(t_1,\ldots,t_p) = e^{\eta_1}(t_1,e^{\eta_2}(\ldots,e^{\eta_p}(t_p,b_0)\ldots)),
    $$
    which proves the theorem.

\oldpage{3-03}
:::


# II. The regular case {.unnumbered #section-II}

For all $b\in B$, set $V_b=\pi^{-1}(b)$.
Consider the family $\{\HH^1(V_b;\Theta_b)\}_{b\in B}$ of finite-dimensional $\CC$-vector spaces, and, for all $b\in B$,  the map
$$
  \varepsilon_b\colon \HH^1(V_b;\widetilde{\Theta}) \to \HH^1(V_b;\Theta_b).
$$

For every open subset $U\subset B$, we have a map
$$
  \widetilde{\varepsilon}_U\colon \HH^1(V_U;\widetilde{\Theta}) \to \prod_{b\in U}\HH^1(V_b;\Theta_B)
$$
that defines, by varying $U$, a homomorphism from the sheaf $\mathrm{R}^1\pi_*\widetilde{\Theta}$ to the sheaf $\Phi$ on $B$ defined by $\Phi(U)=\prod_{b\in U}\HH^1(V_b;\Theta_b)$.

::: {.rmenv #definition title="Definition" latex="{Definition}"}
We say that the proper mixed manifold $\pi\colon V\to B$ is *regular* if

1. the dimension of $\HH^1(V_b;\Theta_b)$ does not depend on the point $b\in B$; and
2. we can endow $E=\bigcup_{b\in B}\HH^1(V_b;\Theta_b)$ with the structure of a $\mathscr{C}^\infty$ vector bundle (resp. ...) such that $\widetilde{\varepsilon}$ is an isomorphism from the sheaf $\mathrm{R}^1\pi_*\widetilde{\Theta}$ to the sheaf of germs of $\mathscr{C}^\infty$ sections (resp. ...) of the bundle $E$.
:::

In fact, Kodaira and Spencer have shown [@2] that, by identifying the $\HH^1$ spaces with spaces of harmonic forms, condition (2) is a consequence of condition (1).

Then [Theorem 1](#theorem-1) has the following corollary:

::: {.itenv #proposition-1 title="Proposition 1" latex="{Proposition 1}"}
For the proper mixed manifold $\pi\colon V\to B$ to be locally trivial, it is necessary and sufficient for it to be regular and, for all $b\in B$, for the Spencer--Kodaira map
$$
  \rho_b\colon T_b \to \HH^1(V_b;\Theta_b)
$$
to be zero.
:::

Indeed, since $\widetilde{\varepsilon}$ is injective, this condition implies that the map
$$
  \widetilde{\rho}_b\colon \widetilde{T}_b \to \HH^1(V_b;\widetilde{\Theta})
$$
is zero for all $b$.
\oldpage{3-04}

At the end of this talk, we will construct a counter-example which shows that it is necessary to assume that the mixed manifold is regular.


# III. An example of non-regular deformation: Hopf manifolds {.unnumbered #section-III}

## 1. Hopf manifolds {.unnumbered #section-III.1}

Let $n\geq2$ be an integer, and let $b$ be an $(n\times n)$ matrix with coefficients in $\CC$, whose eigenvalues are all of modulus $>1$.
The free group $L(b)$ generated by $b$ acts freely on $\widetilde{V}=\CC^n\setminus\{0\}$, and the quotient space $\widetilde{V}/L(b)$, which we call the *Hopf manifold defined by $b$*, is a compact $\CC$-analytic manifold that is homeomorphic to $S^{2n-1}\times S^1$.

Note that $V_b$ and $V_{b'}$ are isomorphic if and only if there exists some $a$ such that $b'=aba^{-1}$ or $b'=ab^{-1}a^{-1}$ (cf. [Appendix](#appendix)).

Let $\Theta$ be the sheaf of germs of holomorphic fields of tangent vectors on $V_b$.

::: {.itenv #proposition-2 title="Proposition 2" latex="{Proposition 2}"}
We can identify $\HH^0(V_b;\Theta)$ with the vector space of matrices that commute with $b$, and $\HH^1(V_b;\Theta)$ has the same dimension as this vector space.
:::

:::: {.proof}
If $X$ is a vector field on an open subset $U\subset\widetilde{V}$, then $b_*(X)$ is the vector field on the open subset $b(U)$ given by transporting via $b$, i.e. $b_*X(u)=bX(b^{-1}u)$.
Let $\mathscr{U}=\{U_i\}$ be a cover of $V$ by simply connected Stein open subsets;
for all $i$, set $\widetilde{U}_i=\chi^{-1}\{U_i\}$, where $\chi$ is the canonical map from $\widetilde{V}$ to $V_b$.
The cover $\widetilde{\mathscr{U}}=\{\widetilde{U}_i\}$ of $\widetilde{V}$ consists of Stein open subsets that are invariant under $b$ (not necessarily connected, but this doesn't matter).
Then $b_*$ defines a map, again denoted by $b_*$, from the group of cochains $C^\bullet(\widetilde{V},\widetilde{U};\Theta)$ to itself.

::: {.itenv #lemma-1 title="Lemma 1" latex="{Lemma 1}"}
We have the exact sequence
$$
  0
  \to C^\bullet(V_b,\mathscr{U};\Theta)
  \xrightarrow{\chi^*} C^\bullet(\widetilde{V},\widetilde{U};\Theta)
  \xrightarrow{1-b_*} C^\bullet(\widetilde{V},\widetilde{U};\Theta)
  \to 0.
$$
:::

::: {.proof}
The only thing that we need to verify is that the map $1-b_*$ is surjective.
For all $(i_0,\ldots,i_q)$, let $U'_{i_0,\ldots,i_q}$ be an open subset of $\widetilde{V}$ such that
\oldpage{3-05}
$$
  \chi\colon U'_{i_0,\ldots,i_q} \to U_{i_0,\ldots,i_q}
$$
is a homeomorphism.
The $\widetilde{U}_{i_0,\ldots,i_q}$ is a disjoint union of the $b_*^p U'_{i_0,\ldots,i_q}$, where $p\in\ZZ$, and every $\gamma\in C^q(\widetilde{V},\widetilde{U};\Theta)$ can be written in the form $\gamma=\gamma_1-\gamma_2$, with $\gamma_1=0$ on $b^p(U'_{i_0,\ldots,i_q})$ for $p<0$, and $\gamma_2=0$ for $p\geq0$.
Set
$$
  \beta = \sum_{p\geq0} b_*^p\gamma_1 + \sum_{p<0} b_*^p\gamma_2
$$
(which is a locally finite sum).
Then $\beta-b_*\beta=\gamma$, whence [Lemma 1](#lemma-1).
:::

Now, to finish the proof of [Proposition 2](#proposition-2).
From [Lemma 1](#lemma-1), we have the following exact sequence:
$$
  0
  \to \HH^0(V_b;\Theta)
  \xrightarrow{\chi^*} \HH^0(\widetilde{V};\Theta)
  \xrightarrow{1-b_*} \HH^0(\widetilde{V};\Theta)
  \xrightarrow{\delta_*} \HH^1(V_b;\Theta)
  \xrightarrow{\chi^*} \HH^1(\widetilde{V}y\Theta)
  \xrightarrow{1-b_*} \HH^1(\widetilde{V};\Theta).
$$
We can show that
$$
  \chi^*\colon \HH^1(V_b;\Theta) \to \HH^1(\widetilde{V};\Theta)
$$
is zero:
if $n>2$, it is evident, since $\HH^1(\widetilde{V};\Theta)=0$;
if $n=2$, then a direct calculation on the cochains of a cover of $\widetilde{V}$ by two Stein open subsets shows that
$$
  1-b_*\colon \HH^1(\widetilde{V};\Theta) \to \HH^1(\widetilde{V};\Theta)
$$
is bijective.

Now $\HH^0(\widetilde{V};\Theta)$ is the space of holomorphic vector fields on $\widetilde{V}$, but such a field extends to a holomorphic vector field on $\CC^n$, and $\HH^0(\widetilde{V},\Theta)=L\oplus M$, where $L$ is the space of fields of linear vectors, and $M$ is the space of fields of second-order vectors at $0$.
The subspaces $L$ and $M$ are invariant under $b_*$, and $1-b_*\colon M\to M$ is an isomorphism.
Then [Proposition 2](#proposition-2) follows from remarking that, if an element of $L$ is represented by a matrix $a$, then $b_*a=bab^{-1}$.
::::


## 2. Mixed manifolds whose fibres are Hopf manifolds {.unnumbered #section-III.2}

Let $B$ be the set of all $(n\times n)$ matrices with coefficients in $\CC$ with eigenvalues all of modulus $>1$.
\oldpage{3-06}
This is an open subset of $\CC^{n^2}$.
Let $\alpha$ be the transformation from $B\times\widetilde{V}$ to itself defined by $\alpha(b,x)=(b,b(x))$.
The free group $L(\alpha)$ generated by $\alpha$ acts linearly on $B\times\widetilde{V}$, and the quotient $V=B\times\widetilde{V}/L(\alpha)$ is a $\CC$-analytic manifold.
By endowing it with the projection $\pi\colon V\to B$ induced by the projection $\pi_1\colon B\times\widetilde{V}\to B$ after passing to the quotient, we obtain a $\CC$-analytic mixed manifold that is proper, but not regular.
Indeed, condition 1 of the definition of regular mixed manifolds is not satisfied: for example, for $n=2$, the dimension of $\HH^1(V_b;\Theta)$ is $4$ if $b$ is a scalar matrix, but $2$ in all other cases.

Note that the dimension of $\HH^1(V_b;\Theta_b)$ is an upper semi-continuous function of $b$, and that the set of $b$ such that $\dim\HH^1(V_b;\Theta_b)\geq k$ is a closed analytic subspace of $B$.
This is a general result, that we hope to be able to prove in a later talk of this seminar.


## 3. Calculation of $\rho$ {.unnumbered #section-III.3}

We have $T_b=\Hom(\CC^n,\CC^n)=L\subset\HH^0(\widetilde{V};\Theta)$, and we defined, to prove [Proposition 2](#proposition-2), a surjective map $\delta_*\colon L\to\HH^1(V_b;\Theta)$.

::: {.itenv #proposition-3 title="Proposition 3" latex="{Proposition 3}"}
The Spencer--Kodaira map $\rho$ is given, for the mixed manifold studied in this section, by
$$
  \rho(a) = \delta_*(ab^{-1}).
$$
In particular, it is surjective, and its kernel is the space of matrices of the form $[\ell,b]$ for $\ell\in L$.
:::

::: {.proof}
Let $a\in T_b=L$.
Let $\{U_i\}$ be a cover of $V_b$ by simply connected Stein open subsets, and, for each $i$, let $U'_i$ be a connected component of $\widetilde{U}_i$.

Let $\eta'_i$ be the projectable holomorphic field on $U'_i$ defined by $\eta'_i(x)=(a,0)$;
let $\widetilde{\eta}_i$ be the projectable holomorphic field on $\widetilde{U}_i$ defined by $\widetilde{\eta}_i=\alpha_*^k\eta'_i$ on $b^k(U'_i)$;
and let $\eta_i$ be the projectable holomorphic field on $U_i$ corresponding to $\widetilde{\eta}_i$.
By definition, $\rho(a)$ is the cohomology class of the cochain $\{\theta_{ij}\}$, where $\theta_{ij}=\eta_j-\eta_i$ is a vertical holomorphic field on $U_{ij}$.
\oldpage{3-07}

Set $\widetilde{\eta}_i(x)=(a,\beta_i(x))$.
Then $\beta\in C^0(\widetilde{V};\Theta)$, and we have $(1-b_*)\beta=ab^{-1}\in L\subset\HH^0(\widetilde{V};\Theta)$.
Indeed, $\alpha_*\eta=\eta$, $\alpha_*\eta_i(b_{-1}x)=\eta_i(x)$, and
$$
  \alpha_*(a,\beta(b^{-1}x)) = (a,\beta(x)),
$$
whence
$$
  ab^{-1}x + b\cdot\beta(b^{-1}x) = \beta(x).
$$
We thus deduce that $\theta=\delta_*(ab^{-1})$, which proves [Proposition 3](#proposition-3).
:::


## 4. A counter-example {.unnumbered #section-III.4}

Take $n=2$, and $\sigma\in\CC$ such that $|\sigma|>1$.
Let $B'\subset B$ be the set of matrices of the form
$$
  \begin{pmatrix}
    \sigma & t
  \\0 & \sigma
  \end{pmatrix}
$$
where $t\in\CC$, and let $V'=\pi^{-1}(B')$ be the mixed manifold induced by $V$ over $V'$;
now $B'$ is a line, and its tangent space $T'_b$ at $b$ is generated, for all $b$, by $a=\begin{pmatrix}0&1\\0&0\end{pmatrix}$.
It follows from [Proposition 3](#proposition-3) that the Spencer--Kodaira map
$$
  \rho'\colon T_b(B') \to \HH^1(V_b;\Theta)
$$
is zero if and only if
$$
  b \neq b_0 =
  \begin{pmatrix}
    \sigma & 0
  \\0 & \sigma
  \end{pmatrix}
$$
since, if $b\neq b_0$, then $a=[\ell,b]$, where $\ell=\begin{pmatrix}t^{-1}&0\\0&0\end{pmatrix}$; and if $b=b_0$, then $\rho'$ is injective.

We can also see that $V'$ is trivial on $B'\setminus\{b_0\}$.

Let $\varphi\colon\CC\to B'\subset B$ be the map defined by
$$
  \varphi(t) =
  \begin{pmatrix}
    \sigma & t^2
  \\0 & \sigma
  \end{pmatrix}
$$
and let $V^\varphi$ be the mixed manifold given by the inverse image of $V$ under $\varphi$.
The Spencer--Kodaira map $\rho_t^\varphi$ from $\CC$ to $\HH^1(V_{\varphi(t)};\Theta)$ is the composition
\oldpage{3-08}
$$
  \rho'_{\varphi(t)}\circ\DD\varphi\colon
  \CC
  \to T'_{\varphi(t)}
  \to \HH^1(V_{\varphi(t)};\Theta),
$$
and this is zero for all $t$, since, if $t\neq0$, then $\rho'_{\varphi(t)}$ is zero; and, if $t=0$, then $\DD\varphi$ is zero.

However, the mixed manifold $V^\varphi$ is not locally trivial, since $V_0^\varphi$ is not isomorphic to $V_t^\varphi$ for $t\neq0$.


## 5. Question (K. Srinivasacharyulu) {.unnumbered #section-III.5}

We know that the Hopf manifolds are non-K\"{a}hler, and thus non-algebraic.
For $n=2$, the manifold $V_b$ admits non-constant meromorphic functions if and only if $b$ can be diagonalised with eigenvalues $\sigma_1$ and $\sigma_2$ satisfying $\sigma_1^p=\sigma_2^q$ for some integers $p$ and $q$ (and there is then the function $x_1^px_2^{-q}$).
The set of $b$ satisfying this property is neither open nor closed, but it is a countable union of closed analytic subspaces.
An analogous phenomenon arises for deformations of complex tori.
Is this result general?


# Appendix {.unnumbered #appendix}

With the notation of [§III.1](#section-III.1), let $f\colon V_b\to V_{b'}$ be an isomorphism of $\CC$-analytic manifolds.
This lifts to an isomorphism of universal coverings
$$
  \widetilde{f}\colon \CC^n\setminus\{0\} \to \CC^n\setminus\{0\}.
$$
By Hartog, $\widetilde{f}$ extends to an isomorphism $g\colon\CC^n\to\CC^n$.
We necessarily have
$$
  g(bz) = (b')^kg(z)
\tag{$*$}
$$
where $z\in\CC^n$, and $k$ is an integer;
the same property, applied to the inverse map of $g$, shows that $k=\pm1$.
Let $a$ be the linear map that is tangent to $g$ at the origin;
the identity ($*$) then gives
$$
  \begin{aligned}
    ab &= (b')^ka
  \\k &= \pm1
  \end{aligned}
$$
whence
$$
  b' = aba^{-1}
  \quad\text{or}\quad
  b'= ab^{-1}a^{-1}.
$$
