--- 
title: "Summary of essential results in the theory of topological tensor products and nuclear spaces"
author: "A. Grothendieck"
date: "1952"
original: 'Grothendieck, A. "Résumé des résultats essentiels dans la théorie des produits tensoriels topologiques et des espaces nucléaires". _Annales de l’institut Fourier_ **4** (1952), 73-122. DOI: [10.5802/aif.46](https://doi.org/10.5802/aif.46)'
bibliography: W-AIF-4-1952-73.bib
nocite: '@*'
link-citations: true
csl: maths-translations.csl
reference-section-title: "Bibliography"
github-repo: "thosgood/translations"
favicon: "favicon.ico"
---

```{r, child = '_translator-note.Rmd'}
```

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\BB}{\mathrm{B}}
\providecommand{\LL}{\mathrm{L}}
\providecommand{\JJ}{\mathrm{J}}
\providecommand{\CC}{\mathrm{C}}
\renewcommand{\ll}{\ell}
\providecommand{\sBB}{\mathscr{B}}
\providecommand{\sLL}{\mathscr{L}}
\providecommand{\sEE}{\mathscr{E}}
\providecommand{\DF}{(\mathscr{DF})}
\providecommand{\FF}{(\mathscr{F})}
\providecommand{\hotimes}{\widehat{\otimes}}
\providecommand{\hhotimes}{\skew{0}{\widehat}{\skew{0}\widehat{\otimes}}}
\providecommand{\scr}{\mathscr}
\providecommand{\dd}{\mathrm{d}}
\providecommand{\lotimes}{\overline{\otimes}}

<!-- Content -->

# Introduction {-}

## Subject {-}

\oldpage{73}

This article aims to give a summary, without proofs, of the principal results found in my work "Produits tensoriels topologiques et espaces nucléaires", which will be published in the _Memoirs of the Amer. Math. Society_ (and which I will refer to as [[PTT](#ref-PTT)]).
The main concern throughout [[PTT](#ref-PTT)] was that of being exhaustive, both in terms of studying all the questions raised by the topics covered, as well as trying to state the more difficult results as theorems that were as general as possible.
This work was also very dense, and the important simple ideas risked being sometimes hidden behind technical details.
This is why this bowdlerised summary is possibly useful in giving a more assimilable outline of the theory.
Some extra comments, interesting but not necessary for the general understanding of this summary, as well as some hints for certain proofs, have been placed between stars, $\star$ like this $\star$.

The importance of topological tensor products shows itself in many different settings:

\oldpage{74}

a. The notion of the topological tensor product forms the foundations of a simple and general formulation of _Fredholm theory_, including, alongside the classical case of an integral operator defined by a continuous kernel, many other operators that are defined in the most important functional spaces.^[Such a formulation of Fredholm theory seems to have appeared for the first time in A. Ruston, "Direct product of Banach spaces and linear functional equations", _Proc. of the London Math. Soc._ **3** (1951), 1. My work on this subject was conceived independently of his (in the autumn of 1951), and is rather different.]

b. The many variants of the notion of topological tensor product give rise, by duality, to the definition of many remarkable classes of bilinear forms and linear operators, whose study is only just barely covered in [[PTT](#ref-PTT), chap. I, §4].
    In particular, the techniques introduced there, conveniently systematised and exploited, allow us to obtain entirely unexpected results in the _theory of linear transformations between the spaces $L^1$, $L^2$, and $L^\infty$_, and their topological-vectorial analogues (these results being, as of yet, not definitive, and thus unpublished).
    I might return to this subject, and restrict myself to explaining, in a rather different way, the systematic work of von Neumann--Schatten on the remarkable classes of compact operators in a Hilbert space [@8, chap. 4].

c. From the point of view of this current work, the most important application of topological tensor products is the theory of _nuclear spaces_.
    We explain this theory, generalise it, and make precise the famous "theory of kernels" of L. Schwartz, and further discover new properties, even for the most classical of spaces.
    Here, the topological tensor calculus is the most simple, since the majority of variants of the notion of topological tensor product coincide, and their properties thus sum.
    For now, there are not many applications of the general theorems that we obtain to specific theories.
    The most interesting seems to be a topological-vectorial variant of the "Künneth theorem", giving the homology of a complex defined as the tensor product of two complexes, a variant which seems useful in topological algebra.

d. Generally, it seems to me that the notions of topological tensor product are perfect for giving a suggestive and manageable _language_ that would be good to use in many situations in functional analysis, especially since we have theorems (some of which are non-trivial) at our disposition from which we can benefit.
  I hope that this summary (or, better, [[PTT](#ref-PTT)]) will succeed in giving the reader a similar impression, before the publication of the articles promised above.


## Terminology and notation {-}

Generally we follow the terminology and notation of [@3], apart from the fact that we call the semi-reflexive spaces of [@3] _reflexive_.
We only consider, unless otherwise stated, spaces that are _locally convex_ and _separated_;
by "quotient space" of a space $E$, we mean the quotient of $E$ by a _closed_ vector subspace.
The _dual_ of $E$, written $E'$, is assumed to be, unless otherwise stated, endowed with the strong topology (i.e. the topology of bounded convergence).
\oldpage{75}
The dual of $E'$, or the _bidual_ of $E$, written $E''$, is assumed to be, unless otherwise stated, endowed with the topology given by uniform convergence on the equicontinuous subsets of $E'$, which induces the original topology on $E$.
We will eventually need to appeal to certain notions defined and studied in [@6], most notably that of a _$\DF$-space_.
For our purposes here, it will suffice to know that the dual of a $\FF$-space is a $\DF$-space; that every normed space is a $\DF$-space; and that the dual of a $\DF$-space is an $\FF$-space.

Let $E$, $F$, and $G$ be locally convex spaces.
Denote by $\BB(E,F;G)$ (resp. $\sBB(E,F;G)$) the space of continuous bilinear maps (resp. of separately continuous bilinear maps, i.e. linear with respect to each variable) from $E\times F$ to $G$.
Denote by $\LL(E;F)$ the space of continuous linear maps from $E$ to $F$.
Denote by $\sBB_e(E'_s,F'_s)$ the space of separately continuous bilinear forms on the product of the weak duals $E'_s$ and $F'_s$ of $E$ and $F$, endowed with the _biequicontinuous topology_, i.e. the topology given by uniform convergence on the products of an equicontinuous subset of $E'$ with equicontinuous subset of $F'$.
This space is complete if and only if the spaces $E$ and $F$ are complete.

We define a _bounded_ (resp. _compact_, resp. _weakly compact_) _linear map_ from $E$ to $F$ to be a linear map from $E$ to $F$ that sends a suitable neighbourhood of $0$ to a bounded (resp. relatively compact, resp. relatively weakly compact) subset of $F$.

For short^[This terminology was suggested to me by R.E. Edwards. _[Trans.] The seemingly more popular terminology these days is to say "absolutely convex" instead of "disked", and to speak of the "absolutely convex hull" instead of the "disked hull"._], if $E$ is a vector space, we say _disk_ or _disked set in $E$_ to mean a convex and circled (a.k.a. balanced) subset of $E$.
If $E$ is a locally convex space, and $A$ a bounded disk in $E$, then we denote by $E_A$ the vector space generated by $A$, and endowed with the norm $\|x\|_A=\inf_{x\in\lambda A}|\lambda|$.
If $A$ is closed, then the unit ball of $E_A$ is $A$.
If $A$ is complete, then $E_A$ is complete.
If $V$ is a disked neighbourhood of $0$ in $E$, then $E_V$ denotes the normed space given by passing to the quotient under the semi-norm $\|x\|_V=\inf_{x\in\lambda V}|\lambda|$.

Recall that a locally convex space is said to be _quasi-complete_ if its closed bounded subsets are complete, _barrelled_ (resp. _quasi-barrelled_) if the bounded subsets of its weak dual (resp. of its strong dual) are equicontinuous, and _bornological_ if every set of linear forms on $E$ that are uniformly bounded on every bounded subset is equicontinuous.
If $E$ is quasi-complete, then tunnelled is equivalent to quasi-tunnelled;
in any case, bornological implies quasi-tunnelled.


# Topological tensor products {#section-1}

## Generalities on $E\hotimes F$ {#section-1.1}

[[PTT](#ref-PTT), chap. 1, §1, no. 1 and no. 3]

\medskip
\oldpage{76}
The axiomatic definition of the algebraic tensor product $E\otimes F$ of two vector spaces $E$ and $F$, and of the canonical bilinear map $(x,y)\mapsto x\otimes y$ from $E\times F$ to $E\otimes F$ ([@1]) asks only that, for every vector space $G$, the bilinear maps from $E\times F$ to $G$ correspond bijectively with linear maps $f$ from $E\otimes F$ to $G$, where the map corresponding to $f$ is given by $(x,y)\mapsto f(x\otimes y)$.

::: {.itenv #section-1-theorem-1 title="Theorem 1" latex="{Theorem 1}"}
If $E$ and $F$ are locally convex spaces, then we can endow $E\otimes F$ with a locally convex topology such that, for every locally convex space $G$, the _continuous_ bilinear maps from $E\times F$ to $G$ correspond exactly to _continuous_ linear maps from $E\otimes F$ to $G$.
Further, such a topology is unique.
:::

Then the _equicontinuous_ subsets of $\BB(E,F;G)$ correspond exactly to the _equicontinuous_ subsets of $\LL(E\otimes F;G)$ as well.
Unless otherwise mentioned, $E\otimes F$ is assumed to be endowed with the above topology, called the _projective tensor product of the topologies of $E$ and $F$_;
endowed with this topology, $E\otimes F$ is called the _projective topological tensor product_ of $E$ and $F$.

If $E$ and $F$ are normed, then $E\otimes F$ is normable, and we can even find a norm such that, for every _normed_ space $G$, the above isomorphism between $\BB(E,F;G)$ and $\LL(E\otimes F;G)$ preserves the natural norms.
Further, such a norm is unique.
This norm on $E\otimes F$, denoted by $u\mapsto\|u\|$, where the norms of $E$ and $F$ are implicit, is the lower bound of the quantities $\sum_i\|x_i\|\|y_i\|$ over all representations of $u$ in the form $u=\sum_i x_i\otimes y_i$ (and this norm has already been considered, in [@8]).
It is also the gauge of the set $\Gamma(U\otimes V)$, where $U$ (resp. $V$) is the unit ball in $E$ (resp. $F$), and where $U\otimes V$ denotes the set of $x\otimes y$ such that $x\in U$ and $y\in V$ (with $\Gamma$ denoting, as per usual, the balanced hull).
\oldpage{77}
In the case where $E$ and $F$ are general locally convex spaces, a fundamental system of neighbourhoods of $0$ in $E\otimes F$ is obtained by taking the sets $\Gamma(U\otimes V)$, where $U$ (resp. $V$) runs over a fundamental system of neighbourhoods of $0$ in $E$ (resp. $F$).

We can introduce the completion of $E\otimes F$, denoted by $E\hotimes F$, and called the _completed projective tensor product_ of $E$ and $F$.
If $E$ and $F$ are normed spaces, then $E\hotimes F$ is a Banach space (with a well-defined norm!).
If $E$ and $F$ are metrisable, then $E\hotimes F$ is of type $\FF$.
We have, by definition, the _scholium_: if $E$ and $F$ are locally convex spaces, and $G$ is a _complete_ locally convex space, then the continuous bilinear maps from $E\times F$ to $G$ correspond bijectively to the continuous linear maps from $E\hotimes F$ to $G$.

This claim still holds true for equicontinuous sets of maps.
In particular, the dual of $E\hotimes F$ is $\BB(E,F)$, with a correspondence between the equicontinuous subsets (which already suffices to characterise the induced topology on $E\otimes F$).

I do not know if, when $E$ and $F$ are of type $\FF$, this algebraic isomorphism from the dual of $E\hotimes F$ to $\BB(E,F)$ is a _topological_ isomorphism, when we endow $\BB(E,F)$ with the topology given by bibounded convergence, i.e. uniform convergence on the products of two bounded sets ("the problem of topologies").
An equivalent question is the following:
is every bounded subset of $E\hotimes F$ contained in the closed disked hull of a set $A\hotimes B$, where $A$ (resp. $B$) is a bounded subset of $E$ (resp. $F$)?

$\star$
We now give some general tips for calculations involving $E\hotimes F$ ([[PTT](#ref-PTT), chap. 1, §1, no. 3]).
If $E=\prod_i E_i$ and $F=\prod_j F_j$ (as topological-vectorial products), then $E\hotimes F$ can be identified with $\prod_{i,j}E_i\hotimes F_j$.
If $E=\sum_i E_i$ (as a topological direct sum), and if $F$ is a normable space, then $E\hotimes F$ can be identified with the topological direct sum $\sum_i(E_i\hotimes F)$.
This remains true if $F$ is an arbitrary $\DF$ space, provided that $I$ is countable, and these statements can also be generalised to the case where $E$ is the inductive limit (in the most general sense) of a family $E_i$ of spaces.
If $E$ and $F$ are both of type $\FF$ (resp. type $\DF$), then so too is $E\hotimes F$.
Similarly, if $E$ and $F$ are quasi-normable spaces, or Schwartz spaces (see definitions in [@6, Section 3]), then so too is $E\hotimes F$.
$\star$


## The space $E\hotimes F$ when $E$ and $F$ are of type $\FF$ {#section-1.2}

[[PTT](#ref-PTT), chap. 1, §2, no. 1]

\medskip
\oldpage{78}

::: {.itenv #section-1-theorem-2 title="Theorem 2" latex="{Theorem 2}"}
Let $E$ and $F$ be two $\FF$ spaces.
Then every element of $E\hotimes F$ is the sum of an absolutely convergent series of the form
$$
    u = \sum_i \lambda_i x_i \otimes y_i
$$
where $(x_i)$ (resp. $(y_i)$) is a bounded sequence in $E$ (resp. $F$), and where $(\lambda_i)$ is a summable sequence of scalars.
:::

(It is also true that, if $(x_i)$, $(y_i)$, and $(\lambda_i)$ are given as above, then the series $\sum_i\lambda_i x_i\otimes y_i$ is always absolutely convergent in $E\hotimes F$, and so we have a _characterisation_ of the elements of $E\hotimes F$).
If $E$ and $F$ are normed, then we can suppose in the above that $\|x_i\|\leq1$, $\|y_i\|\leq1$, $\sum_i|\lambda_i|\leq\|u\|_1+\varepsilon$, where $\varepsilon>0$ is arbitrary and given in advance.
In these two statements, if $u$ runs over a compact subset of $E\hotimes F$, then we can suppose that the sequences $(x_i)$ and $(y_i)$ remain fixed (and we can even suppose that they are sequences that tend to $0$), and that $(\lambda_i)$ runs over a compact subset of $\ll^1$ (the space of summable sequences).
We have an analogous statement for the concrete representation of convergent sequences in $E\hotimes F$.
[Theorem 2](#section-1-theorem-2) and its previous variants serve mainly as a way to:

{.itenv title="Corollary" latex="{Corollary}"}
Let $E$ and $F$ be spaces of type $\FF$.
Then every compact subset $K$ of $E\hotimes F$ is contained inside the canonical image of the unit ball of a space $E_A\hotimes F_B$, where $A$ (resp. $B$) is a compact disked subset of $E$ (resp. $F$).
A fortiori, $K$ is contained in the closed convex hull of $A\otimes B$.
:::

This fact also implies that, on $\BB(E,F)$, the "bicompact convergence" topology is identical to the compact convergence topology on the dual of $E\hotimes F$.

$\star$
For the proof of [Theorem 2](#section-1-theorem-2), we suppose, for simplicity, that $E$ and $F$ are Banach spaces, and let $I$ be the product of their unit balls, and $i\mapsto x_i$ and $i\mapsto y_i$ the projections from $I$ to its factors.
It is easy t see that the linear map $(\lambda_i)\mapsto\sum_i\lambda_i x_i\otimes y_i$ from $\ll^1(I)$ to $E\hotimes F$ is a metric homomorphism from the former to a dense subspace of the latter, and thus _onto_ the latter, whence it indeed follows that $E\hotimes F$ can be identified with a quotient space of $\ll^1(I)$.

\oldpage{79}

From [Theorem 2](#section-1-theorem-2), we can extract results of the following type:
let $\scr{G}$ be a locally compact group (resp. a Lie group), then every summable function $f$ (resp. every infinitely differentiable function of compact support) on $\scr{G}$ is of the form $\sum\lambda_i g_i*h_i$, where $(\lambda_i)\in\ll^1$, and where $(g_i)$ and $(h_i)$ are bounded sequences in $\LL^i(\scr{G})$ (resp. in $\scr{D}(\scr{G})$, the space of infinitely differentiable functions of compact support on $\scr{G}$);
we thus immediately conclude that $f$ is a linear combination of functions of positive type that are in $\LL(\scr{G})$ (resp. $\scr{D}(\scr{G})$).
In the former case, we can also restrict to functions that are all of compact support (with the supports of $g_i$ and $h_i$ being contained inside a compact subset that depends only on the compact support of $f$).
There is a simple direct proof in the case of $\LL^1(\scr{G})$, but I do not think that there is one for $\scr{D}(\scr{G})$, where the question presents difficulties even for $\scr{G}=\mathbb{R}$ (by using the Fourier transformation).
$\star$


## Calculation of $\LL^1\hotimes E$ {#section-1.3}

[[PTT](#ref-PTT), chap. 1, §2, no. 2]

\medskip

Let $M$ be a locally compact space endowed with a measure $\mu\geq0$, $E$ a Banach space, and $\LL_E^1(\mu)$ the space of $\mu$-integrable maps from $M$ to $E$ ([@2]) endowed with its usual norm: $\|f\|_1=\int\|f(t)\|\dd\mu(t)$.
We denote by $\LL^1(\mu)$ the space of $\mu$-summable scalar functions.
Then there exists an obvious bilinear map $(\varphi,a)\mapsto\varphi\cdot a$ from $\LL^1(\mu)\times E$ to $\LL_E^1(\mu)$ that is of norm $\leq1$, and thus defines a linear map of norm $\leq1$ from $\LL^1(\mu)\hotimes E$ to $\LL_E^1(\mu)$.

::: {.itenv #section-1-theorem-3 title="Theorem 3" latex="{Theorem 3}"}
The above map from $\LL^1(\mu)\hotimes E$ to $\LL_E^1(\mu)$ is a metric isomorphism from the former space to the latter.
:::

To see this, we can immediately reduce to the case where $E$ is of finite dimension, and then proceed by transposition.
It then suffices to apply the classical theorem of Dunford--Pettis that characterises continuous linear maps from $\LL^1(\mu)$ to $E'$.

If $E$ is an arbitrary locally convex space, then we denote by $\LL_E^1(\mu)$ the completion of the separated space associated to the space of continuous maps with compact support from $M$ to $E$, endowed with its family of semi-norms $f\mapsto\int p(f(t))\dd\mu(t)$ (where $p$ runs over a fundamental family of continuous semi-norms on $E$).
Then [Theorem 3](#section-1-theorem-3) easily implies that $\LL_E^1(\mu)$ is again isomorphic to $\LL^1(\mu)\hotimes E$.

::: {.itenv title="Corollary" latex="{Corollary}"}
If $E$ is a closed vector subspace of the Banach space $F$, then the canonical linear map from $\LL^1(\mu)\hotimes E$ to $\LL^1(\mu)\hotimes F$ is a metric isomorphism.
:::

\oldpage{80}
This recovers, for example, the well-known fact that every continuous linear map from $E$ to the dual $\LL^\infty(\mu)$ of $\LL^1(\mu)$ can be extended to a linear map of the same norm from $F$ to $\LL^\infty(\mu)$;
or, dually, that every continuous linear map from $\LL^1(\mu)$ to a quotient space $F'/E^0$ of a Banach dual by a weakly closed vector subspace comes from a linear map of the same norm from $\LL^1(\mu)$ to $F'$.

$\star$
The analogue of [Theorem 3](#section-1-theorem-3) for $\LL^p$ spaces is false for all $p>1$.
However, [Theorem 3](#section-1-theorem-3) applies, in an essential way, in many important places in the theory outlined here.
We now give some less important applications (see [[PTT](#ref-PTT), chap. 1, §2, no. 2] for details).
In [Theorem 3](#section-1-theorem-3), if we take $E=c_0$ (the space of scalar sequences that converge to $0$), and note that $\LL_E^1(\mu)$ can then be identified with the space of latticially bounded sequences in $\LL^1(\mu)$ that converge to $0$ almost everywhere, then we see that such sequences in $\LL^1(\mu)$ form a category of invariant sequences from the topological-vectorial point of view.
In particular, a continuous linear map from $\LL^1(\mu)$ to a space $\LL^1(\nu)$ sends latticially bounded sequences that converge to $0$ almost everywhere to sequences of the same type.
We thus also see that the latticially bounded subsets of $\LL^1(\mu)$ form an invariant category from the topological-vectorial point of view.
If we take $F=\ll^p$, with $1\leq p<+\infty$, then we similarly obtain a topological-vectorial interpretation of the sequences $(f_i)$ in $\LL^1(\mu)$ such that
$$
\int \left(
  \sum_i |f_i(t)|^p
\right)^{1/p}
\dd\mu(t) < +\infty.
$$
Such sequences are sent to sequences of the same type by any continuous linear map from $\LL^1(\mu)$ to a space $\LL^1(\nu)$.
Another interesting application of [Theorem 3](#section-1-theorem-3) is the following: every bounded subset $M$ of $\LL^1(\mu)\hotimes E$ is contained in the canonical image of the unit ball of a space $\LL^1(\mu)\hotimes E_A$, where $A$ is a closed bounded disk in the space $E$ of type $\FF$;
a fortiori, $M$ is contained in the closed disked hull of $B\otimes A$, where $B$ is the unit ball of $\LL^1(\mu)$, which solves the ``problem of topologies'' described in \hyperref[1.1]{\S1.1}.
$\star$


## Other examples {#section-1.4}

If $H$ is a Hilbert space, then the elements of $H'\hotimes H$, identified with endomorphisms of $H$ (the _Fredholm maps_ or _nuclear maps_ from $H$ to $H$ --- see **TO-DO**) are exactly the endomorphisms $u$ such that the positive Hermitian operator $\sqrt{u^*u}$ is compact and has a summable sequence of eigenvalues, and $\|u\|_1$ is then equal to the sum of the eigenvalues of $\sqrt{u^*u}$ (repeated with multiplicities, of course).
\oldpage{81}
We obtain the operators that have already been studied in [@4] and [@8].
In fact, $u$ is also a Fredholm operator if and only if its Hermitian components $\frac12(u+u^*)$ and $\frac{1}{2i}(u-u^*)$ are, i.e. if they are compact Hermitian operators whose sequences of eigenvalues are summable.
_Relation to Hilbert--Schmidt operators: If $A$ and $B$ are Hilbert--Schmidt operators, then $AB$ is a Fredholm operator, and $\|AB\|_1\leq\|A\|_2\|B\|_2$_;
and, conversely, every Fredholm operator $u$ is the product of two Hilbert--Schmidt operators $A$ and $B$ of norm $\|A\|_2=\|B\|_2=\sqrt{\|u\|_1}$.
All of these facts are elementary (one we know the spectral decomposition of compact Hermitian operators to a Hilbert space) and well known.

Numerous other examples of products $E\hotimes F$, relating to _nuclear spaces_, will be seen in **TO-DO**.

$\star$
In the setting of infinite-dimensional Banach spaces, I do now know, even in particular cases, other concrete characterisations of the elements of $E\hotimes F$ apart from those that we have given.
Also, the elements of $c_0\hotimes E$ (where $E$ can be any complete locally convex space) can be identified with _certain_ sequences in $E$ that converge to $0$, that we can call _nuclearly convergent to $0$_;
but if $E$ is an infinite-dimensional Banach space, then we always obtain a strictly smaller class than the class of all sequences converging to $0$ (see **TO-DO**).
We even show that (if $E$ is an infinite-dimensional Banach space), for any sequence $(\lambda_i)$ of positive scalars that is not square-summable, there exists a sequence $(x_i)$ in $E$ that does not converge nuclearly to $0$, and such that $\|x_i\|=\lambda_i$ for all $i$.
However, if, for example, $E$ is the space $C(K)$ of continuous functions on a compact space, then we show that every square-summable sequence in $C(K)$ converges nuclearly to $0$.
We also point out that, in any complete locally convex space, every summable sequence converges nuclearly to $0$.
$\star$


## $E\hhotimes F$ spaces {#section-1.5}
