--- 
title: "The dualising complex and duality theorems in complex analytic geometry"
author: "Jean-Pierre Ramis, Gabriel Ruget"
date: "1970"
original: |
  J.-P. Ramis, G. Ruget.
  "Complexe dualisant et théorèmes de dualité en géométrie analytique complexe".
  _Publications mathématiques de l'I.H.É.S._ (1970) pp. 77--91.
  [numdam.org/item?id=PMIHES_1970__38__77_0](http://www.numdam.org/item?id=PMIHES_1970__38__77_0)
bibliography: PMIHES-38-1970-77.bib
---

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\newcommand{\sh}[1]{\scr{#1}}
\newcommand{\cat}[1]{\mathbf{#1}}

\newcommand{\OO}{\sh{O}}

\newcommand{\CC}{\mathrm{C}}
\newcommand{\HH}{\mathrm{H}}
\newcommand{\cc}{\mathrm{c}}
\newcommand{\FS}{\mathbf{FS}}
\newcommand{\DFS}{\mathbf{DFS}}
\newcommand{\QFS}{\mathbf{QFS}}
\newcommand{\QDFS}{\mathbf{QDFS}}
\newcommand{\KK}{\mathbf{K}}
\newcommand{\TT}{\mathbf{T}}
\newcommand{\II}{\mathbf{I}}
\renewcommand{\aa}{\mathrm{a}}
\newcommand{\DD}{\mathbf{D}}

\newcommand{\Hom}{\operatorname{Hom}}
\newcommand{\shHom}{\underline{\Hom}}
\newcommand{\RHom}{\operatorname{RHom}}
\newcommand{\Ext}{\operatorname{Ext}}
\newcommand{\shExt}{\underline{\Ext}}
\newcommand{\HyperExt}{\operatorname{HyperExt}}
\renewcommand{\Im}{\operatorname{Im}}
\newcommand{\Ker}{\operatorname{Ker}}
\newcommand{\Spec}{\operatorname{Spec}}
\newcommand{\dd}{\operatorname{d}}
\newcommand{\codim}{\operatorname{codim}}
\newcommand{\Ob}{\operatorname{Ob}}

<!-- Content -->

*[Trans.] The numbering of the footnotes in this translation (globally sequential, starting from 1) differs to that of the original (starting anew from 1 on each page)*.
\bigskip

\oldpage{77}
Let $X$ be a $\sigma$-compact complex analytic manifold of dimension $n$;
we write $\OO$ to mean the sheaf of germs of holomorphic functions on $X$, and $\Omega$ to mean the sheaf of germs of holomorphic differential forms of degree $n$ on $X$.
The correspondence that, to a locally free $\OO$-module $\sh{F}$, associates $\shHom(X;\sh{F},\Omega)$, is involutive.
In [@11], Serre gives, for every integer $p$ and every locally free $\OO$-module $\sh{F}$, a (Fréchet quotient) topology on $\HH^p(X;\sh{F})$ along with a pairing
$$
  \HH^p(X;\sh{F}) \times \HH_\cc^{n-p}(X;\shHom(X;\sh{F},\Omega))
  \to \mathbb{C}
$$
(where the subscript $\cc$ denotes the family of compacts of $X$) which, whenever the groups $\HH^p(X;\sh{F})$ and $\HH^{p+1}(X;\sh{F})$ are separated, makes the (non-topologised) vector space $\HH_\cc^{n-p}(X;\shHom(X;\sh{F},\Omega))$ the topological dual of $\HH^p(X;\sh{F})$.

We could also mention the pairing
$$
  \HH_\cc^p(X;\sh{F}) \times \HH^{n-p}(X;\shHom(X;\sh{F},\Omega))
  \to\mathbb{C}.
$$

Up to replacing $\HH_\cc^{n-p}(X;\shHom(X;\sh{F},\Omega))$ by $\Ext_\cc^{n-p}(X;\sh{F},\Omega)$, the proof by Serre extends [@10] to the case where $\sh{F}$ is an arbitrary coherent $\OO$-module, but by using difficult theorems (with the notation of Schwartz: $\sh{E}$ is a flat $\OO$-module, and, for every $x\in X$, $\sh{D}'_x$ is an injective $\OO_x$-module), due to coming from the division of distributions.
We will show, following ideas of Grothendieck that were readopted by Malgrange, that the duality theorem for coherent sheaves on an analytic manifold is formally much more simple than this (see also [@14]), and that it can be generalised to analytic spaces, as long as we replace $\Omega$ by a suitable "dualising" complex, and the $\Ext$ by $\HyperExt$.
As future work, probably very soon to appear, we note (not to mention an article in preparation with J.-L. Verdier on a relative duality theorem) that Malgrange expects to be able to use the dualising complex to give new proofs of results of Siu [@13] and Andreotti--Grauert [@1].


# Some lemmas on certain complexes of topological vector spaces {#section-1}

We first clarify a point of vocabulary for those readers not familiar with derived categories [@7]: let $\cat{A}$ be an abelian category, and $C(\cat{A})$ the category of bounded-below complexes of objects of $\cat{A}$ (with differentials of degree $+1$ and morphisms of degree $0$).
\oldpage{78}
We define $T$ to be the automorphism of $C(\cat{A})$ that translates complexes one notch to the left and changes the sign of all the differentials.
An object of $C(\cat{A})$ is said to be *acyclic* if all its cohomology objects are zero.
Let $u\colon X^\bullet\to Y^\bullet$ be a morphism in $C(\cat{A})$;
we say that it is a *quasi-isomorphism* if it induces an isomorphism of cohomology objects of $X^\bullet$ to those of $Y^\bullet$;
in this case, we also say that $\xrightarrow{u}Y^\bullet$ is a *resolution* of $X^\bullet$.
We define the *cylinder* of $u$ to be the complex $T(X^\bullet)\oplus Y^\bullet$ endowed with the differential $\left(\begin{smallmatrix}T(d_X)&0\\T(u)&d_Y\end{smallmatrix}\right)$.
Saying that $u$ is a quasi-isomorphism is equivalent to saying that its cylinder is zero.

We denote by the acronym $\FS$ (resp. $\DFS$) Fréchet--Schwartz spaces (resp. the strong duals of Fréchet--Schwartz spaces [@6]), and by the acronym $\QFS$ (resp. $\QDFS$) the quotients of $\FS$-spaces (resp. of $\DFS$-spaces) (which are, as it were, non-separated $\FS$- or $\DFS$-spaces).

::: {.itenv #lemma-1 title="Lemma 1" latex="{Lemma 1}"}
Let $X^\bullet$ and $Y^\bullet$ be complexes of Fréchet spaces (with continuous linear differentials) and $u\colon X^\bullet\to Y^\bullet$ a (continuos linear) morphism.
If $u$ is a quasi-isomorphism (in the purely algebraic sense) then it is a topological quasi-isomorphism, i.e. it induces isomorphisms between the cohomology spaces of $X^\bullet$ and of $Y^\bullet$, where these spaces are endowed with their natural topologies (which are not necessarily separated).
:::

::: {.proof}
If $H^i$ and $K^i$ denote the cohomology spaces of $X^\bullet$ and $Y^\bullet$ (respectively), then it suffices to show that $u$ sends the closure of $0$ in $H^i$ to the closure of $0$ in $K^i$.
Let $M^i$ and $N^i$ be the spaces of cycles of degree $i$ of $X^\bullet$ and $Y^\bullet$ (respectively);
these are Fréchet spaces;
thus, the map $d_Y+u$ from $Y^{i-1}\oplus M^i$ to $N^i$, which is surjective, is a homomorphism.
Since the closed $Y^{i-1}+\overline{d_X(X^{i-1})}$ is saturated with respect to the "projection" $d_Y+u$, its image is closed in $N^i$, and is thus $\overline{d_Y(Y^{i-1})}$, which implies the desired property when we pass to cohomology groups.
:::

::: {.itenv #lemma-1-bis title="Lemma 1 bis" latex="{Lemma 1 bis}"}
[Lemma 1](#lemma-1) remains true if we suppose that both $X^\bullet$ and $Y^\bullet$ are not Fréchet complexes, but complexes of $\DFS$-spaces.
:::

::: {.proof}
This comes from "permanence" properties of $\DFS$-spaces, and the closed-graph theorem for these spaces [@15].
:::

::: {.itenv #lemma-2 title="Lemma 2" latex="{Lemma 2}"}
Let $E\xrightarrow{u}F\xrightarrow{v}G$ be a sequence of $\FS$-spaces and continuous linear maps, such that $v\circ u=0$;
let $E'\xleftarrow{u'}F'\xleftarrow{v'}G'$ be the transpose sequence (with the duals being endowed with the strong topology).
Then the pairing between $F$ and $F'$ induces a pairing between $\Ker{v}/\overline{\Im{u}}$ and $\Ker{u'}/\overline{\Im{v'}}$, which makes each of these spaces (endowed with their natural topology) the strong dual of one another.
:::

::: {.proof}
The natural map from $\Ker{u'}/\overline{\Im{v'}}$ to $(\Ker{v}/\overline{\Im u})'$ is surjective by Hahn--Banach, injective thanks to the semi-reflexivity of $F$, and continuous since $a$ is hypocontinuous with respect to the bounded subsets of $\Ker{v}/\overline{\Im{u}}$ (to see this, it suffices to know how to lift a bounded, i.e. a relatively compact, of $\Ker{v}/\overline{\Im{u}}$ to a bounded of $\Ker{v}$);
it is thus bicontinuous.
\oldpage{79}
Since $\Ker{v}/\overline{\Im{u}}$, being an $\FS$-space, is reflexive, we have thus proven the claim.
:::

::: {.itenv #lemma-3 title="Lemma 3" latex="{Lemma 3}"}
Let $X^\bullet$ and $Y^\bullet$ be complexes of $\FS$-spaces (or even of $\DFS$-spaces), and let $u\colon X^\bullet\to Y^\bullet$ be a quasi-isomorphism.
Then the transpose $u'$ of $u$ is a quasi-isomorphism.
:::

::: {.proof}
The cylinder of $u$ is acyclic;
it is thus a complex whose differentials are operators with closed image;
the transpose complex, which is the cylinder of $u'$, also has differentials with closed image, and, by [Lemma 2](#lemma-2), is acyclic.
:::

Finally, we give a lemma that allows us to cheaply ensure that the topologies on pairs of spaces in duality coincide:

::: {.itenv #lemma-4 title="Lemma 4" latex="{Lemma 4}"}
Let $P$ and $Q$ be $\QFS$-spaces, and $R$ and $S$ be $\QDFS$-spaces;
let $a$ be a pairing between $P$ and $R$ that puts the associated separated spaces in duality, and let $b$ be a pairing of the same sort between $Q$ and $S$;
let $u\colon P\to Q$ and $v\colon S\to R$ be linear maps;
all such that $u$ and $v$ are transpose to one another with respect to $a$ and $b$.
Then $u$ and $v$ are continuous.
:::

::: {.proof}
Since the closure of $\{0\}$ in $P$ (resp. in $S$) is orthogonal to $R$ (resp. to $Q$), we see that $u\overline{\{0_P\}}\subset\overline{\{0_Q\}}$ and $v\overline{\{0_S\}}\subset\overline{\{0_R\}}$.
The maps $u$ and $v$ thus induce transpose maps $\hat{u}$ and $\hat{v}$ between the separated spaces associated to $P$, $Q$, $R$, and $S$.
Since $\hat{u}$ is a transpose, it is weakly continuous, and so its graph is closed;
it is thus strongly continuous, as is $\hat{v}$, and the continuity of $u$ and $v$ then follow.
:::


# Trace. Elementary duality theorem {#section-2}

We use the notations $X$, $\OO$, and $\Omega$ from the introduction.
As a topological manifold, $X$ is canonically oriented, and Poincaré duality gives us a canonical linear form on $\HH_\cc^{2n}(X;\mathbb{C})$.
This form, pre-composed with the composition product of the $\Ext$ (thinking of the $\Ext$ as sheaves of $\mathbb{C}$-spaces), gives a pairing:
$$
  \HH_\cc^n(X;\Omega) \times \Ext_\cc^n(X;\Omega,\mathbb{C})
\to \mathbb{C}.
$$
The complex structure of $X$ now gives us (thinking of the $\Ext$ in terms of their Yoneda interpretation) a remarkable $n$-extension of $\Omega$ by $\mathbb{C}$, namely:
$$
  0 \to \mathbb{C} \to \OO \xrightarrow{d'} \Omega^1 \xrightarrow{d'} \ldots \xrightarrow{d'} \Omega \to 0
$$
where $\Omega^i$ denotes the sheaf of holomorphic differential forms of degree $i$ on $X$.
The linear form on $\HH_\cc^n(X;\Omega)$ associated to this extension is called the *trace*.
The trace also arises in the following way: the complex
$$
  0 \to {\sh{D}'}^{n,0} \xrightarrow{d''} \ldots \xrightarrow{d''} {\sh{D}'}^{n,n} \to 0
\tag{1}
$$
where ${\sh{D}'}^{i,j}$ denotes the sheaf of germs of differential forms on $X$ of type $(i,j)$ with distribution coefficients, is a fine resolution of $\Omega$.
The group $\HH_\cc^n(X;\Omega)$ is thus the $(n+1)$-th cohomology group of the complex of $\DFS$-spaces
\oldpage{80}
$$
  0 \to {\sh{E}'}^{n,0}(X) \xrightarrow{d''} \ldots \xrightarrow{d''} {\sh{E}'}^{n,n}(X) \to 0.
\tag{2}
$$
It is thus naturally endowed with the structure of a $\QDFS$-space, and we see that integration on $X$ of forms of type $(n,n)$ with compact support induces a continuous linear form on $\HH_\cc^n(X,\Omega)$, and this form is precisely $(-1)^n$ times the trace.
(Given a global section $s$ with compact support of ${\sh{D}'}^{n,n}$, we obtain [@4] an $n$-extension $\overline{s}$, in the sense of Yoneda, of $\mathbb{C}$ by $\Omega$. Pre-composed with the $d'$-cohomology complex, this complex gives the extension $(-1)^{n^2}\omega\times\overline{s}\in\Ext_{\cc,\mathbb{C}}^{2n}(X;\mathbb{C},\mathbb{C})$; but we note that this is also "equivalent" to the $2n$-extension of $\mathbb{C}$ by $\mathbb{C}$ associated to the de Rham complex $$0\to\mathbb{C}\to\sh{D}'_0\to\sh{D}'_1\to\ldots\to\sh{D}'_{2n}\to0$$ and to the global section $s$ of $\sh{D}'_{2n}={\sh{D}'}^{n,n}$. Since Poincaré duality is given by integration, our claim is proved.)

Now let $\sh{F}$ be an arbitrary $\OO$-module.
The composition product of the $\Ext$ (of $\OO$-modules), followed by the trace, gives us the pairings
$$
  \HH^p(X;\sh{F}) \times \Ext_\cc^{n-p}(X;\sh{F},\Omega)
  \to \mathbb{C}
\tag{3}
$$
and
$$
  \HH_\cc^p(X;\sh{F}) \times \Ext^{n-p}(X;\sh{F},\Omega)
  \to \mathbb{C}.
\tag{3~bis}
$$

::: {.itenv #lemma-5 title="Lemma 5" latex="{Lemma 5}"}
If $X$ is a Stein manifold, then $\HH_\cc^i(X;\Omega)$ is zero for $i\neq n$;
$\HH_\cc^n(X;\Omega)$ is separated, and the pairing (3) puts it in duality with $\Gamma(X;\OO)$ (endowed with its usual $\FS$ structure).
:::

::: {.proof}
Denote by $\sh{E}^{i,j}$ the sheaf of germs of differential forms on $X$ of type $(i,j)$ with $C^\infty$ coefficients.
The complex
$$
  0 \to \sh{E}^{0,0} \xrightarrow{d''} \ldots \xrightarrow{d''} \sh{E}^{0,n} \to 0
\tag{1~bis}
$$
is a fine resolution of $\OO$;
thus the groups $\HH^i(X;\OO)$ are the cohomology groups of the complex of $\FS$-spaces
$$
  0 \to \sh{E}^{0,0}(X) \xrightarrow{d''} \ldots \xrightarrow{d''} \sh{E}^{0,n}(X) \to 0
\tag{2~bis}
$$
whereas the $\HH_\cc^i(X;\Omega)$ are the cohomology groups of the transpose complex (2).
The lemma then follows from Theorem B (which implies in particular that all the differentials of (2) and (2 bis) have closed image) and from [Lemma 2](#lemma-2).
:::

::: {.itenv #lemma-5-bis title="Lemma 5 bis" latex="{Lemma 5 bis}"}
If $X$ is a Stein manifold, then $\HH_\cc^i(X;\Omega)$ is zero for $i\neq n$;
the pairing (3 bis) puts $\Gamma(X;\Omega)$ (endowed with its usual $\FS$ structure) and $\HH_\cc^n(X;\OO)$ (endowed with the $\DFS$ structure obtained by considering it as a quotient of ${\sh{E}'}^{0,n}(X)$) in duality.
:::

::: {.itenv #lemma-6 title="Lemma 6" latex="{Lemma 6}"}
If $X$ is a Stein manifold, and if $\sh{F}$ is an $\OO$-module that admits a finite resolution by free $\OO$-modules of finite type, then the groups $\Ext_\cc^i(X;\sh{F},\Omega)$ are zero for $i\neq0$, $\Ext_\cc^n(X;\sh{F},\Omega)$ is endowed with a canonical $\DFS$ structure, and (3) puts it in duality with $\Gamma(X;\sh{F})$.
:::

::: {.proof}
This follows from [Lemma 1 bis](#lemma-1-bis) and [Lemma 2](#lemma-2), by induction on the minimum length of the free resolution of $\sh{F}$.
:::


# The dualising complex: statement of the problem. A first duality theorem {#section-3}

\oldpage{81}
Given a $\sigma$-compact analytic space $X$, of bounded dimension, we want to construct a complex $\KK_X^\bullet$ of $\OO$-modules that is bounded and of coherent cohomology, along with a canonical linear form $\TT_X$ on $\HH_\cc^0(X;\KK_X^\bullet)$ such that the following is true:

::: {.itenv #theorem-1 title="Theorem 1" latex="{Theorem }"}
For every coherent $\OO_X$-module $\sh{F}$ and every integer $p$, there exists on $\HH^p(X;\sh{F})$ a unique $\QFS$ structure and on $\Ext_\cc^{-p}(X;\sh{F},\KK_X^\bullet)$ a unique $\QDFS$ structure such that the form $\TT_X$ induces a perfect pairing between the associated separated spaces.
Furthermore, the separation of $\HH^p(X;\sh{F})$ is equivalent to that of $\Ext_\cc^{n-p}(X;\sh{F},\KK_X^\bullet)$.
:::

If $X$ is smooth and of dimension $n$, then $\KK_X^\bullet$ will be a resolution of $T^n\Omega$, and these topologies and this pairing will be exactly those mentioned in the introduction (modulo, obviously, the substitution of $\Ext_\cc^{-p}(X;\sh{F},T^n\Omega)$ for $\Ext_\cc^{n-p}(X;\sh{F},\Omega)$).

In [§5](#section-5) we will construct:

1. For every manifold $V$, a resolution $\KK_V^\bullet$ of $T^{\dim V}\Omega_V$ such that, for every integer $p$ and every $x\in V$, $\KK_{V,x}^p$ is an injective $\OO_{V,x}$-module.

2. For every embedding $f$ of one manifold $V$ into another manifold $W$, a functorial isomorphism of complexes of $\OO_V$-modules
    $$
      \overline{f}\colon \KK_V^\bullet \xrightarrow{\approx} \shHom(W;f_*\OO_V,\KK_W^\bullet)
    $$
    that is compatible with the traces on $\HH_\cc^{\dim V}(V;\Omega_V)=\HH_\cc^0(V;\KK_V^\bullet)$ and on $\HH_\cc^0(W;\KK_W^\bullet)$.

We will use these complexes $\KK_V^\bullet$ to construct the "dualising complex" $\KK_X^\bullet$ of the analytic space $X$, as follows.
Let $U$ be an open of $X$, realisable as an analytic subset of a Stein manifold, and let $\xrightarrow{\varphi}V$ be such a realisation.
The complex $\KK_U^\bullet=\Hom(V;\varphi_*\OO_U,\KK_V^\bullet)$, considered as an $\OO_U$-module, does not depend on the realisation of $U$, as we can see by covering two realisations by a third and using the transitivity of the isomorphisms $\overline{f}$;
it is clearly endowed with a trace $\TT_U\colon\HH_\cc^0(U;\KK_U^\bullet)\to\mathbb{C}$.
We obtain $\KK_X^\bullet$ by gluing together the $\KK_U^\bullet$, and the trace $\TT_X$ similarly (any two traces $\TT_U$ and $\TT_{U'}$ do indeed glue together by Mayer--Vietoris and the vanishing of $\HH_\cc^1(U\cap U';\KK_{U\cap U'}^\bullet)$).

::: {.itenv #lemma-7 title="Lemma 7" latex="{Lemma 7}"}
Let $U$ be an open of $X$, and $\sh{F}$ an $\OO_U$-module.
Suppose that $U$ admits a realisation $\xrightarrow{\varphi}V$ as an analytic subset of a Stein manifold, and that $\varphi_*\sh{F}$ admits a finite resolution by free $\OO_V$-modules of finite type.
Then the groups $\Ext_\cc^i(U;\sh{F},\KK_U^\bullet)$ are zero for $i\neq0$, and $\Ext_\cc^0(U;\sh{F},\KK_U^\bullet)$ is endowed with a canonical $\DFS$ structure, and the pairing induced by $\TT_U$ puts it in duality with $\Gamma(U;\sh{F})$.
:::

::: {.proof}
Algebraically, the canonical morphism from $\Ext_\cc^i(V;\varphi_*\sh{F},\KK_V^\bullet)$ to $\Ext_\cc^i(U;\sh{F},\KK_U^\bullet)$ is an isomorphism (we can reduce to the local $\shExt$ by a standard spectral sequence argument; the fibres of these $\shExt$ are equal, given the coherence of $\sh{F}$, to the $\Ext$ of the fibres; and there, the isomorphism is evident).
As for $\Gamma(U;\sh{F})$ and $\Gamma(V;\varphi_*\sh{F})$, they are evidently topologically isomorphism.
[Lemma 6](#lemma-6) then gives the topology on $\Ext_\cc^0(U;\sh{F},\KK_U^\bullet)$ and proves the desired duality.
:::

\oldpage{82}
We can now prove [Theorem 1](#theorem-1).
Let $\sh{F}$ be a coherent $\OO_X$-module, and $I$ a countable set of indices.
We can find a family of "charts" $\varphi_i\colon\Theta_i\to\mathbb{C}^{N_i}$ and, in each $\mathbb{C}^{N_i}$, an open polydisc $V_i$ such that, if we set $U_i=\varphi^{-1}(V_i)$, we have:

1. For all $i$, the system $(U_i, \sh{F}|U_i, \varphi_i|U_i,V_i)$ satisfies the hypotheses of [Lemma 7](#lemma-7).
2. The $U_i$ form a locally finite (Stein) open cover of $X$, which we denote by $\frak{U}$.

We can then apply [Lemma 7](#lemma-7) not only to the $U_i$, but also to the finite intersections of the $U_i$.
Leray's theorem, combined with Theorem B, tell us that the groups $\HH^i(X;\sh{F})$ are the cohomology groups of the complex of $\FS$-spaces
$$
  \CC^\bullet(\frak{U},\HH^0(\frak{U};\sh{F})).
\tag{4}
$$
We have thus endowed the $\HH^i(X;\sh{F})$ with $\QFS$ topologies that do not depend on the cover $\frak{U}$, by [Lemma 1](#lemma-1).
By [Lemma 7](#lemma-7), the trace $\TT_X$ puts in (topological) duality the complex of cochains in (4) and the complex of finite chains
$$
  \CC_\bullet^\cc(\frak{U},\Ext_\cc^0(\frak{U};\sh{F},\KK_X^\bullet)),
\tag{5}
$$
where the $\Ext_\cc$ are related to one another by the evident arrows in the direction of increasing size (extension by zero).
To interpret the homology of (5), we consider an injective resolution $L^\bullet$ of $\KK_X^\bullet$, and the double complex
$$
  \CC_i^\cc(\frak{U},\Hom_\cc(\frak{U};\sh{F},L^j)).
\tag{6}
$$
If we calculate the hyperhomology of (6) by first working in the $j$ direction, then we find the homology of (5) (the spectral sequence is degenerate by [Lemma 7](#lemma-7)).
Now we work in the $i$ direction.
Since $L^j$ is injective, the sheaf $\shHom(X;\sh{F},L^j)$ is flasque, and thus $\cc$-soft, and the second spectral sequence of (6) is also degenerate [@3], and the hyperhomology of (6) reduces to the homology of $\Hom_cc(X;\sh{F},L^j)$, i.e. to the $\Ext_\cc^j(X;\sh{F},\KK_X^\bullet)$.
By [Lemma 2](#lemma-2), we have thus obtained $\QDFS$ topologies on the $\Ext_\cc^p(X;\sh{F},\KK_X^\bullet)$, such that $\TT_X$ puts the associated separated spaces in duality with the separated spaces associated to the $\HH^{-p}(X;\sh{F})$ (the sign comes from the fact that the simple complex associated to (6) is graded by $j-i$).
[Lemma 4](#lemma-4) ensures the uniqueness of these $\QDFS$ topologies.

The last claim of the theorem comes from the fact that, for the spaces in question, a map has closed image if and only if its transpose has closed image.


# A second duality theorem {#section-4}

::: {.itenv #theorem-2 title="Theorem 2" latex="{Theorem 2}"}
Let $X$ be a $\sigma$-compact analytic space of bounded dimension, $\KK_X^\bullet$ its dualising complex, and $\sh{F}$ a coherent analytic sheaf on $X$.
Then, for every integer $p$, the spaces $\HH_\cc^p(X;\sh{F})$ and $\Ext^{-p}(X;\sh{F},\KK_X^\bullet)$ are endowed with canonical topologies ($\QDFS$ and $\QFS$, respectively), and the trace $\TT_X$ induces a pairing between these spaces that makes the associated separated space of one the strong dual of the associated separated space of the other.
\oldpage{83}
Furthermore, the separation of $\HH_\cc^p(X;\sh{F})$ is equivalent to that of $\Ext^{1-p}(X;\sh{F},\KK_X^\bullet)$.
:::

Here too, by [Lemma 4](#lemma-4), the pair of topologies on $\HH_\cc^p(X;\sh{F})$ and $\Ext^{-p}(X;\sh{F},\KK_X^\bullet)$ is the only pair of $(\QDFS,\QFS)$ topologies such that that $\TT_X$ puts the associated separated spaces in duality.

We start with a lemma analogous to [Lemma 5](#lemma-5).

::: {.itenv #lemma-8 title="Lemma 8" latex="{Lemma 8}"}
Let $X$ be a Stein manifold of dimension $n$, and $K$ a Stein compact of $X$.
Then the groups $\HH_K^i(X;\Omega)$ are zero for $i\neq n$ and $\HH_K^n(X;\Omega)$ is endowed with the structure of an $\FS$-space, $\OO(K)$ has the structure of a $\DFS$-space, and the trace induces a perfect pairing between these spaces (topologised as such).
:::

::: {.proof}
Consider the case $n\geqslant2$;
the vanishing of the $\HH^i(K;\OO)$ for $1\leqslant i\leqslant n$, combined with the exact sequence
$$
  \ldots
  \leftarrow \HH_\cc^{n-p+1}(X\setminus K;\OO)
  \leftarrow \HH^{n-1}(K;\OO)
  \leftarrow \HH_\cc^{n-p}(X;\OO)
  \leftarrow \HH_\cc^{n-p}(X\setminus K;\OO)
  \leftarrow \ldots
$$
implies the vanishing of the $\HH_\cc^i(X\setminus K;\OO)$ for $2\leqslant i\leqslant n-1$, and we see that the natural morphisms from $\OO(K)$ to $\HH_\cc^1(X\setminus K;\OO)$ and from $\HH_\cc^n(X\setminus K;\OO)$ to $\HH_\cc^n(X;\OO)$ are (algebraic) isomorphisms.
Since the latter morphism is continuous, with separated target, its source is also separated, and it is a topological isomorphism.
Also, $\HH_\cc^1(X\setminus K;\OO)$ is separated (this comes from the principle of analytic continuation, which ensures the $(n-1)$-convexity of $X\setminus K$; this also corresponds to the vanishing [@9] of $\HH^n(X\setminus K;\Omega)$), and thus $\OO(K)$ finds itself endowed with a $\DFS$ topology[^1].
Now consider the exact sequence
$$
  \ldots
  \to \HH^{p-1}(X\setminus K;\Omega)
  \to \HH_K^p(X;\Omega)
  \to \HH^p(X;\Omega)
  \to \HH^p(X\setminus K;\Omega)
  \to \ldots
$$
By duality, we know that the natural map from $\Gamma(X;\Omega)$ to $\Gamma(X\setminus K;\Omega)$ is an isomorphism, whence the vanishing of $\HH_K^i(X;\Omega)$ for $i=0,1$;
for $2\leqslant i\leqslant n-1$, we use the vanishing of $\HH^i(X\setminus K;\Omega)$ for $1\leqslant i\leqslant n-2$, which also comes from the duality ($\HH^1(X\setminus K;\Omega)$ is separated because $\HH_\cc^n(X\setminus K;\OO)$ is).
Finally, $\HH^{n-1}(X\setminus K;\Omega)$, which is algebraically isomorphic to $\HH_K^n(X;\Omega)$, is separated and in duality with $\HH_\cc^1(X\setminus K;\OO)$.
The case $n=1$ is completely the same.
:::

[^1]: By using the duality and the closed-graph theorem, we can show, if $U$ is a Stein neighbourhood of $K$, the continuity of the natural map from $\OO(U)$ to $\OO(K)$ thus topologised; we thus deduce that our $\DFS$ topology on $\OO(K)$ coincides with the usual $\scr{LF}$ topology.

We state, without proof, the analogue of [Lemma 7](#lemma-7).

::: {.itenv #lemma-9 title="Lemma 9" latex="{Lemma 9}"}
Under the hypothesis of [Lemma 7](#lemma-7), let $L$ be a Stein compact of $V$, with inverse image $\varphi^{-1}(L)=K$.
Then the groups $\Ext_K^i(X;\sh{F},\KK_X^\bullet)$ are zero for $i\neq0$ and $\Ext_K^0(X;\sh{F},\KK_X^\bullet)$ is endowed with the structure of an $\FS$-space, $\HH^0(K;\sh{F})$ has the structure of a $\DFS$-space, and the trace puts these two structures in duality.
:::

To prove [Theorem 2](#theorem-2), we take a "cover" of $X$ as we did for the proof of [Theorem 1](#theorem-1);
\oldpage{84}
we further take, in each $V_i$, a compact polydisc $L_i$ such that the compacts $K_i=\varphi_i^{-1}(L_i)$ form a locally finite cover $\frak{R}$ of $X$.
Consider the two complexes that are in duality:
$$
  \CC_\cc^\bullet(\frak{R},\HH^0(\frak{R};\sh{F}))
\tag{8}
$$
and
$$
  \CC_\bullet(\frak{R},\Ext_\frak{R}^0(X;\sh{F},\KK_X^\bullet))
\tag{8~bis}
$$
where the former is a complex of $\DFS$-spaces and the latter of $\FS$-spaces.
Since the cohomology groups of (8) are the $\HH_\cc^i(X;\sh{F})$, and those of (8 bis) are the $\Ext^{-i}(X;\sh{F},\KK_X^\bullet)$, [Lemma 2](#lemma-2) implies [Theorem 2](#theorem-2) (the last claim of the theorem can be proven in the same way as the analogous claim of [Theorem 1](#theorem-1)).


# Construction of the dualising complex {#section-5}

We will first construct, given a germ at a point $x$ of a complex analytic manifold $V$, what will become the fibre at $x$ of the complex $\KK_V^\bullet$.
To each germ of the embedding $f$ of the germ $(V,x)$ into another germ $(W,y)$, we will associate an isomorphism $\overline{f_x}$ from $\KK_{V,x}^\bullet$ to $\Hom_{\OO_{W,y}}(\OO_{V,x},\KK_{W,y}^\bullet)$ (which, by the coherence of $f_*\OO_V$, will be precisely the fibre at $x$ of $\shHom(W;f_*\OO_V,\KK_W^\bullet)$), functorially with respect to the composition of embeddings.
We will then point out which topology on $\bigcup_{x\in V}\KK_{V,x}^\bullet$ makes it into the complex of sheaves $\KK_V^\bullet$.
We will leave to the reader the task of convincing themselves that, given an embedding $f$ of $V$ into $W$, the isomorphisms $\overline{f_x}$ glue together to give an isomorphism $\overline{f}$ from $\KK_V^\bullet$ to $\shHom(W;f_*\OO_V,\KK_W^\bullet)$.

## A. The fibre of the dualising complex {#section-5.a .unnumbered}

Given a germ $(V,x)$ of a manifold, we denote by $A$ the ring $\OO_{V,x}$;
then $\Spec{A}$ denotes the prime spectrum of $A$, and $\widetilde{A}$ denotes the canonical sheaf on $\Spec{A}$.
If $Z^p$ denotes the set of points of $\Spec{A}$ of codimension $\geqslant p$, then the Cousin complex of $\widetilde{A}$ with respect to the filtration $Z^p$ of $\Spec{A}$ is the complex
$$
  0
  \to \sh{H}_{Z^0/Z^1}^0(\widetilde{A})
  \to \sh{H}_{Z^1/Z^2}^1(\widetilde{A})
  \to \ldots \to 0.
$$

The topological space $\Spec{A}$ is Noetherian;
its closed irreducibles have a unique generic point;
the $Z^p$ are stable under specialisation, and every point of $Z^p\setminus Z^{p+1}$ is maximal in $Z^p$.
It thus follows that we have canonical functorial isomorphisms [@7, motif F, p. 225]
$$
  \sh{H}_{Z^p/Z^{p+1}}^q(\widetilde{A})
  \xrightarrow{\approx} \coprod_{\alpha\in Z^p\setminus Z^{p+1}}i_\alpha(\HH_\alpha^q(\widetilde{A}))
\tag{9}
$$
where $\HH_\alpha^q(\widetilde{A})$ is the fibre at $\alpha$ of $\sh{H}_{\overline{\{\alpha\}}}^q(\widetilde{A})$, and where $i_\alpha(G)$ denotes the sheaf that is constant and equal to $G$ along $\overline{\{\alpha\}}$ and zero elsewhere.

The $\sh{H}_{Z^p/Z^{p+1}}^q(\widetilde{A})$ are zero for $q>p$ [@7, Lemma 2.4, p. 235], and also for $q<p$ (since the ring $A$ is regular, and thus Cohen--Macaulay).
\oldpage{85}
The natural map $\widetilde{A}\to\sh{H}_{Z^0/Z^1}^0(\widetilde{A})$ thus makes [@7, Chapter 4, (2.6)] the Cousin complex a flasque resolution of $\widetilde{A}$.
It thus follows that the complex
$$
  0
  \to \Gamma\sh{H}_{Z^0/Z^1}^0(\widetilde{A})
  \to \Gamma\sh{H}_{Z^1/Z^2}^1(\widetilde{A})
  \to \ldots
$$
is a resolution of $\Gamma\widetilde{A}=A$ (the $\HH^i(\Spec{A},\widetilde{A})$ are zero for $i>0$).
We denote this complex by $L_{V,x}^\bullet$, and we can show that it is a complex of injective $A$-modules: by (9), and the fact that $A$ is Noetherian, it suffices to show that the $\HH_\alpha^p(\widetilde{A})$, for $\alpha\in Z^p\setminus Z^{p+1}$, are $A$-injective;
but we know [@8, (4.13)] that $\HH_\alpha^p(\widetilde{A})$ is an injective envelope over $A_\alpha$ of the residue field $\kappa(\alpha)$.

For example, if $V$ is a curve, then we obtain as a resolution of $\OO_x$ the complex $0\to\sh{M}_x\to\sh{M}_x/\OO_x\to0$, where $\sh{M}_x$ is the ring of germs of meromorphic functions at $x$.

We set $\KK_{V,x}^\bullet=T^{\dim V}(L_{V,x}^\bullet\otimes_A\Omega_{V,x})$.

When $f$ is a local isomorphism from one germ $(V,x)$ to another $(W,y)$, the isomorphism $\overline{f_x}$ goes without saying.
We now consider the case where $(V,x)$ is a germ of a codimension 1 submanifold of $(W,y)$: set $A=\OO_{V,x}$ and $B=\OO_{W,y}$, and chose a regular function $z\in B$ that defines $V$.
The sequence
$$
  0 \to B \xrightarrow{\mu_z} B \xrightarrow{\rho} A \to 0
$$
is exact, where $\mu_z$ denotes multiplication by $z$, and $\rho$ denotes restriction;
then $\rho$ induces a map $r$ that witnesses $\Spec{A}$ as a subspace of $\Spec{B}$.
The sequence
$$
  - \to \widetilde{B} \xrightarrow{\mu_z} \widetilde{B} \xrightarrow{\rho} r_*\widetilde{A} \to 0
$$
of sheaves on $\Spec{B}$ is exact.
We denote by $Z^p$ (resp. by $T^p$) the set of points of $\Spec{A}$ (resp. of $\Spec{B}$) of codimension $\geqslant p$;
the trace of $T^p$ on $\Spec{A}$ is equal to $Z^{p-1}$.
We want to understand $\Hom_B(A,\Gamma\sh{H}_{T^p/T^{p+1}}^p(\widetilde{B}))-\coprod_{\beta\in T^p\setminus T^{p+1}}\Hom_B(A,\HH_\beta^p(\widetilde{B}))$.
But $\Hom_B(A,\HH_\beta^p(\widetilde{B}))$ can be identified with the kernel of $\mu_z\colon\HH_\beta^p(\widetilde{B})\to\HH_\beta^p(\widetilde{B})$, which is a morphism that fits into the exact sequence
$$
  \HH_\beta^{p-1}(\widetilde{B})
  \to \HH_\beta^{p-1}(r_*\widetilde{A})
  \xrightarrow{\partial_z} \HH_\beta^p(\widetilde{B})
  \xrightarrow{\mu_z} \HH_\beta^p(\widetilde{B})
$$
in which the first group is zero (since $B$ is regular, and thus Cohen--Macaulay).
If $\beta\not\in\Spec{A}$, then $\Spec{B}\setminus\Spec{A}$ is a neighbourhood of $\beta$, on which the sheaf $r_*\widetilde{A}$ is zero;
thus
$$
  \HH_\beta^{p-1}(r_*\widetilde{A})
  = \Hom_B(A,\HH_\beta^p(\widetilde{B}))
  = 0.
$$
If $\beta\in\Spec{A}$, then $\HH_\beta^{p-1}(\Spec{B};r_*\widetilde{A})$ can be identified with $\HH_\beta^{p-1}(\Spec{A};\widetilde{A})$, and so
$$
  \coprod_{\beta\in T^p\setminus T^{p+1}}\Hom_B(A,\HH_\beta^p(\widetilde{B}))
$$
can be identified with
$$
  \coprod_{\alpha\in Z^{p-1}\setminus Z^p} \HH_\alpha^{p-1}(\widetilde{A})
  = \Gamma\sh{H}_{Z^{p-1}/Z^p}^{p-1}(\widetilde{A}).
$$
\oldpage{86}
We have obtained an isomorphism $\Delta_z$ (depending on the chosen generator $z$ of the ideal of $V$)
$$
  \Delta_z\colon
  L_{V,x}^{p-1}
  \xrightarrow{\approx} \Hom_B(A,L_{W,y}^p).
$$
From this we will deduce an isomorphism
$$
  \overline{f}\colon
  \KK_{V,x}^q
  \xrightarrow{\approx} \Hom_B(A,\KK_{W,y}^q).
$$
For this, it suffices to note that there is a natural isomorphism
$$
  \omega_z\colon
  \Omega_{V,x}\otimes_A\Hom_B(A,L_{W,y}^p)
  \xrightarrow{\approx} \Hom_B(A,\Omega_{W,y}\otimes_B L_{W,y}^p)
$$
coming from the $\rho$-morphism from $\Omega_{W,y}$ to $\Omega_{V,x}$ that, to the holomorphic differential form $\psi\wedge\dd{z}$, associates the form $\psi|V$;
finally, we can show that the isomorphism $\overline{f}$ thus described does not depend on $z$: if we replace $z$ by $z'$, then $\Delta$ is multiplied by $(z/z')|V$, and $\omega^{-1}$ is too (we could have recognised the formalism of the construction of a residue class)[^2].

[^2]: After gluing the fibres, $\overline{f}$ induces the canonical isomorphism from $\Omega_V$ to $\shExt^{n-p}(W;\OO_V,\Omega_W)$, where $n$ denotes the dimension of $W$ and $p$ the dimension of $V$.
    To show the compatibility of $\overline{f}$ with the traces, it is helpful to reinterpret this isomorphism: it comes from the morphisms
    $$
      {\sh{D}'}_V^{p,p-i}
      \to \shHom(W;\OO_V,{\sh{D}'}_W^{n,n-i})
    $$
    which are themselves "*transposes*" of the natural morphisms
    $$
      \sh{E}_V^{0,i}
      \leftarrow \sh{E}_W^{0,i}\otimes_{\OO_W}\OO_V.
    $$


## B. The gluing of fibres {#section-5.b .unnumbered}

Given an open $U$ of $\mathbb{C}^n$, we will show how to glue the complexes $L_{U,x}^\bullet$ at various points $x\in U$ to obtain a resolution $L_U^\bullet$ of $\OO_U$ with injective fibres.
Then, given a manifold $V$, to obtain $\KK_V^\bullet$, it remains only to glue the $L_U^\bullet$, and then to tensor over $\OO_V$ by $\Omega_V$.

If $K$ is a closed polydisc[^3] of $\mathbb{C}^n$, then the ring $\OO_K$ of germs of analytic functions in a neighbourhood of $K$ is Noetherian (cf. [@5]).
We denote by $L_K^\bullet$ the complex of global sections (over $\Spec{\OO_K}$) of the Cousin complex of $\OO_K$.

[^3]: To be completely honest, we actually use polydiscs "*twisted*" by a change of chart.

If $K'$ is a closed sub-polydisc of $K$, then the restriction map $\rho_{KK'}$ from $\OO_K$ to $\OO_{K'}$ makes the latter a flat $\OO_K$-module[^4];
we thus deduce the existence of a natural $\rho_{KK'}$-morphism from $L_K^\bullet$ to $L_{K'}^\bullet$, of which we give an explicit construction below (we note that, in fact, this construction does not use the flatness of $\OO_{K'}$ over $\OO_K$).
We then show that if $x$ is an interior point of the polydisc $K$ then the natural morphism $\lim_{K'\ni x}L_{K'}^\bullet\to L_x^\bullet$ (where the limit is taken over polydiscs: $x\in\mathring{K'}\subset K$) is an isomorphism.
It will then be possible to say that a section over an open $U$ of $\mathbb{C}^n$ of the collection of the $L_x^\bullet$ (for $x\in U$) is continuous if, locally, it is induced by an element of some $L_K^\bullet$.

[^4]: This follows from Theorems A and B in a neighbourhood of $K'$, and from the Oka theorem.


:::: {.rmenv #section-5.b.i title="(i) Germs in the neighbourhood of a polydisc" latex="{(i) Germs in the neighbourhood of a polydisc}"}
We define, as usual, the germs of analytic sets in the neighbourhood of a closed polydisc $K$ in $\mathbb{C}^n$.
Let $\II\colon X_K\to\II(X_K)$ be the map that, to a germ of an analytic set in the neighbourhood of $K$, associates the ideal of germs of $\OO_K$ that vanish identically there;
$\II$ realises a bijection[^5] between the germs of an analytic set in the neighbourhood of $K$ and the closed subsets of $\Spec{\OO_K}$, with the irreducible germs corresponding to the irreducible closed subsets of $\Spec{\OO_K}$ (i.e. to the prime ideals of $\OO_K$).
Furthermore, $\codim X_K=\codim\II(X_K)$ (where $\codim X_K$ is the usual "geometric" codimension, and $\codim\II(X_K)$ is the codimension of the closed associated with $\II(X_K)$ in $\Spec{\OO_K}$).

[^5]: An arbitrary ideal $J\subset\OO_K$ is generated by a finite number of germs, and we have the "Nullstellensatz": the radical of $J$ is equal to $\II$ of the germ defined by $(f_1,\ldots,f_m)$.

Let $A$ and $A'$ be (commutative unital) rings.
To each homomorphism $\varphi\colon A\to A'$, we associate the continuous map $\varphi^\aa\colon\Spec{A'}\to\Spec{A}$.

We say that the triple $(A,A',\varphi)$ satisfies condition (C) if
$$
  (\varphi^\aa)^{-1}(\overline{\{x\}})
  = \overline{\{(\varphi^\aa)^{-1}(x)\}}
  \qquad\text{for all }x\in\Spec{A}.
$$

It is easy to see that, if $(A,A',\varphi)$ satisfies (C), then the map $\varphi^\aa$ is compatible with the canonical filtrations of $\Spec{A}$ and of $\Spec{A'}$:
$$
  (\varphi^\aa)^{-1}(Z_p(A)) \subset Z_p(A').
$$

::: {.itenv #lemma-10 title="Lemma 10" latex="{Lemma 10}"}
If $K$ and $K'$ are closed polydiscs of $\mathbb{C}^n$, with $K'\subset K$, then the triple $(\OO_K,\OO_{K'},\rho_{KK'})$ satisfies condition (C).
:::

::: {.proof}
Since the map $\varphi^\aa$ is continuous, the set $(\varphi^\aa)^{-1}(\overline{\{x\}})$ is closed and we have that $\overline{\{(\varphi^\aa)^{-1}(x\}}\subset(\varphi^\aa)^{-1}(\overline{\{x\}})$.

It remains to prove the inverse inclusion.
Let $z$ be a prime ideal of $\OO_K$.
We associate to it an irreducible germ $Z_K$ (in the neighbourhood of $K$: $z=\II(Z_K)$).
The restriction $Z_{K'}$ of the latter to a germ in the neighbourhood of $K'$ admits the irreducible decomposition $Z_{K'}=\bigcup_{i=1,\ldots,m}Z_{K'}^i$.
Setting $z'_i=\II(Z_{K'}^i)$, we see that the $z'_i$ are the maximal prime ideals of $\OO_{K'}$ over $z$.
Thus, if $y$ is a specialisation of $x\in\Spec{\OO_K}$, the prime ideals of $\OO_{K'}$ over $y$ are the specialisations of the maximal ideals of $\{(\varphi^\aa)^{-1}(x)\}$.
:::
::::

:::: {.rmenv #section-5.b.ii title="(ii) The morphism $L_K^\bullet\to L_{K'}^\bullet$" latex="{(ii) The morphism $L_K^\bullet\to L_{K'}^\bullet$}"}
Let $\alpha$ be a point of $\Spec{\OO_K}$ of codimension $p$.
We need to (following [§5.A](#section-5.a), whose notation we use) construct a $\rho_{KK'}$-morphism $\lambda$ from $\HH_\alpha^p(\widetilde{\OO}_K)$ to $\coprod_{\beta\in Z^p(\OO_{K'})\setminus K^{p+1}(\OO_{K'})} \HH_\beta^p(\widetilde{\OO}_{K'}).$

We spell out the details for $p\geqslant2$;
for $p=0,1$, the situation is the same.
We first interpret $\HH_\alpha^p(\widetilde{\OO}_K)$: it is the limit, over the affine opens containing $\alpha$, of $\HH_{\overline{\{\alpha\}}}^p(U;\widetilde{\OO}_K)$.
\oldpage{88}
When $U$ is affine, $\HH^i(U;\widetilde{\OO}_K)$ is zero for $i\geqslant1$, and $\HH_{\overline{\{\alpha\}}}^p(U;\widetilde{\OO}_K)$ can be identified with $\HH^{p-1}(U\setminus\overline{\{\alpha\}})$.
Let $f\in\OO_K$;
to it, we associate the affine open $D_f=\Spec{\OO_K}\setminus V(f)$.
If $D_{f_1},\ldots,D_{f_m}$ is an affine cover of $\Spec{\OO_K}\setminus\overline{\{\alpha\}}$, the $D_{f_j}\cap U$ form, for every affine open $U=D_g$, an affine open cover of $U\setminus\overline{\{\alpha\}}$ and, by Leray's theorem, an element of $\HH^{p-1}(U\setminus\overline{\{\alpha\}};\widetilde{\OO}_K)$ can be identified with a cocycle (modulo coboundaries) of this cover.
Let $g_{j_1,\ldots,j_p}$ be a cocycle thus associated to an element $c\in\HH_\alpha^p(\widetilde{\OO}_K)$ (where $g_{j_1,\ldots,j_p}\in(gf_{j_1}\ldots f_{j_p})^{-1}\OO_K$).
The restriction $\rho_{KK'}$ induces the map $\rho_{KK'}^\aa$ from $\Spec{\OO_{K'}}$ to $\Spec{\OO_K}$, since the inverse image under $\rho_{KK'}^\aa$ of an affine open is evidently again an affine open.

We are now in such a place where we are able to give the construction of $\lambda$.

If there is not a prime ideal of $\OO_{K'}$ over $\alpha$, we set $\lambda|\HH_\alpha^p(\widetilde{\OO}_K)=0$.
Otherwise, the maximal prime ideals over $\alpha$ are finite in number, and all of the same codimension as $\alpha$ (cf. [§5.B (i)](#section-5.b.i));
we denote them by $\beta_1,\ldots,\beta_s$.
The opens $D_{\rho_{KK'}}(f_i)$ form an affine cover of $(\rho_{KK'}^\aa)^{-1}(U)\setminus(\overline{\{\beta_1\}}\cup\ldots\cup\overline{\{\beta_s\}})$, and the $\rho_{KK'}(g_{j_1,\ldots,j_p})$ determine a cocycle of this cover, and thus an element $\gamma$ of $\HH^{p-1}((\rho_{KK'}^\aa)^{-1}(U)\setminus\bigcup_{i=1,\ldots,s}\overline{\{\beta_i\}};\widetilde{\OO}_{K'})$.
We can find an affine neighbourhood $V$ of $\beta_k$ contained inside $(\rho_{KK'}^\aa)^{-1}(U)\setminus\bigcup_{i\neq k}\overline{\{\beta_i\}}$.
The restriction of $\gamma$ to $\HH^{p-1}(V\setminus\overline{\{\beta_k\}};\widetilde{\OO}_{K'})$ induces an element of $\HH_{\overline{\{\beta_k\}}}^p(V;\widetilde{\OO}_{K'})$, and thus an element $\gamma_k$ of $\HH_{\beta_k}^p(\widetilde{\OO}_{K'})$.
We set
$$
  \lambda(c)
  = \sum_{k=1,\ldots,s} \gamma_k.
$$

Using [Lemma 10](#lemma-10), we can show (with no difficulty apart from writing the diagrams...) that the morphism (of graded objects) thus obtained coincides with the canonical $\rho_{KK'}$-morphism (of complexes) from $L_K^\bullet$ to $L_{K'}^\bullet$ (whose existence we prove by using the flatness of $\OO_{K'}$ over $\OO_K$ and the compatibility of $\rho_{KK'}$ with the canonical filtrations of $\Spec{\OO_K}$ and $\Spec{\OO_{K'}}$).
::::


:::: {.rmenv #section-5.b.iii title="(iii) Surjectivity of $\lim_{K\ni x}L_K^\bullet\to L_x^\bullet$" latex="{(iii) Surjectivity of $\lim_{K\ni x}L_K^\bullet\to L_x^\bullet$}"}
Let $\beta\in Z^p\setminus Z^{p+1}$, and $\gamma\in\HH_\beta^p(\widetilde{\OO}_x)$.
There exists a polydisc $K$ that is a neighbourhood of $x$ such that $(\rho_{Kx}^\aa)^{-1}\rho_{Kx}^\aa(\beta)$ is equal to $\beta$ (which implies that $(\rho_{K'x}^\aa)^{-1}\rho_{K'x}^\aa(\beta)=\beta$ for all $K'$ such that $x\in K'\subset K$, and in particular that the prime ideals $\alpha_{K'}=\rho_{K'x}^\aa(\beta)$ all have the same height $p$).
Choose generators $\varphi_1,\ldots,\varphi_m$ of $\alpha_K$, and let $\psi$ be an element of $\OO_x\setminus\beta$ (so that $\psi$ determines an affine neighbourhood $D_\psi$ of $\beta$).
We still suppose that $p\geqslant2$: $\gamma$ is represented by a cocycle $\gamma_{i_1\ldots i_p}$ (where $\gamma_{i_1\ldots i_p}\in(\psi\rho_{Kx}(\varphi_{i_1})\ldots\rho_{Kx}(\varphi_{i_p}))^{-1}\OO_x$).
Choose a polydisc $L\subset K$ such that $\psi$ lifts to $\overline{\psi}$ in $\OO_L$ and such that the $\lambda_{i_1\ldots i_p}$ that lift to $\overline{\lambda}_{i_1\ldots i_p}(\overline{\psi}\rho_{KL}(\varphi_{i_1})\ldots\rho_{KL}(\varphi_{i_p}))^{-1}\OO_L$ form a cocycle.
This cocycle induces an element $\overline{\gamma}$ of $\HH_{\alpha_L}^p(\widetilde{\OO}_L)$ such that $\lambda(\overline{\gamma})=\gamma$.
::::

:::: {.rmenv #section-5.b.iv title="(iv) Injectivity of $\lim_{K\ni x}L_K^\bullet\to L_x^\bullet$" latex="{(iv) Injectivity of $\lim_{K\ni x}L_K^\bullet\to L_x^\bullet$}"}
We prove injectivity in an entirely similar way (noting that, if $\beta_1\ldots,\beta_s$ belong to $Z^p\setminus Z^{p+1}$, then we can find a closed polydisc $K$ that is a neighbourhood of $x$, as small as we like, such that the $(\rho_{Kx}^\aa)^{-1}\rho_{Kx}^\aa(\beta_i)$ are equal to $\beta_i$ for $i=1,\ldots,s$).
\oldpage{89}
::::

Having described the dualising complex of a manifold, we can now be more precise about that of a space $X$, as we constructed in [§3](#section-3).

At a point $x$ of $X$, this complex appears, *a priori*, to be able to be non-zero from degree $0$ to degree equal to the negative of the tangential dimension of $X$ at $x$.
In fact, the interpretation given in [§5.b (ii)](#section-5.b.ii) of the dualising complex of a manifold shows that $\KK_X^\bullet$ is zero in degrees less than the negative of the dimension of $X$ at $x$ (this also implies, by duality, that the $\HH^I(X;\sh{F})$ are zero whenever $\sh{F}$ is coherent and $i$ exceeds the dimension of $X$).
It is also clear by construction that $\KK_X^\bullet$ is of coherent cohomology, and even of zero cohomology in degrees strictly greater than the negative of the depth of $X$ (if $X$ admits an embedding $f$ into a manifold $U$, then $\HH^i(\KK_X^\bullet)=f^*\Ext^i(U;f_*\OO_X,\KK_U^\bullet)$).

Thus, in the case where $X$ is a curve, $\KK_X^\bullet$ is a resolution of a coherent sheaf in degree $-1$, namely its $(-1)$-st cohomology sheaf (a sheaf which we can interpret [@11] by means of regular differential forms on the normalised curve of $X$, and which is invertible if $X$ is a complete intersection[^6]).

[^6]: We will later see that this sheaf is invertible if and only if $X$ is "Gorenstein".


### Uniqueness of the dualising complex {.unnumbered}

Let $X$ be an analytic space and $\OO$ its structure sheaf.
We denote by $\DD(X)$ the derived category of the abelian category of $\OO$-modules, and by $\DD_\cc(X)$ (resp. by $\DD_\cc^+(X)$, resp. by $\DD_\cc^-(X)$) the full subcategory of $\DD(X)$ whose objects are complexes with coherent cohomology (resp. bounded-below complexes with coherent cohomology, resp. bounded-above complexes with coherent cohomology).

Let $\mathbf{R}^\bullet\in\Ob\DD_\cc^+(X)$ be a complex whose fibres of of finite injective dimension (that is, such that for all $x\in X$ there exists $n(x)\in\mathbb{Z}$ such that $\Ext_{\OO_x}^i(\mathbb{C},\mathbf{R}_x^\bullet)=0$ for $i>n(x)$).
We associate to this complex the functor
$$
  \begin{aligned}
    D\colon \DD(X)
    &\longrightarrow \DD(X)
  \\F^\bullet
    &\longmapsto \RHom^\bullet(F^\bullet,\mathbf{R}^\bullet).
  \end{aligned}
$$

::: {.rmenv title="Definition" latex="{Definition}"}
A complex $F^\bullet\in\Ob\DD(X)$ is said to be *reflexive* with respect to $\mathbf{R}^\bullet$ if the natural map $F^\bullet\to DD(F^\bullet)$ is an isomorphism.
:::

::: {.rmenv title="Definition" latex="{Definition}"}
If every $F^\bullet\in\Ob\DD_\cc(X)$ is reflexive with respect to $\mathbf{R}^\bullet$, then $\mathbf{R}^\bullet$ is said to be *dualising*.
:::

::: {.itenv #proposition-1 title="Proposition 1" latex="{Proposition 1}"}
For a complex $\mathbf{R}^\bullet\in\Ob\DD_\cc^+(X)$ with fibres of finite injective dimension, the following conditions are equivalent:
\oldpage{90}

i. The complex $\mathbf{R}^\bullet$ is dualising.
ii. The structure sheaf $\OO$ is reflexive with respect to $\mathbf{R}^\bullet$.
iii. For all $x\in X$, the complex (of $\OO_x$-modules) $\mathbf{R}_x^\bullet$ is dualising.
:::

::: {.proof}
The implication (i)$\implies$(ii) is clear;
it remains to show (ii)$\implies$(iii) and (iii)$\implies$(i).
The complex $\mathbf{R}^\bullet$ is isomorphic (in $\DD^+(X)$) to a complex $I^\bullet$ of injective $\OO$-modules.
The natural morphism $F^\bullet\to DD(F^\bullet)$ (in $\DD(X)$) comes from a morphism of complexes
$$
  F^\bullet \to \Hom^\bullet(\Hom^\bullet(F^\bullet,I^\bullet),I^\bullet)
\tag{1}
$$
(cf. [@7, Chapter V, (1.2)]).

If (ii) is satisfied, then the morphism (1) associated to $F^\bullet=\OO$ is a quasi-isomorphism, and thus induces a quasi-isomorphism on the fibres (by the coherence of the cohomology objects), and (iii) is satisfied [@7, Chapter V, (2.1), (iv)].
Conversely, if (iii) is true, then the morphism (1) induces the natural map $F_x^\bullet\to D_xD_x(F_x^\bullet)$, which is an isomorphism, and so (1) is a quasi-isomorphism on the fibres and thus a quasi-isomorphism.
Thus (1) induces an isomorphism $F^\bullet\to DD(F^\bullet)$, and (i) is satisfied.
:::

::: {.itenv #theorem-3 title="Theorem 3" latex="{Theorem 3}"}
Let $X$ be a connected analytic space.
Let $\mathbf{R}^\bullet$ be a dualising complex on $X$.
If ${\mathbf{R}'}^\bullet\in\Ob\DD(X)$, then it is dualising if and only if there exists an integer $n$ and an invertible sheaf $\sh{L}$ on $X$ such that
$$
  {\mathbf{R}'}^\bullet \cong \mathbf{R}^\bullet\otimes_{\OO}T^n\sh{L}
$$
(in $\DD(X)$).
Furthermore, if ${\mathbf{R}'}^\bullet$ is dualising, then $\sh{L}$ and $n$ are uniquely determined.
:::

::: {.proof}
If ${\mathbf{R}'}^\bullet=\mathbf{R}^\bullet\otimes_{\OO}T^n\sh{L}$, then it is clear that ${\mathbf{R}'}^\bullet$ is dualising.
Conversely, if $\mathbf{R}^\bullet$ and ${\mathbf{R}'}^\bullet$ are dualising, then denote by $D$ and $D'$ the dualising functors that are associated to them (respectively) and we "reproduce" [@7, Chapter V, (3.1)].
Setting $L^\bullet=D'D(\OO)$ and ${L'}^\bullet=DD'(\OO)$, we can show that $L^\bullet\otimes_{\OO}{L'}^\bullet\cong\OO$;
we conclude by the analogue of [@7, Chapter V, (3.3)].
:::

If $\KK_X^\bullet$ is the complex associated to the analytic space $X$, it is clear that it is dualising (which justifies our terminology!).
The uniqueness theorem will allow us, in certain cases, to obtain some information about $\KK_X^\bullet$.


### Particular cases {.unnumbered}

:::: {.rmenv title="Gorenstein analytic spaces" latex="{Gorenstein analytic spaces}"}
Let $A$ be an integral Noetherian local ring.
Recall that $A$ is said to be *Gorenstein* if the following equivalent conditions are satisfied (cf. [@2; @7]):

i. $A$ is a dualising complex (with respect to itself).
ii. $A$ admits a finite injective resolution.
iii. There exists an integer $d$ such that
    $$
      \Ext_A^i(k,A) =
      \begin{cases}
        0 &\text{for }i\neq d
      \\k &\text{for }i=d
      \end{cases}
    $$
    (where $k$ denotes the residue field of $A$).

A Gorenstein ring is Cohen--Macaulay;
we thus deduce that the integer $d$ from (iii) is the Krull dimension of $A$.

\oldpage{91}
If $A$ is a Noetherian ring, we will say that it is Gorenstein if all its localisations are Gorenstein (i.e. if the scheme $(\Spec{A},\widetilde{A})$ is a Gorenstein scheme!).

::: {.rmenv title="Definition" latex="{Definition}"}
We say that an analytic space $X$ with structure sheaf $\OO$ is *Gorenstein* if, for all $x\in X$, the ring $\OO_x$ is Gorenstein.
:::

::: {.itenv #proposition-2 title="Proposition 2" latex="{Proposition 2}"}
Let $X$ be an analytic space of dimension $n$.
The three following conditions are equivalent:

i. $X$ is an analytic Gorenstein space.
ii. "The" dualising complex $\KK_X^\bullet$ is a resolution of an invertible sheaf (placed in degree $-n$).
iii. The structure sheaf $\OO$ is dualising.
:::

::: {.proof}
(i)$\iff$(iii) by [Proposition 1](#proposition-1), and (ii)$\iff$(iii) by [Theorem 3](#theorem-3).
:::
::::

::: {.rmenv title="Complete intersections" latex="{Complete intersections}"}
Let $X\subset U\subset\mathbb{C}^m$ be a complete intersection defined by $(m-n)$-many scalar functions $f_1,\ldots,f_{m-n}\in\OO(U)$.
It is easy to see that the analytic space $X$, equal to the quotient of $\OO(U)$ by the ideal generated by the $f_i$, is Gorenstein (cf. [@2]).
We can thus "replace" $\KK_X^\bullet$ by an invertible sheaf $\Omega$ that the Koszul complex $K^{\OO(U)}(f_1,\ldots,f_{m-n})$ allows us to "calculate":
$$
  \begin{aligned}
    \Omega
    = \HH^{-n}(\KK_X^\bullet)
    &= \Ext_{\OO(U)}^{m-n}(\OO(X),\Omega^m(U))
  \\&= \HH^{\OO(U)}(f_1,\ldots,f_{m-n};\Omega^m(U))
  \\&= \OO(X)\otimes_{\OO(U)}\Omega^M(U).
  \end{aligned}
$$
:::
