--- 
title: "Relative duality in complex analytic geometry"
author: "J.P. Ramis, G. Ruget, J.L. Verdier"
date: "1971"
original: |
  Ramis, J.P., Ruget, G., and Verdier, J.L.
  "Dualité relative en géométrie analytique complexe".
  _Inventiones Math._ **13** (1971), pp. 261--283.
  [eudml.org/doc/142096](https://eudml.org/doc/142096)'
bibliography: IM-13-1971-261.bib
---

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\sh}[1]{\scr{#1}}

\providecommand{\OO}{\sh{O}}
\providecommand{\HH}{\mathrm{H}}
\providecommand{\cc}{\mathrm{c}}
\providecommand{\coh}{\mathrm{coh}}
\providecommand{\CC}{\mathrm{C}}
\providecommand{\RR}{\mathrm{R}}
\providecommand{\LL}{\mathrm{L}}
\providecommand{\TT}{\mathbf{T}}
\providecommand{\KK}{\mathbf{K}}
\providecommand{\DD}{\mathbf{D}}

\providecommand{\Hom}{\operatorname{Hom}}
\providecommand{\RHom}{\operatorname{RHom}}
\providecommand{\Ext}{\operatorname{Ext}}
\providecommand{\shExt}{\mathscr{E}\mathcal{xt}}
\providecommand{\Supp}{\operatorname{Supp}}

\providecommand{\DFS}{\mathbf{DFS}}
\providecommand{\QDFS}{\mathbf{QDFS}}
\providecommand{\QFS}{\mathbf{QFS}}

<!-- Content -->

# Introduction {.unnumbered}

\oldpage{261}
Given a $\sigma$-compact analytic space $X$, of bounded dimension, we know how to construct [@10] a bounded complex $\KK_X^\bullet$ of $\OO_X$-modules of coherent cohomology, and a (continuous linear) "trace" $\TT_X\colon\HH_\cc^0(X;\KK_X^\bullet)\to\mathbb{C}$ that can happily provide a duality between the separations of the spaces $\HH_\cc^p(X;\sh{F})$ and $\Ext^{-p}(X;\sh{F},\KK_X^\bullet)$, for every integer $p$ and every coherent $\OO_X$-module $\sh{F}$, as long as we endow these space with suitable topologies;
similarly, the trace induces a perfect pairing between $\HH^p(X;\sh{F})$ and $\Ext_\cc^{-p}(X;\sh{F},\KK_X^\bullet)$, suitably topologised.
The purpose of this article is the study of the compatibility of this duality with direct images: if $f\colon X\to Y$ is a morphism of analytic spaces, then we have to construct a "relative trace" $\TT_{X/Y}\in\Ext^0(Y;\RR{f_!}\KK_X^\bullet,\KK_Y^\bullet)$ (where $f_!$ denotes the direct image with proper support).
We then have, for every complex $\sh{F}^\bullet$ of $\OO_X$-modules of coherent cohomology ($\sh{F}^\bullet\in\DD_\coh(X)$) and for every complex $\sh{G}^\bullet$ of bounded-below coherent cohomology ($\sh{G}^\bullet\in\DD_\coh^+(Y)$), a canonical morphism
$$
  \begin{aligned}
    \RR{f_!}\sh{F}\Hom\big(
      X ; \sh{F}^\bullet,
      \RR\Hom(
        \LL f^*&\RR\Hom(
          Y;\sh{G}^\bullet,
          \KK_Y^\bullet
        ),
        \KK_X^\bullet)
    \big)
  \\\to\, &\RR\Hom(Y;\RR{f_*}\sh{F}^\bullet,\sh{G}^\bullet)
  \end{aligned}
\tag{1}
$$
that is, in certain cases, an isomorphism (we obtain another formula by swapping $\RR{f_!}$ and $\RR{f_*}$, and more striking formulas by setting $\sh{G}^\bullet=\KK_Y^\bullet$).

In general, direct images are not coherent, and, just like the absolute case, we can only hope to address these questions by defining a topological dualisation $\RR\Hom(Y;-,\KK_Y^\bullet)$ on $Y$ (the relative trace should live in a topological $\Ext^0$, and (1) only gives isomorphisms of suitable operations up to "separation").
We restrict ourselves here to the case where $f$ is proper, and we use the Grauert direct image theorem.[^1]
In this case, (1) is an isomorphism (the $\Hom$ being the usual functors), and we have an "algebraic" statement.
\oldpage{262}
The proof, however, uses topology: to establish the existence of the relative trace, and then to prove that (1) is an isomorphism;
we invoke, in particular, the separation of certain cohomology spaces.

[^1]: In another article, J.P. Ramis and G. Ruget hope to treat the general case, once there is a generalisation to the relative case of the theorems of Andreotti--Grauret on $p$-convex spaces. The above theorem would then follow from the conjunction of the general duality theorem and the Grauert direct image theorem.

[Section 4](#section-4), which deals with questions of separation, is independent of the previous sections.
There we show the two following theorems, conjectured by Malgrange, and which form an indispensable complement to the absolute duality theorems:

::: {.itenv title="Theorem 4.1" latex="{Theorem 4.1}"}
Given an analytic space $X$, a coherent sheaf $\sh{F}$, and an integer $p$, suppose that every compact $K\subset X$ has a compact "envelope" in $K'$ such that every element of $\HH_K^p(X;\sh{F})$ whose image in $\HH_\cc^p(X;\sh{F})$ is zero already has zero image in $\HH_{K'}^p(X;\sh{F})$.
Then the space $\HH_\cc^p(X;\sh{F})$, endowed with the topology constructed in [@10] (the only quotient topology of the Fréchet--Schwartz dual compatible with the duality theorem), is separated.
:::

As for the statement of Theorem 4.9, we obtain this by replacing, in the lines above, $\HH_\bullet^p(X;\sh{F})$ with $\Ext_\bullet^p(X;\sh{F},\KK_X^\bullet)$.

In an appendix, we will give another proof, using Theorem 4.9, of a theorem of Siu on the vanishing of certain cohomology groups.


# Proof sketch {#section-1}

We denote by $\iota$ the canonical isomorphism from $\HH_\cc^0(Y;\RR{f_*}\KK_X^\bullet)$ to $\HH_c^0(X;\KK_X^\bullet)$.
The trace $\TT_Y$ induces a pairing between $\HH_\cc^0(Y;\RR{f_*}\KK_X^\bullet)$ and $\Ext^0(Y;\RR{f_*}\KK_X^\bullet,\KK_Y^\bullet)$, and we are looking for an element $\TT_{X/Y}$ in this latter space such that we have, for all $a\in\HH_\cc^0(Y;\RR{f_*}\KK_X^\bullet)$,
$$
  \TT_Y(a\cdot\TT_{X/Y})
  = \TT_x\iota a.
$$
In other words, we are looking for a transpose ${}^t\iota$ of $\iota$ with respect to the pairings $\TT_Y$ and $\TT_X$ (with $\TT_{X/Y}$ as the image of ${}^t\iota$ under the function $1\in\HH^0(X;\OO_X)$).
Since this problem is local on $Y$ (provided that we are guaranteed the local vanishing of $\Ext^i(Y;\RR{f_*}\KK_X^\bullet,\KK_Y^\bullet)$ for $i<0$), we can suppose that $Y$ is realisable as an analytic subset of an open polydisc $V$ of dimension $p$.
If we still denote by $f$ the composite of $f$ and an embedding of $Y$ into $V$, it follows from the construction of $\KK_Y^\bullet$ that what we are looking for is an element of $\Ext^p(V;\RR{f_*},\KK_X^\bullet,\Omega_V)$.
We now want to proceed locally on $X$, supposing (being content to shrink $X$) that $X$ is the union of a finite number of opens $X_i$, each of which is embeddable into an open $U_i$ of $\mathbb{C}^n$: we can incorporate each $X_i$ into a commutative diagram
```tikz
\begin{tikzcd}
  X_i
    \ar[r,hook,"I"]
    \ar[dr,swap,"{f_{|X_i}}"]
  & U_i\times V
    \ar[d,"F"]
\\& V
\end{tikzcd}
```
where $I$ is an embedding, and where $F$ denotes the second projection of $U_i\times V$.
\oldpage{263}
We denote by $f_{i_0i_1\ldots i_r}$ the direct image with proper support in $X_{i_0}\cap X_{i_1}\cap\ldots X_{i_r}$ and we first search for a "trace" $\TT_i$ in each $\Ext^p(V;\RR{f_i}\KK_X^\bullet,\Omega_V)$.
We know that $\KK_{X_i}^\bullet$ is precisely
$$
  \Hom_{\OO_{U_i\times V}}(\OO_X,\KK_{U_i\times V}^\bullet)
$$
where $\KK_{U_i\times V}^\bullet$ is (with a shift by $n_i+p$) a particularly beautiful resolution of the sheaf $\Omega_i$ of holomorphic differential forms of maximum degree on $U_i\times V$.
The function $1$ on $X_i$ thus gives a morphism from $\KK_{X_i}^\bullet$ to $\KK_{U_i\times V}^\bullet$, whence a morphism to $\Ext^p(V;\RR{f_i}\KK_X^\bullet,\Omega_V)$ from $\Ext^n(V;\RR{F_!}\Omega_i,\Omega_V)$, and it is in this latter space that we will find an elementary trace $t_i$.

The sheaf $\RR^q{F_!}\Omega_i$ is generated, by a Künneth formula, by the presheaf $v\mapsto\HH_\cc^{n_i}(U_i;\Omega_{U_i})\widehat{\otimes}\HH^{q-n}(v;\Omega_V)$ (since $\HH_\cc^\bullet(U_i;\Omega_{U_i})$ is zero in degrees not equal to $n_i$)[^2];
it thus follows that the complex $\RR{F_!}\Omega_i$ is equivalent to the sheaf $\RR^{n_i}F_!\Omega_i$ in degree $n_i$, and that we are simply looking for a homomorphism from this sheaf to $\Omega_V$, which immediately gives the interpretation given above, and the absolute trace on $U_i$.

[^2]: We only deal with nuclear spaces in these questions.

To glue the $\TT_i$, we would like to be able to confirm the existence of a spectral sequence abutting to $\Ext^{r-q}(V;\RR{f}\KK_X^\bullet,\Omega_V)$ with page
$$
  E_1^{r,q}
 \prod \Ext^{-q}(V;\RR{f_{i_0i_1\ldots i_r}}\KK_X^\bullet,\Omega_V)
$$
and then say that the $\TT_i$ give an element of $E_2^{0,-p}$, which would be equal to $\Ext^p(V;\RR{f_*}\KK_X^\bullet,\Omega_V)$ by the vanishing of $E_1^{r,q}$ for $q<-p$.
All of this is sadly unlikely to be feasible, since the usual $\Ext$ groups are not well adapted to the study of complexes such as $\RR{f_i}\KK_X^\bullet$; why, for example, would $\Ext^j(V;\RR{F_!}\Omega_i,\Omega_i)$ be zero for $j\geqslant1$ when $\RR{F_!}\Omega_i$ is a sheaf of analytic functions on $V$ with values in a $\DFS$ space?
Having still not established a direct solution to this (i.e. defined for certain complexes of $\OO_V$-modules of $\mathrm{Extop}^\bullet(V;-,\Omega_V)$ groups that should coincide with the "algebraic" $\Ext$ under the hypothesis of perfectness of the complexes), we note in [Section 2](#section-2) a more artificial method of construction for $\TT_{X/Y}$.

Thanks to the relative trace, which is, up to homotopy, a morphism from $\RR_{f_*}\KK_X^\bullet$ to $\KK_Y^\bullet$, it is easy to construct the morphism (1): first, for any complex $\sh{F}^\bullet$ of $\OO_X$-modules of coherent cohomology, we denote by $D_X\sh{F}^\bullet$ the complex $\RHom(\sh{F}^\bullet,\KK_X^\bullet)$, which is also of coherent cohomology.
\oldpage{264}
We know [@10] that the canonical morphism from $\sh{F}^\bullet$ to $D_XD_X\sh{F}^\bullet$ is a quasi-isomorphism, and we will note that, if $\sh{G}^\bullet\in\DD_\coh^+(X)$, there is a canonical isomorphism from $\RHom(\sh{F}^\bullet,\sh{G}^\bullet)$ to $D_X(\sh{F}^\bullet\otimes^\LL D_X\sh{G}^\bullet)$ (where $X$ denotes an arbitrary analytic space, for example $Y$).
Indeed,
$$
  \begin{aligned}
    \RHom(\sh{F}^\bullet,\sh{G}^\bullet)
    &= \RHom(\sh{F}^\bullet,D_XD_X\sh{G}^\bullet)
  \\&= \RHom(\sh{F}^\bullet,\RHom(D_X\sh{G}^\bullet,\KK_X^\bullet))
  \\&= \RHom(\sh{F}^\bullet\otimes^\LL D_X\sh{G}^\bullet,\KK_X^\bullet)
  \\&= D_X(\sh{F}^\bullet\otimes^\LL D_X\sh{G}^\bullet).
  \end{aligned}
$$
Finding the morphism (1) thus reduces to exhibiting a morphism
$$
  \tau\colon
  \RR{f_*}D_X(\sh{F}^\bullet\otimes^\LL\LL{f^*}D_Y\sh{G}^\bullet)
  \to D_Y(\RR{f_*}\sh{F}^\bullet\otimes^\LL D_Y\sh{G}^\bullet)
$$
and this comes from the canonical homomorphism from
$$
  \RR{f_*}\RHom(\sh{F}^\bullet\otimes^\LL\LL{f^*}D_Y\sh{G}^\bullet,\KK_X^\bullet)
$$
to
$$
  \RHom(\RR{f_*}(\sh{F}^\bullet\otimes^\LL\LL{f^*}D_Y\sh{G}^\bullet), \RR{f_*}\KK_X^\bullet)
$$
along with the isomorphism given by the projection formula
$$
  \RR{f_*}(\sh{F}^\bullet\otimes^\LL\LL{f^*}D_Y\sh{G}^\bullet)
  \to \RR{f_*}\sh{F}^\bullet\otimes^\LL D_Y\sh{G}^\bullet
$$
and the trace $\TT_{X/Y}$.

To prove that $\tau$ is an isomorphism, it suffices, by substituting $\sh{F}^\bullet\otimes^\LL\LL^{f^*}D_Y\sh{G}^\bullet$ for $\sh{F}^\bullet$, to consider the case where $\sh{G}^\bullet=\KK_Y^\bullet$, i.e. to prove that
$$
  \tau\colon
  \RR{f_*}\RHom(\sh{F}^\bullet,\KK_X^\bullet)
  \to \RHom(\RR{f_*}\sh{F}^\bullet,\KK_Y^\bullet)
$$
is a quasi-isomorphism;
for this, we show that $\tau$ induces a quasi-isomorphism between the above complexes of sections of the above complexes over every sufficiently nice open of $Y$: in plain words, we show that, if $Y$ is a Stein space, then $\tau$ induces, for every $i$, an isomorphism from $\Ext^{-i}(X;\sh{F}^\bullet,\KK_X^\bullet)$ to $\Ext^{-i}(Y;\RR{f_*}\sh{F}^\bullet,\KK_Y^\bullet)$.
By a lemma on $\partial$-functors [@3, I.7], it suffices to prove this in the case where $\sh{F}^\bullet$ consists of a single coherent sheaf $\sh{F}$;
in this case, $\Ext^{-i}(X;\sh{F},\KK_X^\bullet)$ is in duality with $\HH_\cc^i(X;\sh{F})$, and we will show in [Section 3](#section-3) that $\Ext^{-i}(X;\RR{f_*}\sh{F},\KK_Y^\bullet)$ is in duality (in a topological sense) with $\HH_\cc^i(Y;\RR{f_*}\sh{F})$, and, by the same construction, the transpose of $\tau$ with respect to these pairings is the natural algebraic isomorphism from $\HH_\cc^i(Y;\RR{f_*}\sh{F})$ to $\HH_\cc^i(X;\sh{F})$.
The fact that $\tau$ is an isomorphism then follows from the fact that the four spaces in question are separated, the proof of which is completed in [Section 4](#section-4).

The vanishing of $\Ext^{-i}(Y;\RR{f_*}\KK_X^\bullet,\KK_X^\bullet)$ when $Y$ is a Stein space and $i>0$, to which we alluded in the start of this section, can be proved in the same way:
\oldpage{265}
this space is in duality with $\HH_\cc^i(Y;\RR{f_*}\KK_X^\bullet)$, which is algebraically isomorphic to $\HH_\cc^i(X;\KK_X^\bullet)=\Ext_\cc^i(X;\OO_X,\KK_X^\bullet)$, which is in duality with $\HH^{-i}(X;\OO_X)$, which is zero, even though all these spaces were a priori separated (the first two by construction of even their topologies --- cf. [Section 3](#section-3); as for $\Ext_\cc^i(X;\OO_X,\KK_X^\bullet)$, we know that its separation is equivalent to that of $\HH^{-i+1}(X;\OO_X)$).

The argument above strongly encourages us to define the trace $\TT_{X/Y}$ as the image of the function $1\in\HH^0(X;\OO_X)$ under the transpose of the natural algebraic isomorphism $\iota$ from $\HH_\cc^0(Y;\RR{f_*}\KK_X^\bullet)$ to $\HH_\cc^0(X;\KK_X^\bullet)$;
that is, we need to prove the continuity of $\iota$.
We can even conclude, using the separation theorem [Theorem 4.2](#theorem-4.2) and [Lemma 3.5](#lemma-3.5), that $\HH_\cc^0(X;\KK_X^\bullet)$ is separated whenever $Y$ is a Stein space, which implies that, in this case, $\HH^1(X;\OO_X)$ is separated, and $\Ext^0(Y;\RR{f_*}\KK_X^\bullet,\KK_Y^\bullet)$ is isomorphic to $\HH^0(X;\OO_X)$.


# The relative trace {#section-2}

From now on, let $f\colon X\to Y$ be a proper morphism, where $Y$ is an open polydisc of $\mathbb{C}^p$.
Let $Y'$ be an open sub-polydisc of $Y$, with $\overline{Y'}\subset Y$.
We set $X'=f^{-1}(Y')$.

We will define "in a natural way" a complex of $\DFS$ spaces whose cohomology will be the hypercohomology with compact support of $Y$ with values in $\RR{f_*}\KK_{X'}^\bullet$.
Since $\RR{f_*}\KK_X^\bullet$ is bounded and of coherent cohomology, we can find [@4], in a neighbourhood of $Y'$, a representative $\sh{L}^\bullet$ that is perfect (i.e. bounded, and whose objects are free of finite type).
Let $\frak{L}$ be a locally finite cover of $Y'$ by closed polydiscs.
Since the groups $\HH_\cc^i(Y';\RR{f_*}\KK_{X'}^\bullet)$ are the cohomology groups of the total complex of the double complex $\CC^\bullet(\frak{L};\HH^0(\frak{L};\sh{L}^\bullet))$ of $\DFS$ spaces (when there is no ambiguity in the choice of cover, we denote this complex by $\CC_{Y'}^\bullet(\sh{L}^\bullet)$), which allows us to topologise them, in a way that is independent of the choice of resolution $\sh{L}^\bullet$, since if $\sh{L}_1^\bullet\to$ and $\sh{L}_2^\bullet\to$ are perfect resolutions of $\RR{f_*}\KK_{X'}^\bullet$ then there exists another perfect resolution $\sh{L}_3^\bullet$ that dominates them both:
```tikz
\begin{tikzcd}[row sep=tiny]
  & \mathscr{L}_1^\bullet \ar[dr]
\\\mathscr{L}_3^\bullet \ar[ur] \ar[dr]
  && \mathrm{R}f_*\mathbf{K}_{X'}^\bullet
\\& \mathscr{L}_2^\bullet \ar[ur]
\end{tikzcd}
```

With the group $\HH_\cc^0(Y';\RR{f_*}\KK_{X'}^\bullet)$ being thus topologised[^3], we endow $\HH_\cc^0(X';\KK_{X'}^\bullet)$ with its usual $\DFS$ topology[^4], and we propose the following proposition.

[^3]: We can show that this topology also does not depend on the choice of $\sh{L}^\bullet$.

[^4]: But not natural: when we know how to topologise the hypercohomology of a complex of coherent cohomology on a general space [@5], the lemma becomes evident.

\oldpage{266}

::: {.itenv #proposition-2.1 title="Proposition 2.1" latex="{Proposition 2.1}"}
The natural algebraic isomorphism $\iota$ from $\HH_\cc^0(Y';\RR{f_*}\KK_{X'}^\bullet)$ to $\HH_\cc^0(X';\KK_{X'}^\bullet)$ is continuous.
:::

Before proving this, we note that there exists on
$$
  \HH_\cc^i(Y';\RR{f_*}\KK_{X'}^\bullet)
  = \HH_\cc^i(Y';\sh{L}^\bullet)
$$
a unique $\QDFS$ topology, and on $\Ext^{-i}(Y';\RR{f_*}\KK_{X'}^\bullet,\KK_{Y'}^\bullet)$ a unique $\QFS$ topology, such that the trace $\TT_{Y'}$ places in duality the separations of these spaces.
Furthermore, these spaces are separated, and the topology on $\HH_\cc^i(Y';\RR{f_*}\KK_{X'}^\bullet)$ coincides with that described above (we proceed as in [@10, Theorem 2], by using the fact that $\sh{L}^\bullet$ is perfect, and thus has coherent objects, and, in parallel, we use [Proposition 3.2](#proposition-3.2); the topologies are the same by uniqueness, and thus separated).

We recall that [Proposition 2.1](#proposition-2.1) allows us to construct the relative trace $\TT_{X'/Y'}$;
it is the image of the function $1\in\HH^0(X';\OO_{X'})$ under the transpose[^5] of $\iota$ (note that $\Ext^0(Y';\sh{L}^\bullet,\KK_{Y'}^\bullet)=\Ext^0(Y';\RR{f_*}\KK_{X'}^\bullet,\KK_{Y'}^\bullet)$).

[^5]: $\HH^0(X';\OO_{X'})$ is in duality with the separation of $\HH_\cc^0(X';\KK_{X'}^\bullet)$ (in fact, we can prove that this space is separated).

It remains to prove the proposition.
For this, we introduce the diagram
$$
  \begin{CD}
    \HH_\cc^0(Y';\RR{f_*}\KK_{X'}^\bullet) @>{\iota}>> \HH_\cc^0(X';\KK_{X'}^\bullet)
  \\@V{\alpha}VV @AA{\gamma}A
  \\\HH_\cc^0(Y';\RR{f_*}\LL{f^*}\RR{f_*}\KK_{X'}^\bullet) @>>{\beta}> \HH_\cc^0(X';\LL{f^*}\RR{f_*}\KK_{X'}^\bullet)
  \end{CD}
$$
where $\beta$ is the natural map, $\alpha$ is the morphism induced by the natural morphism
$$
  \rho\colon \sh{F}^\bullet \to \RR{f_*}\LL{f^*}\sh{F}^\bullet
$$
(cf. [@3, II, Proposition 5.10]), and where $\gamma$ is a map (that makes the diagram commute) that we will define later on.

To show the continuity of $\iota$, we will topologise
$$
  \HH_\cc^0(Y';\RR{f_*}\LL{f^*}\RR{f_*}\KK_{X'}^\bullet)
  \quad\text{and}\quad
  \HH_\cc^0(X';\LL{f^*}\RR{f_*}\KK_{X'}^\bullet).
$$
We then prove the continuity of the maps $\alpha$, $\beta$, and $\gamma$.

::: {.itenv #lemma-2.2 title="Lemma 2.2" latex="{Lemma 2.2}"}
Let $K$ be a Stein compact of $X'$, and $\sh{F}$ a coherent $\OO_{X'}$-module.
Let $\sh{F}_K$ be the sheaf whose germs of sections at the points of $K$ are those of $\sh{F}$, and $0$ elsewhere.
Then the sheaf $\sh{F}_K$ is $f_*$-acyclic, and the direct image $f_*\sh{F}_K$ is $\Gamma_\cc(Y';-)$-acyclic.
:::

If $f_!$ denotes the direct image with proper support functor, then $\RR{f_*}\sh{F}_K=\RR{f_!}\sh{F}_K$ and we are reduced to proving the $f_!$-acyclicity of $\sh{F}_K$.
This simply follows from the fact that the intersection of a Stein open of $X'$ with the preimage of a Stein open of $Y'$ is a Stein open.

\oldpage{267}
To establish the $\Gamma_\cc(Y';-)$-acyclicity of $f_*\sh{F}_K=f_!\sh{F}_K$, we note that $\Gamma_\cc(X';-)=\Gamma_\cc(Y';-)f_!$, and we use the spectral sequence for composite functors, which gives $\HH_cc^p(Y';\RR^qf_!\sh{F}_K)\Rightarrow\HH_\cc^{p+q}(X';\sh{F}_K)$.

Let $\frak{M}$ be a finite cover of $\overline{X'}$ by Stein compacts.
The intersection of the compacts of $\frak{M}$ with the preimages of compacts of $\frak{L}$ are Stein compacts, and form a locally finite cover $\frak{R}$ of $X'$.

Let $\sh{L}^i$ be the $i$-th component of the complex $\sh{L}^i$.
If $L$ is a compact of $Y'$, we denote by $\sh{L}_L^i$ the sheaf that is equal to $\sh{L}^i$ on $L$ and zero elsewhere;
$\sh{L}^i$ is a free $\OO_{Y'}$-module, and so $\sh{L}_L^i$ is an $\OO_{Y'}$-module with projective fibres, and thus $f^*$-acyclic.
We evidently have $f^*\sh{L}_L^i=(f^*\sh{L}^i)_{f^{-1}(L)}$, and $f^*\sh{L}^i$ is a free $\OO_{X'}$-module of finite type.
Thus $f^*\CC_{Y'}^\bullet(\sh{L}^\bullet)$ is a representative of $\LL{f^*}\RR{f_*}\KK_{X'}^\bullet$.
We denote by $\CC_{X'}^\bullet(f^*\CC_{Y'}^\bullet(\sh{L}^\bullet))$ the total complex of the double complex
$$
  \CC^\bullet\big(\frak{R};\HH^0(\frak{R};f^*\CC_{Y'}^\bullet(\sh{L}^\bullet))\big).
$$
We evidently have a morphism
$$
  f^*\CC_{Y'}^\bullet(\sh{L}^\bullet)
  \to \CC_{X'}^\bullet(f^*\CC_{Y'}^\bullet(\sh{L}^\bullet)),
$$
and $\CC_{X'}^\bullet(f^*\CC_{Y'}^\bullet(\sh{L}^\bullet))$ is a representative of $\LL{f^*}\RR{f_*}\KK_{X'}^\bullet$.
If $K_{k_0\ldots k_n}$ is an $n$-simplex of $\frak{R}$, and $L_{l_0\ldots l_m}$ an $m$-simplex of $\frak{L}$, it is clear that the sheaf $(f^*\sh{L}_{L_{l_0\ldots l_m}}^i)_{K_{k_0\ldots k_n}}$ is $f^*$-acyclic and that its direct image is $\Gamma_\cc(Y';-)$-acyclic ([Lemma 2.2](#lemma-2.2)).
Thus $f_*\CC_{X'}^\bullet(f^*\CC_{Y'}^\bullet(\sh{L}^\bullet))$ is a representative of $\RR{f_*}\LL{f^*}\RR{f_*}\KK_{X'}^\bullet$.
Finally, the natural morphism from $\CC_{Y'}^\bullet(\sh{L}^\bullet)$ to $f_*\CC_{X'}^\bullet(f^*\CC_{Y'}^\bullet(\sh{L}^\bullet))$ is a representative of the morphism $\rho\colon\RR{f_*}\KK_{X'}^\bullet\to\RR{f_*}\LL{f^*}\RR{f_*}\KK_{X'}^\bullet$.

We will now clearly see how to topologise our spaces, and how to prove the continuity of $\alpha$ and $\beta$, since, if $\frak{R}'$ denotes the Stein cover of $Y'$ consisting of the $K'=f(K)$, where $K$ runs over $\frak{R}$, then $\HH_\cc^0(Y';\RR{f_*}\KK_{X'}^\bullet)$ is the $0$-th cohomology group of the complex of $\DFS$ spaces given by the total complex of $\CC^\bullet(\frak{L};\HH^0(\frak{L};\sh{L}^\bullet))$, or even of $\CC^\bullet(\frak{R}';\HH^0(\frak{R}';\sh{L}^\bullet))$;
$\HH_\cc^0(Y';\RR{f_*}\LL{f^*}\RR{f_*}\KK_{X'}^\bullet)$ is the $0$-th cohomology group of the complex of $\DFS$ spaces given by the total complex of $\CC^\bullet(\frak{R}';\HH^0(\frak{R};f^*\CC_{Y'}^\bullet(\sh{L}^\bullet)))$;
and $\HH_\cc^0(X';\LL{f^*}\RR{f_*}\KK_{X'}^\bullet)$ similarly comes from $\CC^\bullet(\frak{R};\HH^0(\frak{R};f^*\CC_{Y'}^\bullet(\sh{L}^\bullet)))$.

It remains to construct a suitable morphism $\gamma$.

For this, we introduce the morphisms
```tikz
\begin{tikzcd}
  \operatorname{RHom}^\bullet(Y';\mathrm{R}{f_*}\mathbf{K}_{X'}^\bullet, \mathrm{R}{f_*}\mathbf{K}_{X'}^\bullet)
  & \mathrm{R}{f_*}\operatorname{RHom}^\bullet(X';\mathbf{K}_{X'}^\bullet,\mathbf{K}_{X'}^\bullet)
    \ar[l,swap,"l"]
\\\operatorname{RHom}^\bullet(Y';\mathrm{R}{f_*}\mathrm{L}{f^*}\mathrm{R}{f_*}\mathbf{K}_{X'}^\bullet, \mathrm{R}{f_*}\mathbf{K}_{X'}^\bullet)
    \ar[u,"m"]
  & \mathrm{R}{f_*}\operatorname{RHom}^\bullet(X';\mathrm{L}{f^*}\mathrm{R}{f_*}\mathbf{K}_{X'}^\bullet,\mathbf{K}_{X'}^\bullet)
    \ar[l,"n"] \ar[ul,swap,"mn"]
\end{tikzcd}
```
where $l$ and $n$ are the natural morphisms, and where $m$ in induced by $\rho$; by [@3, Chapter II, Proposition 5.10], $mn$ is an isomorphism.

\oldpage{268}
We thus obtain the diagram (where $\tau=\mu\nu)$
```tikz
\begin{tikzcd}
  \operatorname{Ext}^0(Y';\mathrm{R}{f_*}\mathbf{K}_{X'}^\bullet, \mathrm{R}{f_*}\mathbf{K}_{X'}^\bullet)
  & \operatorname{Ext}^0(X';\mathbf{K}_{X'}^\bullet,\mathbf{K}_{X'}^\bullet)
    \ar[l,swap,"\lambda"]
\\\operatorname{Ext}^0(Y';\mathrm{R}{f_*}\mathrm{L}{f^*}\mathrm{R}{f_*}\mathbf{K}_{X'}^\bullet, \mathrm{R}{f_*}\mathbf{K}_{X'}^\bullet)
    \ar[u,"\mu"]
  & \operatorname{Ext}^0(X';\mathrm{L}{f^*}\mathrm{R}{f_*}\mathbf{K}_{X'}^\bullet,\mathbf{K}_{X'}^\bullet)
    \ar[l,"\tau"] \ar[ul,swap,"\nu"]
\end{tikzcd}
```
The identity morphism $\RR{f_*}\KK_{X'}^\bullet\to\RR{f_*}\KK_{X'}^\bullet$ induces an element of $\Ext^0(Y';\RR{f_*}\KK_{X'}^\bullet,\RR{f_*}\KK_{X'}^\bullet)$, which comes, by $\tau$, from an element $e$ of $\Ext^0(X';\LL{f^*}\RR{f_*}\KK_{X'}^\bullet,\KK_{X'}^\bullet)$;
we set $\nu(e)=\varepsilon$.

The composition product of the $\Ext$ gives
$$
  \HH_\cc^0(Y';\RR{f_*}\LL{f^*}\RR{f_*}\KK_{X'}^\bullet)
  \times \Ext^0(Y';\RR{f_*}\LL{f^*}\RR{f_*}\KK_{X'}^\bullet, \mathrm{R}{f_*}\KK_{X'}^\bullet)
  \longrightarrow \HH_\cc^0(Y';\RR{f_*}\KK_{X'}^\bullet)
$$
and
$$
  \HH_\cc^0(X';\LL{f^*}\RR{f_*}\KK_{X'}^\bullet)
  \times \Ext^0(X';\LL{f^*}\RR{f_*}\KK_{X'}^\bullet,\KK_{X'}^\bullet)
  \longrightarrow \HH_\cc^0(X';\KK_{X'}^\bullet).
$$
We can thus build, corresponding to $\varepsilon$, a linear map
$$
  \delta\colon
  \HH_\cc^0(Y';\RR{f_*}\LL{f^*}\RR{f_*}\KK_{X'}^\bullet)
  \longrightarrow \HH_\cc^0(Y';\RR{f_*}\KK_{X'}^\bullet)
$$
and, to $e$, a linear map
$$
  \gamma\colon
  \HH_\cc^0(X';\LL{f^*}\RR{f_*}\KK_{X'}^\bullet)
  \longrightarrow \HH_\cc^0(X';\KK_{X'}^\bullet).
$$

By construction, $\delta\alpha$ is equal to the identity.
The commutativity of diagram (2) then follows.

The trace $\TT_{X'}$ puts into duality (the separation of) $\HH_\cc^0(X;\KK_{X'}^\bullet)$ and $\Gamma(X';\OO_{X'})$.
We can easily show (as in [@10]) that there exists on $\HH_\cc^i(X';\LL{f^*}\RR{f_*}\KK_{X'}^\bullet)=\HH_\cc^i(X';\LL{f^*}\sh{L}^\bullet)$ a unique $\QDFS$ structure, and on $\Ext^{-i}(X';\LL{f^*}\RR{f_*}\KK_{X'}^\bullet,\KK_{X'}^\bullet)=\Ext^{-i}(X';\LL{f^*}\sh{L}^\bullet,\KK_{X'}^\bullet)$ a unique $\QFS$ structure, such that the trace $\TT_{X'}$ puts the separations[^6] of these two spaces into duality (since $\LL{f^*}\sh{L}^\bullet$ is a perfect complex of $\OO_{X'}$-modules; the $\QDFS$ structure thus obtained on $\HH_\cc^0(X';\LL{f^*}\RR{f_*}\KK_{X'}^\bullet)$ coincides with that with which we have already endowed this space).

[^6] We can in fact show that these spaces are separated.

Denote by $\theta$ the morphism given by the composite of the natural map $\Gamma(X';\OO_{X'})\to\Ext^0(X';\KK_{X'}^\bullet,\KK_{X'}^\bullet)$ and $\tau^{-1}\lambda$.
We have that $\theta(1)=e$.
It thus follows that the map $\beta$ admits $\theta$ as transpose, and is thus continuous.
The proof of [Proposition 2.1](#proposition-2.1) is thus complete.


# Complexes of coherent cohomology on a Stein space {#section-3}

All throughout this section, $Y$ denotes a Stein space, and $\sh{F}^\bullet$ a complex of $\OO_Y$-modules of coherent cohomology.
Before endowing the spaces $\HH^i(Y;\sh{F}^\bullet)$ with (Fréchet–Schwartz) topologies, recall the following lemma.
\oldpage{269}

::: {.itenv #lemma-3.0 title="Lemma 3.0" latex="{Lemma 3.0}"}
Let $A$ and $B$ be abelian categories, with $A$ having enough injectives, and let $F$ be an additive functor from $A$ to $B$, left exact and of finite cohomological dimension.
Let $I^\bullet$ be a complex in $A$ whose objects, as well as its cohomology objects, are $F$-acyclic.
Then we have, for all $i$,
$$
  \HH^i F(I^\bullet)
  = F(\HH^i I^\bullet).
$$
:::

::: {.proof}
This is particularly evident when $I^\bullet$ has bounded-below cohomology: we can show, by induction from the left, that all the boundary and cycle objects of $I^\bullet$ are $F$-acyclic, by cutting $I^\bullet$ into short exact sequences to which we then apply $F$.
In the general case, one should use a Cartan–Eilenberg resolution of $I^\bullet$.
:::

We apply this lemma to the category $A$ of $\OO_Y$-modules, and to the global sections functor, taking $I^\bullet$ to be an injective resolution of the complex $\sh{F}^\bullet$ of coherent cohomology.
By Cartan's Theorem B, all the hypotheses are satisfied, and we have, for all $i$,
$$
  \HH^i(Y;\sh{F}^\bullet)
  = \Gamma(Y;\HH^i\sh{F}^\bullet)
$$
which allows us to topologise the left-hand side.

We can now prove a first duality theorem for complexes of coherent cohomology on Stein spaces:

::: {.itenv #proposition-3.1 title="Proposition 3.1" latex="{Proposition 3.1}"}
For all $i$, the trace $\TT_Y$ gives a pairing
$$
  \tau\colon
  \HH^i(Y;\sh{F}^\bullet)
  \times \Ext_\cc^{-i}(Y;\sh{F}^\bullet,\KK_Y^\bullet)
  \to \mathbb{C}.
$$
There exists a (unique) pair of ($\FS$ and $\DFS$, respectively) topologies on these spaces such that $\tau$ makes each one the strong dual of the other.
:::
