---
title: 1.1 Filtered objects
---

{{< include ../macros.qmd >}}

::: {.rmenv #ii-1.1.1 number="1.1.1"}
Let $\mathscr{A}$ be an abelian category.

We will be considering $\ZZ$-filtrations, finite, in general, on the objects of $\mathscr{A}$:
:::

::: {.rmenv #ii-1.1.2 number="1.1.2" taxon="Definition"}
A **decreasing** (resp. **increasing**) **filtration** $F$ of an object $A$ of $\mathscr{A}$ is a family $(F^n(A))_{n\in\ZZ}$ (resp. $(F_n(A))_{n\in\ZZ}$) of sub-objects of $A$ satisfying
$$
  \forall n,m
  \quad n\leqslant m \implies F^m(A)\subset F^n(A)
$$
(resp. $n\leqslant m\implies F_n(A)\subset F_m(A)$).

A **filtered object** is an object endowed with a filtration.
When there is no chance of confusion, we often denote by the same letter filtrations on different objects of $\mathscr{A}$.

If $F$ is a decreasing (resp. increasing) filtration on $A$, then we set $F^\infty(A)=0$ and $F^{-\infty}(A)=A$ (resp. $F_{-\infty}(A)=0$ and $F_\infty(A)=A$).

The **shifted filtrations** of a decreasing filtration $W$ are defined by
$$
  W[n]^p(A)
  = W^{n+p}(A)
$$
for $n\in\ZZ$.
:::

::: {.rmenv #ii-1.1.3 number="1.1.3"}
If $R$ is a decreasing (resp. increasing) filtration of $A$, then the $F_n(A)=F^{-n}(A)$ (resp the $F^n(A)=F_{-n}(A)$) form an increasing (resp. decreasing) filtration of $A$.
\oldpage{7}
This allows us in principal to consider only decreasing filtrations;
*unless otherwise explicitly mentioned, when we say "filtration" we always mean "decreasing filtration"*.
:::

::: {.rmenv #ii-1.1.4 number="1.1.4"}
A filtration $F$ of $A$ is said to be **finite** if there exist $n$ and $m$ such that $F^n(A)=A$ and $F^m(A)=0$.
:::

::: {.rmenv #ii-1.1.5 number="1.1.5"}
A **morphism** from a filtered object $(A,F)$ to a filtered object $(B,F)$ is a morphism $f$ from $A$ to $B$ that satisfies $f(F^n(A))\subset F^n(B)$ for all $n\in\ZZ$.

Filtered objects (resp. finite filtered objects) of $\mathscr{A}$ form an additive category in which inductive limits and finite projective limits exist (and thus kernels, cokernels, images, and coimages of a morphism).

A morphism $f\colon(A,F)\to(B,F)$ is said to be **strict**, or **strictly compatible with the filtrations**, if the canonical arrows from $\Coim(f)$ to $\Im(f)$ is an isomorphism of filtered objects (cf. [(1.1.11)](#ii-1.1.11)).
:::

::: {.rmenv #ii-1.1.6 number="1.1.6"}
Let $(-)^\op$ be the contravariant identity functor from $\mathscr{A}$ to the dual category $\mathscr{A}^\op$.
If $(A,F)$ is a filtered object of $\mathscr{A}$, then the $(A/F^n(A))^\op$ can be identified with sub-objects of $A^\op$.
The **dual** filtration on $A^\op$ is defined by
$$
  F^n(A^\op)
  = (A/F^{1-n})^\op.
$$

The double dual of $(A,F)$ can be identified with $(A,F)$.
This construction identifies the dual of the category of filtered objects of $\mathscr{A}$ with the category of filtered objects of $\mathscr{A}^\op$.
:::

::: {.rmenv #ii-1.1.7 number="1.1.7"}
If $(A,F)$ is a filtered object of $\mathscr{A}$, then its **associated graded** is the object of $\mathscr{A}^\ZZ$ defined by
$$
  \Gr^n(A)
  = F^n(A)/F^{n+1}(A).
$$
The convention [(1.1.6)](#ii-1.1.6) is justified by the simple formula
$$
  \Gr^n(A^\op)
  = \Gr^{-n}(A)^\op
$$
which follows from the self-dual diagram
```tikz
\begin{tikzcd}
  A/F^n(A)
  && A/ F^{n+1}(A)
    \ar[ll]
  && 0
\\& A
    \ar[ul] \ar[ur]
  && \operatorname{Gr}^n(A)
    \ar[ul] \ar[ur]
  && (1.1.7.1)
\\F^{n+1}(A)
    \ar[ur] \ar[rr]
  && F^n(A)
    \ar[ul] \ar[ur]
  && 0
    \ar[ul]
\end{tikzcd}
```
:::


::: {.rmenv #ii-1.1.8 number="1.1.8"}
Let $(A,F)$ be a filtered object, and $j\colon X\hookrightarrow A$ a sub-object of $A$.
The **filtration induced by $F$** (or simply the **induced filtration**) on $X$ is the unique filtration on $X$ such that $j$ is strictly compatible with the filtrations;
we have
$$
  F^n(X)
  = j^{-1}(F^n(A))
  = X\cap F^n(A).
$$

Dually, the **quotient filtration** on $A/X$ (the unique filtration such that $p\colon A\to A/X$ is strictly compatible with the filtrations) is given by
$$
  F^n(A/X)
  = p(F^n(A))
  \cong (X+F^n(A))/X
  \cong F^n(A)/(X\cap F^n(A)).
$$
:::

::: {.itenv #ii-1.1.9 number="1.1.9" taxon="Lemma"}
\oldpage{8}
If $X$ and $Y$ are sub-objects of $A$, with $X\subset Y$, then on $Y/X\simto\Ker(A/X\to A/Y)$ the quotient filtration of $Y$ agrees with that induced by that of $A/X$.
In the diagram
```tikz
\begin{tikzcd}
  A/Y
  && A/X
    \ar[ll]
\\& A
    \ar[ul] \ar[ur]
  && Y/X
    \ar[ul]
\\X
    \ar[rr] \ar[ur]
  && Y
    \ar[ul] \ar[uu] \ar[ur]
\end{tikzcd}
```
:::

::: {.rmenv #ii-1.1.10 number="1.1.10"}
We call the filtration [(1.1.9)](#ii-1.1.9) on $Y/X$ the **filtration induced by that of $A$** (or simply the **induced filtration**).
By [(1.1.9)](#ii-1.1.9), its definition is self-dual.

In particular, if $\Sigma\colon A\xrightarrow{f}B\xrightarrow{G}C$ is a $0$-sequence, and if $B$ is filtered, then $\HH(\Sigma)=\Ker(g)/\Im(f)=\Ker(\Coker(f)\to\Coim(g))$ is endowed with a canonical induced filtration.
:::

The reader can show that:

::: {.itenv #ii-1.1.11 number="1.1.11" taxon="Proposition"}
i. Let $f\colon(A,F)\to(B,F)$ be a morphism of filtered objects with finite filtrations.
  For $f$ to be strict, it is necessary and sufficient that the sequence
  $$
    0
    \to \Gr(\Ker(f))
    \to \Gr(A)
    \to \Gr(B)
    \to \Gr(\Coker(f))
    \to 0
  $$
  be exact.

ii. Let $\sigma\colon(A,F)\to(B,F)\to(C,F)$ be a $0$-sequence sequence of strict morphisms.
  We then have
  $$
    \HH(\Gr(\Sigma))
    \cong \Gr(\HH(\Sigma))
  $$
  canonically.
  In particular, if $\Sigma$ is exact in $\mathscr{A}$, then $\Gr(\Sigma)$ is exact in $\mathscr{A}^\ZZ$.
:::

In a category of modules, to say that a morphism $f\colon(A,F)\to(B,F)$ is strict implies that every $b\in B$ of filtration $\geqslant n$ (i.e. $b\in F^n(B)$) that is in the image of $A$ is already in the image of $F^n(A)$:
$$
f(F^n(A))
= f(A)\cap F^n(B).
$$

::: {.rmenv #ii-1.1.12 number="1.1.12"}
If $\otimes\colon\mathscr{A}_1\times\ldots\times\mathscr{A}_n\to\mathscr{B}$ is a multiadditive right-exact functor, and if $A_i$ is an object of finite filtration of $\mathscr{A}_i$ (for $1\leqslant i\leqslant n$), then we define a filtration on $\bigotimes_{i=1}^n A_i$ by
$$
  F^k(\bigotimes_{i=1}^n A_i)
  = \sum_{\sum k_i=k} \Im(\bigotimes_{i=1}^n F^{k_i}(A_i)\to\bigotimes_{i=1}^n A_i)
$$
(a sum of sub-objects).

Dually, if $H$ is left-exact, then we set
$$
  F^k(H(A_i))
  = \bigcap_{\sum k_i=k} \Ker(H(A_i)\to H(A_i/F^{k_i}(A_i))).
$$

\oldpage{9}
If $H$ is exact, then the two definitions are equivalent.

We extend these definitions to contravariant functors in certain variables by [(1.1.6)](#ii-1.1.6).
In particular, for the left-exact functor $\Hom$, we set
$$
  F^k(\Hom(A,B))
  = \{f\colon A\to B \mid f(F^n(A))\subset F^{n+k}(B)\,\,\forall n\}.
$$
We thus have
$$
  \Hom((A,F),(B,F))
  = F^0(\Hom(A,B)).
$$

Under the above hypotheses, we have obvious morphisms
$$
  \begin{aligned}
    \bigotimes_{i=1}^n \Gr(A_i)
    &\to \Gr(\bigotimes_{i=1}^n A_i)
  \\\Gr H(A_i)
    &\to H(\Gr(A_i)).
  \end{aligned}
$$
If $H$ is exact, then these are isomorphisms and inverse to one another.

These constructions are compatible with composition of functors, in a sense whose details we leave to the reader.
:::
