---
title: 3.1 Logarithmic poles and residues
---

{{< include ../macros.qmd >}}

::: {.rmenv #env-ii-3.1.1 number="3.1.1"}
We recall several classical properties of "logarithmic poles" of holomorphic differential forms.
The reader will find proofs in [@D1970, II, (3.1) to (3.7)], for example.
:::

::: {.rmenv #env-ii-3.1.2 number="3.1.2"}
A divisor $Y$ in a smooth complex analytic variety $X$ is said to be of **normal crossing** if the inclusion of $Y$ into $X$ is locally isomorphic to the inclusion of a union of coordinate hyperplanes in $\CC^n$;
this does not imply that $Y$ is the union of smooth divisors.
Let $Y$ be a normal crossing divisor in $X$, and $j$ the inclusion of $X^*=X\setminus Y$ into $X$.
We denote by $\Omega_X^1\langle Y\rangle$ the locally free sub-$\OO$-module of $j_*\Omega_{X^*}^1$ generated by $\Omega_X^1$ and the $\dd z_i/z_i$ for $z_i$ local coordinates of a local irreducible component of $Y$.
The **sheaf $\Omega_X^p\langle Y\rangle$ of differential $p$-forms on $X$ with logarithmic poles along $Y$** is by the definition the locally free sub-sheaf $\wedge^p\Omega_X^1\langle Y\rangle$ of $j_*\Omega_{X^*}^p$.
:::

::: {.itenv #env-ii-3.1.3 number="3.1.3" taxon="Proposition"}
—

i. A section $\alpha$ of $j_*\Omega_{X^*}^p$ belongs to $\Omega_X^p\langle Y\rangle$ if and only if $\alpha$ and $\dd\alpha$ have at worst simple poles along the divisor $Y$.
ii. The $\Omega_X^p\langle Y\rangle$ form the smallest subcomplex of $j_*\Omega_{X^*}^\bullet$ that is stable under exterior product and that contains $\Omega_X^\bullet$ and the logarithmic differential $\dd f/f$ of every local section of $j_*\Omega_{X^*}^p$ meromorphic along $Y$.
:::

We call $\Omega_X^\bullet\langle Y\rangle$ the **logarithmic de Rham complex** of $X$ along $Y$.
By (ii) of [(3.1.3)](#ii-3.1.3), this complex is contravariant in the pair $(X,X^*)$.

::: {.rmenv #env-ii-3.1.4 number="3.1.4"}
Locally on $X$, $Y$ is the union of various smooth divisors $Y_i$, and we denote by $Y^n$ (resp. $\widetilde{Y}^n$) the union (resp. disjoint sum) of the $n$-fold intersections of the $Y_i$.
The $Y^n$ glue to give a subspace $Y^n$ of $X$, and the $\widetilde{Y}^n$ glue to give the normalisation variety of $Y^n$.
We have $\widetilde{Y}^0=Y^0=X$, and we set $\widetilde{Y}=\widetilde{Y}^1$.

We define the two-element set of **orientations** of an $n$-element set $E$ as the set of generators of $\wedge^n\ZZ^E$.
\oldpage{32}
For $n\geqslant2$, this set is that of the conjugation classes under the alternating group of total orders on $E$.

If, to each point $y$ of $\widetilde{Y}^n$, we associate the set of $n$ local components of $Y$ that contain the image in $X$ of a neighbourhood of $y$ in $\widetilde{Y}^n$, then we define on $\widetilde{Y}^n$ a local system $E_n$ of $n$-element sets.
The local system of orientations of these sets is a $\ZZ/(2)$-torsor.
This torsor defines, via the inclusion of $\ZZ/(2)$ into $\CC^*$, a complex local system $\varepsilon^n$ of rank 1 on $\widetilde{Y}^n$, endowed with an isomorphism $(\varepsilon^n){\otimes2}\simeq\CC$.
We have
$$
  \varepsilon^n
  \simeq \bigwedge^n \CC^{E_n}.
$$

Locally on $\widetilde{Y}^n$, $\varepsilon^n$ is endowed with two opposite isomorphisms $\pm\alpha\colon\varepsilon^n\simto\CC$.
We set
$$
  \varepsilon_\ZZ^n
  = \alpha^{-1}((2\pi i)^{-n}\ZZ).
$$
There is a way of seeing $\varepsilon^n$, endowed with $\varepsilon_\ZZ^n$, as a twisted version of $\ZZ(-n)$ over $\widetilde{Y}^n$.

We denote by $\varepsilon_X^n$ (resp. by $(\varepsilon_X^n)$\ZZ}) the direct image of $\varepsilon^n$ (resp. of $\varepsilon_\ZZ^n$) under the mat from $\widetilde{Y}^n$ to $X$.
We have
$$
  \varepsilon_X^n
  \simeq \bigwedge^n\varepsilon_X^1
  \qquad\text{for }n\geqslant0.
\tag{3.1.4.1}
$$

If $Y$ is the union of distinct smooth divisors $(Y_i)_{i\in I}$, then the choice of a total order on $I$ trivialises the $\varepsilon^n$.
:::

::: {.rmenv #env-ii-3.1.5 number="3.1.5"}
We denote by $W_n(\Omega_X^p\langle Y\rangle)$ the sub-module of $\Omega_X^p\langle Y\rangle$ consisting of linear combinations of products
$$
  \alpha
  \wedge \frac{\dd t_{i(1)}}{t_{i(1)}}
  \ldots
  \wedge \frac{\dd t_{i(m)}}{t_{i(m)}}
  \qquad\text{for }m\leqslant n
$$
with $\alpha$ holomorphic and the $t_{i(j)}$ local coordinates of the distinct local components $Y_j$ of $Y$.
We define the $weight filtration$ of $\Omega_X^\bullet\langle Y\rangle$ to be the *increasing* filtration by the subcomplexes $W_n(\Omega_X^\bullet\langle Y\rangle)$.
We have
$$
  W_n(\Omega_X^p\langle Y\rangle)
  \wedge W_m(\Omega_X^p\langle Y\rangle)
  \subset W_{n+m}(\Omega_X^{p+q}\langle Y\rangle).
\tag{3.1.5.1}
$$

If we denote by $i_n$ the map from $\widetilde{Y}^n$ to $X$, then we can show that the mapping
$$
  \alpha
  \wedge \frac{\dd t_{i(1)}}{t_{i(1)}}
  \ldots
  \wedge \frac{\dd t_{i(m)}}{t_{i(m)}}
  \longmapsto
  (\alpha|Y_{i(1)}\cap\ldots\cap Y_{i(n)})\otimes(\text{orientation }i(1)\ldots i(n))
$$
defines an isomorphism of complexes
$$
  \Res\colon\Gr_n^W(\Omega_X^\bullet\langle Y\rangle)
  \approx (i_n)_*\Omega_{\widetilde{Y}^n}^\bullet(\varepsilon^n)[-n]
\tag{3.1.5.2}
$$
(the **Poincaré residue**).
:::

::: {.rmenv #env-ii-3.1.6 number="3.1.6"}
The interpretation that follows, in terms of [(3.1.5.2)](#ii-3.1.5), of the Leray spectral sequence for the inclusion of $X^*$ into $X$, was pointed out to me by N. Katz.
It will allow us to prove a point that I had initially considered as evident (the first part of (ii) of [(3.2.5)](3.2-mixed-hodge-theory.html#ii-3.2.5)).
:::

::: {.rmenv #env-ii-3.1.7 number="3.1.7"}
Every point of $X$ admits a fundamental system of Stein open neighbourhoods whose intersections on $X^*$ are again Stein.
\oldpage{33}
For a coherent analytic sheaf $\sh{F}$ on $X^*$, we thus have $\Rd^i j_*\sh{F}=0$ for $i>0$.
The de Rham complex $\Omega_{X^*}^\bullet$ is thus a resolution of the constant sheaf $\CC$ by sheaves acyclic for the functor $j_*$.
Then
$$
  \HH^\bullet(X^*,\CC)
  \simto \bHH^\bullet(X^*,\Omega_{X^*}^\bullet)
  \simfrom \bHH^\bullet(X,j_*\Omega_{X^*}^\bullet)
$$
and the Leray spectral sequence for the morphism $j$ can be identified with the hypercohomology spectral sequence for $j_*\Omega_{X^*}^\bullet$ corresponding to the filtration $\tau$ by the subcomplexes $\tau_{\leqslant -n}(j_*\Omega_{X^*}^\bullet)$ [(1.4.6)](1.4-hypercohomology-of-filtered-complexes.html#ii-1.4.6).
:::

::: {.itenv #env-ii-3.1.8 number="3.1.8" taxon="Proposition"}
The morphisms of filtered complexes
$$
  (\Omega_X^\bullet\langle Y\rangle, W)
  \xleftarrow{\alpha} (\Omega_X^\bullet\langle Y\rangle, \tau)
  \xhookrightarrow{\beta} (j_*\Omega_{X^*}^\bullet, \tau)
$$
are filtered quasi-isomorphisms.
They define an isomorphism between the Leray spectral sequence for $j$ in complex cohomology and the hypercohomology spectral sequence of the filtered complex $(\Omega_X^\bullet\langle Y\rangle, W)$ on $X$.
:::

::: {.proof}
By [(1.4.5)](1.4-hypercohomology-of-filtered-complexes.html#ii-1.4.5) and [(3.1.7)](#ii-3.1.7), it suffices to prove the first claim.
In [@D1970, II, (6.9)] or [@AH1955], one can find a proof of the fact that $\beta$ is a quasi-isomorphism, and thus a filtered quasi-isomorphism.
We can also directly calculate the cohomology sheaves of the two sides: those of $\Omega_X^\bullet\langle Y\rangle$ are determined by [(3.1.5.2)](#ii-3.1.5), while those of $j_*\Omega_{X^*}^\bullet$ are the $\Rd^ij_*\CC$, which can be calculated by topological methods.

For $n\geqslant p$, we have
$$
  W_n(\Omega_X^p\langle Y\rangle)
  = \Omega_X^p\langle Y\rangle
$$
and so $\alpha$ is a morphism from $\Omega_X^\bullet\langle Y\rangle$, endowed with $\tau$, to $\Omega_X^\bullet\langle Y\rangle$, endowed with the decreasing filtration associated to $W$ [(1.1.3)](1.1-filtered-objects.html#ii-1.1.3).
By [(3.1.5.2)](#ii-3.1.5), we have
$$
  \sHH^i(\Gr_n^W(\Omega_X^\bullet\langle Y\rangle)) =
  \begin{cases}
    0 &\text{for }i\neq n
  \\\varepsilon_X^n &\text{for }i=n
  \end{cases}
\tag{3.1.8.1}
$$
and we deduce from the first line of this equation that $\alpha$ is a filtered quasi-isomorphism.
This proves [(3.1.8)](#ii-3.1.8).
:::

By [(3.1.7)](#ii-3.1.7), the isomorphism [(3.1.8.1)](#ii-3.1.8) defines an isomorphism
$$
  \Rd^n j_*\CC
  \simeq \sHH^n(j_*\Omega_{X^*}^\bullet)
  \simeq \sHH^n(\Omega_X^\bullet\langle Y\rangle)
  \simeq \varepsilon_X^n.
\tag{3.1.8.2}
$$

The isomorphisms [(3.1.4.1)](#ii-3.1.4) correspond, via [(3.1.8.1)](#ii-3.1.8), to the cup product.

::: {.itenv #env-ii-3.1.9 number="3.1.9" taxon="Proposition"}
The canonical morphism from $\Rd^nj_*\ZZ$ to $\Rd^nj_*\CC$ identifies, via [(3.1.8.2)](#ii-3.1.8), the sheaf $\Rd^nj_*\ZZ$ with $(\varepsilon_X^n)$\ZZ} [(3.1.4)](#ii-3.1.4).
:::

::: {.proof}
The question is local on $X$.
We can thus suppose that $X$ is an open polycylinder $D^m$, with
$$
  D
  = \{z\in\CC \mid |z|<1\}
$$
and also that $Y=\bigcup_{k=1}^\ell Y_k$ with $Y_k=\pr_k^{-1}(0)$.
The fibre at $0$ of $\Rd^nj_*\ZZ$ is then the integer cohomology of $X^*=(D^*)^\ell\times D^{m-\ell}$, with
$$
  D^*
  = \{z\in\CC \mid 0<|z|<1\}.
$$
\oldpage{34}
The space $X^*$ has the homotopy type of a torus;
its cohomology is thus torsion free, and the cup product defines isomorphisms
$$
  \bigwedge^n(\Rd^1j_*\ZZ)
  \simto (\Rd^nj_*\ZZ)_0.
$$
It thus suffices to prove [(3.1.9)](#ii-3.1.9) for $n=1$.

The integer homology $\HH_1(X^*)$ is generated by the loops $\gamma_k$ that go around the various $Y_k$.
We have
$$
  \oint_{\gamma_k} \frac{\dd z_k}{z_k}
  = \pm2\pi i
$$
and so the integer cohomology is generated by the $\frac{1}{2\pi i}\frac{\dd z_k}{z_k}$, and this proves [(3.1.9)](#ii-3.1.9).
:::

::: {.rmenv #env-ii-3.1.10 number="3.1.10"}
Let $\sh{F}$ be a coherent analytic sheaf on $X^*$, given as the restriction to $X^*$ of a coherent analytic sheaf $\sh{F}'$ on $X$.
We define the **meromorphic direct image** $j_*^\mm\sh{F}$ of $\sh{F}$ to be the inductive limit
$$
  j_*^\mm\sh{F}
  = \varinjlim\sh{F}'(nY).
$$

Locally on $X$, $Y$ is the sum of a finite family $(Y_i)${i\in I}} of smooth divisors, and we define the **pole-order filtration** $P$ on $j_*^\mm\OO_X^*$ by the equation
$$
  P^p(j_*^\mm\OO_{X^*})
  = \sum_{n\in A_p} \OO_X\left(\sum(n_i+1)Y_i\right)
\tag{3.1.10.1}
$$
where
$$
  A_p
  = \left\{(n_i)_{i\in I} \mid \sum_i n_i\leqslant -p \text{ and } n_i\geqslant0\text{ for all } i\right\}.
$$
This construction globalises by endowing $j_*^\mm\OO_{X^*}$ with an exhaustive filtration such that $P^p=0$ for $p>0$.

We define the **pole-order filtration** of the complex $j_*^\mm\Omega_{X^*}^\bullet=j_*^\mm\OO_{X^*}\otimes\Omega_X^\bullet$ to be the filtration
$$
  P^p(j_*^\mm\Omega_{X^*}^k)
  = P^{p-k}(j_*^\mm\OO_X)\otimes\Omega_X^k.
\tag{3.1.10.2}
$$

The filtration $P$ induces, on the subcomplex $\Omega_X^\bullet\langle Y\rangle$ of $j_*^\mm\Omega_{X^*}^\bullet$, the stupid filtration by the $\sigma_{\geqslant p}(\Omega_X^\bullet\langle Y\rangle)$, which we also call the **Hodge filtration** $F$.
:::

::: {.itenv #env-ii-3.1.11 number="3.1.11" taxon="Proposition"}
The inclusion morphism
$$
  (\Omega_X^\bullet\langle Y\rangle, F)
  \to (j_*^\mm\Omega_{X_*}^\bullet, P)
$$
is a filtered quasi-isomorphism.
:::

::: {.proof}
This statement was suggested to me by [@G1969].
A proof can be found in [@D1970, II, (3.13)].
:::
