---
title: 3.2 Mixed Hodge theory
---

{{< include ../macros.qmd >}}

*We recall that, from here on, we say "scheme" to mean a scheme of finite type over $\CC$, and "sheaf on $S$" to mean a sheaf on $S^\an$.*

::: {.rmenv #env-ii-3.2.1 number="3.2.1"}
Let $X$ be a smooth and separated scheme.
By Nagata [@N1962], $X$ is a Zariski open of a complete scheme $\overline{X}$.
By Hironaka [@H1964], we can take $\overline{X}$ to be smooth and such that $Y=\overline{X}\setminus X$ is a normal crossing divisor.

The reader who wishes to avoid the reference to Nagata can suppose $X$ to be quasi-projective.
\oldpage{35}
The smooth completion $\overline{X}$ can then be chosen to be projective and such that $Y$ is the union of smooth divisors.
If we limit ourselves to such compactifications, then we only need Hodge theory in its standard form [(2.2.1)](2.2-hodge-theory.qmd#ii-2.2.1).
:::

::: {.rmenv #env-ii-3.2.2 number="3.2.2"}
By [(3.1.7)](3.1-logarithmic-poles-and-residues.qmd#ii-3.1.7) and [(3.1.8)](3.1-logarithmic-poles-and-residues.qmd#ii-3.1.8), we have
$$
  \HH^\bullet(X,\CC)
  \simeq \bHH^\bullet(\overline{X},\Omega_{\overline{X}}^\bullet\langle Y\rangle).
$$
We define the **Hodge filtration** $F$ on the complex $\Omega_{\overline{X}}^\bullet\langle Y\rangle$ as the filtration $F^p=\sigma_{\geqslant p}$ given by the stupid truncations [(1.4.5)](1.4-hypercohomology-of-filtered-complexes.qmd#ii-1.4.5).
On $\Omega_{\overline{X}}^\bullet\langle Y\rangle$, we thus have two filtrations: $F$ and $W$ [(3.1.5)](3.1-logarithmic-poles-and-residues.qmd#ii-3.1.5).
:::

::: {.rmenv #env-ii-3.2.3 number="3.2.3"}
We will need to make use of the fact that there exist bifiltered resolutions $i\colon\Omega_{\overline{X}}^\bullet\langle Y\rangle\to K^\bullet$ such that the $\Gr_F^p\Gr_n^W(K^j)$ are $\Gamma$-acyclic sheaves:
$$
  \HH^i(\overline{X},\Gr_F^p\Gr_n^W(K^j))
  = 0
  \qquad\text{for }i>0.
$$

Here are two methods to construct such a resolution:

a. We can take $K^\bullet$ to be the canonical Godement resolution $\mathscr{C}^\bullet(\Omega_{\overline{X}}^\bullet\langle Y\rangle)$, filtered by the $\mathscr{C}^\bullet(W_n(\Omega_{\overline{X}}\langle Y\rangle))$ and the $\mathscr{C}^\bullet(F^p(\Omega_{\overline{X}}^\bullet\langle Y\rangle))$.
    This is a bifiltered resolution since $\mathscr{C}^\bullet$ is an exact functor.
b. We can take $K^\bullet$ to be the $\dd''$-resolution of $\Omega_{\overline{X}}^\bullet\langle Y\rangle$.
    Let $\Omega_{\overline{X}}^{pq}$ be the sheaf of $C^\infty$ forms of degree $(p,q)$;
    then $K^\bullet$ is the simple complex associated to the double complex of the $\Omega_{\overline{X}}^p\langle Y\rangle\otimes_\OO\Omega_{\overline{X}}^{0,q}$ (a subcomplex of the $j_*\Omega_X^{\bullet\bullet}$).
    This complex is filtered by the $F^p(\Omega_{\overline{X}}^\bullet\langle Y\rangle)\otimes\Omega_{\overline{X}}^{0,\bullet}$ and by the $W_n(\Omega_{\overline{X}}^\bullet\langle Y\rangle)\otimes\Omega_{\overline{X}}^{0,\bullet}$;
    to prove that this is a bifiltered resolution, we use the fact that the sheaf $\OO_\infty$ of complex $C^\infty$ functions on $\overline{X}$ is flat over $\OO$ (a corollary of the Malgrange $C^\infty$ preparation theorem).
    The sheaves $\Gr_F\Gr_W(K^\bullet)$ are fine, since they are sheaves of modules over the soft sheaf $\OO_\infty$.
:::

::: {.rmenv #env-ii-3.2.4 number="3.2.4"}
With the notation of [(3.2.3)](#ii-3.2.3), the complex cohomology of $X$ appears as the cohomology of the bifiltered complex $\Gamma(\overline{X},K^\bullet)$.
We thus have two spectral sequences abutting to $\HH^\bullet(X,\CC)$.
They can be written, with the notation of [(3.1.4)](3.1-logarithmic-poles-and-residues.qmd#ii-3.1.4), as:
$$
  {}_WE_1^{pq}
  = \bHH^{p+q}(\overline{X},\varepsilon_{\overline{X}}^{-p}[p])
  = \bHH^{2p+q}(\widetilde{Y}^p,\varepsilon^{-q})
  \To \HH^n(X,\CC)
\tag{3.2.4.1}
$$
$$
  {}_FE_1^{pq}
  = \HH^q(\overline{X},\Omega_{\overline{X}}^p\langle Y\rangle)
  \To \HH^n(X,\CC).
\tag{3.2.4.2}
$$
The first of these, up to the renumbering ${}_WE_1^{pq}\mapsto E_2^{2p+q,-p}$, is exactly the Leray spectral sequence of the inclusion $j$.
:::

::: {.rmenv #env-ii-3.2.5 number="3.2.5" taxon="Theorem"}
—

i. On the pages ${}_WE_r^{pq}$ of the spectral sequence [(3.2.4.1)](#ii-3.2.4), the first direct filtration, the second direct filtration, and the recurrent filtration defined by $F$ all coincide.
ii. The filtration on $\HH^n(X,\CC)$ that is the abutment of the spectral sequence ${}_WE$ comes from a filtration $W$ of $\HH^n(X,\QQ)$.
  Neither it, nor the filtration $F$ that is the abutment of the spectral sequence ${}_FE$, depend on the choice of compactification $\overline{X}$ of $X$ or on the choice of $K^\bullet$.
iii. The filtrations $W[n]$ [(1.1.2)](1.1-filtered-objects.qmd#ii-1.1.2) and $F$ define on $\HH^n(X,\ZZ)$ a mixed Hodge structure, functorially in $X$.
:::

\oldpage{36}
By \ref{hodge-theory-ii-3.1.7}, the spectral sequence ${}_WE$ is the Leray spectral sequence for $j_*$ (up to renumbering).
It is thus induced by tensoring a $\QQ$-vectorial spectral sequence with $\CC$, and so the first claim of (ii) is true.
Complex conjugation acts on the ${}_WE$;
it can be calculated via [(3.1.10)](3.1-logarithmic-poles-and-residues.qmd#ii-3.1.10).

::: {.itenv #env-ii-3.2.6 number="3.2.6" taxon="Lemma"}
The hypercohomology spectral sequences of the filtered complexes $\Gr_n^W(\Omega_{\overline{X}}^\bullet\langle Y\rangle)$, endowed with the filtration induced by the Hodge filtration, degenerate at the $E_1$ page.
:::

::: {.proof}
Define the $Y^n$ and the $\widetilde{Y}^n$ as in [(3.1.4)](3.1-logarithmic-poles-and-residues.qmd#ii-3.1.4), and let $i_n\colon\widetilde{Y}^n\to X$.
By [(3.1.5.2)](#ii-3.1.5), we have
$$
  \Gr_n^W(\Omega_{\overline{X}}^\bullet\langle Y\rangle)
  \sim (i_n)_*\Omega_{\widetilde{Y}^n}^\bullet(\varepsilon^n)[-n].
$$
Furthermore, the Hodge filtration induces the stupid filtration [(1.4.5)](1.4-hypercohomology-of-filtered-complexes.qmd#ii-1.4.5), and so the spectral sequence in [(3.2.6)](#ii-3.2.6) is given by translations of the degrees of the classical spectral sequence
$$
  E_1^{pq}
  = \HH^q(\widetilde{Y}^n,\Omega_{\widetilde{Y}^n}^p(\varepsilon^n))
  \To \HH^{p+q}(\widetilde{Y}^n,\varepsilon^n).
$$

If $\overline{X}$ is projective and $Y$ the union of smooth divisors, then $\widetilde{Y}^n$ is projective, $\varepsilon^n$ is a trivial local system, and classical Hodge theory [(2.2.1)](2.2-hodge-theory.qmd#ii-2.2.1) gives the degeneration claimed in [(3.2.6)](#ii-3.2.6).
For the general case, refer to [@D1968] (see also [(2.2.2)](2.2-hodge-theory.qmd#ii-2.2.2)  and [(2.2.3)](2.2-hodge-theory.qmd#ii-2.2.3)).
:::

Hodge theory also tells us that the Hodge filtration on $\HH^k(\widetilde{Y}^n,\varepsilon^n)$ is $k$-opposite to its complex conjugate (the complex conjugate being defined in terms of $\varepsilon_\ZZ^n$ [(3.1.4)](3.1-logarithmic-poles-and-residues.qmd#ii-3.1.4).
We have, taking into account the translations of the degrees:

::: {.itenv #env-ii-3.2.7 number="3.2.7" taxon="Lemma"}
The filtration on
$$
  {}_WE_1^{-n,k+n}
  = \bHH^k(\overline{X},\Gr_n^W(\Omega_{\overline{X}}^\bullet\langle Y\rangle))
  \approx \HH^{k-n}(\widetilde{Y}^n,\varepsilon^n)
$$
which is the abutment of the spectral sequence in [(3.2.6)](#ii-3.2.6) is $(k+n)$-opposite to its complex conjugate.
:::

::: {.itenv #env-ii-3.2.8 number="3.2.8" taxon="Lemma"}
The differentials $d_1$ of the spectral sequence ${}_WE$ are strictly compatible with the filtration $F$.
:::

::: {.proof}
On the $E_1$ pages, there is only the filtration induced by $F$ to consider ([(1.3.10)](1.3-the-two-filtrations-lemma.qmd#ii-1.3.10) and (iii) of [(1.3.13)](1.3-the-two-filtrations-lemma.qmd#ii-1.3.13)), and $d_1$ is compatible with this filtration ((i) of [(1.3.13)](1.3-the-two-filtrations-lemma.qmd#ii-1.3.13)).
This filtration is the abutment of the spectral sequence in [(3.2.6)](#ii-3.2.6) ((ii) of [(1.4.8)](1.4-hypercohomology-of-filtered-complexes.qmd#ii-1.4.8)).
By [(3.2.7)](#ii-3.2.7), the arrow
$$
  d_1\colon
  \bHH^k(\overline{X},\Gr_n^W(\Omega_{\overline{X}}^\bullet\langle Y\rangle))
  \to \bHH^{k+1}(\overline{X},\Gr_{n-1}^W(\Omega_{\overline{X}}^\bullet\langle Y\rangle))
$$
or
$$
  d_1\colon
  \HH^{k-n}(\widetilde{Y}^n,\varepsilon^n)
  \to \HH^{k-n+1}(\widetilde{Y}^{n-1},\varepsilon^{n-1})
\tag{3.2.8.1}
$$
is compatible with the filtrations that are $(k+n)$-opposite to their complex conjugate.
Since $d_1$ commutes up to complex conjugation, $d_1$ respects the bigrading (of weight $k+n$) defined by $F$ and $\overline{F}$, which proves [(3.2.8)](#ii-3.2.8).
:::

Furthermore, the cohomology of the complex $E_1$ is again bigraded:

::: {.itenv #env-ii-3.2.9 number="3.2.9" taxon="Lemma"}
The recurrent filtration $F$ on ${}_WE_2^{pq}$ is $q$-opposite to its complex conjugate.
:::

We prove by induction on $r$ that:

::: {.itenv #env-ii-3.2.10 number="3.2.10" taxon="Lemma"}
For $r\geqslant0$, the differentials $d_r$ of the spectral sequence ${}_WE$ are strictly compatible with the recurrent filtration $F$.
For $r\geqslant2$, they are zero.
:::

::: {.proof}
For $r=0$ (resp. $r=1$) we apply [(3.2.6)](#ii-3.2.6) and (iii) of [(1.4.8)](1.4-hypercohomology-of-filtered-complexes.qmd#ii-1.4.8) (resp. [(3.2.8)](#ii-3.2.8)).
\oldpage{37}
For $r\geqslant2$, it suffices to prove that $d_r=0$.
By induction, and following [(1.3.16)](1.3-the-two-filtrations-lemma.qmd#ii-1.3.16), we can assume that, on the pages ${}_WE^s$ (for $s\geqslant r+1$), we have $F_d=F_r=F_{d^*}$, and that ${}_WE_r={}_WE_2$.
By (i) of [(1.3.13)](1.3-the-two-filtrations-lemma.qmd#ii-1.3.13)), $d_r$ is thus compatible with the filtration $F_r$.

On ${}_WE_r^{pq}={}_WE_2^{pq}$, the filtration $F_r$ is $q$-opposite to its complex conjugate.
The morphism
$$
  d_r\colon {}_WE_r^{pq}
  \to {}_WE_r^{p+r,q-r+1}
$$
thus satisfies, for $r-1>0$,
$$
  \begin{aligned}
    d_r({}_WE_r^{pq})
    &= d_r\left(
      \sum_{a+b=q} \Big(
        F^a({}_WE_r^{pq}) \cap \overline{F}^b({}_WE_r^{pq})
      \Big)
    \right)
  \\&\subset \sum_{a+b=q} \Big(
      F^a({}_WE_r^{p+r,q-r+1}) \cap \overline{F}^b({}_WE_r^{p+r,q-r+1})
    \Big)
  \\&= 0.
  \end{aligned}
$$

This proves [(3.2.10)](#ii-3.2.10).
:::

[(3.2.10)](#ii-3.2.10), using [(1.3.16)](1.3-the-two-filtrations-lemma.qmd#ii-1.3.16)), proves (i) of [(3.2.5)](#ii-3.2.5).

By [(1.3.17)](1.3-the-two-filtrations-lemma.qmd#ii-1.3.17)), the filtration on ${}_WE_\infty^{pq}$ induced by the filtration $F$ of $\HH^{p+q}(X,\CC)$ is $q$-opposite to its complex conjugate.
Since $q=-p+(p+q)$, this proves the first part of (iii) of [(3.2.5)](#ii-3.2.5).

::: {.rmenv #env-ii-3.2.11 number="3.2.11"}
We now prove (ii) and (iii) of [(3.2.5)](#ii-3.2.5), which will finish the proof.

a. *Independence from the choice of $K^\bullet$.*

    The filtrations $F$ and $W$ of $\HH^\bullet(X,\CC)$ are the abutments of the hypercohomology spectral sequences of $\Omega_{\overline{X}}^\bullet\langle Y\rangle$ for the filtrations $F$ and $W$.
    These whole spectral sequences do not depend on the choice of $K^\bullet$.

b. *Functoriality.*
    
    Let $f\colon X_1\to X_2$ be a morphism of schemes.
    Suppose that we are given a morphism of smooth compactifications
    $$
      \begin{CD}
        X_1 @>f>> X_2
      \\@V{j_1}VV @VV{j_2}V
      \\\overline{X}_1 @>>{\overline{f}}> \overline{X}_2
      \end{CD}
    \tag{3.2.11.1}
    $$
    with the $Y_i=\overline{X}_i\setminus X_i$ normal crossing divisors.
    The canonical morphism (cf. [(3.1.3)](3.1-logarithmic-poles-and-residues.qmd#ii-3.1.3)) from $\overline{f}^*\Omega_{\overline{X}_2}^\bullet\langle Y_2\rangle$ to $\Omega_{\overline{X}_1}^\bullet\langle Y_1\rangle$ is then a morphism of bifiltered complexes;
    on hypercohomology, it induces a morphism compatible with $F$ and $W$, and thus $f^*\colon\HH^n(X_2,\ZZ)\to\HH^n(X_1,\ZZ)$ is a morphism of mixed Hodge structures, for the structures defined by the compactifications $\overline{X}_i$.

c. *Independence from the choice of compactification.*
    
    With the notation of (b), if $f$ is an isomorphism, then $f^*$ is a bijective morphism of mixed Hodge structures, and thus an isomorphism [(2.3.5)](2.3-mixed-structures.qmd#ii-2.3.5).

    If $\overline{X}_1$ and $\overline{X}_2$ are two smooth compactifications of $X$, with $Y_i=\overline{X}_i\setminus X$ smooth crossing divisors, then there exists a third smooth compactification $\overline{X}$, with $Y=\overline{X}\setminus X$ a smooth crossing divisor, that fits into a commutative diagram
    \oldpage{38}

    ```tikz
    \begin{tikzcd}
      & X \ar[dl,hook] \ar[d,hook] \ar[dr,hook]
    \\\overline{X}_1
      & \overline{X} \ar[l] \ar[r]
      & \overline{X}_2
    \end{tikzcd}
    ```

    Namely, we can take $\overline{X}$ to be a resolution of singularities of the closure of the diagonal image of $X$ in $\overline{X}_1\times\overline{X}_2$.
    The identity map from $\HH^n(X,\ZZ)$ endowed with the mixed Hodge structure defined by $\overline{X}_1$ to $\HH^n(X,\ZZ)$ endowed with the mixed Hodge structure defined by $\overline{X}_2$ is thus the composite of two isomorphisms.

To finish the proof of (ii) and (iii), we note that every morphism $f$ fits into a diagram of the form in [(3.2.11.1)](#ii-3.2.11): we choose compactifications $\overline{X}'_1$ and $\overline{X}_2$ of $X_1$ and $X_2$, then we take $\overline{X}_1$ to be a resolution of singularities of the closure of the image of $X_1$ in $\overline{X}'_1\times\overline{X}_2$.
:::

::: {.rmenv #env-ii-3.2.12 number="3.2.12" taxon="Definition"}
The **mixed Hodge structure of the cohomology of a smooth separated algebraic variety** is the mixed Hodge structure from (iii) of [(3.2.5)](#ii-3.2.5).
:::

::: {.itenv #env-ii-3.2.13 number="3.2.13" taxon="Corollary"}
With the above notation:

i. The spectral sequence in [(3.2.4.1)](#ii-3.2.4) degenerates at $E_2$, i.e. the Leray spectral sequence for the inclusion $j\colon X^*\hookrightarrow X$ degenerates at $E_3$ (i.e. $E_3=E_\infty$).
ii. The spectral sequence in [(3.2.4.2)](#ii-3.2.4)
    $$
      {}_FE_1^{pq}
      = \HH^q(\overline{X},\Omega_{\overline{X}}^p\langle Y\rangle)
      \To \HH^{p+q}(X,\CC)
    $$
    degenerates at $E_1$.
iii. The spectral sequence defined by the sheaf $\Omega_X^p\langle Y\rangle$, endowed with the filtration $W$
    $$
      \begin{aligned}
        E_1^{-n,k+n}
        &= \HH^k(\overline{X},\Gr_n^W(\Omega_X^p\langle Y\rangle))
      \\&\approx \HH^k(\widetilde{Y}^n,\Omega_{\widetilde{Y}^n}^{p-n}(\varepsilon^n))
        \To \HH^k(\overline{X},\Omega_X^p\langle Y\rangle)
      \end{aligned}
    $$
    degenerates at $E_2$.
:::

::: {.proof}
Claim (i) is proven in [(3.2.10)](#ii-3.2.10).

Consider the four spectral sequences in [(1.4.2)](1.4-hypercohomology-of-filtered-complexes.qmd#ii-1.4.2), with respect to the bifiltered complex $\Omega_{\overline{X}}^\bullet\langle Y\rangle$.
By (i), we have
$$
  \sum_n \dim\HH^n(X,\CC)
  = \sum_{p,q} \dim {}_WE_2^{p,q}.
$$
The ${}_WE_1^{n,k-n}$ pages are, for fixed $n$, the abutments of a spectral sequence *that degenerates at $E_1$* [(3.2.6)](#ii-3.2.6) with initial pages $E_1^{p,n,k-p-n}$ (with the notation of [(1.4.12)](1.4-hypercohomology-of-filtered-complexes.qmd#ii-1.4.12)) the initial pages of the spectral sequence in (iii).
\oldpage{39}
Since ${}_Wd_1$ is strictly compatible with the filtration $F$ which is the abutment of this spectral sequence [(3.2.7)](#ii-3.2.7), and is [(1.4.12)](1.4-hypercohomology-of-filtered-complexes.qmd#ii-1.4.12) the abutment of a morphism between these spectral sequences, which starts with the differentials from (iii), we have
$$
  \Gr_F^p({}_WE_2^{n,k-n})
  \approx \HH^\bullet(E_1^{p,n-1,k-n-p} \to E_1^{p,n,k-n-p} \to E_1^{p,n+1,k-n-p})
$$
and $\Gr_F^\bullet({}_WE_2^{\bullet\bullet})$ is the sum of the pages $E_2^{\bullet\bullet\bullet}$ of the spectral sequences in (iii).
We thus have
$$
  \sum_n \dim \HH^n(X,\CC)
  = \sum \dim E_2^{\bullet\bullet\bullet}.
\tag{3.2.13.1}
$$
We also have
$$
  \sum_n \dim \HH^n(X,\CC)
  \leqslant \dim {}_FE_1^{\bullet\bullet}
$$
with equality if and only if the spectral sequence in (ii) degenerates at $E_1$, and
$$
  \sum \dim {}_FE_1^{\bullet\bullet}
  \leqslant \sum \dim E_2^{\bullet\bullet\bullet}
$$
with equality if and only if the spectral sequences in (iii) degenerate at $E_2$.
Comparing with [(3.2.13.1)](#ii-3.2.13), we obtain [(3.2.13)](#ii-3.2.13).
:::

::: {.itenv #env-ii-3.2.14 number="3.2.14" taxon="Corollary"}
Let $\omega$ be a meromorphic differential $p$-form on $\overline{X}$ that is holomorphic on $X$ and presents at worst logarithmic poles along $Y$.
Then the restriction $\omega|X$ of $\omega$ to $X$ is closed, and if the cohomology class in $\HH^p(X,\CC)$ defined by $\omega$ is zero then $\omega=0$.
:::

::: {.proof}
This is the particular case of (ii) of [(3.2.13)](#ii-3.2.13) where ${}_FE_1^{p0}={}_FE_\infty^{p0}$.
:::

::: {.itenv #env-ii-3.2.15 number="3.2.15" taxon="Corollary"}
—

i. If $X$ is a smooth complete algebraic variety, then the mixed Hodge structure on $\HH^n(X,\ZZ)$ is the classical Hodge structure of weight $n$.
ii. The Hodge numbers $h^{pq}$ of the mixed Hodge structure of $\HH^n(X,\ZZ)$ (with $X$ algebraic and smooth) can only be zero for $p\leqslant n$, $q\leqslant n$, and $p+q\geqslant n$
:::

::: {.proof}
Claim (i) is clear;
to prove (ii), note that, if $Y$ is the union of smooth divisors, then the rational Hodge structure $\Gr_k^W(\HH^n(X,\QQ))$ is the quotient of a sub-object of a Hodge structure of weight $n+k$, namely
$$
  \HH^{n-k}(\widetilde{Y}^n,\QQ)\otimes\QQ(-k).
$$
:::

::: {.rmenv #env-ii-3.2.16 number="3.2.16"}
Let $X$ be a smooth separated scheme.
We know that $X$ admits smooth compactifications $\overline{X}$ and that the subgroup of $\HH^n(X,\ZZ)$ given by the image of $\HH^n(\overline{X},\ZZ)$ is independent of the choice of $\overline{X}$ (cf. [@G1968, (9.1) to (9.4)]).
:::

::: {.itenv #env-ii-3.2.17 number="3.2.17" taxon="Corollary"}
Under the hypotheses of [(3.2.16)](#ii-3.2.16), the image of $\HH^n(\overline{X},\QQ)$ in $\HH^n(X,\QQ)$ is $W_n(\HH^n(X,\QQ))$ (where $W$ denotes the weight filtration [(3.2.12)](#ii-3.2.12)).
:::

::: {.proof}
We can suppose that $\overline{X}\setminus X$ is a normal crossing divisor.
The claim then follows from the fact that $W[-n]$ is the abutment of the Leray spectral sequence for the inclusion $j\colon X\hookrightarrow\overline{X}$.
:::

::: {.itenv #env-ii-3.2.18 number="3.2.18" taxon="Corollary"}
Let $f$ be a morphism from a smooth proper scheme $Y$ to a smooth scheme $X$, with $X$ admitting a smooth compactification $j\colon X\hookrightarrow\overline{X}$.
Then the groups $\HH^n(X,\QQ)$ and $\HH^n(\overline{X},\QQ)$ have the same image in $\HH^n(Y,\QQ)$.
:::

::: {.proof}
Since $f^*$ and $(jf)^*$ are strictly compatible with the weight filtration ((iii) of [(3.2.5)](#ii-3.2.5)), it suffices to prove that $\Gr^W(f^*)$ and $\Gr^W(f^*j^*)$ have the same image in $\Gr^W(\HH^n(Y,\QQ))$.
\oldpage{40}
By [(3.2.17)](#ii-3.2.17) and [(3.2.15)](#ii-3.2.15), $\Gr_n^W(j^*)$ is an isomorphism, while $\Gr_m^W(f^*)=0$ for $m\neq n$ since $\Gr_m^W(\HH^n(Y,\QQ))=0$ for $m\neq n$.
:::

::: {.rmenv #env-ii-3.2.19 number="3.2.19" taxon="Remark"}
By [(3.1.11)](3.1-logarithmic-poles-and-residues.qmd#ii-3.1.11) and [(1.4.5)](1.4-hypercohomology-of-filtered-complexes.qmd#ii-1.4.5), under the hypotheses of [(3.2.5)](#ii-3.2.5), the Hodge filtration on $\HH^n(X,\CC)$ is the abutment of the hypercohomology spectral sequence of the complex $j_*^m\Omega_{X^*}^\bullet$ endowed with the filtration given by the pole-order filtration [(3.1.10)](3.1-logarithmic-poles-and-residues.qmd#ii-3.1.10): this spectral sequence coincides with [(3.2.4.2)](#ii-3.2.4).
:::
