project:
  output-dir: _output

# Nice things to have
repo-url: https://github.com/thosgood/translations
favicon: "_favicon.ico"

# Page structure
toc: true
number-sections: true

# Citations
nocite: '@*'
link-citations: true
csl: _maths-translations.csl
reference-section-title: "Bibliography"

format:
  html:
    # General
    html-math-method: katex
    self-contained: true
    date-format: "YYYY"
    css:
      - _environments.css
    # ToC and links
    other-links:
      - text: Source files
        href: https://github.com/thosgood/translations
        icon: github
      - text: More translations
        href: https://thosgood.net/translations
        icon: collection
    # Visual things
    title-block-banner: true
    classoption: fleqn
    theme:
      light: [journal, _custom.scss]
      dark: [darkly, _custom.scss]
  pdf:
    template: _template.tex
    date-format: "YYYY"
    cite-method: biblatex
    biblatexoptions: [backend=biber]
    pdf-engine: pdflatex
