project:
  output-dir: _output

# Nice things to have
repo-url: https://github.com/thosgood/translations
favicon: "_favicon.ico"

# Page structure
toc: true
number-sections: true

# Citations
nocite: '@*'
link-citations: true
csl: _maths-translations.csl
reference-section-title: "Bibliography"

# Filters
filters:
  - diagram
  - _filters.lua

diagram:
  cache: true
  cache-dir: ./tikz-cache
  engine:
    tikz:
      execpath: lualatex
      header-includes:
        - '\usepackage{tikz-cd}'

# Formats
format:
  html:
    ## General
    html-math-method: katex
    embed-resources: true
    date-format: "YYYY"
    lang: en-GB
    css:
      - _environments.css
    ## ToC and links
    other-links:
      - text: Source files
        href: https://github.com/thosgood/translations
        icon: github
      - text: More translations
        href: https://thosgood.net/translations
        icon: collection
    ## Visual things
    title-block-banner: true
    theme:
      light: [flatly, _custom.scss]
      dark: [darkly, _custom.scss]
    callout-appearance: simple
  pdf:
    template: _template.tex
    pdf-engine: latexmk
    cite-method: biblatex
    biblatexoptions: [backend=biber]
    date-format: "YYYY"
    keep-tex: true
