--- 
title: "The dualising complex and duality theorems in complex analytic geometry"
author: "Jean-Pierre Ramis, Gabriel Ruget"
date: "1970"
original: |
  J.-P. Ramis, G. Ruget.
  "Complexe dualisant et théorèmes de dualité en géométrie analytique complexe".
  _Publications mathématiques de l'I.H.É.S._ (1970) pp. 77--91.
  [numdam.org/item?id=PMIHES_1970__38__77_0](http://www.numdam.org/item?id=PMIHES_1970__38__77_0)
bibliography: PMIHES-38-1970-77.bib
---

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\newcommand{\sh}[1]{\scr{#1}}
\newcommand{\cat}[1]{\mathbf{#1}}

\newcommand{\OO}{\sh{O}}

\newcommand{\HH}{\mathrm{H}}
\newcommand{\cc}{\mathrm{c}}
\newcommand{\FS}{\mathbf{FS}}
\newcommand{\DFS}{\mathbf{DFS}}
\newcommand{\QFS}{\mathbf{QFS}}
\newcommand{\QDFS}{\mathbf{QDFS}}
\newcommand{\KK}{\mathbf{K}}
\newcommand{\TT}{\mathbf{T}}

\newcommand{\Hom}{\operatorname{Hom}}
\newcommand{\shHom}{\underline{\Hom}}
\newcommand{\Ext}{\operatorname{Ext}}
\newcommand{\shExt}{\underline{\Ext}}
\newcommand{\HyperExt}{\operatorname{HyperExt}}
\renewcommand{\Im}{\operatorname{Im}}
\newcommand{\Ker}{\operatorname{Ker}}

<!-- Content -->

\oldpage{77}

Let $X$ be a $\sigma$-compact complex analytic manifold of dimension $n$;
we write $\OO$ to mean the sheaf of germs of holomorphic functions on $X$, and $\Omega$ to mean the sheaf of germs of holomorphic differential forms of degree $n$ on $X$.
The correspondence that, to a locally free $\OO$-module $\sh{F}$, associates $\shHom(X;\sh{F},\Omega)$, is involutive.
In [@11], Serre gives, for every integer $p$ and every locally free $\OO$-module $\sh{F}$, a (Fréchet quotient) topology on $\HH^p(X;\sh{F})$ along with a pairing
$$
  \HH^p(X;\sh{F}) \times \HH_\cc^{n-p}(X;\shHom(X;\sh{F},\Omega))
  \to \mathbb{C}
$$
(where the subscript $\cc$ denotes the family of compacts of $X$) which, whenever the groups $\HH^p(X;\sh{F})$ and $\HH^{p+1}(X;\sh{F})$ are separated, makes the (non-topologised) vector space $\HH_\cc^{n-p}(X;\shHom(X;\sh{F},\Omega))$ the topological dual of $\HH^p(X;\sh{F})$.

We could also mention the pairing
$$
  \HH_\cc^p(X;\sh{F}) \times \HH^{n-p}(X;\shHom(X;\sh{F},\Omega))
  \to\mathbb{C}.
$$

Up to replacing $\HH_\cc^{n-p}(X;\shHom(X;\sh{F},\Omega))$ by $\Ext_\cc^{n-p}(X;\sh{F},\Omega)$, the proof by Serre extends [@10] to the case where $\sh{F}$ is an arbitrary coherent $\OO$-module, but by using difficult theorems (with the notation of Schwartz: $\sh{E}$ is a flat $\OO$-module, and, for every $x\in X$, $\sh{D}'_x$ is an injective $\OO_x$-module), due to coming from the division of distributions.
We will show, following ideas of Grothendieck that were readopted by Malgrange, that the duality theorem for coherent sheaves on an analytic manifold is formally much more simple than this (see also [@14]), and that it can be generalised to analytic spaces, as long as we replace $\Omega$ by a suitable "dualising" complex, and the $\Ext$ by $\HyperExt$.
As future work, probably very soon to appear, we note (not to mention an article in preparation with J.-L. Verdier on a relative duality theorem) that Malgrange expects to be able to use the dualising complex to give new proofs of results of Siu [@13] and Andreotti--Grauert [@1].


# Some lemmas on certain complexes of topological vector spaces {#section-1}

We first clarify a point of vocabulary for those readers not familiar with derived categories [@7]: let $\cat{A}$ be an abelian category, and $C(\cat{A})$ the category of bounded-below complexes of objects of $\cat{A}$ (with differentials of degree $+1$ and morphisms of degree $0$).
\oldpage{78}
We define $T$ to be the automorphism of $C(\cat{A})$ that translates complexes one notch to the left and changes the sign of all the differentials.
An object of $C(\cat{A})$ is said to be *acyclic* if all its cohomology objects are zero.
Let $u\colon X^\bullet\to Y^\bullet$ be a morphism in $C(\cat{A})$;
we say that it is a *quasi-isomorphism* if it induces an isomorphism of cohomology objects of $X^\bullet$ to those of $Y^\bullet$;
in this case, we also say that $\xrightarrow{u}Y^\bullet$ is a *resolution* of $X^\bullet$.
We define the *cylinder* of $u$ to be the complex $T(X^\bullet)\oplus Y^\bullet$ endowed with the differential $\left(\begin{smallmatrix}T(d_X)&0\\T(u)&d_Y\end{smallmatrix}\right)$.
Saying that $u$ is a quasi-isomorphism is equivalent to saying that its cylinder is zero.

We denote by the acronym $\FS$ (resp. $\DFS$) Fréchet--Schwartz spaces (resp. the strong duals of Fréchet--Schwartz spaces [@6]), and by the acronym $\QFS$ (resp. $\QDFS$) the quotients of $\FS$ spaces (resp. of $\DFS$ spaces) (which are, as it were, non-separated $\FS$ or $\DFS$ spaces).

::: {.itenv #lemma-1 title="Lemma 1" latex="{Lemma 1}"}
Let $X^\bullet$ and $Y^\bullet$ be complexes of Fréchet spaces (with continuous linear differentials) and $u\colon X^\bullet\to Y^\bullet$ a (continuos linear) morphism.
If $u$ is a quasi-isomorphism (in the purely algebraic sense) then it is a topological quasi-isomorphism, i.e. it induces isomorphisms between the cohomology spaces of $X^\bullet$ and of $Y^\bullet$, where these spaces are endowed with their natural topologies (which are not necessarily separated).
:::

::: {.proof}
If $H^i$ and $K^i$ denote the cohomology spaces of $X^\bullet$ and $Y^\bullet$ (respectively), then it suffices to show that $u$ sends the closure of $0$ in $H^i$ to the closure of $0$ in $K^i$.
Let $M^i$ and $N^i$ be the spaces of cycles of degree $i$ of $X^\bullet$ and $Y^\bullet$ (respectively);
these are Fréchet spaces;
thus, the map $d_Y+u$ from $Y^{i-1}\oplus M^i$ to $N^i$, which is surjective, is a homomorphism.
Since the closed $Y^{i-1}+\overline{d_X(X^{i-1})}$ is saturated with respect to the "projection" $d_Y+u$, its image is closed in $N^i$, and is thus $\overline{d_Y(Y^{i-1})}$, which implies the desired property when we pass to cohomology groups.
:::

::: {.itenv #lemma-1-bis title="Lemma 1 bis" latex="{Lemma 1 bis}"}
[Lemma 1](#lemma-1) remains true if we suppose that both $X^\bullet$ and $Y^\bullet$ are not Fréchet complexes, but complexes of $\DFS$ spaces.
:::

::: {.proof}
This comes from "permanence" properties of $\DFS$ spaces, and the closed graph theorem for these spaces [@15].
:::

::: {.itenv #lemma-2 title="Lemma 2" latex="{Lemma 2}"}
Let $E\xrightarrow{u}F\xrightarrow{v}G$ be a sequence of $\FS$ spaces and continuous linear maps, such that $v\circ u=0$;
let $E'\xleftarrow{u'}F'\xleftarrow{v'}G'$ be the transpose sequence (with the duals being endowed with the strong topology).
Then the pairing between $F$ and $F'$ induces a pairing between $\Ker{v}/\overline{\Im{u}}$ and $\Ker{u'}/\overline{\Im{v'}}$, which makes each of these spaces (endowed with their natural topology) the strong dual of one another.
:::

::: {.proof}
The natural map from $\Ker{u'}/\overline{\Im{v'}}$ to $(\Ker{v}/\overline{\Im u})'$ is surjective by Hahn--Banach, injective thanks to the semi-reflexivity of $F$, and continuous since $a$ is hypocontinuous with respect to the bounded subsets of $\Ker{v}/\overline{\Im{u}}$ (to see this, it suffices to know how to lift a bounded, i.e. a relatively compact, of $\Ker{v}/\overline{\Im{u}}$ to a bounded of $\Ker{v}$);
it is thus bicontinuous.
\oldpage{79}
Since $\Ker{v}/\overline{\Im{u}}$, being an $\FS$ space, is reflexive, we have thus proven the claim.
:::

::: {.itenv #lemma-3 title="Lemma 3" latex="{Lemma 3}"}
Let $X^\bullet$ and $Y^\bullet$ be complexes of $\FS$ spaces (or even of $\DFS$ spaces), and $u\colon X^\bullet\to Y^\bullet$ a quasi-isomorphism.
Then the transpose $u'$ of $u$ is a quasi-isomorphism.
:::

::: {.proof}
The cylinder of $u$ is acyclic;
it is thus a complex whose differentials are operators with closed image;
the transpose complex, which is the cylinder of $u'$, also has differentials with closed image, and, by [Lemma 2](#lemma-2), is acyclic.
:::

Finally, we give a lemma that allows us to cheaply ensure that the topologies on pairs of spaces in duality coincide:

::: {.itenv #lemma-4 title="Lemma 4" latex="{Lemma 4}"}
Let $P$ and $Q$ be $\QFS$ spaces, and $R$ and $S$ be $\QDFS$ spaces;
let $a$ be a pairing between $P$ and $R$ that puts the associated separated spaces in duality, and let $b$ be a pairing of the same sort between $Q$ and $S$;
let $u\colon P\to Q$ and $v\colon S\to R$ be linear maps;
all such that $u$ and $v$ are transpose to one another with respect to $a$ and $b$.
Then $u$ and $v$ are continuous.
:::

::: {.proof}
Since the closure of $\{0\}$ in $P$ (resp. in $S$) is orthogonal to $R$ (resp. to $Q$), we see that $u\overline{\{0_P\}}\subset\overline{\{0_Q\}}$ and $v\overline{\{0_S\}}\subset\overline{\{0_R\}}$.
The maps $u$ and $v$ thus induce transpose maps $\hat{u}$ and $\hat{v}$ between the separated spaces associated to $P$, $Q$, $R$, and $S$.
Since $\hat{u}$ is a transpose, it is weakly continuous, and so its graph is closed;
it is thus strongly continuous, as is $\hat{v}$, and the continuity of $u$ and $v$ then follow.
:::


# Trace. Elementary duality theorem {#section-2}

We use the notations $X$, $\OO$, and $\Omega$ from the introduction.
As a topological manifold, $X$ is canonically oriented, and Poincaré duality gives us a canonical linear form on $\HH_\cc^{2n}(X;\mathbb{C})$.
This form, pre-composed with the composition product of the $\Ext$ (thinking of the $\Ext$ as sheaves of $\mathbb{C}$-spaces), gives a pairing:
$$
  \HH_\cc^n(X;\Omega) \times \Ext_\cc^n(X;\Omega,\mathbb{C})
\to \mathbb{C}.
$$
The complex structure of $X$ now gives us (thinking of the $\Ext$ in terms of their Yoneda interpretation) a remarkable $n$-extension of $\Omega$ by $\mathbb{C}$, namely:
$$
  0 \to \mathbb{C} \to \OO \xrightarrow{d'} \Omega^1 \xrightarrow{d'} \ldots \xrightarrow{d'} \Omega \to 0
$$
where $\Omega^i$ denotes the sheaf of holomorphic differential forms of degree $i$ on $X$.
The linear form on $\HH_\cc^n(X;\Omega)$ associated to this extension is called the *trace*.
The trace also arises in the following way: the complex
$$
  0 \to {\sh{D}'}^{n,0} \xrightarrow{d''} \ldots \xrightarrow{d''} {\sh{D}'}^{n,n} \to 0
\tag{1}
$$
where ${\sh{D}'}^{i,j}$ denotes the sheaf of germs of differential forms on $X$ of type $(i,j)$ with distribution coefficients, is a fine resolution of $\Omega$.
The group $\HH_\cc^n(X;\Omega)$ is thus the $(n+1)$-th cohomology group of the complex of $\DFS$ spaces
\oldpage{80}
$$
  0 \to {\sh{E}'}^{n,0}(X) \xrightarrow{d''} \ldots \xrightarrow{d''} {\sh{E}'}^{n,n}(X) \to 0.
\tag{2}
$$
It is thus naturally endowed with the structure of a $\QDFS$ space, and we see that integration on $X$ of forms of type $(n,n)$ with compact support induces a continuous linear form on $\HH_\cc^n(X,\Omega)$, and this form is precisely $(-1)^n$ times the trace.
(Given a global section $s$ with compact support of ${\sh{D}'}^{n,n}$, we obtain [@4] an $n$-extension $\overline{s}$, in the sense of Yoneda, of $\mathbb{C}$ by $\Omega$. Pre-composed with the $d'$-cohomology complex, this complex gives the extension $(-1)^{n^2}\omega\times\overline{s}\in\Ext_{\cc,\mathbb{C}}^{2n}(X;\mathbb{C},\mathbb{C})$; but we note that this is also "equivalent" to the $2n$-extension of $\mathbb{C}$ by $\mathbb{C}$ associated to the de Rham complex $$0\to\mathbb{C}\to\sh{D}'_0\to\sh{D}'_1\to\ldots\to\sh{D}'_{2n}\to0$$ and to the global section $s$ of $\sh{D}'_{2n}={\sh{D}'}^{n,n}$. Since Poincaré duality is given by integration, our claim is proved.)

Now let $\sh{F}$ be an arbitrary $\OO$-module.
The composition product of the $\Ext$ (of $\OO$-modules), followed by the trace, gives us the pairings
$$
  \HH^p(X;\sh{F}) \times \Ext_\cc^{n-p}(X;\sh{F},\Omega)
  \to \mathbb{C}
\tag{3}
$$
and
$$
  \HH_\cc^p(X;\sh{F}) \times \Ext^{n-p}(X;\sh{F},\Omega)
  \to \mathbb{C}.
\tag{3~bis}
$$

::: {.itenv #lemma-5 title="Lemma 5" latex="{Lemma 5}"}
If $X$ is a Stein manifold, then $\HH_\cc^i(X;\Omega)$ is zero for $i\neq n$;
$\HH_\cc^n(X;\Omega)$ is separated, and the pairing (3) puts it in duality with $\Gamma(X;\OO)$ (endowed with its usual $\FS$ structure).
:::

::: {.proof}
Denote by $\sh{E}^{i,j}$ the sheaf of germs of differential forms on $X$ of type $(i,j)$ with $C^\infty$ coefficients.
The complex
$$
  0 \to \sh{E}^{0,0} \xrightarrow{d''} \ldots \xrightarrow{d''} \sh{E}^{0,n} \to 0
\tag{1~bis}
$$
is a fine resolution of $\OO$;
thus the groups $\HH^i(X;\OO)$ are the cohomology groups of the complex of $\FS$ spaces
$$
  0 \to \sh{E}^{0,0}(X) \xrightarrow{d''} \ldots \xrightarrow{d''} \sh{E}^{0,n}(X) \to 0
\tag{2~bis}
$$
whereas the $\HH_\cc^i(X;\Omega)$ are the cohomology groups of the transpose complex (2).
The lemma then follows from Theorem B (which implies in particular that all the differentials of (2) and (2 bis) have closed image) and from [Lemma 2](#lemma-2).
:::

::: {.itenv #lemma-5-bis title="Lemma 5 bis" latex="{Lemma 5 bis}"}
If $X$ is a Stein manifold, then $\HH_\cc^i(X;\Omega)$ is zero for $i\neq n$;
the pairing (3 bis) puts $\Gamma(X;\Omega)$ (endowed with its usual $\FS$ structure) and $\HH_\cc^n(X;\OO)$ (endowed with the $\DFS$ structure obtained by considering it as a quotient of ${\sh{E}'}^{0,n}(X)$) in duality.
:::

::: {.itenv #lemma-6 title="Lemma 6" latex="{Lemma 6}"}
If $X$ is a Stein manifold, and if $\sh{F}$ is an $\OO$-module that admits a finite resolution by free $\OO$-modules of finite type, then the groups $\Ext_\cc^i(X;\sh{F},\Omega)$ are zero for $i\neq0$, $\Ext_\cc^n(X;\sh{F},\Omega)$ is endowed with a canonical $\DFS$ structure, and (3) puts it in duality with $\Gamma(X;\sh{F})$.
:::

::: {.proof}
This follows from [Lemma 1 bis](#lemma-1-bis) and [Lemma 2](#lemma-2), by induction on the minimum length of the free resolution of $\sh{F}$.
:::


# The dualising complex: statement of the problem. A first duality theorem {#section-3}

\oldpage{81}
Given a $\sigma$-compact analytic space $X$, of bounded dimension, we want to construct a complex $\KK_X^\bullet$ of $\OO$-modules that is bounded and of coherent cohomology, along with a canonical linear form $\TT_X$ on $\HH_\cc^0(X;\KK_X^\bullet)$ such that the following is true:

::: {.itenv #theorem-1 title="Theorem 1" latex="{Theorem }"}
For every coherent $\OO_X$-module $\sh{F}$ and every integer $p$, there exists on $\HH^p(X;\sh{F})$ a unique $\QFS$ structure and on $\Ext_\cc^{-p}(X;\sh{F},\KK_X^\bullet)$ a unique $\QDFS$ structure such that the form $\TT_X$ induces a perfect pairing between the associated separated spaces.
Furthermore, the separation of $\HH^p(X;\sh{F})$ is equivalent to that of $\Ext_\cc^{n-p}(X;\sh{F},\KK_X^\bullet)$.
:::

If $X$ is smooth and of dimension $n$, then $\KK_X^\bullet$ will be a resolution of $T^n\Omega$, and these topologies and this pairing will be exactly those mentioned in the introduction (modulo, obviously, the substitution of $\Ext_\cc^{-p}(X;\sh{F},T^n\Omega)$ for $\Ext_\cc^{n-p}(X;\sh{F},\Omega)$).

In [§5](#section-5) we will construct:

1. For every manifold $V$, a resolution $\KK_V^\bullet$ of $T^{\dim V}\Omega_V$ such that, for every integer $p$ and every $x\in V$, $\KK_{V,x}^p$ is an injective $\OO_{V,x}$-module.

2. For every embedding $f$ of one manifold $V$ into another manifold $W$, a functorial isomorphism of complexes of $\OO_V$-modules
    $$
      \overline{f}\colon \KK_V^\bullet \xrightarrow{\approx} \shHom(W;f_*\OO_V,\KK_W^\bullet)
    $$
    that is compatible with the traces on $\HH_\cc^{\dim V}(V;\Omega_V)=\HH_\cc^0(V;\KK_V^\bullet)$ and on $\HH_\cc^0(W;\KK_W^\bullet)$.

We will use these complexes $\KK_V^\bullet$ to