--- 
title: "The work of Koszul, III"
author: "Henri Cartan"
date: "May 1949"
original: 'Cartan, H. "Les travaux de Koszul, III". _Séminaire Bourbaki_ **1** (1952), Talk no. 12, pp. 71--74. [numdam.org/book-part/SB_1948-1951__1__71_0](http://www.numdam.org/book-part/SB_1948-1951__1__71_0).'
---

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\llp}{\mathbin{\llcorner}}
\providecommand{\lrp}{\mathbin{\lrcorner}}
\providecommand{\dd}{\mathrm{d}}
\providecommand{\RR}{\mathbb{R}}
\providecommand{\HH}{\operatorname{H}}
\providecommand{\tr}{\operatorname{tr}}

<!-- Content -->

We keep the notation from the previous talk.
However, we now write $\Gamma^*(\frak{a})$ (instead of $\Gamma(\frak{a}')$) to denote the exterior algebra of the dual of $\frak{a}$, which is in duality with $\Gamma(\frak{a})$ (the exterior algebra of $\frak{a}$).
We denote by $\HH^*(\frak{a})$ (instead of $\HH(\frak{a}')$) the _cohomology algebra_ of $\frak{a}$, and by $\HH^p(\frak{a})$ the subspace of homogeneous elements of degree $p$ of $\HH^*(\frak{a})$.
We keep the notation $\HH(\frak{a})$ for the homology _space_ of $\frak{a}$, and $\HH_p(\frak{a})$ for the subspace of elements of degree $p$ of $\HH(\frak{a})$.
If $\frak{a}$ is a _reductive_ Lie algebra, then, as we have seen, $\HH(\frak{a})$ is endowed with a _multiplicative structure_:
we denote by $\HH_*(\frak{a})$ the _homology algebra_ of $\frak{a}$ (i.e. the space $\HH(\frak{a})$ endowed with this multiplicative structure).

Recall that a Lie algebra $\frak{a}$ (over a field $K$) is said to be _reductive_ if the representation $x\mapsto\theta(x)$ of $\frak{a}$ in the endomorphism algebra of the vector space $\Gamma(\frak{a})$ is completely reducible;
such an algebra $\frak{a}$ is the direct sum of a semi-simple Lie algebra and an abelian algebra, and the converse is true if $K$ is of _characteristic $0$_.
More generally, let $\frak{b}$ be a sub-algebra of a Lie algebra $\frak{a}$;
we say that $\frak{b}$ is _reductive in $\frak{a}$_ if the representation $x\mapsto\theta(x)$ of $\frak{b}$ in the endomorphism algebra of $\Gamma(\frak{a})$ is completely reducible;
the $\frak{b}$ is also reductive (i.e. reductive in itself).

If $\frak{a}$ is a Lie algebra of a _compact_ group (an algebra over the field of reals), then every sub-algebra of $\frak{a}$ is reductive in $\frak{a}$.


# Relative chains and cochains {#III.1}

Let $\frak{b}$ be a sub-algebra of a Lie algebra $\frak{a}$;
this gives a bijective homomorphism $\varphi\colon\Gamma(\frak{b})\to\Gamma(\frak{a})$, and its transpose $\varphi^*\colon\Gamma^*(\frak{a})\to\Gamma^*(\frak{b})$ (which is _onto_).
A subspace of $\Gamma(\frak{a})$ (resp. of $\Gamma^*(\frak{a})$) is said to be _$\frak{b}-stable$_ if it is stable under the endomorphisms $\theta(x)$ (resp. $\theta^*(x)$) for all $x\in\frak{b}$.
We denote by $I(\frak{a},\frak{b})$ the subspace of chains of $\frak{a}$ that are _invariant under $\frak{b}$_, that is, the $\alpha\in\Gamma(\frak{a})$ such that $\theta(x)\cdot\alpha=0$ for all $x\in\frak{b}$.
There is the analogous definition of the subspace $I^*(\frak{a},\frak{b})$ of $\frak{b}$-invariant cochains of $\frak{a}$.

\oldpage{72}
Let $N(\frak{a},\frak{b})$ be the ideal of $\Gamma(\frak{a})$ generated by $\varphi(\frak{b})$;
the subspace of $\Gamma^*(\frak{a})$ that is orthogonal to $N(\frak{a},\frak{b})$ is the _sub-algebra_ $N^(\frak{a},\frak{b})$ generated by the unit and the degree $1$ cochains that are orthogonal to $\frak{b}$.
We write $N^p(\frak{a},\frak{b})$ to mean the subspace of degree $p$ elements of $N^*(\frak{a},\frak{b})$.
The subspaces $N(\frak{a},\frak{b})$ and $N^*(\frak{a},\frak{b})$ are $\frak{b}$-stable.

We first study the particular case where $\frak{b}$ is an _invariant_ sub-algebra (an ideal of the Lie algebra $\frak{a}$), that is, the case where $\frak{b}$ is $\frak{a}$-stable, in which case we have the Lie algebra $\frak{a}/\frak{b}$.
Then $N(\frak{a},\frak{b})$ is _stable under $\partial$_, and $\Gamma(\frak{a})/N(\frak{a},\frak{b})$, endowed with the operator induced by $\partial$ by passing to the quotient, can be identified with $\Gamma(\frak{a}/\frak{b})$;
by duality, $N^(\frak{a},\frak{b})$ endowed with $\delta$ (under which it is stable) can be identified with $\Gamma^*(\frak{a}/\frak{b})$, and is contained inside $I^*(\frak{a},\frak{b})$.

In the general case of an arbitrary sub-algebra $\frak{b}$, the subspace $N(\frak{a},\frak{b})+\partial N(\frak{a},\frak{b})$ is stable under $\partial$, and is generated by $N(\frak{a},\frak{b})$ and by the $\theta(x)\cdot\alpha$ (where $\alpha\in\Gamma(\frak{a})$ and $x\in\frak{b}$);
then $\partial$ acts on the quotient $L(\frak{a},\frak{b})$ of $\Gamma(\frak{a})$ by $N(\frak{a},\frak{b})+\partial N(\frak{a},\frak{b})$, and we call this quotient the _space of relative chains_.
By duality, the intersection $N^*(\frak{a},\frak{b})\cap I^*(\frak{a},\frak{b}) = L^*(\frak{a},\frak{b})$ consists of the cochains $\alpha'$ of $N^*(\frak{a},\frak{b})$ such that $\delta\alpha'\in N^*(\frak{a},\frak{b})$;
this is a _sub-algebra_ of $\Gamma^*(\frak{a})$, called the _algebra of relative cochains_.

Endowing $L(\frak{a},\frak{b})$ with $\partial$ defines a _relative homology space_, denoted by $\HH(\frak{a},\frak{b})$;
it is graded.
The algebra $L^*(\frak{a},\frak{b})$ endowed with $\delta$ defines a _relative cohomology algebra_, denoted by $\HH^*(\frak{a},\frak{b})$;
this is a graded algebra.
In the particular case where $\frak{b}$ is an invariant sub-algebra of $\frak{a}$, we can identify $\HH(\frak{a},\frak{b})$ (resp. $\HH^*(\frak{a},\frak{b})$) with $\HH(\frak{a}/\frak{b})$ (resp. $\HH^*(\frak{a}/\frak{b})$).

In the case where $\frak{a}$ is the Lie algebra of a _compact connected group_ $G$, and $\frak{b}$ is the sub-algebra of a _closed subgroup_ $U$, then $L^*(\frak{a},\frak{b})$ can be identified with the algebra of exterior differential forms of the _homogeneous space_ $W=G/U$ that are invariant under $G$, and $H^*(\frak{a},\frak{b})$ is then the cohomology algebra of the (compact) topological space $W$.
The following results (some of which are new) explain the relations between the cohomology algebras of the spaces $G$, $U$, and $W=G/U$.
We note that $G$ is the fibre bundle with fibre $U$ and base $W$.


# Canonical homomorphisms {#III.2}

We have
$$
  \begin{gathered}
    \Gamma(\frak{b}) \xrightarrow{\varphi} \Gamma(\frak{a}) \xrightarrow{\pi} L(\frak{a},\frak{b})
  \\L^*(\frak{a},\frak{b}) \xrightarrow{\pi^*} \Gamma^*(\frak{a}) \xrightarrow{\varphi^*} \Gamma^*(\frak{b}).
  \end{gathered}
$$
These define
\oldpage{73}
$$
  \begin{gathered}
    \HH(\frak{b}) \xrightarrow{\widetilde{\varphi}} \HH(\frak{a}) \xrightarrow{\widetilde{\pi}} \HH(\frak{a},\frak{b})
  \\\HH^*(\frak{a},\frak{b}) \xrightarrow{\widetilde{\pi}^*} \HH^*(\frak{a}) \xrightarrow{\widetilde{\varphi}^*} \HH^*(\frak{b}).
  \end{gathered}
$$
The homomorphisms $\pi^*$, $\varphi^*$, $\widetilde{\pi}^*$, and $\widetilde{\varphi}^*$ are _algebra homomorphisms_.
The image of $\widetilde{\varphi}$ is contained inside the kernel of $\widetilde{\pi}$;
the image of $\widetilde{\varphi}^*$ is contained inside the kernel of $\widetilde{\pi}^*$.

If $\frak{a}$ is a _reductive_ algebra, then the kernel of $\HH(\frak{a})\to\HH(\frak{a},\frak{b})$ is a two-sided _ideal_ of the _algebra_ $\HH_*(\frak{a})$.
If, furthermore, $K$ is of characteristic $0$, then the Hopf theorem applies to $\HH^*(\frak{a})$, which can be identified with the exterior algebra of the subspace of its _primitive_ elements;
then the image of $\HH^*(\frak{a},\frak{b})\to\HH^*(\frak{a})$ is a sub-algebra of $\HH^*(\frak{a})$ that is _generated by the unit and by the primitive elements of $\HH^*(\frak{a})$_.

If $\frak{b}$ is a _reductive sub-algebra of $\frak{a}$_, then we have a homology algebra $\HH_*(\frak{b})$, and the kernel of $\HH(\frak{b})\to\HH(\frak{a})$ is a two-sided _ideal_ of $\HH_*(\frak{b})$.
If, furthermore, $K$ is of characteristic $0$, then the image of $\HH^*(\frak{a})\to\HH^*(\frak{b})$ is a sub-algebra of $\HH^*(\frak{b})$ that is _generated by the unit and by the primitive elements of $\HH^*(\frak{b})$_.


# Poincaré duality for relative homology and cohomology {#III.3}

Let $n$ (resp. $m$) be the dimension of $\frak{a}$ (resp. $\frak{b}$).
Let $\omega$ be the image in $\Gamma(\frak{a})$ of the $m$-dimensional chain of $\Gamma(\frak{b})$ (defined up to a constant factor).
Then $N(\frak{a},\frak{b})$ is the kernel of the endomorphism $\alpha\mapsto\omega\wedge\alpha$ of $\Gamma(\frak{a})$.
Let $\tau\in\Gamma^{n-m}(\frak{a})$ be such that $\omega\wedge\tau\neq0$;
then, in $\Gamma(\frak{a})/N(\frak{a},\frak{b})$, every element of degree $>(n-m)$ is zero, and the elements of degree $(n-m)$ are proportional to the class $\dot{\tau}$ of $\tau$.
So $\alpha'\mapsto i(\alpha')\cdot\tau$ defines an _isomorphism_ from $N^*(\frak{a},\frak{b})$ _onto_ $\Gamma(\frak{a})/N(\frak{a},\frak{b})$ which depends only on $\dot{\tau}$.

From now on, suppose that $\frak{a}$ and $\frak{b}$ are _unimodular_;
then $\dot{\tau}$ is a $\frak{b}$-invariant element of $\Gamma(\frak{a})/N(\frak{a},\frak{b})$, and so $\alpha'\mapsto i(\alpha')\cdot\lambda$ defines an isomorphism from $N^*(\frak{a},\frak{b})\cap I^*(\frak{a},\frak{b}) = L^*(\frak{a},\frak{b})$ onto the subspace of $\frak{b}$-invariant elements of $\Gamma(\frak{a})/N(\frak{a},\frak{b})$.

If, furthermore, $\frak{b}$ is _reductive in $\frak{a}$_, then this subspace can be identified with $L(\frak{a},\frak{b}) = \Gamma(\frak{a})/N(\frak{a},\frak{b})+\partial N(\frak{a},\frak{b})$.
This gives an isomorphism $f$ from $L^*(\frak{a},\frak{b})$ onto $L(\frak{a},\frak{b})$.
Furthermore,
$$
  \partial i(\alpha')\cdot\tau
  = i(\delta\overline{\alpha}')\cdot\tau + i(\overline{\alpha}')\cdot\partial\tau.
$$
But the fact that $\frak{b}$ is reductive in $\frak{a}$ implies that $\partial\tau\in N+\partial N$, and since $i(\overline{\alpha}')\cdot(N+\partial N)\subset N+\partial N$, we have that $\partial f(\alpha')=f(\delta\overline{\alpha}')$.
By passing to quotients, $f$ thus defines an _isomorphism from $\HH(\frak{a},\frak{b})$ onto $\HH^*(\frak{a},\frak{b})$_ that sends degree $p$ elements to degree $(n-m-p)$ elements.
\oldpage{74}
We thus deduce that the "relative" Betti numbers are equal for dimensions $p$ and $(n-m-p)$ ("Poincaré duality"), and that _every non-zero ideal of $\HH^*(\frak{a},\frak{b})$ contains $\HH^{n-m}(\frak{a},\frak{b})$_.


# Sub-algebras that are not homologous to zero {#III.4}

From now on, we also suppose that the sub-algebra $\frak{b}$ of $\frak{a}$ is _reductive in $\frak{a}$_.
Let $m$ be the dimension of $\frak{b}$.

For $\HH(\frak{b})\xrightarrow{\widetilde{\varphi}}\HH(\frak{a})$ to be _bijective_, it _suffices_ for $\HH_m(\frak{b})$ (which consists of multiples of a single element) to not be contained in the kernel of $\widetilde{\varphi}$ (since every two-sided ideal of $\HH_*(\frak{b})$ that does not contain $\HH_m(\frak{b})$ is zero).
We then say that $\frak{b}$ is _not homologous to zero in $\frak{a}$_.

If $\frak{b}$ is not homologous to zero in $\frak{a}$, then $\HH^*(\frak{a},\frak{b})\to\HH^*(\frak{a})$ is _bijective_ (and the converse is also true).
So, if $\frak{a}$ is further assumed to be reductive, and the base field to be of characteristic $0$, then $\HH^*(\frak{a},\frak{b})$ has a subspace whose homogeneous components are of _odd degree_, and that can be identified with the _exterior algebra of this subspace_.

If $\frak{b}$ is not homologous to zero in $\frak{a}$, then $\HH^*(\frak{a})\to\HH^*(\frak{b})$ is evidently _onto_.
If, furthermore, the field is of characteristic $0$, then we can define an isomorphism from the algebra $\HH^*(\frak{b})$ to the algebra $\HH^*(\frak{a})$, such that, by composing with the canonical map $\HH^*(\frak{a})\to\HH^*(\frak{b})$, we obtain the identity automorphism of $\HH^*(\frak{b})$.
This map $\HH^*(\frak{b})\to\HH^*(\frak{a})$, along with the canonical map $\HH^*(\frak{a},\frak{b})\to\HH^*(\frak{a})$, define a _homomorphism of (graded) algebras_
$$
  \HH^*(\frak{b})\otimes\HH^*(\frak{a},\frak{b}) \to \HH^*(\frak{a}),
$$
and we can show that this is an _onto isomorphism_ ("Samelson's theorem").

The case of _sub-algebras that are homologous to zero_ will not be examined here (see instead the Koszul's thesis: _Bull. Soc. Math. France_ **78** (1950), 65--127).
