project:
  type: book
  output-dir: _output
  preview:
    port: 4242
    browser: false

book:
  title: "Deligne's Hodge Theory I, II, and III"
  page-footer: "[thosgood.net/translations](https://thosgood.net/translations)"
  # GitHub links in table of contents #
  repo-url: https://github.com/thosgood/translations
  repo-subdir: hodge-theory
  repo-actions: ["source", "issue"]
  page-navigation: true
  search: true
  sidebar:
    style: docked
  chapters:
    - text: "*About this translation*"
      href: index.qmd
    - text: "---"
    - hodge-theory-i/index.qmd
    - text: "---"
    - hodge-theory-ii/index.qmd
    - part: "1. Filtrations"
      chapters:
        - hodge-theory-ii/1.1-filtered-objects.qmd
        - hodge-theory-ii/1.2-opposite-filtrations.qmd
        - hodge-theory-ii/1.3-the-two-filtrations-lemma.qmd
    - part: "2. Hodge structures"
    - part: "3.Hodge theory of non-singular algebraic varieties"
    - part: "4. Applications and supplements"
    - text: "---"
    - hodge-theory-iii/index.qmd
    - part: "5. Cohomological descent"
      chapters:
      - hodge-theory-iii/5.1-simplicial-topological-spaces.qmd
      - hodge-theory-iii/5.2-cohomology-of-simplicial-topological-spaces.qmd
    - part: "6. Examples of simplicial topological spaces"
    - part: "7. Supplements to §1"
    - part: "8. Hodge theory of algebraic spaces"
    - part: "9. Examples and applications"
    - part: "10. Hodge theory in level ≤1"

format:
  # latex:
  #   documentclass: report
  html:
    lang: en-GB
    date-format: "YYYY"
    # Style #
    theme:
      light: [flatly, _quarto/custom.scss]
      dark: [darkly, _quarto/custom.scss]
    css:
      - _quarto/CrimsonPro/fonts.css
    callout-appearance: simple
    anchor-sections: false
    classoption: fleqn
    # Page layout and structure #
    grid:
      sidebar-width: 350px
    toc: false
    number-sections: false
    # Rendering and assets/resources #
    html-math-method: katex
    embed-resources: true
    # Citations #
    link-citations: true
    reference-section-title: "Bibliography"
    bibliography: hodge-theory.bib

# Filters #
filters:
  - _quarto/callouts.lua
  - _quarto/tikz.lua
