--- 
title: "Local analytic geometry, II. Theory of finite morphisms"
author: "Christian Houzel"
date: "June 1961"
original: 'Houzel, C. "Géométrie analytique locale, II. Théorie des morphismes finis". _Séminaire Henri Cartan_ **13 (2)** (1960--61), Talk no. 19. [numdam.org/item/SHC_1960-1961__13_2_A6_0](https://www.numdam.org/item/SHC_1960-1961__13_2_A6_0)'
bibliography: SHC-13_2-19.bib
---

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}
\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

<!-- Shortcuts -->

\providecommand{\Cat}[1]{\mathsf{#1}}

\providecommand{\sh}[1]{\scr{#1}}
\providecommand{\OO}{\sh{O}}
\providecommand{\op}{\mathrm{op}}

\providecommand{\AA}{\sh{A}}
\providecommand{\BB}{\sh{B}}
\providecommand{\EE}{\sh{E}}
\providecommand{\II}{\sh{I}}
\providecommand{\JJ}{\sh{J}}
\providecommand{\MM}{\sh{M}}
\providecommand{\NN}{\sh{N}}

\providecommand{\Hom}{\operatorname{Hom}}
\providecommand{\shHom}{\underline{\Hom}}

\providecommand{\Specan}[1]{\operatorname{Specan}(#1)}
\providecommand{\Alg}[1]{{#1}\text{-}\Cat{Alg}}
\providecommand{\Mod}[1]{{#1}\text{-}\Cat{Mod}}

<!-- Content -->

# Analytic spectrum of an algebra of finite presentation {#section-1}

\oldpage{19-01}

::: {.rmenv #definition-1 title="Definition 1" latex="{Definition 1}"}
Let $S$ be a ringed space.
We say that an $\OO_S$-algebra $\AA$ is of *finite presentation* if every $s\in S$ admits a neighbourhood $U$ such that $\AA|U$ is isomorphic to a sheaf of the form
$$
  \frac{(\OO_S|U)[t_1,\ldots,t_n]}{(f_1,\ldots,f_m)}
$$
with $f_1,\ldots,f_m\in\Gamma(U,\OO_S[t_1,\ldots,t_n])$.
:::

That is, $\AA$ is locally generated over $\OO_S$ by a finite number of sections subject to a finite number of relations.

We are interested in the case where $S$ is an analytic space, over a non-discrete complete valued base field $k$.
For every analytic space $T$ over $S$, consider the sheaf $\AA_T=\AA\times_S T$, the inverse image of $\AA$ on $T$, and the set $F_\AA(T)=\Hom_{\OO_T}(\AA_T,\OO_T)$ of algebra homomorphisms;
we immediately see that $T\mapsto F_\AA(T)$ defines a contravariant functor $F_\AA\colon(\Cat{An})^\op/S\to\Cat{Set}$.

::: {.itenv #proposition-1 title="Proposition 1" latex="{Proposition }"}
Let $\AA$ be an algebra of finite presentation on an analytic space $S$;
the functor $F_\AA$ is representable in the category $\Cat{An}/S$ by an analytic space separated over $S$.
:::

::: {.proof}
We note first of all that the functor $F_\AA$ is of a local nature (cf. Exposé 11, Definition 5.4), since if $T$ is an analytic space over $S$, then the presheaf $U\mapsto F_\AA(U)$ (where $U$ runs over the opens of $T$) is precisely the sheaf of germs of algebra homomorphisms $\shHom_{\OO_T}(\AA_T,\OO_T)$.

Thus, by Corollary 5.7 of Exposé 11, it suffices, to show that $F_\AA$ is representable, to find an open cover $(S_i)$ of $S$ such that, for each index $i$, the functor $F_\AA/S_i$ is representable in $\Cat{An}/S_i$.

By [Definition 1](#definition-1), we thus see that it suffices to consider the case where $\AA$ is of the form $\OO_S[t_1,\ldots,t_n]/(f_1,\ldots,f_m)$.
Then the exact sequence
\oldpage{19-02}
$$
  0 \to \II \xrightarrow{i} \OO_S[t_1,\ldots,t_n] \to \AA \to 0
$$
(where $\II=(f_1,\ldots,f_m)$) gives, by base extension, an exact sequence
$$
  \II_T \xrightarrow{i_T} \OO_T[t_1,\ldots,t_n] \to \AA_T \to 0
$$
for every analytic space $T$ over $S$.
This allows us to identify $F_\AA(T)=\Hom_{\OO_T}(\AA_T,\OO_T)$ with the set of homomorphisms from $\OO_T[t_1,\ldots,t_n]$ to $\OO_T$ that vanish on $i_T(\II_T)$.

But the functor $F_{\OO_S[t_1,\ldots,t_n]}\colon T\mapsto\Hom_{\OO_T}(\OO_T[t_1,\ldots,t_n],\OO_T)$ is isomorphic to $T\mapsto(\Gamma(T,\OO_T))^n$;
by Theorem 1.1 of Exposé 10 and Proposition 3.1 of Exposé 11, we see that $F_{\OO_S[t_1,\ldots,t_n]}$ is represented in $\Cat{An}/S$ by the pair $(S\times\EE^n,\eta)$, where $\eta$ is the homomorphism of algebras $\eta\colon\OO_{S\times\EE^n}[t_1,\ldots,t_n]\to\OO_{S\times\EE^n}$ defined by $\eta(t_i)=q^*(z_i)$ (for $i=1,\ldots,n$) and denoting by $q$ the projection from $S\times\EE^n$ onto $\EE^n$.
It immediately follows that the sub-functor $F_\AA$ is represented by the closed subspace $X\subset S\times\EE^n$ defined by the ideal $\II=\eta\circ i_{S\times\EE^n}(\II_{S\times\EE^n})\subset\OO_{S\times\EE^n}$ (cf. Exposé 11, Lemma 3.6).

In the case in question, $X$ is evidently separated over $S$.
Since the property of being separated over $S$, for an object of $\Cat{An}/S$, is local on $S$, the latter claim of the statement is also proven (cf. Expose 11, Proposition 5.6: we obtain the space that represents $F_\AA$ by gluing together those that represent the $F_{\AA/S_i}$).
:::

::: {.rmenv #definition-2 title="Definition 2" latex="{Definition 2}"}
For every $\OO_S$-algebra $\AA$ of finite presentation, we define the *analytic spectrum* of $\AA$, denoted $\Specan{\AA}$, to be the object of $\Cat{An}/S$ (defined up to $S$-isomorphism) that represents the functor
$$
  F_\AA\colon T\longmapsto \Hom_{\OO_T}(\AA_T,\OO_T).
$$
\oldpage{19-3}
$\Specan{\AA}$ is thus an analytic space separated over $S$.
:::

::: {.rmenv title="Example" latex="{Example}"}
Consider an $\OO_S$-module $\EE$ of finite presentation;
its symmetric algebra $S(\EE)$ is an $\OO_S$-algebra of finite presentation, and $\Specan{S(\EE)}$ represents the functor
$$
  T\longmapsto
  \Hom_{\Alg{\OO_T}}(S(\EE_T),\OO_T)
  \simeq \Hom_{\Mod{\OO_T}}(\EE_T,\OO_T).
$$
This is the *vector bundle* defined by $\EE$ (cf. Exposé 12, §1).
:::

::: {.itenv #proposition-2 title="Proposition 2" latex="{Proposition 2}"}
i. $\AA\mapsto\Specan{\AA}$ defines a contravariant functor from the category of $\OO_S$-algebras of finite presentation to $\Cat{An}/S$.
ii. For any $\OO_S$-algebras $\AA$ and $\BB$ of finite presentation, $\AA\otimes_{\OO_S}\BB$ is of finite presentation, and $\Specan{\AA\otimes_{\OO_S}\BB}\simeq\Specan{\AA}\times_S\Specan{\BB}$.
iii. Let $h\colon\AA\to\BB$ be a surjective homomorphism of algebras of finite presentation. Then the corresponding morphism $\Specan{h}\colon\Specan{\BB}\to\Specan{\AA}$ is a closed immersion.
iv. For every $\OO_S$-algebra $\AA$ of finite presentation, and for every analytic space $T$ over $S$, $\Specan{\AA}\times_S T\simeq\Specan{\AA_T}$ (compatibility with base change).
:::

::: {.proof}
(i) is immediate, since $F_\AA(T)$ is a contravariant functor in $\AA$;
(ii) follows from the formula
$$
  \Hom_{\OO_T}(\AA_T\otimes_{\OO_T}\BB_T,\OO_T)
  \simeq \Hom_{\OO_T}(\AA_T,\OO_T)\times\Hom_{\OO_T}(\BB_T,\OO_T)
$$
(iii) follows easily from the proof of [Proposition 1](#proposition-1), and (iv) can be proven by Corollary 3.2 of Exposé 11.
:::

Consider the pair $(X,\xi)$ that represents the functor $F_\AA$ defined by an $\OO_S$-algebra $\AA$ of finite presentation.
Then $X=\Specan{\AA}$ is an analytic space over $S$, with structure morphism $f\colon X\to S$, and $\xi\in F_\AA(X)=\Hom_{\OO_X}(\AA_X,\OO_X)$ is a homomorphism from $\AA_X=f^*(\AA)$ to $\OO_X$.
In other words, $\xi$ defines a factorisation
$$
  X \xrightarrow{\hat{f}} (|S|,\AA) \to S
$$
of the structure morphism $f$ of $X$ through the ringed space $(|S|,\AA)$ (where $|S|$ denotes the underlying topological space of $S$) endowed with the canonical morphism $(|S|,\AA)\to S$ (consisting of the identity map on $|S|$ and the homomorphism $\OO_S\to\AA$).

\oldpage{19-04}
For any $\AA$-module $\MM$, set
$$
  \widetilde{\MM}
  = \hat{f}^*(\MM)
  = f^*(\MM)\otimes_{f^*(\AA)}\OO_X.
$$
We thus define a functor $\MM\mapsto\widetilde{\MM}$ from the category of $\AA$-modules to the category of $\OO_X$-modules (where $X=\Specan{\AA}$).
If $\MM$ and $\NN$ are $\AA$-modules then
$$
  (\MM\otimes_\AA\NN)^\sim
  = \widetilde{\MM}\otimes_{\OO_X}\widetilde{\NN}.
$$

Consider an analytic space $T$ over $S$, and the space
$$
  X_T
  = \Specan{\AA_T}
  = X\times_S T
$$
over $T$ ((iv) of [Proposition 2](#proposition-2));
the structure morphism from $X_T$ to $T$ again factors as
$$
  X_T
  \xrightarrow{\hat{f}_T}
  (|T|,\AA_T)
  \to T
$$
and we obtain a commutative diagram
$$
  \begin{CD}
    X @<<< X_T
  \\@V{\hat{f}}VV @VV{\hat{f}_T}V
  \\(|S|,\AA) @<<< (|T|,\AA_T)
  \end{CD}
$$
Let $\MM$ be an $\AA$-module;
the inverse image $\MM_T=\MM\times_S T$ of $\MM$ over $T$ is an $\AA_T$-module.
We thus see that $\widetilde{\MM}_T=\hat{f}_T^*(\MM_T)$ can be identified with the inverse image of $\widetilde{\MM}$ under the morphism $X_T\to X$ (compatibility of the functor $\MM\mapsto\widetilde{\MM}$ with base change).


# Fibre of the analytic spectrum over a point in the base {#section-2}

Consider an $\OO_S$-algebra $\AA$ of finite presentation, and its analytic spectrum $X=\Specan{\AA}$.
If $s\in S$, recall (Exposé 10, §2) that the *fibre* of $X$ at $s$ is the fibre product $X_s=X\times_S\{s\}$, where $\{s\}$ is the analytic space consisting of the point $s$, endowed with the field $\OO_s/\frak{m}_s\OO_s=K(s)\simeq k$ (where $\frak{m}_s$ denotes the maximal ideal of the local ring $\OO_s$).
\oldpage{19-05}
Then (by (iv) of [Proposition 2](#proposition-2))
$$
  X_s
  = X\times_S\{s\}
  \simeq \Specan{\AA_{\{s\}}}
  = \Specan{\AA(s)}
$$
where $\AA(s)=\AA_s/\frak{m}_s\AA_s=\AA_s\otimes_{\OO_s}k=\AA_{\{s\}}$;
if on a neighbourhood $U$ of $s$ we have that
$$
  \AA|U \simeq \frac{\OO_U[t_1,\ldots,t_n]}{(f_1,\ldots,f_m)}
$$
then
$$
  \AA(s) \simeq \frac{k[t_1,\ldots,t_n]}{(f_1(s),\ldots,f_m(s))}.
$$
$X_s=\Specan{\AA(s)}$ is the closed subspace of $\{s\}\times\EE^n\simeq\EE^n$ defined by the "equations"
$$
  f_i(s)(z_1,\ldots,z_n) = 0
  \qquad\text{for }i=1,2,\ldots,m.
$$

More precisely, if the functor $F_\AA$ is represented in $\Cat{An}/S$ by the pair $(X,\xi)$, then the functor $F_{\AA(s)}=F_{\AA/\{s\}}$ is represented in $\Cat{An}/\{s\}$ by the pair $(X_s,\xi_s)$, where $X_s$ is the fibre of $X$ at $s$ and where $\xi_s\colon\AA_{X_s}\to\OO_{X_s}$ is obtained from $\xi\colon\AA_X\to\OO_X$ by reduction modulo $\frak{m}_s$.
In particular, the map from $\Hom_{\{s\}}(\{s\},X_s)$ to $\Hom_k(\AA(s),k)$ that sends a section $f$ of $X_s/\{s\}$ to the composite homomorphism $f^*\circ\xi'_{s,f(s)}$ (where $\xi'_{s,f(s)}\colon\AA(s)\to\OO_{X_{s,f(s)}}$ is induced by the germ of $\xi_s$ at $f(s)$) is bijective.
Since $\Hom(\{s\},X_s)$ can be identified with the set of points of $X_s$ by sending $f\colon\{s\}\to X_s$ to the point $f(s)=x$ (so that $f^*=\epsilon_X\colon\OO_{X_s,x}\to k$ is the augmentation homomorphism), we obtain a bijection between the set of points of $X_s$ and the set of ideals of $\AA(s)$ that give $k$ as their quotient, by sending $x\in X_s$ to the inverse image under $\xi'_{s,x}\colon\AA(s)\to\OO_{X_s,x}$ of the maximal ideal of $\OO_{X_s,x}$.
But $\OO_{X_s,x}=\OO_{X,x}/\frak{m}_s\OO_{X,x}$ (Exposé 10, §2), $\AA(s)=\AA_s/\frak{m}_s\AA_s$, and $\xi'_{s,x}$ is obtained by reduction modulo $\frak{m}_s$ of $\xi'_X\colon\AA_s\to\OO_{X,x}$ (induced by the germ of $\xi$ at $x$).
We can thus state:

\oldpage{19-06}
::: {.itenv #proposition-3 title="Proposition 3" latex="{Proposition 3}"}
We obtain a bijection between the set of points of $X_s$ and the set of maximal ideals $\frak{n}$ of $\AA_s$ such that $\frak{n}\supset\frak{m}_s\AA_s$ and $\AA_s/\frak{n}\xleftarrow{\sim}k$, by associating to each $x\in X_s$ the inverse image under the homomorphism $\xi'_x\colon\AA_s\to\OO_{X,x}$ of the maximal ideal of $\OO_{X,x}$.
:::

If $\frak{n}$ is the maximal ideal of $\AA_s$ that corresponds to the point $x\in X_s$, then we thus have a factorisation of $\xi'_x$ as $\AA_s\to(\AA_s)_\frak{n}\xrightarrow{\varphi_x}\OO_{X,x}$.

::: {.itenv #proposition-4 title="Proposition 4" latex="{Proposition 4}"}
The homomorphism $\widehat{\varphi}_x\colon\widehat{(\AA_s)_\frak{n}}\to\widehat{\OO}_{X,x}$ induced by $\varphi_x$ by passing to completions of the local rings in question in an isomorphism.
:::

::: {.proof}
We use the notation used in the proof of [Proposition 1](#proposition-1).
We can write
$$
  \AA_s \simeq \OO_s[t_1,\ldots,t_n]/\II_s
$$
where $\II=(f_{1,s},\ldots,f_{n,s})$, and then
$$
  \OO_{X,x} = \OO_{S\times\EE^n,x}/\II_x
$$
where $\II=\eta_x(\II_s\OO_{S\times\EE^n,x}[t_1,\ldots,t_n])$;
$\eta_x$ is the germ of the homomorphism $\eta\colon\OO_{S\times\EE^n}[t_1,\ldots,t_n]\to\OO_{S\times\EE^n}$ defined by $\eta(t_i)=q^*(z_1)$ (for $i=1,2,\ldots,n$), and $\xi_x$ is induced from $\eta_x$ by passing to quotients, so that we have a commutative diagram with exact horizontal lines
$$
  \begin{CD}
    0 @>>> \II_s @>>> \OO_s[t_1,\ldots,t_n] @>>> \AA_s @>>> 0
  \\@. @VVV @VV{\eta'_x}V @VV{\xi'_x}V
  \\0 @>>> \II_x @>>> \OO_{S\times\EE^n} @>>> \OO_{X,x} @>>> 0
  \end{CD}
$$
where $\eta'_x$ is induced by $\eta_x$.

We denote by $\frak{p}$ the inverse image under $\eta'_x$ of the maximal ideal of $\OO_{S\times\EE^n}$;
$\frak{p}$ is the ideal generated by $\frak{m}_s$ and $t_1-x_1,\ldots,t_n-x_n$, where $x_i\in k$ denotes the value at $x$ of the section $q^*(z_i)$ of $\OO_{S\times\EE^n}$ (for $i=1,2,\ldots,n$).
We can write a commutative diagram with exact horizontal lines
\oldpage{19-07}
$$
  \begin{CD}
    0 @>>> (\II_s)_\frak{p} @>>> \OO_s[t_1,\ldots,t_n]_\frak{p} @>>> (\AA_s)_\frak{n} @>>> 0
  \\@. @VVV @VV{\psi_x}V @VV{\varphi_x}V
  \\0 @>>> \II_x @>>> \OO_{S\times\EE^n,x} @>>> \OO_{X,x} @>>> 0
  \end{CD}
$$
We can take the completion of this diagram to get
$$
  \big(\OO_s[t_1,\ldots,t_n]\big)_\frak{p}^\wedge
  \xrightarrow{\sim} \widehat{\OO}_s[[v_1,\ldots,v_n]]
$$
with this isomorphism being defined by sending $t_i$ to $x_i+v_i$ (for $i=1,2,\ldots,n)$;
we also have that
$$
  \widehat{\OO}_{S\times\EE^n,x}
  \simeq \widehat{\OO}_s\widehat{\otimes}_k \widehat{\OO}_{\EE^n,(x_1,\ldots,x_n)}
  \simeq \widehat{\OO}_s[[v_1,\ldots,v_n]]
$$
with this isomorphism being defined by sending $q^*(z_i)_x$ to $x_i+v_i$;
we thus see that $\widehat{\psi}_x$ is an isomorphism.
Since $\II_x=\eta_x(\II\OO_{S\times\EE^n,x}[t_1,\ldots,t_n])$ is generated by $(\II)_\frak{p}$, we also have an isomorphism $\widehat{(\II_s)}_\frak{p}\xrightarrow{\sim}\widehat{\II}_x$.
The proposition then follows.
:::

::: {.itenv title="Corollary" latex="{Corollary}"}
The morphism $\widehat{f}\colon X\to(|S|,\AA)$ of ringed spaces (defined via $\xi$) is flat, i.e. the functor $\MM\mapsto\widetilde{\MM}=\widehat{f}^*(\MM)$ from the category of $\AA$-modules to the category of $\OO_X$-modules is exact.
:::


# Analytic spectrum of a finite algebra {#section-3}

::: {.rmenv #definition-3 title="Definition 3" latex="{Definition 3}"}
Let $S$ be an analytic space over $k$ (a non-discrete complete valued field).
We say that an $\OO_S$-algebra $\AA$ is finite if it is a coherent sheaf of $\OO_S$-modules.
:::

::: {.itenv #proposition-5 title="Proposition 5" latex="{Proposition 5}"}
Every finite $\OO_S$-algebra $\AA$ is of finite presentation (as an algebra).
:::

::: {.proof}
Let $s\in S$;
the fibre $\AA_s$ is an $\OO_s$-module of finite type, generated by elements $\sigma_{i,s}$ (for $1\leqslant i\leqslant n$) that are integral over $\OO_s$;
for each $i$, let $F_{i,s}(\sigma_{i,s})=0$ be an equation of integral dependence: $F_{i,s}\in\OO_s[t_i]$ is unitary polynomial (for $i=1,\ldots,n$).
\oldpage{19-08}
In a small enough neighbourhood $U$ of $s$, there exist sections $\sigma_i\in\Gamma(U,\OO_S)$ , with germs $\sigma_{i,s}$ (respectively) at $s$ (for $1\leqslant i\leqslant n$), that generate $\AA|U$, as well as unitary polynomials $F_i\in\Gamma(U,\OO_S[t_i])$, with germs $F_{i,s}$ (respectively) at $s$ (for $1\leqslant i\leqslant n$), and such that $F_i(\sigma_i)=0$ for $i=1,\ldots,n$.
The sheaf $\BB=\OO_U[t_1,\ldots,t_n]/(F_1,\ldots,F_n)$ is coherent, and we have a surjective homomorphism $\BB\to\AA|U$, since the $\sigma_i$ generate $\AA|U$;
the kernel $\II$ of this homomorphism if of finite type;
we can find a neighbourhood $V\subset U$ of $s$ such that $\II|V$ is generated by the sections $\bar{G_1},\ldots,\bar{G_m}$.
If $G_1,\ldots,G_m\in\Gamma(V,\OO_S[t_1,\ldots,t_n])$ lift $\bar{G_1},\ldots,\bar{G_m}$, then we have
$$
  \AA|V
  \xleftarrow{\sim}
  \OO_V[t_1,\ldots,t_n] / (F_1,\ldots,F_n,G_1,\ldots,G_m).
$$
:::

As a consequence: every finite $\OO_S$-algebra $\AA$ defines an analytic space $X=\Specan{\AA}$ over $S$.

::: {.itenv #proposition-6 title="Proposition 6" latex="{Proposition 6}"}
Let $\AA$ be a finite $\OO_S$-algebra.
If $X=\Specan{\AA}$ and $s\in S$, then the fibre $X_s$ has a finite number of points, in bijective correspondence with the maximal ideals $\frak{n}$ of $\AA_s$ such that $\AA_s/\frak{n}\simeq k$.
If $\frak{n}$ is the maximal ideal that corresponds to a point $x\in X_s$, then we have an isomorphism $\varphi_x\colon(\AA_s)_\frak{n}\xrightarrow{\sim}\OO_{X,x}$.
:::

::: {.proof}
We can use the statements of [Proposition 3](#proposition-3) and [Proposition 4](#proposition-4), by remarking that $\AA_s$ is a semi-local ring (since $\AA(s)=\AA_s/\frak{m}_s\AA_s$ is of finite rank over $k$, and thus Artinian; furthermore, every maximal ideal of $\AA_s$ contains $\frak{m}_s\AA_s$, by the Cohen–Seidenberg theorem).
Also, $\widehat{\varphi}_x\colon\widehat{(\AA_s)_\frak{n}}\xrightarrow{\sim}\OO_{X,x}$ and, since $(\AA_s)_\frak{n}$ is separated, $\varphi_x$ is injective;
since $\OO_{X,x}$ is quasi-finite over $\OO_s$ (since $(\AA_s)_\frak{n}$ is), it follows from the preparation theorem that $\OO_{X,x}$ is finite over $\OO_s$;
we thus conclude by the Nakayama lemma (or the Krull theorem) that $\varphi_x$ is also surjective.
:::

::: {.itenv #corollary-1-proposition-6 title="Corollary 1" latex="{Corollary 1}"}
Let $(X,x)$ be an analytic germ, and let $f_1,\ldots,f_N$ be generators of an ideal of definition of $\OO_{X,x}$.
Consider $(X,x)$ as a germ over $(\EE^n,0)$ via the morphism $(X,x)\to(\EE^n,0)$ defined by $(f_1,\ldots,f_n)$.
There exists an open neighbourhood $U$ of $0$ in $\EE^n$ along with a finite $\OO_U$-algebra $\AA$ such that $\AA_0\simeq\OO_{X,x}$;
the spectrum $X'=\Specan{\AA}$ has a single point $x'$ over $0$, and $(X,x)$ is $(\EE^n,0)$-isomorphic to $(X',x')$.
:::

::: {.proof}
This follows from [Proposition 6](#proposition-6) by using Corollary 1.4 (ii) from Exposé 13, the preparation theorem, and the following lemma.
:::

::: {.itenv #lemma-1 title="Lemma 1" latex="{Lemma 1}"}
Let $S$ be an analytic space and $s\in S$;
consider a finite $\OO_{S,s}$-algebra $A$;
then there exists an open neighbourhood $U$ of $s$ in $S$ along with a finite $\OO_U$-algebra $\AA$ such that $\AA_s\simeq A$.
:::

::: {.proof}
\oldpage{19-09}
We first construct a neighbourhood $V$ of $s$ and a coherent $\OO_V$-module $\sh{F}$ such that $\sh{F}_s\simeq A$;
for this, we use a finite presentation $\OO_{S,s}^p\xrightarrow{u}\OO_{S,s}^q\to A\to 0$ of $A$;
if $(u_{ij})$ is the matrix of $u$, there exists a neighbourhood $V$ of $s$ and sections $f_{ij}$ of $\OO_s$ on $V$ such that $(f_{ij})_s=u_{ij}$ for every pair $(i,j)$;
the matrix $(f_{ij})$ defines a homomorphism $\OO_V^p\to\OO_V^q$ whose cokernel is the desired sheaf $\sh{F}$.

Since $\sh{F}\otimes_{\OO_V}\sh{F}$ is coherent, there exists a neighbourhood $W\subset V$ of $s$ and a homomorphism $(\sh{F}\otimes_{\OO_V}\sh{F})|W\to\sh{F}|W$ whose germ at $s$ is identified with the multiplication $A\otimes_{\OO_S}A\to A$ of the algebra $A$;
we can then find a neighbourhood $U\subset W$ of $s$ on which this homomorphism endows $\AA=\sh{F}|U$ with the structure of an $\OO_U$-algebra.
:::

::: {.itenv #corollary-2-proposition-6 title="Corollary 2" latex="{Corollary 2}"}
Every analytic algebra is a Henselian local ring.
:::

::: {.proof}
For the definition and the equivalent characterisations of Henselian local rings, we refer to [the appendix](#appendix).
We will use here the following characterisation:

> *For a local ring $A$ to be Henselian, it is necessary and sufficient that, for every finite $A$-algebra $B$ and every maximal ideal $\frak{n}$ of $B$, the localisation $B_\frak{n}$ is finite over $A$.*

When $A$ is an analytic algebra, [Lemma 1](#lemma-1) and [Proposition 6](#proposition-6) show that $B_\frak{n}$ is an analytic algebra finite over $A$ for every maximal ideal $\frak{n}$ of $B$ such that $B/\frak{n}=k$.
Consider an arbitrary maximal idea $\frak{n}$ of $B$, and set $K=B/\frak{n}$;
this is a finite extension of $k$.
We introduce the algebras $A'=A\otimes_kK$ and $B'=B\otimes_kK$;
so $A'$ is an analytic algebraic over the field $K$, and $B'$ is finite over $A'$.
To the ideal $\frak{n}$ of $K$ there corresponds a maximal ideal $\frak{n}'$ of $B'$, given by the kernel of the homomorphism from $B'$ to $K$ that extends $B\to K$;
from $B'/\frak{n}'=K$, we deduce that $B'_{\frak{n}'}$ is finite over $A'$, and thus also over $A$ (since $A'$ is finite over $A$).
It then follows that $B_\frak{n}$ is finite over $A$, since the canonical homomorphism $B_\frak{n}\to B'_\frak{n}$ is clearly injective (and $A$ is Noetherian).
This finishes the proof.
:::

::: {.itenv #proposition-7 title="Proposition 7" latex="{Proposition 7}"}
Let $\AA$ be a finite $\OO_S$-algebra.
The structure morphism $f\colon\Specan{\AA}\to S$ of its analytic spectrum is a closed map.
:::

Since the property is local on $S$, we can immediately reduce to the case where $\AA$ is generated by sections $\sigma_1,\ldots,\sigma_n$ subject to relations $F_i(\sigma_i)=0$, where the $F_i$ are unitary polynomials belonging to $\Gamma(\OO_S)[t_i]$ (for $i=1,\ldots,n$), and $G_j(\sigma_1,\ldots,\sigma_n)=0$ (for $j=1,\ldots,m$), so that $\AA\simeq\BB/\JJ$ with $\BB=\OO_S[t_1,\ldots,t_n]/(F_1,\ldots,F_n)$ (cf. the proof of [Proposition 5](#proposition-5)).
\oldpage{19-10}
We then have a closed immersion $\Specan{\AA}\to\Specan{\BB}$, and it evidently suffices to prove the property for the structure morphism of $\Specan{\BB}$;
this follows from the following statement:

> *Let $(x_p)$ be a sequence of points of $\Specan{\BB}$ such that $s_p=f(x_p)$ converges to a point $s\in S$. Then there exists a subsequence of $(x_p)$ that converges.*

By noting that
$$
  \Specan{\BB}
  \simeq
  \Specan{\OO_S[t]/(F_1)} \times_S \ldots \times_S \Specan{\OO_S[t]/(F_n)}
$$
by [Proposition 2, (ii)](#proposition-2), we see that it suffices to prove this statement in the case where $n=1$.
For $\Specan{\OO_S[t]/(F)}\subset S\times\EE$, the result comes from the following:

::: {.itenv #lemma-2 title="Lemma 2 (continuity of roots)" latex="{Lemma 2 (continuity of roots)}"}
Let
:::
