--- 
title: "The theory of Chern classes"
author: "A. Grothendieck"
date: ""
original: 'Grothendieck, A. "La théorie des classes de Chern". _Bulletin de la Société Mathématique de France_ **86** (1958), 137--154. DOI: [10.24033/bsmf.1501](https://www.doi.org/10.24033/bsmf.1501)'
bibliography: BSMF-86-1958-137.bib
nocite: '@*'
link-citations: true
csl: maths-translations.csl
reference-section-title: "Bibliography"
---

```{r, child = if (knitr::is_html_output()) '_translator-note.Rmd'}
```

\providecommand{\HH}{\operatorname{H}}
\providecommand{\rank}{\operatorname{rank}}
\providecommand{\cl}{\operatorname{cl}}
\providecommand{\PP}{\mathbf{P}}

\providecommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\cal}[1]{{\mathcal{#1}}}

\renewcommand{\geq}{\geqslant}
\renewcommand{\leq}{\leqslant}

# Introduction {-}

\oldpage{137}

In this appendix, we will develop an axiomatic theory of Chern classes that will allow us, in particular, to define the Chern classes of an algebraic vector bundle $E$ on a non-singular quasi-projective algebraic variety $X$ as elements of the Chow ring $A(X)$ of $X$, i.e. as classes of cycles under rational equivalence.
This exposé is inspired one one hand by the book of Hirzebruch (where the essential _formal properties_ characterising a theory of Chern classes were brought to light), and on the other hand by an idea of Chern [@2] that consists of using the multiplicative structure of the ring of cycle classes on the bundle of projective spaces $\mathbb{P}(E)$ associated to $E$, to give an effective _construction_ of Chern classes.
We note that the exposition given here also applies to other settings than algebraic geometry, and recovers, for example, an entirely elementary theory of Chern classes for complex vector bundles on topological manifolds (and, from this, on any space for which the classification theorem of principal bundles with a structure group via a "classifying space" holds true).
Similarly, we will obtain, for a complex-analytic vector bundle $E$ on a (non-singular) complex-analytic manifold $X$, Chern classes
$$
  c_p(E) \in \HH^p(X,\Omega_X^p),
$$
where $\Omega_X^p$ is the sheaf of germs of holomorphic differential forms of degree $p$ on $X$.
[And it is certainly easy to prove that this definition agrees with the one given recently by Atiyah [@1], and that it is related to the topological definition of Chern classes via the spectral sequence relating $\HH^p(X,\Omega_X^q)$ and $\HH^\bullet(X,\mathbb{C})$.]
Similarly, the theory of Stiefel--Whitney classes in $\mathbb{Z}/2\mathbb{Z}$ cohomology fits into the framework that we will describe here.

\oldpage{138}

It appears that a satisfying theory of Chern classes in algebraic geometry was given, for the first time, by W.L. Chow (unpublished), using the Grassmannian.
The main aim of the current paper has been to eliminate the Grassmannian from the theory.
I have already shown [@4] how the theory of Chern classes allows us to _recover_ the structure of $A(X)$ when $X$ is a Grassmannian.


# Notation {#section-1}

In order to not expose ourselves to the complications arising from intersection theory, we will limit ourselves in what follows to considering only _non-singular_ topological spaces.
We fix, once and for all, a base field $k$.
To better understand the ideas, the reader can assume that $k$ is algebraically closed.
All the bundles, subvarieties, morphisms, etc. that we consider in what follows will be defined over $k$.

If $X$ is an algebraic space, and $E$ a vector bundle on $X$, then we denote by $\mathbb{P}(E)$ the associated projective bundle.
The fibre $\mathbb{P}(E)_x$ of $\mathbb{P}(E)$ at a point $x\in X$ is thus the projective space associated to the vector space $E_x$, and so a point of $\mathbb{P}(E)_x$ over a point $x\in X$ is exactly a homogeneous line in $E_x$.
Let $f\colon\mathbb{P}(E)\to X$ be the projection of the bundle;
we will consider the inverse image of $E$ under $f$, which is the vector bundle $f^{-1}(E)$ on $\mathbb{P}(E)$.
There is a canonical rank-$1$ subbundle of $f^{-1}(E)$, whose fibre at a point $d$ of $\mathbb{P}(E)$ (over a point $x\in X$) is the line $d$ in $E_x=f^{-1}(E)_d$.
The dual bundle of this subbundle of $f^{-1}(E)$ is denoted by $L_E$, and we thus have the inclusion
$$
  \check{L}_E \subset f^{-1}(E).
$$

Let $p$ be the rank of $E$ (assumed to be constant, which is always the case if $X$ is connected).
Then $E^{(1)}=f^{-1}(E)/\check{L}_E$ is a vector bundle of rank $p-1$ on $X^{(1)}=\mathbb{P}(E)$, and we can thus construct $X^{(2)}=\mathbb{P}(E^{(1)})$ and the analogous bundle $E^{(2)}=(E^{(1)})^{(1)}$ of rank $p-2$ on $X^{(2)}$.
In this manner, we inductively construct manifolds $X^{(i)}$ and vector bundles $E^{(i)}$ of rank $p-i$ on $X^{(i)}$ (for $1\leq i\leq p$), where $X^{(i)}$ is the bundle $\mathbb{P}(E^{(i-1)})$ on $X^{(i-1)}$.
We define a _flag of length $i$_ in a vector space $V$ to be an increasing sequence $(V_j)_{0\leq j\leq i}$ of vector subspaces $V_j$, with $\dim V_j=j$.
Then $X^{(i)}$ can also be understood as the _bundle on $X$ of flags of length $i$_ in $E$, and, if $f^{(i)}$ is the projection from $X^{(i)}$ to $X$, then we directly define, as in the definition of $L_E$, an increasing sequence of subbundles $(V_j)_{0\leq j\leq i}$ of $E_i=(f^{(i)})^{(-1)}(E)$, with $\rank(V_j)=j$, with the quotient of $E_i$ by $V_i$ being exactly the vector bundle $E^{(i)}$.
In particular, $X^{(p)}$ is the _flag manifold_ $D(E)$ (of maximum length $p$) of $E$, which resembles a "multiple extension" of $X$ by fibrations in projective spaces associated to vector bundles;
the inverse image $E_p$ of $E$ in $X^{(p)}=D(E)$ is further _completely split_.
By this, we mean that this rank-$p$ vector bundle is endowed with a sequence $(V_i)_{0\leq i\leq p}$ of vector subbundles,
with $\rank(V_i)=i$.
Then the $V_i/V_{i-1}$ ($1\leq i\leq p$) are vector bundles of rank $1$, and are called the _factors_ of the given splitting.

\oldpage{139}

If $X$ is an algebraic space, then we denote by $\PP(X)$ the group of isomorphism classes of rank-$1$ vector bundles on $X$ (the composition law of the group being given by the tensor product of bundles).
If $L$ is such a rank-$1$ vector bundle, then we denote by $\cl_X(L)$ the element of $\PP(X)$ that it defines.
We thus have
$$
  \begin{aligned}
    \cl_X(L\otimes L') &= \cl_X(L) + \cl_X(L')
  \\\cl_X(\check{L}) &= -\cl_X(L).
  \end{aligned}
$$

If $f\colon X\to Y$ is a morphism, then the formula
$$
  f^*(\cl_X(L)) = \cl_X(f^{-1}(L))
$$
defines a homomorphism $f^*$ from $\PP(Y)$ to $\PP(X)$.
In this way, $\PP(X)$ can be considered as a _contravariant functor_ in $X$.

With $f\colon X\to Y$ still a morphism, let $F$ be a rank-$p$ vector bundle on $Y$, and set $E=f^{-1}(F)$.
This is a rank-$p$ vector bundle on $X$, and we have a canonical isomorphism $\mathbb{P}(E)=f^{-1}(\mathbb{P}(F))$, whence a natural morphism
$$
  \bar{f}\colon \mathbb{P}(E) \to \mathbb{P}(F).
$$

With this, we can immediately verify that $L_E$ is canonically isomorphic to the inverse image $\bar{f}^{-1}(L_F)$_.
We thus have the formula
$$
  \cl(L_E) = \bar{f}^*(\cl(L_F)).
$$

Let $E$ be a rank-$p$ vector bundle on $X$, and $s$ a regular section of $E$.
Then $s$ is a morphism from $X$ to $E$, and even an isomorphism from $X$ to a closed subspace of codimension $p$ of $E$.
In particular, the image of $X$ under the zero section is a closed non-singular subspace $X'$ of codimension $p$ of $E$.
Evidently, the inverse image $s^{-1}(X')$ is exactly the set of zeros of $s$.
For the _cycle_ $s^{-1}(X')$ to be well defined, it is necessary and sufficient for the set of zeros of $s$ to be everywhere empty, or of codimension $p$ in $X$.
In this case, we can then speak of the _cycle of zeros_ of the section $s$.
Recall also that the morphism $s$ is said to be _transversal_ to the subvariety $X'$ of $X$ if, at every point of the inverse image of $X'$ under $s$, the tangent map to $s$ is surjective modulo the tangent space to $X'$.
In this case, $s^{-1}(X')$ is a non-singular algebraic subspace of $X$ that is everywhere of codimension $p$, and all of its components are of multiplicity $1$ in the cycle of zeros of $s$.
We will then say, for brevity, that the section $s$ is _transversal to the zero section_.
We can express this property by a calculation:
since it is local on $X$, we can assume that $E$ is the trivial bundle $X\times k^p$, so that $s$ is defined by the data of $p$ regular functions $(f_1,\ldots,f_p)$ on $X$;
for $s$ to be transversal to the zero section, it is necessary and sufficient for the functions $f_1,\ldots,f_p$ to give a regular system of parameters of $\scr{O}_x$ at every point $x$.


# The functor $A(X)$ {#section-2}

\oldpage{140}

In what follows, suppose that we have a category $\cal{V}$ of non-singular algebraic spaces (the morphisms in this category being the morphisms of algebraic spaces).
The only condition that we impose on $\cal{V}$ is that
